#ifndef UE4SS_SDK_AFE_Radiation_WaveCooker_Enemies_HPP
#define UE4SS_SDK_AFE_Radiation_WaveCooker_Enemies_HPP

class UAFE_Radiation_WaveCooker_Enemies_C : public UAttachedParticlesAfflictionEffect
{
};

#endif
