#ifndef UE4SS_SDK_AFE_FP_PlagueTentacles_SlimetrailStabbingStabbing_HPP
#define UE4SS_SDK_AFE_FP_PlagueTentacles_SlimetrailStabbingStabbing_HPP

class UAFE_FP_PlagueTentacles_SlimetrailStabbingStabbing_C : public UAttachedParticlesAfflictionEffect
{
};

#endif
