#ifndef UE4SS_SDK_BP_BarGlass_OilyOafBrew_SupporterEdition_HPP
#define UE4SS_SDK_BP_BarGlass_OilyOafBrew_SupporterEdition_HPP

class ABP_BarGlass_OilyOafBrew_SupporterEdition_C : public ABP_BarGlass_Standard_C
{
};

#endif
