#ifndef UE4SS_SDK_BP_CrystalFormations_SlantedPillars_01Rot_HPP
#define UE4SS_SDK_BP_CrystalFormations_SlantedPillars_01Rot_HPP

class ABP_CrystalFormations_SlantedPillars_01Rot_C : public ABP_CrystalFormations_SlantedPillars_Base_C
{
};

#endif
