#ifndef UE4SS_SDK_BP_CrystalFormations_SlantedPillars_01_HPP
#define UE4SS_SDK_BP_CrystalFormations_SlantedPillars_01_HPP

class ABP_CrystalFormations_SlantedPillars_01_C : public ABP_CrystalFormations_SlantedPillars_Base_C
{
};

#endif
