#ifndef UE4SS_SDK_BP_EscortDestination_HPP
#define UE4SS_SDK_BP_EscortDestination_HPP

class ABP_EscortDestination_C : public AEscortDestination
{
    FPointerToUberGraphFrame UberGraphFrame;
    class UBillboardComponent* PatrolPoint9;
    class UBillboardComponent* PatrolPoint8;
    class UBillboardComponent* PatrolPoint7;
    class UBillboardComponent* PatrolPoint6;
    class UBillboardComponent* PatrolPoint5;
    class UBillboardComponent* PatrolPoint4;
    class UBillboardComponent* PatrolPoint3;
    class UBillboardComponent* PatrolPoint2;
    class UBillboardComponent* PatrolPoint1;
    class USceneComponent* EnergySpritePatrolPoints;
    class UBillboardComponent* EnergySpriteSpawnPOS;
    class UBP_Extractor_Shell_C* Layer3Break3_Shell3;
    class UBP_Extractor_Shell_C* Layer3Break3_Shell2;
    class UBP_Extractor_Shell_C* Layer3Break3_Shell1;
    class UBP_Extractor_Shell_C* Layer3Break2_Shell2;
    class UBP_Extractor_Shell_C* Layer3Break2_Shell1;
    class UStaticMeshComponent* Layer3Break2;
    class UStaticMeshComponent* Layer3Break1;
    class UBP_Extractor_Shell_C* OuterBreak4_Shell4;
    class UBP_Extractor_Shell_C* OuterBreak4_Shell3;
    class UBP_Extractor_Shell_C* OuterBreak4_Shell2;
    class UBP_Extractor_Shell_C* OuterBreak4_Shell1;
    class UBP_Extractor_Shell_C* OuterBreak3_Shell3;
    class UBP_Extractor_Shell_C* OuterBreak3_Shell2;
    class UBP_Extractor_Shell_C* OuterBreak3_Shell1;
    class UBP_Extractor_Shell_C* OuterBreak2_Shell3;
    class UBP_Extractor_Shell_C* OuterBreak2_Shell2;
    class UBP_Extractor_Shell_C* OuterBreak2_Shell1;
    class UStaticMeshComponent* OuterBreak3;
    class UStaticMeshComponent* OuterBreak2;
    class UStaticMeshComponent* OuterBreak1;
    class UAudioComponent* FlyingRocksEnergyLinkLoop;
    class UBillboardComponent* BeamerSpawnLocation_9;
    class UBillboardComponent* BeamerSpawnLocation_5;
    class UBillboardComponent* BeamerSpawnLocation_10;
    class UChildActorComponent* BP_Heartstone_Claw_04;
    class USceneComponent* BeamersR;
    class UBillboardComponent* BeamerSpawnLocation_7;
    class UBillboardComponent* BeamerSpawnLocation_8;
    class UBillboardComponent* BeamerSpawnLocation_2;
    class UBillboardComponent* BeamerSpawnLocation_4;
    class UBillboardComponent* BeamerSpawnLocation_12;
    class UBillboardComponent* BeamerSpawnLocation_3;
    class USphereComponent* Sphere12;
    class USphereComponent* Sphere10;
    class USphereComponent* Sphere9;
    class USphereComponent* Sphere8;
    class USphereComponent* Sphere7;
    class USphereComponent* Sphere5;
    class USphereComponent* Sphere4;
    class USphereComponent* Sphere3;
    class USphereComponent* Sphere2;
    class USceneComponent* BeamersL;
    class UParticleSystemComponent* P_Heartstone_AmbientDust;
    class UParticleSystemComponent* P_CaveFX_heartstoneHangingDust;
    class UStaticMeshComponent* Cone3;
    class USpotLightComponent* SpotLight3;
    class UPointLightComponent* PointLight3;
    class USceneComponent* SpotlightCenter;
    class UBillboardComponent* Check_24;
    class UBillboardComponent* Check_23;
    class UBillboardComponent* Check_22;
    class UBillboardComponent* Check_21;
    class UBillboardComponent* Check_20;
    class UBillboardComponent* Check_19;
    class UBillboardComponent* Check_18;
    class UBillboardComponent* Check_17;
    class UBillboardComponent* Check_16;
    class UBillboardComponent* Check_15;
    class UBillboardComponent* Check_14;
    class UBillboardComponent* Check_13;
    class UBillboardComponent* Check_12;
    class UBillboardComponent* Check_11;
    class UBillboardComponent* Check_10;
    class UBillboardComponent* Check_9;
    class UBillboardComponent* Check_8;
    class UBillboardComponent* Check_7;
    class UBillboardComponent* Check_6;
    class UBillboardComponent* Check_5;
    class UBillboardComponent* Check_4;
    class UBillboardComponent* Check_3;
    class UBillboardComponent* Check_2;
    class UBillboardComponent* Check_1;
    class USceneComponent* PlatformChecks;
    class UBillboardComponent* AoE_Origin;
    class UDamageComponent* GroundSlamDamage;
    class UTerrainScannerStaticMesh* TerrainScannerStaticMesh;
    class ULevelGenerationDebris* LevelGenerationDebris_Ring_02;
    class ULevelGenerationCarverComponent* 1_LevelGenerationCarver_Floor;
    class ULevelGenerationCarverComponent* 2_LevelGeneration_CleanCarver;
    class UStaticMeshComponent* GunTower_Carver01;
    class USceneComponent* ArenaCarvers;
    class UStaticMeshComponent* CleanCraterCarver;
    class USimpleObjectInfoComponent* SimpleObjectInfo;
    class UChildActorComponent* BP_Heartstone_Claw_07;
    class UChildActorComponent* BP_Heartstone_Claw_08;
    class UChildActorComponent* BP_Heartstone_Claw_06;
    class UChildActorComponent* BP_Heartstone_Claw_02;
    class USceneComponent* Spikes;
    class USpawnActorWithDebrisPosComponent* LaserClawDebrisPos;
    class ULevelGenerationDebris* LevelGenerationDebris_Ring_01;
    class ULevelGenerationDebris* LevelGenerationDebris_CORE;
    class UStaticMeshComponent* Layer1Broken;
    class UStaticMeshComponent* Layer1;
    class UStaticMeshComponent* Layer2Broken;
    class UStaticMeshComponent* Layer2;
    class UStaticMeshComponent* Layer3Broken;
    class UStaticMeshComponent* Layer3;
    class UStaticMeshComponent* Layer4Broken;
    class UStaticMeshComponent* Layer4;
    class USceneComponent* HeartstoneMeshes;
    class UPathfinderCollisionComponent* PathfinderCollision;
    class UPointLightComponent* PointLight;
    class USceneComponent* Rings;
    class ULevelGenerationDebris* LevelGenerationDebris_MultipleRings;
    class USceneComponent* GemSpawnPos;
    class UTerrainPlacementComponent* terrainPlacement;
    class USceneComponent* DefaultSceneRoot;
    int32 Stage;
    class UEscortObjective* EscortObj;
    int32 SmarkRockSpawnGroups;
    class UEWC_Escort_EndDefense_C* WaveController_FinalFight;
    int32 SmartRockSpawnIndex;
    float SmartRockGropuDelay;
    TArray<class ABP_Heartstone_DefensiveCrystal_C*> DefensiveCrystals;
    bool IsMainCrystalWave;
    float LaserClawSpawnRadius;
    TArray<FVector> ForbiddenBeamerLocations;
    TArray<class USceneComponent*> BeamerLocationsL;
    TArray<class USceneComponent*> BeamerLocationsR;
    int32 BeamerIndexL;
    int32 BeamerIndexR;
    bool LRBeamerToggle;
    int32 NumActiveFlyingRocks;
    int32 OuterShellMiniBreakStage;
    float prevBreakPoint;
    TArray<FVector> SpawnPoints;
    bool CanSpawnEnergySprites;
    float SoloRockGroupMultiplier;
    int32 RandomPhase2;
    int32 RandomPhase4;
    int32 NumberOfPhaseOptions;
    TArray<class APawn*> SpawnedFlyingRocks;
    int32 RockStartStage;

    void Update Shell Break Sub Stage();
    void OnRep_OuterShellMiniBreakStage();
    void OnRep_Stage();
    void ReleaseShellCustom(class UBP_Extractor_Shell_C* Shell);
    void OnRep_NumActiveFlyingRocks();
    void UserConstructionScript();
    void ReceiveBeginPlay();
    void DrillingComplete();
    void CountdownTimeChanged(float Progress);
    void NewStage();
    void SpawnRocks(int32 SpawnCountPerGroup, int32 NumGroups, int32 StageAtStart);
    void GrowLaserClaws();
    void DoBrokenShellEffects();
    void OnObjectiveUpdated(class UObjective* Objective);
    void RegisterCrystal(class ABP_Heartstone_DefensiveCrystal_C* Crystal);
    void DoAoEPush();
    void CheckForEngPlatofrms();
    void MoreLaserClaws();
    void TurnOffBrokenSHellEmissive();
    void OnPickedUp_Event_0();
    void TurnSpotOff();
    void SpawnBeamer();
    void DisableAllBeamers();
    void RegisterFlyingRock();
    void DeRegisterFlyingRock();
    void Spawn Group();
    void SpawnEnergySprites();
    void SpawnSupportingWave();
    void SpawnFinalSupportingWave();
    void RockEnemySpawned(class APawn* enemy);
    void KillRemainingRocks();
    void ExecuteUbergraph_BP_EscortDestination(int32 EntryPoint);
};

#endif
