#ifndef UE4SS_SDK_CP_Halloween_LastYearsHorrors2023_OldHats_HPP
#define UE4SS_SDK_CP_Halloween_LastYearsHorrors2023_OldHats_HPP

class UCP_Halloween_LastYearsHorrors2023_OldHats_C : public UCampaign
{
};

#endif
