#ifndef UE4SS_SDK_ITM_BarGlass_Item_OilyOafBrew_SupporterEdition_HPP
#define UE4SS_SDK_ITM_BarGlass_Item_OilyOafBrew_SupporterEdition_HPP

class AITM_BarGlass_Item_OilyOafBrew_SupporterEdition_C : public AITM_BarGlass_Item_C
{
};

#endif
