#ifndef UE4SS_SDK_Loadout_GrenadeProxy_PlasmaBoomerang_HPP
#define UE4SS_SDK_Loadout_GrenadeProxy_PlasmaBoomerang_HPP

class ALoadout_GrenadeProxy_PlasmaBoomerang_C : public ALoadout_GrenadeProxy_Ball_C
{
};

#endif
