#ifndef UE4SS_SDK_LVL_SpaceRig_HPP
#define UE4SS_SDK_LVL_SpaceRig_HPP

class ALVL_SpaceRig_C : public ALevelScriptActor
{
    FPointerToUberGraphFrame UberGraphFrame;
    float SunSpeed;
    int32 CurrentNumberOfBarrelsInDroppod;
    int32 CurrentNumberOfBarrels;
    int32 DesiredBarrelNumber;
    int32 MedbayBantersPlayed;
    int32 Players spawned;
    class UFSDAchievement* TimeWellSpentAchievement;
    class UFSDAchievement* ForeignObjectsInTheLaunchbay;
    TArray<class TSubclassOf<UUserWidget>> Preload_Widgets;
    TArray<class UAudioComponent*> AmbientAudioComponents;
    FLinearColor BarLightColor;
    class USoundCue* CurrentAmbienceCue;
    class USoundCue* DefaultAmbienceCue;
    class AStaticMeshActor* ForceShield_ExecuteUbergraph_LVL_SpaceRig_RefProperty;
    class AEmitter* P_SpaceRig_Smoke_2_ExecuteUbergraph_LVL_SpaceRig_RefProperty;
    class AStaticMeshActor* SaluteStatue_B2_ExecuteUbergraph_LVL_SpaceRig_RefProperty;
    class AStaticMeshActor* Statue_Engineer_5_ExecuteUbergraph_LVL_SpaceRig_RefProperty;
    class AStaticMeshActor* Statue_Driller_2_ExecuteUbergraph_LVL_SpaceRig_RefProperty;
    class AStaticMeshActor* Statue_Gunner_8_ExecuteUbergraph_LVL_SpaceRig_RefProperty;
    class ASkeletalMeshActor* SK_DonkeyMK5_ExecuteUbergraph_LVL_SpaceRig_RefProperty;
    class AStaticMeshActor* Statue_Scout_11_ExecuteUbergraph_LVL_SpaceRig_RefProperty;
    class AStaticMeshActor* SaluteStatue_B_14_ExecuteUbergraph_LVL_SpaceRig_RefProperty;
    class AStaticMeshActor* Plane_2_ExecuteUbergraph_LVL_SpaceRig_RefProperty;
    class AStaticMeshActor* Plane2_ExecuteUbergraph_LVL_SpaceRig_RefProperty;
    class AStaticMeshActor* Plane3_ExecuteUbergraph_LVL_SpaceRig_RefProperty;
    class AStaticMeshActor* Plane4_ExecuteUbergraph_LVL_SpaceRig_RefProperty;
    class AStaticMeshActor* Plane5_ExecuteUbergraph_LVL_SpaceRig_RefProperty;
    class AStaticMeshActor* Plane6_ExecuteUbergraph_LVL_SpaceRig_RefProperty;
    class AStaticMeshActor* SaluteStatue_A_2_ExecuteUbergraph_LVL_SpaceRig_RefProperty;
    class AStaticMeshActor* Plane7_ExecuteUbergraph_LVL_SpaceRig_RefProperty;
    class AStaticMeshActor* Plane8_ExecuteUbergraph_LVL_SpaceRig_RefProperty;
    class ASign_MemorialUnlock_C* Memorial_Sign_DRILLERSTATUE_lvl10_ExecuteUbergraph_LVL_SpaceRig_RefProperty;
    class ASign_MemorialUnlock_C* Memorial_Sign_ENGINEERSTATUE_lvl10_ExecuteUbergraph_LVL_SpaceRig_RefProperty;
    class ASign_MemorialUnlock_C* Memorial_Sign_GUNNERSTATUE_lvl10_ExecuteUbergraph_LVL_SpaceRig_RefProperty;
    class ASign_MemorialUnlock_C* Memorial_Sign_SCOUTSTATUE_lvl10_ExecuteUbergraph_LVL_SpaceRig_RefProperty;
    class ASign_MemorialUnlock_C* Memorial_Sign_MULESTATUE_Rank6_ExecuteUbergraph_LVL_SpaceRig_RefProperty;
    class ASign_MemorialUnlock_C* Memorial_Sign_POSTER_Rank3_L_ExecuteUbergraph_LVL_SpaceRig_RefProperty;
    class ASign_MemorialUnlock_C* Memorial_Sign_POSTER_Rank3_R_ExecuteUbergraph_LVL_SpaceRig_RefProperty;
    class ASign_MemorialUnlock_C* Memorial_Sign_POSTER_Rank5_L_ExecuteUbergraph_LVL_SpaceRig_RefProperty;
    class ASign_MemorialUnlock_C* Memorial_Sign_POSTER_Rank5_R_ExecuteUbergraph_LVL_SpaceRig_RefProperty;
    class ASign_MemorialUnlock_C* Memorial_Sign_POSTER_Rank7_R_ExecuteUbergraph_LVL_SpaceRig_RefProperty;
    class ASign_MemorialUnlock_C* Memorial_Sign_POSTER_Rank7_L_ExecuteUbergraph_LVL_SpaceRig_RefProperty;
    class ASign_MemorialUnlock_C* Memorial_Sign_POSTER_Rank4_R_ExecuteUbergraph_LVL_SpaceRig_RefProperty;
    class ASign_MemorialUnlock_C* Memorial_Sign_POSTER_Rank4_L_ExecuteUbergraph_LVL_SpaceRig_RefProperty;
    class ASign_MemorialUnlock_C* Memorial_Sign_GIANTSTATUE_Rank8_R_ExecuteUbergraph_LVL_SpaceRig_RefProperty;
    class ASign_MemorialUnlock_C* Memorial_Sign_GIANTSTATUE_Rank8_L_ExecuteUbergraph_LVL_SpaceRig_RefProperty;
    class ASign_MemorialUnlock_C* Memorial_Sign_GOLDDRILLERSTATUE_lvl20_ExecuteUbergraph_LVL_SpaceRig_RefProperty;
    class ASign_MemorialUnlock_C* Memorial_Sign_GOLDENGINEERSTATUE_lvl20_ExecuteUbergraph_LVL_SpaceRig_RefProperty;
    class ASign_MemorialUnlock_C* Memorial_Sign_GOLDGUNNERSTATUE_lvl20_ExecuteUbergraph_LVL_SpaceRig_RefProperty;
    class ASign_MemorialUnlock_C* Memorial_Sign_GOLDSCOUTSTATUE_lvl20_ExecuteUbergraph_LVL_SpaceRig_RefProperty;
    class ASign_MemorialUnlock_C* Memorial_Sign_GOLDSALUTINGSTATUE_Rank20_ExecuteUbergraph_LVL_SpaceRig_RefProperty;
    class ASign_MemorialUnlock_C* Memorial_Sign_GOLDMULESTATUE_Rank12_ExecuteUbergraph_LVL_SpaceRig_RefProperty;
    class ASign_MemorialUnlock_C* Memorial_Sign_GOLDGIANTSTATUES_Rank15_ExecuteUbergraph_LVL_SpaceRig_RefProperty;
    class AStaticMeshActor* SM_DonkeyStatic01_4_ExecuteUbergraph_LVL_SpaceRig_RefProperty;
    class APointLight* Light_Dropchute_BlueLight_ExecuteUbergraph_LVL_SpaceRig_RefProperty;
    class ABP_DropPod_Rig_C* BP_DropPod_Rig_2_ExecuteUbergraph_LVL_SpaceRig_RefProperty;
    class AActor* TrashCompactorDirection_ExecuteUbergraph_LVL_SpaceRig_RefProperty;
    class ATriggerBox* TriggerBox_TrashCompactor_ExecuteUbergraph_LVL_SpaceRig_RefProperty;
    class ABP_Phys_Newsstand_FreeBeer_C* BP_Phys_Newsstand_FreeBeer4_EdGraph_0_RefProperty;
    class ABP_Phys_Newsstand_FreeBeer_C* BP_Phys_Newsstand_FreeBeer3_EdGraph_0_RefProperty;
    class ABP_Phys_Newsstand_FreeBeer_C* BP_Phys_Newsstand_FreeBeer2_EdGraph_0_RefProperty;
    class ABP_Phys_Newsstand_FreeBeer_C* BP_Phys_Newsstand_FreeBeer_2_EdGraph_0_RefProperty;
    class ABP_ConfettiPlane_C* BP_ConfettiPlane3_EdGraph_0_RefProperty;
    class ABP_ConfettiPlane_C* BP_ConfettiPlane2_EdGraph_0_RefProperty;
    class ABP_ConfettiPlane_C* BP_ConfettiPlane_4_EdGraph_0_RefProperty;
    class ASkeletalMeshActor* SK_Banner3_EdGraph_0_RefProperty;
    class ABP_ModularLamp_C* BP_Lamp_BASE3_EdGraph_2_RefProperty;
    class ABP_ModularLamp_C* BP_Lamp_BASE2_5_EdGraph_2_RefProperty;

    void UpdateAmbienceAudioComponents();
    void OnRep_BarLightColor();
    void GetEventOrDefaultAmbiance(class USoundCue*& OutAmbiance);
    void Set Beer Event Active(bool Is Active);
    void OnLoaded_C80486AD4277C47F32FE05A37AB96333(UClass* Loaded);
    void ReceiveBeginPlay();
    void OnLeaveSpacerig_Event_0();
    void BndEvt__DockingBayTriggerBox_K2Node_ActorBoundEvent_0_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__InsideDroppodTriggerBox_K2Node_ActorBoundEvent_4_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__DockingBayTriggerBox_AllbarrelsIn_K2Node_ActorBoundEvent_18_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__DockingBayTriggerBox_AllbarrelsIn_K2Node_ActorBoundEvent_48_ActorEndOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__Start_10_K2Node_ActorBoundEvent_0_PlayerSpawnInHub__DelegateSignature(class AFSDPlayerController* Controller);
    void BndEvt__Start_14_K2Node_ActorBoundEvent_2_PlayerSpawnInHub__DelegateSignature(class AFSDPlayerController* Controller);
    void BndEvt__Start_12_K2Node_ActorBoundEvent_3_PlayerSpawnInHub__DelegateSignature(class AFSDPlayerController* Controller);
    void BndEvt__Start_16_K2Node_ActorBoundEvent_5_PlayerSpawnInHub__DelegateSignature(class AFSDPlayerController* Controller);
    void Play medbay banter(class AFSDPlayerController* Player controller);
    void BndEvt__InsideDroppodTriggerBox_AllBarrelsIn_K2Node_ActorBoundEvent_6_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__InsideDroppodTriggerBox_AllBarrelsIn_K2Node_ActorBoundEvent_7_ActorEndOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void OnFreeBeerRewardChanged(bool IsBeersFree);
    void OnCountdownChanged_Event_0(bool Active);
    void StreamSubLevels();
    void BndEvt__LVL_SpaceRig_TriggerBox_TrashCompactor_K2Node_ActorBoundEvent_8_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void SpawnTrashCompactor(float Seed);
    void OnStreamerModeChanged(bool NewValue);
    void HandleEventSpecifics();
    void ExecuteUbergraph_LVL_SpaceRig(int32 EntryPoint);
};

#endif
