#ifndef UE4SS_SDK_MENU_EscapeMenu_HPP
#define UE4SS_SDK_MENU_EscapeMenu_HPP

class UMENU_EscapeMenu_C : public UEscapeMenuWindow
{
    FPointerToUberGraphFrame UberGraphFrame;
    class UBasic_Menu_ColorBar_C* Basic_Menu_ColorBar;
    class UBasic_MenuLabel_C* Basic_MenuLabel_C_0;
    class UBasic_ButtonLargeImage_C* BTN_CallToAction2;
    class UBasic_ButtonCutCorner_C* BTN_ChangeProfile;
    class UBasic_ButtonScalable_C* BTN_Controls;
    class UBasic_ButtonScalable_C* BTN_Credits;
    class UBasic_ButtonScalable_C* BTN_Discord;
    class UHeader_ButtonCutCorner_C* BTN_DLC;
    class UHeader_ButtonCutCorner_C* BTN_DummyModding;
    class UBasic_ButtonCutCorner_C* BTN_Exit;
    class UITM_Special_ButtonCutCorner_C* BTN_Leave;
    class UHeader_ButtonCutCorner_C* BTN_Merch;
    class UHeader_ButtonCutCorner_C* BTN_MinersManual;
    class UHeader_ButtonCutCorner_C* BTN_Modding;
    class UHeader_ButtonCutCorner_C* BTN_News;
    class UHeader_ButtonCutCorner_C* BTN_Options;
    class UHeader_ButtonCutCorner_C* BTN_PatchNotes;
    class UITM_Special_ButtonCutCorner_C* BTN_Reconnect;
    class UBasic_ButtonScalable_C* BTN_Resume;
    class UHeader_ButtonCutCorner_C* BTN_Social;
    class UHeader_ButtonCutCorner_C* BTN_Status;
    class UBasic_ButtonScalable2_C* BTN_Survey2;
    class UVerticalBox* ConsoleBox;
    class UImage* DRG_Logo;
    class UImage* Icon_GhostShip;
    class UITM_MenuBackground_C* ITM_EscapeMenuBackground;
    class UITM_MenuDamageIndicator_C* ITM_MenuDamageIndicator;
    class UITM_RestoreSave_C* ITM_RestoreSave;
    class UBasic_Menu_LargeWindowNoHeader_C* MainMenu;
    class UMenu_StatusScreen_C* Menu_StatusScreen;
    class UUI_AdvancedLabel_C* OptionIconNext;
    class UUI_AdvancedLabel_C* OptionIconPrev;
    class UOverlay* Overlay_Status;
    class UOverlay* Overlay_SubMenuHolder;
    class UUI_PlayerSpeaking_List_C* PlayerSpeaking_List;
    class USafeZone* SafeZone_2;
    class UMenu_Options_C* Menu_Options;
    class UOptions_ControlLayout_C* ControlLayout;
    bool WasUsingCustomScale;
    bool ApplySettingsOnClose;
    FBlueprintSessionResult RejoinSearchResult;
    ESlateVisibility GSG Logo Visibility;
    class U_MENU_MinersManual_C* Menu_MinersManual;
    TArray<class UHeader_ButtonCutCorner_C*> buttons;
    TArray<class UWindowWidget*> Sections;
    class UHeader_ButtonCutCorner_C* SelectedButton;
    class UWindowWidget* SelectedSection;
    EMinersManualSection MMPendingSection;
    FGuid MMPending_ID;
    float MMNotificationShownTime;
    bool IsClosingSection;
    class UMENU_PatchNotes_C* MENU_PatchNotes;
    class UMENU_Modding_C* MENU_Modding;
    class UMenu_DLC_C* Menu_DLC;
    class UMENU_DummyModding_C* MENU_DummyModding;
    bool IsLeftCtrlDown;
    class UMENU_Merch_C* MENU_Merch;

    void Remove Buttons If Condition(TArray<class UHeader_ButtonCutCorner_C*>& InButtons, bool InCondition);
    void Remove Button If Condition(class UHeader_ButtonCutCorner_C* InButton, bool InCondition);
    void Should Modding Menu be Enabled(bool& Result);
    FEventReply OnKeyDown(FGeometry MyGeometry, FKeyEvent InKeyEvent);
    void OnMinersManualOpen(class UObject* IdentifyingObject, bool Open Specific Page, EMinersManualSinglePage page);
    void OnMinersManualNotification(EMinersManualSection PendingSection, FGuid Pending_ID, FText Text);
    void ToggleButton(class UHeader_ButtonCutCorner_C* InButton);
    void OpenSection(class UWindowWidget* InSection);
    FEventReply OnMouseButtonUp(FGeometry MyGeometry, const FPointerEvent& MouseEvent);
    void SetHUDVisible(bool Visible);
    bool NotInParty();
    void UpdateDebugTerrainHash();
    void SetupLeaveButton();
    FEventReply OnKeyUp(FGeometry MyGeometry, FKeyEvent InKeyEvent);
    void OnFailure_B9B49EC34D71CFDC07BF12AA58CE1ADE();
    void OnSuccess_B9B49EC34D71CFDC07BF12AA58CE1ADE();
    void No_AE1052D648D3B4733E52C594A5522CE9();
    void Yes_AE1052D648D3B4733E52C594A5522CE9();
    void No_1ADE94D8445F020C5D27B8822516025E();
    void Yes_1ADE94D8445F020C5D27B8822516025E();
    void No_7D7D93E642CD15AC8E341D8B5ED1ACA8();
    void Yes_7D7D93E642CD15AC8E341D8B5ED1ACA8();
    void Construct();
    void FSDSetFocus();
    void BndEvt__BTN_Discord_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature();
    void PreConstruct(bool IsDesignTime);
    void OnShown();
    void OnClosed();
    void BndEvt__BTN_Resume2_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature();
    void BndEvt__BTN_CallToAction2_K2Node_ComponentBoundEvent_11_OnClicked__DelegateSignature();
    void BndEvt__BTN_Survey2_K2Node_ComponentBoundEvent_12_OnClicked__DelegateSignature();
    void OpenMinersManualSection(class UObject* IdentifyingObject);
    void BndEvt__Basic_ButtonCutCorner_K2Node_ComponentBoundEvent_14_OnClicked__DelegateSignature(class UHeader_ButtonCutCorner_C* Button);
    void BndEvt__BTN_Statuss_K2Node_ComponentBoundEvent_15_OnClicked__DelegateSignature(class UHeader_ButtonCutCorner_C* Button);
    void BndEvt__BTN_Options_K2Node_ComponentBoundEvent_16_OnClicked__DelegateSignature(class UHeader_ButtonCutCorner_C* Button);
    void OpenMinersManualPage(EMinersManualSinglePage page);
    void SelectNextButton();
    void SelectPrevButton();
    void BndEvt__B_Exit_K2Node_ComponentBoundEvent_4_OnClicked__DelegateSignature(class UBasic_ButtonCutCorner_C* Button);
    void BndEvt__B_Leave_K2Node_ComponentBoundEvent_8_OnClicked__DelegateSignature();
    void BndEvt__BTN_ChangeProfile_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature(class UBasic_ButtonCutCorner_C* Button);
    void OnNewTopWindow();
    void BndEvt__BTN_PatchNotes_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature(class UHeader_ButtonCutCorner_C* Button);
    void BndEvt__BTN_Modding_K2Node_ComponentBoundEvent_5_OnClicked__DelegateSignature(class UHeader_ButtonCutCorner_C* Button);
    void BndEvt__ITM_RestoreSave_K2Node_ComponentBoundEvent_6_OnShowRestoreSaveClicked__DelegateSignature();
    void BndEvt__BTN_DLC_K2Node_ComponentBoundEvent_7_OnClicked__DelegateSignature(class UHeader_ButtonCutCorner_C* Button);
    void BndEvt__BTN_DummyModding_K2Node_ComponentBoundEvent_9_OnClicked__DelegateSignature(class UHeader_ButtonCutCorner_C* Button);
    void OpenMinersManualFromID(EMinersManualSection Section, const FGuid& ID);
    void BndEvt__MENU_EscapeMenu_BTN_Merch_K2Node_ComponentBoundEvent_10_OnClicked__DelegateSignature(class UHeader_ButtonCutCorner_C* Button);
    void OnMinersManualClosed(class UWindowWidget* Window);
    void OnCreditsClicked();
    void OnInputSourceChanged(EFSDInputSource InputSource);
    void ExecuteUbergraph_MENU_EscapeMenu(int32 EntryPoint);
};

#endif
