#ifndef UE4SS_SDK_STE_WoodlouseYounglingExplosiveResistance_HPP
#define UE4SS_SDK_STE_WoodlouseYounglingExplosiveResistance_HPP

class USTE_WoodlouseYounglingExplosiveResistance_C : public UStatusEffect
{
};

#endif
