#ifndef UE4SS_SDK_Loadout_GrenadeProxy_NeedleSprayer_HPP
#define UE4SS_SDK_Loadout_GrenadeProxy_NeedleSprayer_HPP

class ALoadout_GrenadeProxy_NeedleSprayer_C : public ALoadout_GrenadeProxy_Stick_C
{
};

#endif
