// BlueprintGeneratedClass BP_Spider_TankBoss_Armor.BP_Spider_TankBoss_Armor_C
// Size: 0x240 (Inherited: 0x238)
struct ABP_Spider_TankBoss_Armor_C : ADestructibleActor {
	struct FPointerToUberGraphFrame UberGraphFrame; // 0x238(0x08)

	void BndEvt__DestructibleComponent_K2Node_ComponentBoundEvent_0_ComponentFractureSignature__DelegateSignature(struct FVector HitPoint, struct FVector HitDirection); // Function BP_Spider_TankBoss_Armor.BP_Spider_TankBoss_Armor_C.BndEvt__DestructibleComponent_K2Node_ComponentBoundEvent_0_ComponentFractureSignature__DelegateSignature
	void ExecuteUbergraph_BP_Spider_TankBoss_Armor(int32_t EntryPoint); // Function BP_Spider_TankBoss_Armor.BP_Spider_TankBoss_Armor_C.ExecuteUbergraph_BP_Spider_TankBoss_Armor
};

