// BlueprintGeneratedClass BPL_UpgradeHelpers.BPL_UpgradeHelpers_C
// Size: 0x28 (Inherited: 0x28)
struct UBPL_UpgradeHelpers_C : UBlueprintFunctionLibrary {

	void UPGDESC_DPS(struct AActor* Item, struct AActor* upgradedItem, struct AFSDPlayerState* Player, struct FText StatName, float Interval, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry, bool HasUpgradedValue); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_DPS
	void FormatUpgradeToEntry(struct FText Text, struct FUpgradeValues UpgradeValues, char StatFormat, char PreviewFormat, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry, bool HasAnyUpgrades); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.FormatUpgradeToEntry
	void FormatUpgrade(struct FUpgradeValues UpgradeValues, char StatFormat, char PreviewFormat, struct UObject* __WorldContext, struct FText BaseText, struct FText UpgradeText, struct FText Value, enum class EItemPreviewStatus Format, bool HasAnyUpgrades); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.FormatUpgrade
	void UPGDESC_Generic(struct AFSDPlayerState* Player, struct AItem* Item, struct UItemUpgrade* upgradeType, bool UseCustomText, struct FText Text, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry, bool HasUpgradedValue); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_Generic
	void UPGDESC_CryoSprayProjectile(struct AItem* Item, struct AFSDPlayerState* Player, struct AProjectile* projectileClass, struct FText UpgradeText, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry, bool HasUpgradedValue); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_CryoSprayProjectile
	void UPGDESC_DamageBonus_Random(struct AItem* Item, struct AFSDPlayerState* Player, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry, bool HasUpgradedValue); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_DamageBonus_Random
	void UPGDESC_HitCounter(struct AItem* Item, struct AFSDPlayerState* Player, struct UWeaponHitCounterComponent* HitCounterClass, struct FText Upgrade Text, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry, bool HasUpgradedValue); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_HitCounter
	void FormatToPercentageNormalized(float Base Value, float Upgrade Value, float Old Upgrade Value, float Final Value, char FormatType, struct UObject* __WorldContext, struct FText Base Text, struct FText Upgrade Text, struct FText Value); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.FormatToPercentageNormalized
	void UPGDESC_AmmoDrivenEx(struct AItem* Item, struct AFSDPlayerState* Player, struct TArray<enum class EAmmoDrivenWeapnUpgradeType> UpgradeTypes, struct TArray<struct FGearStatEntry> GearStats, struct UObject* __WorldContext); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_AmmoDrivenEx
	enum class EItemPreviewStatus FormatPreviewStatus(bool FormatValue, struct FUpgradeValues UpgradeValues, char FormatType, struct UObject* __WorldContext); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.FormatPreviewStatus
	void UPGDESC_DualMPs(struct AItem* Item, struct AFSDPlayerState* Player, enum class EDualMachinePistolsUpgrades upgradeType, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry, bool HasUpgradedValue); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_DualMPs
	void UPGDESC_SentryGun(struct AItem* Item, struct AFSDPlayerState* Player, enum class ESentryGunUpgradeType Upgrade Type, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry, bool Has Upgraded Value); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_SentryGun
	void UPGDESC_Detpack(struct AItem* Item, struct AFSDPlayerState* PlayerState, enum class EDetPackUpgrades upgradeType, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry, bool HasUpgradedValue); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_Detpack
	void UPGDESC_Flaregun(struct AItem* Item, struct AFSDPlayerState* PlayerState, enum class EFlaregunUpgrades upgradeType, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry, bool HasUpgradedValue); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_Flaregun
	void UPGDESC_ArmorStat(struct AFSDPlayerState* Player, struct AArmorPiece* armorClass, struct UPawnStat* Stat, struct FText Text, char Format, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry, bool Changed); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_ArmorStat
	void UPGDESC_TriggeredStat(struct AFSDPlayerState* Player, struct AActor* Item, struct UStatusEffect* Status Effect, struct FText Text, enum class ETriggeredStatusEffectType Type, char Format, struct UObject* __WorldContext, struct FGearStatEntry gear stat entry, bool is upgraded); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_TriggeredStat
	void UPGDESC_PlatformGun(struct AItem* Item, struct AFSDPlayerState* Player, enum class EPlatformGunUpgrades upgradeType, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry, bool Should show text); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_PlatformGun
	void UPGDESC_Bosco(struct AActor* upgradedItem, struct AFSDPlayerState* Player, enum class EBoscoUpgrades upgradeType, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry, bool HasChanged); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_Bosco
	void UPGDESC_CoooldownAggregator(struct AItem* Item, struct AFSDPlayerState* Player, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry, bool HasUpgradedValue); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_CoooldownAggregator
	void UPGDESC_GrapplingHook(struct AItem* Item, struct AFSDPlayerState* Player, enum class EGrapplingHookUpgrade upgradeType, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry, bool HasUpgradedValue); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_GrapplingHook
	void UPGDESC_FlaregunProjectile(struct AItem* Item, struct AFSDPlayerState* Player, enum class EFlaregunProjectileUpgrades upgradeType, struct AActor* upgradedActor, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry, bool HasUpgradedValue); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_FlaregunProjectile
	void UPGDESC_ZiplineGun(struct AItem* Item, struct AFSDPlayerState* Player, enum class EZiplineGunUpgrades upgradeType, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry, bool HasUpgradedValue); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_ZiplineGun
	void UPGDESC_Grenades(struct AGrenade* Item, struct AFSDPlayerState* Player, enum class EGrenadeUpgradeType upgradeType, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_Grenades
	void UPGDESC_Pickaxe(struct AItem* Item, struct AFSDPlayerState* Player, enum class EPickaxeUpgradeType upgradeType, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry, bool HasUpgradedValue); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_Pickaxe
	void UPGDESC_LineCutterProjectile(struct AItem* Item, struct AFSDPlayerState* Player, enum class ELineCutterProjectileUpgradeType upgradeType, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry, bool HasUpgradedValue); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_LineCutterProjectile
	void UPGDESC_CombatShotgun(struct AItem* Item, struct AFSDPlayerState* Player, enum class EAutoShotgunUpgrades upgradeType, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry, bool HasUpgradedValue); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_CombatShotgun
	void UPGDESC_ChargedProjectile(struct AItem* Item, struct AFSDPlayerState* Player, enum class EChargedProjectileUpgrades upgradeType, struct AActor* upgradedActor, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry, bool HasUpgradedValue); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_ChargedProjectile
	void UPGDESC_StickyFlame(struct AItem* Item, struct AFSDPlayerState* Player, struct UStatusEffect* StatusEffect, struct FText Text, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry, bool HasUpgradedValue); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_StickyFlame
	void UPGDESC_SawedOff(struct AItem* Item, struct AFSDPlayerState* Player, enum class ESawedOffShotgunUpgrades upgradeType, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry, bool HasUpgradedValue); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_SawedOff
	void UPGDESC_Armor(struct AFSDPlayerState* Player, struct AArmorPiece* armorClass, enum class EArmorUpgradeType Armor Upgrade Type, struct FText Text, char Format, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_Armor
	void UPGDESC_BurstWeapon(struct AItem* Item, struct AFSDPlayerState* Player, enum class EBurstWeaponUpgrades upgradeType, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry, bool HasUpgradedValue); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_BurstWeapon
	void UPGDESC_DamageBonus_AoEFear(struct AItem* Item, struct AFSDPlayerState* Player, struct FText StatName, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry, bool HasUpgradedValue); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_DamageBonus_AoEFear
	void UPGDESC_DamageBonus_HotBullets(struct AItem* Item, struct AFSDPlayerState* Player, struct UDamageClass* DamageClass, struct FText StatName, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry, bool HasUpgradedValue); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_DamageBonus_HotBullets
	void UPGDESC_BeltDriven(struct AItem* Item, struct AFSDPlayerState* Player, enum class EBeltDrivenWeaponUpgrade upgradeType, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry, bool HasUpgradedValue); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_BeltDriven
	void UPGDESC_AutoCannon(struct AItem* Item, struct AFSDPlayerState* Player, enum class EAutoCannonUpgrades upgradeType, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry, bool HasUpgradedValue); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_AutoCannon
	void FormatValues(struct FUpgradeValues UpgradeValues, char Format, struct UObject* __WorldContext, struct FText BaseText, struct FText UpgradeText, struct FText Value); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.FormatValues
	void UPGDESC_AssaultRifle(struct AItem* Item, struct AFSDPlayerState* Player, enum class EAssaultRifleUpgrade upgradeType, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry, bool HasUpgradedValue); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_AssaultRifle
	void UPGDESC_GatlingGun(struct AItem* Item, struct AFSDPlayerState* Player, enum class EGatlingGunUpgrade upgradeType, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry, bool HasUpgradedValue); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_GatlingGun
	void UPGDESC_ShieldRegenerator(struct AItem* Item, struct AFSDPlayerState* Player, enum class EArmorRegeneratorUpgrades upgradeType, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry, bool HasUpgradedValue); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_ShieldRegenerator
	void FormatCmtoM(float Base Value, float Upgrade Value, float Old Upgrade Value, float Final Value, struct UObject* __WorldContext, struct FText Base Text, struct FText Upgrade Text, struct FText Value); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.FormatCmtoM
	void FormatPercentage(float Base Value, float Upgraded Value, float Old Upgraded Value, float Final Value, char Format, struct UObject* __WorldContext, struct FText Base Text, struct FText Upgrade Text, struct FText Value); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.FormatPercentage
	void UPGDESC_Cryospray(struct AItem* Item, struct AFSDPlayerState* Player, enum class ECryoSprayUpgrades upgradeType, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry, bool HasUpgradedValue); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_Cryospray
	void UPGDESC_FlameThrower(struct AItem* Item, struct AFSDPlayerState* Player, enum class EFlameThrowerUpgradeType upgradeType, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry, bool HasUpgradedValue); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_FlameThrower
	void UPGDESC_ChargedWeapon(struct AItem* Item, struct AFSDPlayerState* Player, enum class EChargedWeaponUpgrades upgradeType, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry, bool HasUpgradedValue); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_ChargedWeapon
	void UPGDESC_Projectile(struct AActor* Item, struct AActor* upgradedItem, struct AFSDPlayerState* Player, enum class EProjectileUpgrade upgradeType, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry, bool HasUpgradedValue); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_Projectile
	void UPGDESC_BoltAction(struct AItem* Item, struct AFSDPlayerState* Player, enum class EBoltActionRifleUpgrades upgradeType, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry, bool HasUpgradedValue); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_BoltAction
	void UPGDESC_DamageBonus_TargetStateBonus(struct AItem* Item, struct AFSDPlayerState* Player, struct FText StatName, enum class ETargetStateDamageBonusType TargetState, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry, bool HasUpgradedValue); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_DamageBonus_TargetStateBonus
	void UPGDESC_DamageBonus_TargetTypeBonus(struct AItem* Item, struct AFSDPlayerState* Player, struct FText StatName, struct FName Key, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry, bool HasUpgradedValue); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_DamageBonus_TargetTypeBonus
	void UPGDESC_DamageBonus_StatusBonus(struct AItem* Item, struct AFSDPlayerState* Player, struct UStatusEffect* SstatusEffectIn, struct FText StatName, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry, bool HasUpgradedValue); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_DamageBonus_StatusBonus
	void UPGDESC_ElectricalSMG(struct AItem* Item, struct AFSDPlayerState* Player, enum class EElectricalSMGUpgrades upgradeType, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry, bool HasUpgradedValue); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_ElectricalSMG
	void UPGDESC_DamageBonus_Flat(struct AItem* Item, struct AFSDPlayerState* Player, struct UDamageClass* DamageClass, struct FText StatName, char FormatType, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry, bool HasUpgradedValue); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_DamageBonus_Flat
	void UPGDESC_DamageBonus_DamageConversion(struct AItem* Item, struct AActor* upgradedItem, struct AFSDPlayerState* Player, struct UDamageClass* DamageClass, struct FText StatName, bool OverrideStatType, char StatTypeOverride, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry, bool HasUpgradedValue); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_DamageBonus_DamageConversion
	void UPGDESC_DamageBonus_PushStatus(struct AActor* Item, struct AFSDPlayerState* Player, struct UStatusEffect* StatusEffect, struct FText StatName, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry, bool HasUpgradedValue); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_DamageBonus_PushStatus
	void UPGDESC_AmmoDriven(struct AItem* Item, struct AFSDPlayerState* Player, enum class EAmmoDrivenWeapnUpgradeType upgradeType, bool OverrideStatType, char StatTypeOverride, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry, bool HasAnyUpgrades); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_AmmoDriven
	void FormatValue(float BaseValue, float UpgradeValue, float OldUpgradeValue, enum class EItemPreviewStatus PreviewStatus, float FinalValue, char Format, struct UObject* __WorldContext, struct FText BaseText, struct FText UpgradeText, struct FText Value); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.FormatValue
	void UPGDESC_Damage(struct AActor* Item, struct AActor* upgradedItem, struct AFSDPlayerState* Player, enum class EDamageUpgrade upgradeType, struct FText Prefix, enum class EDamageComponentType DamageComponentType, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry, bool HasUpgradedValue); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_Damage
	void UPGDESC_HitScan(struct AItem* Item, struct AFSDPlayerState* Player, enum class EHitScanBaseUpgradeType upgradeType, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry, bool HasAnyUpgrades); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_HitScan
	void UPGDESC_SingleUsable_UseDuration(struct AItem* Item, struct AActor* subItem, struct AFSDPlayerState* Player, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_SingleUsable_UseDuration
	void UPGDESC_SentryGun_Capacity(struct AItem* Item, struct AFSDPlayerState* Player, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_SentryGun_Capacity
	void UPGDESC_Item(struct AFSDPlayerState* Player, struct AItem* Item, enum class EInventoryItemUpgradeType upgradeType, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry, bool HasUpgradedValue); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_Item
	void UPGDESC_Flare_Base(struct AFlare* flareClass, struct AFSDPlayerState* Player, enum class EFlareUpgradeType upgradeType, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_Flare_Base
	void UPGDESC_Drills(struct AItem* Item, struct AFSDPlayerState* Player, enum class EDoubleDrillUpgradeType upgradeType, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry, bool Has Upgraded Value); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_Drills
	void UPGDESC_Capacity(struct AActor* upgradedItem, struct AFSDPlayerState* Player, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_Capacity
	void UPGDESC_Explosion_Damage(struct AActor* upgradedItem, struct AActor* componentItem, struct AFSDPlayerState* Player, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_Explosion_Damage
	void UPGDESC_Explosion_Radius(struct AActor* upgradedItem, struct AActor* componentItem, struct AFSDPlayerState* Player, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_Explosion_Radius
	void UPGDESC_HitScan_Bullets(struct AItem* Item, struct AFSDPlayerState* Player, struct UObject* __WorldContext, struct FGearStatEntry GearStatEntry, bool HasUpgradedValue); // Function BPL_UpgradeHelpers.BPL_UpgradeHelpers_C.UPGDESC_HitScan_Bullets
};

