#ifndef UE4SS_SDK_ITM_CommunityGoal_TotalProgress_HPP
#define UE4SS_SDK_ITM_CommunityGoal_TotalProgress_HPP

class UITM_CommunityGoal_TotalProgress_C : public UFSDUserWidget
{
    FPointerToUberGraphFrame UberGraphFrame;
    class UButton* BackgroundButton;
    class UButton* Button_Goal_0;
    class UButton* Button_Goal_1;
    class UButton* Button_Goal_2;
    class UButton* Button_Goal_3;
    class UButton* Button_Goal_4;
    class UButton* Button_Goal_5;
    class UButton* Button_Goal_6;
    class UButton* Button_Goal_7;
    class UButton* Button_Goal_8;
    class UCheckBox* CheckBox_Goal_0;
    class UCheckBox* CheckBox_Goal_1;
    class UCheckBox* CheckBox_Goal_2;
    class UCheckBox* CheckBox_Goal_3;
    class UCheckBox* CheckBox_Goal_4;
    class UCheckBox* CheckBox_Goal_5;
    class UCheckBox* CheckBox_Goal_6;
    class UCheckBox* CheckBox_Goal_7;
    class UCheckBox* CheckBox_Goal_8;
    class UButton* FactionIconToolTip;
    class UImage* Image_132;
    class UImage* Image_524;
    class UImage* Image_Goal_0;
    class UImage* Image_Goal_1;
    class UImage* Image_Goal_2;
    class UImage* Image_Goal_3;
    class UImage* Image_Goal_4;
    class UImage* Image_Goal_5;
    class UImage* Image_Goal_6;
    class UImage* Image_Goal_7;
    class UImage* Image_Goal_8;
    class UProgressBar* ProgressBar_0;
    class UProgressBar* ProgressBar_1;
    class UProgressBar* ProgressBar_2;
    class UProgressBar* ProgressBar_3;
    class UProgressBar* ProgressBar_4;
    class UProgressBar* ProgressBar_5;
    class UProgressBar* ProgressBar_6;
    class UProgressBar* ProgressBar_7;
    class UProgressBar* ProgressBar_8;
    class UTextBlock* Title_Text;
    class UUI_ImageTinted_C* UI_ImageTinted;
    float AnimTime;
    float TotalAnimTime;
    float CurrentProgress;
    float CurrentlyTopGoalProgress;
    float ProgressBarAnimSpeed;
    bool Show_Title;
    FLinearColor CheckColorTier1;
    FLinearColor UnCheckColorTier1;
    FLinearColor CheckColorTier2;
    FLinearColor UnCheckColorTier2;
    FLinearColor CheckColorTier3;
    FLinearColor UnCheckColorTier3;
    FLinearColor BarColor;
    FITM_CommunityGoal_TotalProgress_CHoverStarted HoverStarted;
    void HoverStarted(class UCommunityGoalFaction* Faction, class UCommunityGoal* Goal);
    FITM_CommunityGoal_TotalProgress_CHoverEnded HoverEnded;
    void HoverEnded();
    class UITM_CommunityGoalRewardToolTip_C* ToolTip;
    class UITM_FactionToolTip_C* FactionToolTip;

    void DoFactionToolTip();
    void SendButtonToolTipOpen(class UWidget* Button, int32 Tier);
    FLinearColor Get_Image_Goal_8_ColorAndOpacity_0();
    FLinearColor Get_Image_Goal_7_ColorAndOpacity_0();
    FLinearColor Get_Image_Goal_6_ColorAndOpacity_0();
    FLinearColor Get_Image_Goal_5_ColorAndOpacity_0();
    FLinearColor Get_Image_Goal_4_ColorAndOpacity_0();
    FLinearColor Get_Image_Goal_3_ColorAndOpacity_0();
    FLinearColor Get_Image_Goal_2_ColorAndOpacity_0();
    FLinearColor Get_Image_Goal_1_ColorAndOpacity_0();
    FLinearColor Get_Image_Goal_0_ColorAndOpacity_0();
    void IncreaseTotalGoalsProgressByGoal(class UCommunityGoal* Goal, float Value, int32 memberCount);
    float ProgressBar_8_Percent_0();
    float ProgressBar_7_Percent_0();
    float ProgressBar_6_Percent_0();
    float ProgressBar_5_Percent_0();
    float ProgressBar_4_Percent_0();
    float ProgressBar_3_Percent_0();
    float ProgressBar_2_Percent_0();
    float ProgressBar_1_Percent_0();
    float ProgressBar_0_Percent_0();
    void ResetAnim();
    void PreConstruct(bool IsDesignTime);
    void Tick(FGeometry MyGeometry, float InDeltaTime);
    void SetGoals(const TArray<FString>& GoalID, const TArray<float>& GoalValue, const TArray<int32>& Members);
    void SetGoalsTier(float TierProgress);
    void BndEvt__BackgroundButton_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__BackgroundButton_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__Button_Goal_1_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__Button_Goal_0_K2Node_ComponentBoundEvent_3_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__Button_Goal_2_K2Node_ComponentBoundEvent_4_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__Button_Goal_3_K2Node_ComponentBoundEvent_6_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__Button_Goal_4_K2Node_ComponentBoundEvent_7_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__Button_Goal_5_K2Node_ComponentBoundEvent_8_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__Button_Goal_6_K2Node_ComponentBoundEvent_9_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__Button_Goal_7_K2Node_ComponentBoundEvent_10_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__Button_Goal_8_K2Node_ComponentBoundEvent_11_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__Button_Goal_0_K2Node_ComponentBoundEvent_12_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__Button_Goal_1_K2Node_ComponentBoundEvent_13_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__Button_Goal_2_K2Node_ComponentBoundEvent_14_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__Button_Goal_4_K2Node_ComponentBoundEvent_15_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__Button_Goal_3_K2Node_ComponentBoundEvent_16_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__Button_Goal_5_K2Node_ComponentBoundEvent_17_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__Button_Goal_6_K2Node_ComponentBoundEvent_18_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__Button_Goal_7_K2Node_ComponentBoundEvent_19_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__Button_Goal_8_K2Node_ComponentBoundEvent_20_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__FactionIconToolTip_K2Node_ComponentBoundEvent_5_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__FactionIconToolTip_K2Node_ComponentBoundEvent_21_OnButtonHoverEvent__DelegateSignature();
    void Construct();
    void ExecuteUbergraph_ITM_CommunityGoal_TotalProgress(int32 EntryPoint);
    void HoverEnded__DelegateSignature();
    void HoverStarted__DelegateSignature(class UCommunityGoalFaction* Faction, class UCommunityGoal* Goal);
};

#endif
