#ifndef UE4SS_SDK__SCREEN_MissionSelectionMK3_HPP
#define UE4SS_SDK__SCREEN_MissionSelectionMK3_HPP

class U_SCREEN_MissionSelectionMK3_C : public UWindowWidget
{
    FPointerToUberGraphFrame UberGraphFrame;
    class UAnimatedStaticOverlay_WithScanlines_C* AnimatedStaticOverlay_WithScanlines;
    class UBasic_ButtonScalable2_C* BTN_Close;
    class UBasic_ButtonScalable2_C* BTN_Join;
    class UBasic_ButtonScalable2_C* BTN_ServerList;
    class UCanvasPanel* CanvasPanel_PannerOuter;
    class UImage* ImageAsteroids01;
    class UImage* ImageAsteroids02;
    class UImage* ImageClouds01;
    class UImage* ImageClouds02;
    class UITM_MisSel_Biome_C* ITEM_Biome_AzureWeald;
    class UITM_MisSel_Biome_C* ITEM_Biome_Crystal;
    class UITM_MisSel_Biome_C* ITEM_Biome_Dense;
    class UITM_MisSel_Biome_C* ITEM_Biome_Fungus;
    class UITM_MisSel_Biome_C* ITEM_Biome_Glacial;
    class UITM_MisSel_Biome_C* ITEM_Biome_HollowBough;
    class UITM_MisSel_Biome_C* ITEM_Biome_Magma;
    class UITM_MisSel_Biome_C* ITEM_Biome_Radioactive;
    class UITM_MisSel_Biome_C* ITEM_Biome_Salt;
    class UITM_MisSel_Biome_C* ITEM_Biome_Sandblasted;
    class UITM_MisSel_BG_Planet_C* ITEM_MissionSelection_BG;
    class UITM_MisSel_FullBiome_C* ITEM_MissionSelection_FullBiome;
    class UITM_MisSel_Timer_C* ITEM_MissionSelection_Timer;
    class UITM_CampaignProgress_C* ITM_CampaignProgressMain;
    class UITM_Challenge_InfoBox_C* ITM_Challenge_InfoBox;
    class UITM_MisSel_ZoneLock_C* ITM_LockZone_2;
    class UITM_MisSel_ZoneLock_C* ITM_LockZone_3;
    class UITM_MisSel_ZoneLock_C* ITM_LockZone_4;
    class ULobby_BarTop_Countdown_C* Lobby_BarTop_Countdown;
    class USafeZone* PlatformSafeZone;
    class UITM_MisSel_ZoneImage_C* Region_AzureWeald;
    class UITM_MisSel_ZoneImage_C* Region_CrystallineCaverns;
    class UITM_MisSel_ZoneImage_C* Region_DenseBiozone;
    class UITM_MisSel_ZoneImage_C* Region_FungusBogs;
    class UITM_MisSel_ZoneImage_C* Region_GlacialStrata;
    class UITM_MisSel_ZoneImage_C* Region_HollowBough;
    class UITM_MisSel_ZoneImage_C* Region_MagmaCore;
    class UITM_MisSel_ZoneImage_C* Region_Radioactive;
    class UITM_MisSel_ZoneImage_C* Region_SaltPits;
    class UITM_MisSel_ZoneImage_C* Region_Sandblasted;
    class UHorizontalBox* SelectionBox_Active;
    class UUI_AdvancedLabel_C* UI_AdvancedLabel;
    class UUI_PlayerSpeaking_List_C* UI_PlayerSpeaking_List;
    class UWND_MisSel_BiomeDescription_C* WINDOW_MissionSelection_BiomeDescription;
    class UWND_MisSel_MissionDescription_C* WINDOW_MissionSelection_MissionDescription;
    class UWND_MisSel_MissionOptions_C* WINDOW_MissionSelection_MissionOptions;
    class UImage* Zone_Outlines;
    class UImage* ZoneBorders;
    TArray<class UITM_MisSel_Biome_C*> Biomes;
    class UITM_MisSel_MissionMapIcon_C* SelectedMissionIcon;
    class UITM_MisSel_Biome_C* SelectedBiome;
    TArray<class UITM_MisSel_ZoneLock_C*> ZoneLocks;
    TArray<class UBiome*> NewBiomes;
    FVector2D CurrPos;
    FVector2D TargetPos;
    bool IsBiomeHovered;
    bool CanParalaxCamera;
    float BiomeHoverStartTime;

    void HighlightChallenges(const TArray<class UObject*>& assetReferences, bool ShouldHighlight, class USeasonChallenge* challenge, int32 Temp_int_Loop_Counter_Variable, class UMissionGenerationManager* CallFunc_GetGameInstanceSubsystem_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, TArray<class UGeneratedMission*>& CallFunc_GetAvailableMissions_ReturnValue, int32 Temp_int_Loop_Counter_Variable_1, int32 CallFunc_Add_IntInt_ReturnValue_1, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Array_Index_Variable_1, int32 Temp_int_Loop_Counter_Variable_2, int32 CallFunc_Add_IntInt_ReturnValue_2, int32 Temp_int_Array_Index_Variable_2, class UTexture2D* CallFunc_GetIconOutlined_ReturnValue, class UTexture2D* CallFunc_GetIconOutlined_ReturnValue_1, int32 Temp_int_Loop_Counter_Variable_3, class UObject* CallFunc_Array_Get_Item, class UMissionTemplate* K2Node_DynamicCast_AsMission_Template, bool K2Node_DynamicCast_bSuccess, class UBiome* K2Node_DynamicCast_AsBiome, bool K2Node_DynamicCast_bSuccess_1, int32 CallFunc_Add_IntInt_ReturnValue_3, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_IsValid_ReturnValue, int32 Temp_int_Array_Index_Variable_3, bool Temp_bool_True_if_break_was_hit_Variable, bool CallFunc_Not_PreBool_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_1, class UITM_MisSel_Biome_C* CallFunc_Array_Get_Item_1, bool CallFunc_Less_IntInt_ReturnValue_1, class UITM_MisSel_Biome_C* CallFunc_Array_Get_Item_2, int32 CallFunc_Array_Length_ReturnValue_2, bool CallFunc_Less_IntInt_ReturnValue_2, TArray<class UGeneratedMission*>& CallFunc_GetMissionsForBiome_Missions, class UGeneratedMission* CallFunc_Array_Get_Item_3, bool CallFunc_EqualEqual_ObjectObject_ReturnValue, bool CallFunc_EqualEqual_ObjectObject_ReturnValue_1, int32 CallFunc_Array_Length_ReturnValue_3, bool CallFunc_Less_IntInt_ReturnValue_3, bool CallFunc_BooleanAND_ReturnValue);
    FEventReply OnKeyDown(FGeometry MyGeometry, FKeyEvent InKeyEventbool CallFunc_HandleKeyDown_OutHandled, FEventReply CallFunc_HandleKeyDown_OutReply);
    void ClearServerListMissionRestrictions(class APlayerController* CallFunc_GetPlayerController_ReturnValue, class ABP_PlayerController_SpaceRig_C* K2Node_DynamicCast_AsBP_Player_Controller_Space_Rig, bool K2Node_DynamicCast_bSuccess, class U_MENU_ServerList_C* K2Node_DynamicCast_As_MENU_Server_List, bool K2Node_DynamicCast_bSuccess_1);
    FEventReply OnMouseButtonUp(FGeometry MyGeometry, const FPointerEvent& MouseEventFEventReply CallFunc_Unhandled_ReturnValue, bool CallFunc_IsBackMenuMouse_ReturnValue, FEventReply CallFunc_Handled_ReturnValue);
    void UpdateMapPan(bool SnapToMouse, float NewLocalVar_1, float SpeedFactor, bool IsMissSelected, FVector2D BG_OriginalOffset, FVector2D MaxPanDistance, float Delta, FVector2D Diff, bool Temp_bool_Variable, FVector2D CallFunc_Multiply_Vector2DFloat_ReturnValue, class UCanvasPanelSlot* CallFunc_SlotAsCanvasSlot_ReturnValue, FVector2D CallFunc_Multiply_Vector2DFloat_ReturnValue_1, class UCanvasPanelSlot* CallFunc_SlotAsCanvasSlot_ReturnValue_1, FVector2D CallFunc_Multiply_Vector2DFloat_ReturnValue_2, class UFSDGameUserSettings* CallFunc_FSDGameUserSettings_ReturnValue, class UCanvasPanelSlot* CallFunc_SlotAsCanvasSlot_ReturnValue_2, bool CallFunc_GetShowUIAnimations_ReturnValue, float CallFunc_GetRealTimeSeconds_ReturnValue, float CallFunc_GetRealTimeSeconds_ReturnValue_1, float CallFunc_Subtract_FloatFloat_ReturnValue, float CallFunc_Divide_FloatFloat_ReturnValue, float CallFunc_Subtract_FloatFloat_ReturnValue_1, float CallFunc_Multiply_FloatFloat_ReturnValue, bool CallFunc_GreaterEqual_FloatFloat_ReturnValue, float CallFunc_FClamp_ReturnValue, float CallFunc_SelectFloat_ReturnValue, float CallFunc_SelectFloat_ReturnValue_1, bool CallFunc_IsValid_ReturnValue, FVector2D CallFunc_Subtract_Vector2DVector2D_ReturnValue, FVector2D CallFunc_Multiply_Vector2DFloat_ReturnValue_3, float CallFunc_BreakVector2D_X, float CallFunc_BreakVector2D_Y, FVector2D CallFunc_Add_Vector2DVector2D_ReturnValue, float CallFunc_BreakVector2D_X_1, float CallFunc_BreakVector2D_Y_1, FMargin K2Node_MakeStruct_Margin, bool CallFunc_IsVisible_ReturnValue, class UCanvasPanelSlot* CallFunc_SlotAsCanvasSlot_ReturnValue_3, float CallFunc_VSize2D_ReturnValue, bool CallFunc_LessEqual_FloatFloat_ReturnValue, bool CallFunc_BooleanOR_ReturnValue, FVector2D CallFunc_Normal2D_ReturnValue, FVector2D CallFunc_Multiply_Vector2DFloat_ReturnValue_4, float CallFunc_VSize2D_ReturnValue_1, float CallFunc_Multiply_FloatFloat_ReturnValue_1, FVector2D CallFunc_Add_Vector2DVector2D_ReturnValue_1, float CallFunc_FClamp_ReturnValue_1, FVector2D K2Node_Select_Default, FVector2D CallFunc_Subtract_Vector2DVector2D_ReturnValue_1, FVector2D CallFunc_Multiply_Vector2DFloat_ReturnValue_5, float CallFunc_GetWorldDeltaSeconds_ReturnValue, class UCanvasPanelSlot* CallFunc_SlotAsCanvasSlot_ReturnValue_4, float CallFunc_Multiply_FloatFloat_ReturnValue_2, float CallFunc_Multiply_FloatFloat_ReturnValue_3, FVector2D CallFunc_Multiply_Vector2DFloat_ReturnValue_6, FVector2D CallFunc_GetViewportSize_ReturnValue, float CallFunc_BreakVector2D_X_2, float CallFunc_BreakVector2D_Y_2, class UCanvasPanelSlot* CallFunc_SlotAsCanvasSlot_ReturnValue_5, class APlayerController* CallFunc_GetPlayerController_ReturnValue, float CallFunc_GetMousePosition_LocationX, float CallFunc_GetMousePosition_LocationY, bool CallFunc_GetMousePosition_ReturnValue, float CallFunc_Divide_FloatFloat_ReturnValue_1, float CallFunc_Divide_FloatFloat_ReturnValue_2, FVector2D CallFunc_MakeVector2D_ReturnValue, FVector2D CallFunc_Subtract_Vector2DFloat_ReturnValue, FVector2D CallFunc_Multiply_Vector2DFloat_ReturnValue_7, FVector2D CallFunc_Multiply_Vector2DFloat_ReturnValue_8, FVector2D CallFunc_ClampAxes2D_ReturnValue, FVector2D CallFunc_Multiply_Vector2DVector2D_ReturnValue);
    void CheckForNewZones(TArray<class UBiome*> NewLocalVar_0, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, class UITM_MisSel_ZoneLock_C* CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, TArray<class UObject*>& K2Node_MakeArray_Array, const TArray<class UBiome*>& CallFunc_GetBiomes_ReturnValue, bool CallFunc_CheckItemUINotification_HasNotification);
    void GetAvailableBiomes(TArray<class UITM_MisSel_Biome_C*>& AvailableBiomes1, TArray<class UITM_MisSel_Biome_C*> AvailableBiomes, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable, bool Temp_bool_True_if_break_was_hit_Variable, int32 Temp_int_Array_Index_Variable_1, bool CallFunc_Not_PreBool_ReturnValue, class UMissionGenerationManager* CallFunc_GetGameInstanceSubsystem_ReturnValue, TArray<class UGeneratedMission*>& CallFunc_GetAvailableMissions_ReturnValue, class UGeneratedMission* CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, int32 Temp_int_Loop_Counter_Variable_1, class UITM_MisSel_Biome_C* CallFunc_Array_Get_Item_1, int32 CallFunc_Array_Length_ReturnValue_1, int32 CallFunc_Array_Add_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_EqualEqual_ObjectObject_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue_1, int32 CallFunc_Add_IntInt_ReturnValue_1, bool CallFunc_BooleanAND_ReturnValue);
    void GetMode(TEnumAsByte<EMissionSelection_Mode::Type>& Mode);
    void ShouldEnableQuickJoin(bool& Show, EFSDTargetPlatform Temp_byte_Variable, bool Temp_bool_Variable, bool Temp_bool_Variable_1, bool Temp_bool_Variable_2, bool Temp_bool_Variable_3, bool Temp_bool_Variable_4, EFSDTargetPlatform CallFunc_FSDTargetPlatform_ReturnValue, bool K2Node_Select_Default, bool CallFunc_IsPlayingOffline_ReturnValue, class AGameModeBase* CallFunc_GetGameMode_ReturnValue, class AFSDGameModeSpaceRig* K2Node_DynamicCast_AsFSDGame_Mode_Space_Rig, bool K2Node_DynamicCast_bSuccess, bool CallFunc_Not_PreBool_ReturnValue, bool CallFunc_BooleanOR_ReturnValue);
    void HandleButtonVisibility(EFSDTargetPlatform Temp_byte_Variable, bool Temp_bool_Variable, bool Temp_bool_Variable_1, bool Temp_bool_Variable_2, bool Temp_bool_Variable_3, bool Temp_bool_Variable_4, EFSDTargetPlatform Temp_byte_Variable_1, bool Temp_bool_Variable_5, bool Temp_bool_Variable_6, bool Temp_bool_Variable_7, bool Temp_bool_Variable_8, bool Temp_bool_Variable_9, bool Temp_bool_Variable_10, ESlateVisibility Temp_byte_Variable_2, ESlateVisibility Temp_byte_Variable_3, EFSDTargetPlatform Temp_byte_Variable_4, ESlateVisibility Temp_byte_Variable_5, ESlateVisibility Temp_byte_Variable_6, ESlateVisibility Temp_byte_Variable_7, ESlateVisibility Temp_byte_Variable_8, ESlateVisibility Temp_byte_Variable_9, bool CallFunc_ShouldEnableQuickJoin_show, EFSDTargetPlatform CallFunc_FSDTargetPlatform_ReturnValue, class UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue, bool K2Node_Select_Default, EFSDTargetPlatform CallFunc_FSDTargetPlatform_ReturnValue_1, bool K2Node_Select_Default_1, ESlateVisibility K2Node_Select_Default_2, bool CallFunc_BooleanAND_ReturnValue, bool CallFunc_BooleanOR_ReturnValue, ESlateVisibility K2Node_Select_Default_3);
    void GetMission_CheckBiome(class UGeneratedMission*& mission, bool CallFunc_IsValid_ReturnValue, bool CallFunc_EqualEqual_ObjectObject_ReturnValue);
    FEventReply OnKeyUp(FGeometry MyGeometry, FKeyEvent InKeyEventFEventReply CallFunc_Handled_ReturnValue, FKey CallFunc_GetKey_ReturnValue, bool CallFunc_EqualEqual_KeyKey_ReturnValue, bool CallFunc_IsCloseOrBackMenu_ReturnValue, FEventReply CallFunc_Unhandled_ReturnValue, FEventReply CallFunc_Handled_ReturnValue_1);
    void GetMission(class UGeneratedMission*& mission, bool CallFunc_IsValid_ReturnValue);
    bool IsMissionLocked(class UGeneratedMission* missionclass ABP_PlayerController_SpaceRig_C* CallFunc_GetController_AsBP_Player_Controller_Space_Rig, bool CallFunc_IsLocked_ReturnValue);
    void GetActiveSelectionMode(TEnumAsByte<EMissionSelection_Mode::Type>& NewParam, bool Temp_bool_Variable, TEnumAsByte<EMissionSelection_Mode::Type> Temp_byte_Variable, TEnumAsByte<EMissionSelection_Mode::Type> Temp_byte_Variable_1, class UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue, TEnumAsByte<EMissionSelection_Mode::Type> K2Node_Select_Default, class AGameModeBase* CallFunc_GetGameMode_ReturnValue, class AFSDGameModeSpaceRig* K2Node_DynamicCast_AsFSDGame_Mode_Space_Rig, bool K2Node_DynamicCast_bSuccess, class UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_1, class AFSDGameState* CallFunc_GetFSDGameState_ReturnValue, bool CallFunc_HasAuthority_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue);
    void GetController(class ABP_PlayerController_SpaceRig_C*& AsBP Player Controller Space Rig, class APlayerController* CallFunc_GetPlayerController_ReturnValue, class ABP_PlayerController_SpaceRig_C* K2Node_DynamicCast_AsBP_Player_Controller_Space_Rig, bool K2Node_DynamicCast_bSuccess);
    void GetMissionBiome(class UBiome* Biome, class UITM_MisSel_Biome_C*& Array Element, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, class UITM_MisSel_Biome_C* CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_EqualEqual_ObjectObject_ReturnValue);
    void OnFailure_ED6FBDF64F71976389535788275C482E();
    void OnSuccess_ED6FBDF64F71976389535788275C482E();
    void PreConstruct(bool IsDesignTime);
    void Construct();
    void BndEvt__CheckBox_Solo_K2Node_ComponentBoundEvent_22_OnCheckBoxComponentStateChanged__DelegateSignature(bool bIsChecked);
    void BiomeHovered(class UITM_MisSel_Biome_C* Biome);
    void BiomeSelected(class UITM_MisSel_Biome_C* Biome);
    void ShowMission();
    void ShowPlanet();
    void MissionHover(class UGeneratedMission* mission, bool IsHovering);
    void StartMission();
    void OnStartMission_Event_0();
    void ShowMode(TEnumAsByte<EMissionSelection_Mode::Type> Mode);
    void Back();
    void ShowServerBrowser();
    void BndEvt__BTN_ServerList_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature();
    void BndEvt__BTN_Close_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature();
    void InputSourceChanged(EFSDInputSource InputSource);
    void OnShown();
    void Tick(FGeometry MyGeometry, float InDeltaTime);
    void MissionSelected(class UITM_MisSel_MissionMapIcon_C* mission);
    void StartSoloMission();
    void OnClosed();
    void DifficultyChanged(class UDifficultySetting* NewDifficulty, class UGeneratedMission* mission);
    void StartupCameraPan();
    void OnStartSoloMission();
    void BndEvt__ITM_Challenge_InfoBox_K2Node_ComponentBoundEvent_1_OnChallengeHovered__DelegateSignature(TArray<class UObject*>& assetReferences, bool InHovered, class USeasonChallenge* challenge);
    void ExecuteUbergraph__SCREEN_MissionSelectionMK3(int32 EntryPoint, TArray<class UObject*>& K2Node_ComponentBoundEvent_assetReferences, bool K2Node_ComponentBoundEvent_InHovered, class USeasonChallenge* K2Node_ComponentBoundEvent_challenge, class UMissionGenerationManager* CallFunc_GetGameInstanceSubsystem_ReturnValue, TArray<class UGeneratedMission*>& CallFunc_GetAvailableMissions_ReturnValue, FExecuteUbergraph__SCREEN_MissionSelectionMK3K2Node_CreateDelegate_OutputDelegate K2Node_CreateDelegate_OutputDelegate, class UMissionGenerationManager* CallFunc_GetGameInstanceSubsystem_ReturnValue_1, int32 Temp_int_Loop_Counter_Variable, TArray<class UGeneratedMission*>& CallFunc_GetAvailableMissions_ReturnValue_1, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Array_Index_Variable_1, FExecuteUbergraph__SCREEN_MissionSelectionMK3K2Node_CreateDelegate_OutputDelegate_1 K2Node_CreateDelegate_OutputDelegate_1, FExecuteUbergraph__SCREEN_MissionSelectionMK3K2Node_CreateDelegate_OutputDelegate_2 K2Node_CreateDelegate_OutputDelegate_2, bool K2Node_Event_IsDesignTime, class UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, class APlayerController* CallFunc_GetPlayerController_ReturnValue, class UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_1, bool CallFunc_FSDUpdateSessionInfo_ReturnValue, class AFSDGameState* CallFunc_GetFSDGameState_ReturnValue, class UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_2, bool K2Node_ComponentBoundEvent_bIsChecked, bool CallFunc_HasTooManyModsEnabled_ReturnValue, class UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_3, bool CallFunc_BooleanOR_ReturnValue, class UITM_MisSel_Biome_C* K2Node_CustomEvent_Biome_1, bool CallFunc_IsValid_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, class UITM_MisSel_Biome_C* K2Node_CustomEvent_Biome, int32 Temp_int_Loop_Counter_Variable_1, class UITM_MisSel_Biome_C* CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_1, int32 CallFunc_Array_Length_ReturnValue_1, class UITM_MisSel_Biome_C* CallFunc_Array_Get_Item_1, int32 CallFunc_Array_Length_ReturnValue_2, bool CallFunc_Less_IntInt_ReturnValue_1, class UGeneratedMission* K2Node_CustomEvent_Mission_2, bool K2Node_CustomEvent_IsHovering, bool CallFunc_IsValid_ReturnValue_2, TEnumAsByte<EMissionSelection_Mode::Type> K2Node_CustomEvent_Mode, FText CallFunc_GetPassword_Password, bool CallFunc_GetPassword_HasPassword, bool CallFunc_IsFriendsOnly_ReturnValue, FString CallFunc_Conv_TextToString_ReturnValue, class UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_4, int32 CallFunc_RandomInteger_ReturnValue, class UGeneratedMission* CallFunc_GetMission_Mission, int32 Temp_int_Loop_Counter_Variable_2, bool CallFunc_IsValid_ReturnValue_3, bool CallFunc_Less_IntInt_ReturnValue_2, int32 CallFunc_Add_IntInt_ReturnValue_2, class ABP_PlayerController_SpaceRig_C* CallFunc_GetController_AsBP_Player_Controller_Space_Rig, class UGeneratedMission* CallFunc_GetMission_CheckBiome_Mission, bool CallFunc_IsValid_ReturnValue_4, class UFSDGameUserSettings* CallFunc_FSDGameUserSettings_ReturnValue, EFSDInputSource K2Node_CustomEvent_InputSource, EFSDInputSource CallFunc_GetCurrentInputSource_ReturnValue, class UWindowManager* CallFunc_GetWindowManager_ReturnValue, class UWindowManager* CallFunc_GetWindowManager_ReturnValue_1, bool CallFunc_IsFriendsOnly_ReturnValue_1, int32 Temp_int_Array_Index_Variable_2, class UITM_MisSel_Biome_C* CallFunc_Array_Get_Item_2, FGeometry K2Node_Event_MyGeometry, float K2Node_Event_InDeltaTime, class UITM_MisSel_MissionMapIcon_C* K2Node_CustomEvent_Mission_1, bool CallFunc_IsValid_ReturnValue_5, FLinearColor CallFunc_MenuColorsAndOpacity_OutputColor, FLinearColor CallFunc_MenuColorsAndOpacity_OutputColor_1, class UCampaignManager* CallFunc_GetCampaingManager_ReturnValue, class APlayerController* CallFunc_GetOwningPlayer_ReturnValue, class ABP_PlayerControllerBase_C* K2Node_DynamicCast_AsBP_Player_Controller_Base, bool K2Node_DynamicCast_bSuccess, class UDifficultySetting* K2Node_CustomEvent_NewDifficulty, class UGeneratedMission* K2Node_CustomEvent_Mission, class UDifficultySetting* CallFunc_GetSelectedDifficulty_ReturnValue, class APlayerController* CallFunc_GetOwningPlayer_ReturnValue_1, class AFSDPlayerState* CallFunc_GetOwningFSDPlayerState_ReturnValue, class ABP_PlayerControllerBase_C* K2Node_DynamicCast_AsBP_Player_Controller_Base_1, bool K2Node_DynamicCast_bSuccess_1, class UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_5, class AFSDGameModeSpaceRig* CallFunc_GetFSDSRGameMode_ReturnValue, ESlateVisibility Temp_byte_Variable, ESlateVisibility Temp_byte_Variable_1, ESlateVisibility Temp_byte_Variable_2, EFSDInputSource Temp_byte_Variable_3, ESlateVisibility K2Node_Select_Default, FExecuteUbergraph__SCREEN_MissionSelectionMK3K2Node_CreateDelegate_OutputDelegate_3 K2Node_CreateDelegate_OutputDelegate_3, class UGeneratedMission* Temp_object_Variable, bool Temp_bool_Variable, TArray<class UITM_MisSel_ZoneLock_C*>& K2Node_MakeArray_Array, bool CallFunc_Array_Contains_ReturnValue, bool CallFunc_IsValid_ReturnValue_6, FExecuteUbergraph__SCREEN_MissionSelectionMK3K2Node_CreateDelegate_OutputDelegate_4 K2Node_CreateDelegate_OutputDelegate_4, class UGeneratedMission* K2Node_Select_Default_1, FExecuteUbergraph__SCREEN_MissionSelectionMK3K2Node_CreateDelegate_OutputDelegate_5 K2Node_CreateDelegate_OutputDelegate_5, FExecuteUbergraph__SCREEN_MissionSelectionMK3K2Node_CreateDelegate_OutputDelegate_6 K2Node_CreateDelegate_OutputDelegate_6, bool CallFunc_Not_PreBool_ReturnValue, class UWindowManager* CallFunc_GetWindowManager_ReturnValue_2, bool CallFunc_IsTopWindow_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue_1, class UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_6, class UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_7, TArray<class UITM_MisSel_Biome_C*>& K2Node_MakeArray_Array_1, class UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_8, int32 CallFunc_GetMaxPublicConnections_ReturnValue, class UFSDCreateSessionCallbackProxy* CallFunc_FSDCreateSession_ReturnValue, bool CallFunc_IsValid_ReturnValue_7);
};

#endif
