#ifndef UE4SS_SDK_BP_BeastMaster_HPP
#define UE4SS_SDK_BP_BeastMaster_HPP

class UBP_BeastMaster_C : public UBeastMasterComponent
{
    FPointerToUberGraphFrame UberGraphFrame;
    class ASpiderEnemy* PossibleTarget;
    class ASpiderEnemy* FriendedEnemy;
    FGameplayTagQuery Filter;
    UClass* LoadedFriendable;
    TSoftClassPtr<UObject> Friendable;
    float MaxAttackDMGMod;
    FText HoldText;
    FTimerHandle HoldTimer;
    float HoldProgress;
    float HoldDuration;
    class ASpiderEnemy* ActiveTarget;

    void ChangeAttacks(class ASpiderEnemy* enemy, bool Temp_bool_Variable, class UEnemyComponent* CallFunc_GetComponentByClass_ReturnValue, float CallFunc_MakeLiteralFloat_ReturnValue, float CallFunc_MakeLiteralFloat_ReturnValue_1, bool CallFunc_EqualEqual_ObjectObject_ReturnValue, float K2Node_Select_Default, class UMeleeAttackComponent* CallFunc_GetComponentByClass_ReturnValue_1, float CallFunc_Multiply_FloatFloat_ReturnValue);
    void UpdateHoldProgress(bool CallFunc_IsValid_ReturnValue, class APlayerCharacter* CallFunc_GetPlayerCharacter_AsPlayer_Character, class AFSDPlayerController* CallFunc_GetPlayerController_ReturnValue, bool CallFunc_Greater_FloatFloat_ReturnValue, class UOutlineComponent* CallFunc_GetComponentByClass_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, float CallFunc_Divide_FloatFloat_ReturnValue, class AFSDPlayerController* CallFunc_GetPlayerController_ReturnValue_1, float CallFunc_FClamp_ReturnValue, class APlayerCharacter* CallFunc_GetPlayerCharacter_AsPlayer_Character_1, float CallFunc_Add_FloatFloat_ReturnValue, class UPlayerFPAnimInstance* CallFunc_GetFPAnimInstance_ReturnValue, class APlayerCharacter* CallFunc_GetPlayerCharacter_AsPlayer_Character_2, bool CallFunc_GreaterEqual_FloatFloat_ReturnValue, bool CallFunc_IsValid_ReturnValue_2, bool CallFunc_IsValid_ReturnValue_3, bool CallFunc_Not_PreBool_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, class APlayerCharacter* CallFunc_GetPlayerCharacter_AsPlayer_Character_3, float CallFunc_GetDistanceTo_ReturnValue, bool CallFunc_Less_FloatFloat_ReturnValue);
    class AFSDPlayerController* GetPlayerController(class APlayerCharacter* CallFunc_GetPlayerCharacter_AsPlayer_Character, class AFSDPlayerController* CallFunc_GetPlayerController_ReturnValue);
    void SetupStatusEffects(class ASpiderEnemy* enemy, bool Temp_bool_Variable, TSubclassOf<class UStatusEffect> Temp_class_Variable, float CallFunc_GetHealth_ReturnValue, bool CallFunc_Greater_FloatFloat_ReturnValue, TSubclassOf<class UStatusEffect> Temp_class_Variable_1, TSubclassOf<class UStatusEffect> K2Node_Select_Default, bool CallFunc_PopActiveStatusEffect_ReturnValue);
    void GetPlayerCharacter(class APlayerCharacter*& AsPlayer Character, class AActor* CallFunc_GetOwner_ReturnValue, class APlayerCharacter* K2Node_DynamicCast_AsPlayer_Character, bool K2Node_DynamicCast_bSuccess);
    void GetPerk(class UFloatPerkAsset*& Perks Beast Master, class UGameData* CallFunc_GetFSDGameData_ReturnValue);
    bool CanBefriend(class ASpiderEnemy* enemyclass UBP_PetComponent_C* CallFunc_GetComponentByClass_ReturnValue, bool CallFunc_HasActiveEffect_ReturnValue, bool CallFunc_IsValid_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue_1, bool CallFunc_IsAlive_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue_2, bool CallFunc_DoesContainerMatchTagQuery_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, bool CallFunc_BooleanAND_ReturnValue, bool CallFunc_BooleanAND_ReturnValue_1, bool CallFunc_BooleanAND_ReturnValue_2, bool CallFunc_BooleanAND_ReturnValue_3);
    void OnLoaded_8AE17C7C4ABC357330FD319C5F5E7796(UClass* Loaded);
    void BeginBeastMasterActivation();
    void Server_Befriend(class ASpiderEnemy* Spider);
    void OnTargetChanged(class AActor* NewTarget, class UPrimitiveComponent* NewPrimitive);
    void ReceiveBeginPlay();
    void Setup Shouts();
    void OnFriendedEnemyDeath(class UHealthComponentBase* HealthComponent);
    void EndBeastMasterActivation();
    void ExecuteUbergraph_BP_BeastMaster(int32 EntryPoint, UClass* K2Node_CustomEvent_Loaded, bool CallFunc_IsValid_ReturnValue, class ASpiderEnemy* K2Node_CustomEvent_Spider, FExecuteUbergraph_BP_BeastMasterK2Node_CreateDelegate_OutputDelegate K2Node_CreateDelegate_OutputDelegate, class AAIController* CallFunc_GetAIController_ReturnValue, bool CallFunc_RunBehaviorTree_ReturnValue, class UHealthComponentBase* CallFunc_GetHealthComponent_ReturnValue, bool CallFunc_CanBefriend_ReturnValue, float CallFunc_Heal_ReturnValue, class UFloatPerkAsset* CallFunc_GetPerk_Perks_Beast_Master, class UFloatPerkAsset* CallFunc_GetPerk_Perks_Beast_Master_1, class UFloatPerkAsset* CallFunc_GetPerk_Perks_Beast_Master_2, class AActor* K2Node_CustomEvent_NewTarget, class UPrimitiveComponent* K2Node_CustomEvent_NewPrimitive, FName CallFunc_MakeLiteralName_ReturnValue, class ASpiderEnemy* K2Node_DynamicCast_AsSpider_Enemy, bool K2Node_DynamicCast_bSuccess, bool CallFunc_CanBefriend_ReturnValue_1, TSubclassOf<class ASpiderEnemy> CallFunc_GetObjectClass_ReturnValue, bool CallFunc_ClassIsChildOf_ReturnValue, bool CallFunc_DoesContainerMatchTagQuery_ReturnValue, bool CallFunc_PushActiveStatusEffect_ReturnValue, FExecuteUbergraph_BP_BeastMasterK2Node_CreateDelegate_OutputDelegate_1 K2Node_CreateDelegate_OutputDelegate_1, class APlayerCharacter* CallFunc_GetPlayerCharacter_AsPlayer_Character, class AFSDPlayerController* CallFunc_GetPlayerController_ReturnValue, bool CallFunc_CanUseCharge_ReturnValue, bool CallFunc_IsLocallyControlled_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, bool CallFunc_BooleanAND_ReturnValue_1, bool CallFunc_BooleanAND_ReturnValue_2, UClass* Temp_class_Variable, class APlayerCharacter* CallFunc_GetPlayerCharacter_AsPlayer_Character_1, class USphereComponent* CallFunc_AddPetComponent_ReturnValue, class UBP_PetUsable_C* CallFunc_AddPetComponent_ReturnValue_1, class UBP_PetComponent_C* CallFunc_AddPetComponent_ReturnValue_2, class UHealthComponentBase* K2Node_CustomEvent_HealthComponent, class AFSDPlayerController* CallFunc_GetPlayerController_ReturnValue_1, bool CallFunc_UseCharge_ReturnValue, bool CallFunc_CanUseCharge_ReturnValue_1, FExecuteUbergraph_BP_BeastMasterK2Node_CreateDelegate_OutputDelegate_2 K2Node_CreateDelegate_OutputDelegate_2, bool CallFunc_BooleanAND_ReturnValue_3, FExecuteUbergraph_BP_BeastMasterK2Node_CreateDelegate_OutputDelegate_3 K2Node_CreateDelegate_OutputDelegate_3, FExecuteUbergraph_BP_BeastMasterK2Node_CreateDelegate_OutputDelegate_4 K2Node_CreateDelegate_OutputDelegate_4, FTimerHandle CallFunc_K2_SetTimerDelegate_ReturnValue, FExecuteUbergraph_BP_BeastMasterK2Node_CreateDelegate_OutputDelegate_5 K2Node_CreateDelegate_OutputDelegate_5, class UOutlineComponent* CallFunc_GetComponentByClass_ReturnValue, bool CallFunc_IsValid_ReturnValue_1);
};

#endif
