#ifndef UE4SS_SDK_BP_CrystalFormation_SpikyBunch_03_HPP
#define UE4SS_SDK_BP_CrystalFormation_SpikyBunch_03_HPP

class ABP_CrystalFormation_SpikyBunch_03_C : public ABP_CrystalFormationsSpikyBunch_Base_C
{
};

#endif
