#ifndef UE4SS_SDK_BP_EscortDestination_HPP
#define UE4SS_SDK_BP_EscortDestination_HPP

class ABP_EscortDestination_C : public AEscortDestination
{
    FPointerToUberGraphFrame UberGraphFrame;
    class UBP_Extractor_Shell_C* Layer3Break3_Shell3;
    class UBP_Extractor_Shell_C* Layer3Break3_Shell2;
    class UBP_Extractor_Shell_C* Layer3Break3_Shell1;
    class UBP_Extractor_Shell_C* Layer3Break2_Shell2;
    class UBP_Extractor_Shell_C* Layer3Break2_Shell1;
    class UStaticMeshComponent* Layer3Break2;
    class UStaticMeshComponent* Layer3Break1;
    class UBP_Extractor_Shell_C* OuterBreak4_Shell4;
    class UBP_Extractor_Shell_C* OuterBreak4_Shell3;
    class UBP_Extractor_Shell_C* OuterBreak4_Shell2;
    class UBP_Extractor_Shell_C* OuterBreak4_Shell1;
    class UBP_Extractor_Shell_C* OuterBreak3_Shell3;
    class UBP_Extractor_Shell_C* OuterBreak3_Shell2;
    class UBP_Extractor_Shell_C* OuterBreak3_Shell1;
    class UBP_Extractor_Shell_C* OuterBreak2_Shell3;
    class UBP_Extractor_Shell_C* OuterBreak2_Shell2;
    class UBP_Extractor_Shell_C* OuterBreak2_Shell1;
    class UStaticMeshComponent* OuterBreak3;
    class UStaticMeshComponent* OuterBreak2;
    class UStaticMeshComponent* OuterBreak1;
    class UAudioComponent* FlyingRocksEnergyLinkLoop;
    class UBillboardComponent* BeamerSpawnLocation_9;
    class UBillboardComponent* BeamerSpawnLocation_5;
    class UBillboardComponent* BeamerSpawnLocation_10;
    class UChildActorComponent* BP_Heartstone_Claw_04;
    class USceneComponent* BeamersR;
    class UBillboardComponent* BeamerSpawnLocation_7;
    class UBillboardComponent* BeamerSpawnLocation_8;
    class UBillboardComponent* BeamerSpawnLocation_2;
    class UBillboardComponent* BeamerSpawnLocation_4;
    class UBillboardComponent* BeamerSpawnLocation_12;
    class UBillboardComponent* BeamerSpawnLocation_3;
    class USphereComponent* Sphere12;
    class USphereComponent* Sphere10;
    class USphereComponent* Sphere9;
    class USphereComponent* Sphere8;
    class USphereComponent* Sphere7;
    class USphereComponent* Sphere5;
    class USphereComponent* Sphere4;
    class USphereComponent* Sphere3;
    class USphereComponent* Sphere2;
    class USceneComponent* BeamersL;
    class UParticleSystemComponent* P_Heartstone_AmbientDust;
    class UParticleSystemComponent* P_CaveFX_heartstoneHangingDust;
    class UStaticMeshComponent* Cone3;
    class USpotLightComponent* SpotLight3;
    class UPointLightComponent* PointLight3;
    class USceneComponent* SpotlightCenter;
    class UBillboardComponent* Check_24;
    class UBillboardComponent* Check_23;
    class UBillboardComponent* Check_22;
    class UBillboardComponent* Check_21;
    class UBillboardComponent* Check_20;
    class UBillboardComponent* Check_19;
    class UBillboardComponent* Check_18;
    class UBillboardComponent* Check_17;
    class UBillboardComponent* Check_16;
    class UBillboardComponent* Check_15;
    class UBillboardComponent* Check_14;
    class UBillboardComponent* Check_13;
    class UBillboardComponent* Check_12;
    class UBillboardComponent* Check_11;
    class UBillboardComponent* Check_10;
    class UBillboardComponent* Check_9;
    class UBillboardComponent* Check_8;
    class UBillboardComponent* Check_7;
    class UBillboardComponent* Check_6;
    class UBillboardComponent* Check_5;
    class UBillboardComponent* Check_4;
    class UBillboardComponent* Check_3;
    class UBillboardComponent* Check_2;
    class UBillboardComponent* Check_1;
    class USceneComponent* PlatformChecks;
    class UBillboardComponent* AoE_Origin;
    class UDamageComponent* GroundSlamDamage;
    class UTerrainScannerStaticMesh* TerrainScannerStaticMesh;
    class ULevelGenerationDebris* LevelGenerationDebris_Ring_02;
    class ULevelGenerationCarverComponent* 1_LevelGenerationCarver_Floor;
    class ULevelGenerationCarverComponent* 2_LevelGeneration_CleanCarver;
    class UStaticMeshComponent* GunTower_Carver01;
    class USceneComponent* ArenaCarvers;
    class UStaticMeshComponent* CleanCraterCarver;
    class USimpleObjectInfoComponent* SimpleObjectInfo;
    class UChildActorComponent* BP_Heartstone_Claw_07;
    class UChildActorComponent* BP_Heartstone_Claw_08;
    class UChildActorComponent* BP_Heartstone_Claw_06;
    class UChildActorComponent* BP_Heartstone_Claw_02;
    class USceneComponent* Spikes;
    class USpawnActorWithDebrisPosComponent* LaserClawDebrisPos;
    class ULevelGenerationDebris* LevelGenerationDebris_Ring_01;
    class ULevelGenerationDebris* LevelGenerationDebris_CORE;
    class UStaticMeshComponent* Layer1Broken;
    class UStaticMeshComponent* Layer1;
    class UStaticMeshComponent* Layer2Broken;
    class UStaticMeshComponent* Layer2;
    class UStaticMeshComponent* Layer3Broken;
    class UStaticMeshComponent* Layer3;
    class UStaticMeshComponent* Layer4Broken;
    class UStaticMeshComponent* Layer4;
    class USceneComponent* HeartstoneMeshes;
    class UPathfinderCollisionComponent* PathfinderCollision;
    class UPointLightComponent* PointLight;
    class USceneComponent* Rings;
    class ULevelGenerationDebris* LevelGenerationDebris_MultipleRings;
    class USceneComponent* GemSpawnPos;
    class UTerrainPlacementComponent* terrainPlacement;
    class USceneComponent* DefaultSceneRoot;
    int32 Stage;
    class UEscortObjective* EscortObj;
    int32 SmarkRockSpawnGroups;
    class UEWC_Escort_EndDefense_C* WaveController_FinalFight;
    int32 SmartRockSpawnIndex;
    float SmartRockGropuDelay;
    TArray<class ABP_Heartstone_DefensiveCrystal_C*> DefensiveCrystals;
    bool IsMainCrystalWave;
    float LaserClawSpawnRadius;
    TArray<FVector> ForbiddenBeamerLocations;
    TArray<class USceneComponent*> BeamerLocationsL;
    TArray<class USceneComponent*> BeamerLocationsR;
    int32 BeamerIndexL;
    int32 BeamerIndexR;
    bool LRBeamerToggle;
    int32 NumActiveFlyingRocks;
    int32 OuterShellMiniBreakStage;
    float prevBreakPoint;
    TArray<FVector> SpawnPoints;

    void Update Shell Break Sub Stage(bool K2Node_SwitchInteger_CmpSuccess);
    void OnRep_OuterShellMiniBreakStage(FOnRep_OuterShellMiniBreakStageK2Node_CreateDelegate_OutputDelegate K2Node_CreateDelegate_OutputDelegate, FTimerHandle CallFunc_K2_SetTimerDelegate_ReturnValue);
    void OnRep_Stage();
    void ReleaseShellCustom(class UBP_Extractor_Shell_C* Shell);
    void OnRep_NumActiveFlyingRocks(class UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue, bool CallFunc_IsPlaying_ReturnValue, bool CallFunc_IsPlaying_ReturnValue_1, FString CallFunc_Conv_IntToString_ReturnValue, bool CallFunc_GreaterEqual_IntInt_ReturnValue, FString CallFunc_Concat_StrStr_ReturnValue);
    void UserConstructionScript();
    void ReceiveBeginPlay();
    void DrillingComplete();
    void CountdownTimeChanged(float Progress);
    void NewStage();
    void SpawnRocks(int32 SpawnCountPerGroup, int32 NumGroups);
    void GrowLaserClaws();
    void DoBrokenShellEffects();
    void OnObjectiveUpdated(class UObjective* Objective);
    void RegisterCrystal(class ABP_Heartstone_DefensiveCrystal_C* Crystal);
    void DoAoEPush();
    void CheckForEngPlatofrms();
    void MoreLaserClaws();
    void TurnOffBrokenSHellEmissive();
    void OnPickedUp_Event_0();
    void TurnSpotOff();
    void SpawnBeamer();
    void DisableAllBeamers();
    void RegisterFlyingRock();
    void DeRegisterFlyingRock();
    void Spawn Group();
    void ExecuteUbergraph_BP_EscortDestination(int32 EntryPoint, FVector CallFunc_K2_GetActorLocation_ReturnValue, bool Temp_bool_Has_Been_Initd_Variable, int32 Temp_int_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Variable_1, FExecuteUbergraph_BP_EscortDestinationK2Node_CreateDelegate_OutputDelegate K2Node_CreateDelegate_OutputDelegate, int32 CallFunc_Add_IntInt_ReturnValue_1, bool CallFunc_HasAuthority_ReturnValue, int32 Temp_int_Variable_2, bool CallFunc_HasAuthority_ReturnValue_1, int32 Temp_int_Variable_3, int32 CallFunc_Add_IntInt_ReturnValue_2, bool Temp_bool_Variable, bool CallFunc_HasAuthority_ReturnValue_2, bool CallFunc_HasAuthority_ReturnValue_3, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue_3, int32 Temp_int_Array_Index_Variable, bool CallFunc_HasAuthority_ReturnValue_4, bool Temp_bool_Has_Been_Initd_Variable_1, bool Temp_bool_IsClosed_Variable, bool Temp_bool_Variable_1, bool CallFunc_HasAuthority_ReturnValue_5, FExecuteUbergraph_BP_EscortDestinationK2Node_CreateDelegate_OutputDelegate_1 K2Node_CreateDelegate_OutputDelegate_1, bool CallFunc_HasAuthority_ReturnValue_6, bool Temp_bool_Variable_2, class AFSDGameState* CallFunc_GetFSDGameState_ReturnValue, bool CallFunc_HasAuthority_ReturnValue_7, bool CallFunc_IsValid_ReturnValue, class UObjective* CallFunc_GetPrimaryObjective_ReturnValue, class AFSDGameState* CallFunc_GetFSDGameState_ReturnValue_1, class UEscortObjective* K2Node_DynamicCast_AsEscort_Objective, bool K2Node_DynamicCast_bSuccess, FVector CallFunc_K2_GetActorLocation_ReturnValue_1, float K2Node_CustomEvent_progress, FExecuteUbergraph_BP_EscortDestinationK2Node_CreateDelegate_OutputDelegate_2 K2Node_CreateDelegate_OutputDelegate_2, FTransform CallFunc_K2_GetComponentToWorld_ReturnValue, class AActor* CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue, class ABP_EscortGem_Heartstone_C* CallFunc_FinishSpawningActor_ReturnValue, bool K2Node_SwitchInteger_CmpSuccess, bool Temp_bool_IsClosed_Variable_1, FVector CallFunc_K2_GetActorLocation_ReturnValue_2, int32 K2Node_CustomEvent_SpawnCountPerGroup, int32 K2Node_CustomEvent_NumGroups, float CallFunc_Multiply_IntFloat_ReturnValue, TArray<FVector>& CallFunc_GetSpawnPointsInCircle_ReturnValue, int32 CallFunc_FTrunc_ReturnValue, int32 Temp_int_Array_Index_Variable_1, bool CallFunc_Greater_IntInt_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue, class AFSDGameState* CallFunc_GetFSDGameState_ReturnValue_2, bool CallFunc_HasAuthority_ReturnValue_8, int32 CallFunc_Array_Length_ReturnValue, class AFSDGameState* CallFunc_GetFSDGameState_ReturnValue_3, bool CallFunc_LessEqual_IntInt_ReturnValue, class UObjective* CallFunc_GetPrimaryObjective_ReturnValue_1, class UEscortObjective* K2Node_DynamicCast_AsEscort_Objective_1, bool K2Node_DynamicCast_bSuccess_1, int32 K2Node_Select_Default, class UObjective* K2Node_CustomEvent_Objective, bool K2Node_SwitchEnum_CmpSuccess, float CallFunc_RandomFloatInRange_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, float CallFunc_Multiply_FloatFloat_ReturnValue, class AFSDGameState* CallFunc_GetFSDGameState_ReturnValue_4, bool CallFunc_IsValid_ReturnValue_2, int32 CallFunc_Array_Length_ReturnValue_1, bool CallFunc_LessEqual_IntInt_ReturnValue_1, float K2Node_Select_Default_1, bool CallFunc_IsValid_ReturnValue_3, float CallFunc_Array_Get_Item, bool CallFunc_GreaterEqual_FloatFloat_ReturnValue, int32 CallFunc_Array_Find_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_4, float CallFunc_Array_Get_Item_1, FVector CallFunc_K2_GetActorLocation_ReturnValue_3, bool CallFunc_Array_IsValidIndex_ReturnValue, bool Temp_bool_Variable_3, FVector CallFunc_K2_GetActorLocation_ReturnValue_4, int32 Temp_int_Array_Index_Variable_2, int32 CallFunc_Add_IntInt_ReturnValue_5, FVector CallFunc_K2_GetActorLocation_ReturnValue_5, class UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue, class UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue_1, class ABP_Heartstone_DefensiveCrystal_C* K2Node_CustomEvent_Crystal, FVector CallFunc_K2_GetActorLocation_ReturnValue_6, int32 CallFunc_Array_AddUnique_ReturnValue, FExecuteUbergraph_BP_EscortDestinationK2Node_CreateDelegate_OutputDelegate_3 K2Node_CreateDelegate_OutputDelegate_3, class ABP_Heartstone_DefensiveCrystal_C* CallFunc_Array_Get_Item_2, bool CallFunc_IsValid_ReturnValue_4, int32 CallFunc_Array_Length_ReturnValue_2, class AFSDGameState* CallFunc_GetFSDGameState_ReturnValue_5, int32 Temp_int_Loop_Counter_Variable_1, int32 CallFunc_Array_Length_ReturnValue_3, int32 CallFunc_Add_IntInt_ReturnValue_6, int32 Temp_int_Loop_Counter_Variable_2, class ADeepCSGWorld* CallFunc_GetCSGWorld_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_7, FVector CallFunc_K2_GetActorLocation_ReturnValue_7, FVector CallFunc_K2_GetComponentLocation_ReturnValue, FVector CallFunc_K2_GetComponentLocation_ReturnValue_1, class UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue_2, float CallFunc_MakeLiteralFloat_ReturnValue, TArray<class APlayerCharacter*>& CallFunc_GetPlayersInRange_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue_8, int32 CallFunc_Array_Length_ReturnValue_4, bool CallFunc_Less_IntInt_ReturnValue, class ADeepCSGWorld* CallFunc_GetCSGWorld_ReturnValue_1, TArray<class USceneComponent*>& CallFunc_GetChildrenComponents_Children, class ADeepCSGWorld* CallFunc_GetCSGWorld_ReturnValue_2, class USceneComponent* CallFunc_Array_Get_Item_3, int32 CallFunc_Array_Length_ReturnValue_5, FVector CallFunc_K2_GetComponentLocation_ReturnValue_2, bool CallFunc_Less_IntInt_ReturnValue_1, FCSGRaycastHitInfo CallFunc_Raycast_hitInfo, bool CallFunc_Raycast_ReturnValue, class UTerrainMaterial* CallFunc_GetTerrainMaterialByHandle_ReturnValue, class UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue_3, bool CallFunc_EqualEqual_ObjectObject_ReturnValue, bool CallFunc_EqualEqual_ObjectObject_ReturnValue_1, bool CallFunc_EqualEqual_ObjectObject_ReturnValue_2, bool CallFunc_EqualEqual_ObjectObject_ReturnValue_3, bool CallFunc_BooleanOR_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue_9, bool CallFunc_BooleanOR_ReturnValue_1, TArray<FVector>& K2Node_MakeArray_Array, bool CallFunc_BooleanOR_ReturnValue_2, class AFSDGameState* CallFunc_GetFSDGameState_ReturnValue_6, int32 K2Node_Select_Default_2, bool CallFunc_Greater_IntInt_ReturnValue_1, int32 CallFunc_Array_Length_ReturnValue_6, float CallFunc_Conv_IntToFloat_ReturnValue, float CallFunc_Divide_FloatFloat_ReturnValue, float CallFunc_Add_FloatFloat_ReturnValue, int32 Temp_int_Variable_4, int32 Temp_int_Array_Index_Variable_3, class APlayerCharacter* CallFunc_Array_Get_Item_4, bool CallFunc_IsValid_ReturnValue_5, FVector CallFunc_K2_GetActorLocation_ReturnValue_10, FVector CallFunc_Subtract_VectorVector_ReturnValue, int32 Temp_int_Variable_5, int32 CallFunc_GetNumMaterials_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue_1, bool CallFunc_LessEqual_IntInt_ReturnValue_2, int32 CallFunc_GetNumMaterials_ReturnValue_1, int32 CallFunc_Subtract_IntInt_ReturnValue_2, bool CallFunc_LessEqual_IntInt_ReturnValue_3, TArray<class USceneComponent*>& CallFunc_GetChildrenComponents_Children_1, int32 CallFunc_Array_Length_ReturnValue_7, int32 CallFunc_Subtract_IntInt_ReturnValue_3, class AProceduralSetup* CallFunc_GetProceduralSetup_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_8, class USceneComponent* CallFunc_Array_Get_Item_5, bool CallFunc_GreaterEqual_IntInt_ReturnValue, FVector CallFunc_K2_GetComponentLocation_ReturnValue_3, TArray<class AActor*>& CallFunc_PlaceActors_OutSpawnedActors, bool CallFunc_PlaceActors_ReturnValue, int32 K2Node_Select_Default_3, TArray<class USceneComponent*>& CallFunc_GetChildrenComponents_Children_2, int32 CallFunc_Array_Length_ReturnValue_8, int32 CallFunc_Subtract_IntInt_ReturnValue_4, class AProceduralSetup* CallFunc_GetProceduralSetup_ReturnValue_1, bool CallFunc_GreaterEqual_IntInt_ReturnValue_1, int32 CallFunc_Add_IntInt_ReturnValue_9, FVector CallFunc_K2_GetActorLocation_ReturnValue_11, bool CallFunc_Not_PreBool_ReturnValue, TArray<FVector>& CallFunc_GetSpawnPointsFromLocation_ReturnValue, class AFSDGameState* CallFunc_GetFSDGameState_ReturnValue_7, class USceneComponent* CallFunc_Array_Get_Item_6, int32 CallFunc_Array_Length_ReturnValue_9, FVector CallFunc_K2_GetComponentLocation_ReturnValue_4, int32 CallFunc_Add_IntInt_ReturnValue_10, TArray<class AActor*>& CallFunc_PlaceActors_OutSpawnedActors_1, bool CallFunc_PlaceActors_ReturnValue_1, bool CallFunc_LessEqual_IntInt_ReturnValue_4, int32 Temp_int_Loop_Counter_Variable_3, bool CallFunc_Less_IntInt_ReturnValue_2, int32 CallFunc_Add_IntInt_ReturnValue_11, TArray<class ABP_Heartstone_DefensiveCrystal_C*>& CallFunc_GetAllActorsOfClass_OutActors, class ABP_Heartstone_DefensiveCrystal_C* CallFunc_Array_Get_Item_7, int32 CallFunc_Array_Length_ReturnValue_10, bool CallFunc_Less_IntInt_ReturnValue_3, int32 CallFunc_Add_IntInt_ReturnValue_12, int32 CallFunc_Subtract_IntInt_ReturnValue_5, float CallFunc_Divide_FloatFloat_ReturnValue_1, bool K2Node_SwitchInteger_CmpSuccess_1, int32 CallFunc_Add_IntInt_ReturnValue_13, float CallFunc_Conv_IntToFloat_ReturnValue_1, float CallFunc_Multiply_FloatFloat_ReturnValue_1, bool CallFunc_GreaterEqual_FloatFloat_ReturnValue_1, int32 CallFunc_Add_IntInt_ReturnValue_14, FVector CallFunc_K2_GetActorLocation_ReturnValue_12, float CallFunc_Subtract_FloatFloat_ReturnValue, class UNiagaraComponent* CallFunc_SpawnSystemAtLocation_ReturnValue, float CallFunc_Divide_FloatFloat_ReturnValue_2, FVector CallFunc_K2_GetActorLocation_ReturnValue_13, FVector CallFunc_K2_GetActorLocation_ReturnValue_14, FVector CallFunc_K2_GetActorLocation_ReturnValue_15, FVector CallFunc_K2_GetActorLocation_ReturnValue_16, class UAudioComponent* CallFunc_SpawnSoundAtLocation_ReturnValue, class UAudioComponent* CallFunc_SpawnSoundAtLocation_ReturnValue_1, int32 CallFunc_Array_Length_ReturnValue_11, FVector CallFunc_Array_Get_Item_8, float CallFunc_Conv_IntToFloat_ReturnValue_2, float CallFunc_Add_FloatFloat_ReturnValue_1, bool CallFunc_Less_IntInt_ReturnValue_4, float CallFunc_Divide_FloatFloat_ReturnValue_3, float CallFunc_Subtract_FloatFloat_ReturnValue_1, float CallFunc_RandomFloatInRange_ReturnValue_1, int32 Temp_int_Variable_6, int32 CallFunc_Add_IntInt_ReturnValue_15, int32 CallFunc_Add_IntInt_ReturnValue_16, float CallFunc_Conv_IntToFloat_ReturnValue_3, float CallFunc_Multiply_FloatFloat_ReturnValue_2, float CallFunc_Add_FloatFloat_ReturnValue_2, bool CallFunc_IsValid_ReturnValue_6, bool CallFunc_GreaterEqual_FloatFloat_ReturnValue_2, float CallFunc_RandomFloatInRange_ReturnValue_2, class AFSDGameMode* CallFunc_GetFSDGameMode_ReturnValue, bool Temp_bool_Variable_4, class UEnemyWaveManager* CallFunc_GetWaveManager_ReturnValue, bool CallFunc_IsValid_ReturnValue_7, int32 K2Node_Select_Default_4, class UEWC_Escort_EndDefense_C* CallFunc_TriggerWave_ReturnValue, int32 Temp_int_Variable_7, bool CallFunc_Less_IntInt_ReturnValue_5, FVector CallFunc_K2_GetComponentLocation_ReturnValue_5, FVector CallFunc_Subtract_VectorVector_ReturnValue_1, float CallFunc_VSize_ReturnValue, float CallFunc_Divide_FloatFloat_ReturnValue_4, float CallFunc_FMin_ReturnValue, float CallFunc_Subtract_FloatFloat_ReturnValue_2, FVector CallFunc_VLerp_ReturnValue, FVector CallFunc_Normal_ReturnValue, FVector CallFunc_Multiply_VectorFloat_ReturnValue, float CallFunc_BreakVector_X, float CallFunc_BreakVector_Y, float CallFunc_BreakVector_Z, FVector CallFunc_MakeVector_ReturnValue);
};

#endif
