#ifndef UE4SS_SDK_BP_EnemyControlState_HPP
#define UE4SS_SDK_BP_EnemyControlState_HPP

class UBP_EnemyControlState_C : public UEnemyControlStateComponent
{
    FPointerToUberGraphFrame UberGraphFrame;
    class UAnimMontage* GetOnMontage;

    void OnNotifyEnd_C6BE400543D83DD77DB15BA38DC1ED24(FName NotifyName);
    void OnNotifyBegin_C6BE400543D83DD77DB15BA38DC1ED24(FName NotifyName);
    void OnInterrupted_C6BE400543D83DD77DB15BA38DC1ED24(FName NotifyName);
    void OnBlendOut_C6BE400543D83DD77DB15BA38DC1ED24(FName NotifyName);
    void OnCompleted_C6BE400543D83DD77DB15BA38DC1ED24(FName NotifyName);
    void OnControllingEnemy(bool IsControlling);
    void OnControllingEnemyAttached();
    void ExecuteUbergraph_BP_EnemyControlState(int32 EntryPoint, FName K2Node_CustomEvent_NotifyName_4, FName K2Node_CustomEvent_NotifyName_3, FExecuteUbergraph_BP_EnemyControlStateK2Node_CreateDelegate_OutputDelegate K2Node_CreateDelegate_OutputDelegate, FName K2Node_CustomEvent_NotifyName_2, FExecuteUbergraph_BP_EnemyControlStateK2Node_CreateDelegate_OutputDelegate_1 K2Node_CreateDelegate_OutputDelegate_1, FName K2Node_CustomEvent_NotifyName_1, FExecuteUbergraph_BP_EnemyControlStateK2Node_CreateDelegate_OutputDelegate_2 K2Node_CreateDelegate_OutputDelegate_2, FName K2Node_CustomEvent_NotifyName, FExecuteUbergraph_BP_EnemyControlStateK2Node_CreateDelegate_OutputDelegate_3 K2Node_CreateDelegate_OutputDelegate_3, FName Temp_name_Variable, bool K2Node_Event_IsControlling, FExecuteUbergraph_BP_EnemyControlStateK2Node_CreateDelegate_OutputDelegate_4 K2Node_CreateDelegate_OutputDelegate_4, class UAnimInstance* CallFunc_GetAnimInstance_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue, class UAudioComponent* CallFunc_SpawnSoundAtLocation_ReturnValue, class UAIPlayerControlComponent* CallFunc_GetAiPlayerControlComponent_ReturnValue, bool CallFunc_IsValid_ReturnValue, class UAnimInstance* CallFunc_GetAnimInstance_ReturnValue_1, class UAnimInstance* CallFunc_GetAnimInstance_ReturnValue_2, class UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue, bool CallFunc_IsValid_ReturnValue_1);
};

#endif
