#ifndef UE4SS_SDK_BP_EscortMule_HPP
#define UE4SS_SDK_BP_EscortMule_HPP

class ABP_EscortMule_C : public AEscortMule
{
    FPointerToUberGraphFrame UberGraphFrame;
    class UBoxComponent* Collision_Drill_Pawn;
    class USceneComponent* ForwardTracePointTop;
    class UBoxComponent* Collision_Platform1;
    class UBoxComponent* Collision_Platform;
    class UAutoCarverComponent* AutoCarverSmall;
    class UAutoCarverComponent* AutoCarverbig;
    class USceneComponent* CarverRoot;
    class UNiagaraComponent* P_LTracks;
    class UNiagaraComponent* P_RTracks;
    class UNiagaraComponent* P_LeftBoxDamagedLow;
    class UNiagaraComponent* P_LeftBoxDamagedHigh;
    class UNiagaraComponent* P_LeftBoxDamagedMedium;
    class USceneComponent* LeftBoxParticleNormal;
    class UNiagaraComponent* P_RightBoxDamagedHigh;
    class UNiagaraComponent* P_RightBoxDamagedLow;
    class UNiagaraComponent* P_RightBoxDamagedMedium;
    class USceneComponent* RightBoxParticleNormal;
    class USceneComponent* LeftBoxParticleMainBody;
    class USceneComponent* RightBoxParticleMainBody;
    class UNiagaraComponent* EngineStoppedSmoke;
    class UPointLightComponent* Box_Light_L;
    class UPointLightComponent* Box_Light_R;
    class UPointLightComponent* PointLight6;
    class UPointLightComponent* PointLight5;
    class UNiagaraComponent* JetFlame;
    class USceneComponent* impactLocation;
    class UNiagaraComponent* P_DrillHeartstone;
    class USkeletalMeshComponent* Mesh_DrillHead;
    class USceneComponent* DrillRotator;
    class UNiagaraComponent* ExhaustRight;
    class UNiagaraComponent* ExhaustLeft;
    class UWidgetComponent* Widget_Canister2;
    class UWidgetComponent* Widget_Canister1;
    class USpotLightComponent* SpotLight3;
    class UStaticMeshComponent* Cone3;
    class UStaticMeshComponent* Cone2;
    class USpotLightComponent* SpotLight2;
    class USceneComponent* SpotlightRight;
    class USceneComponent* SpotlightLeft;
    class UStaticMeshComponent* DrillDozerGuts_Right;
    class UStaticMeshComponent* DrillDozerGuts_Left;
    class UBoxComponent* Collision_RepairBoxBody;
    class UPointLightComponent* Red Button Light;
    class UPointLightComponent* DorettaPointLight;
    class USpotLightComponent* Doretta_SpotLight;
    class UStaticMeshComponent* Doretta_Cone;
    class UStaticMeshComponent* SM_WallLamp_004;
    class UPointLightComponent* PointLight2;
    class UBoxComponent* Achievement_Riding_Collider;
    class USphereComponent* Collision_Drill_Damage;
    class UBoxComponent* Colission_Doretta;
    class UInstantUsable* PetDorettaUsable;
    class USceneComponent* FlameHover;
    class UAudioComponent* Drilldozer_JetEngine_Start_Cue;
    class UAudioComponent* Drilldozer_JetEninge_Cue;
    class UChildActorComponent* OxygenTank01;
    class UOxygenSourceComponent* OxygenSource;
    class USkeletalMeshComponent* Cannister_02;
    class USkeletalMeshComponent* Cannister_01;
    class UWidgetComponent* Widget_Button;
    class USphereComponent* UseSphere_Activate;
    class USceneComponent* ButtonRoot;
    class UNiagaraComponent* P_Drill;
    class UBoxComponent* Collision_RepairBoxLeft;
    class UBoxComponent* Collision_RepairBoxRight;
    class USkeletalMeshComponent* RepairBoxRight;
    class USkeletalMeshComponent* RepairBoxLeft;
    class UOutlineComponent* outline;
    class UBoxComponent* FearBox;
    class UPawnStatsComponent* PawnStats;
    class UAudioComponent* DrillingVehicle_DrillingShell_Cue;
    class UChildActorComponent* RTrack;
    class UChildActorComponent* LTrack;
    class USceneComponent* DrillHeadRoot;
    class UDamageComponent* WeakpointDestroyedDamage;
    class UDamageComponent* DrillDamage;
    class UEscortMuleAttackerPositioning* EscortMuleAttackerPositioning;
    class UAudioComponent* Engine_Cue;
    class UAudioComponent* DrillHead_Cue;
    class USceneComponent* ForwardTracePoint;
    class UPointLightComponent* CannisterLight2;
    class UPointLightComponent* CannisterLight1;
    class USphereComponent* Sphere2;
    class USphereComponent* Sphere1;
    class UBP_EscortCannisterUsable_C* Cannister2Usable;
    class UBP_EscortCannisterUsable_C* Cannister1Usable;
    class UAudioComponent* DrillVehicle_RubbleSoftB_Cue;
    class UAudioComponent* DrillVehicle_RubbleSoftA_Cue;
    class UAudioComponent* DrillVehicleTrack2_Cue;
    class UAudioComponent* Rubble_Cue;
    class UAudioComponent* DrillVehicleTrack1_Cue;
    class UPointLightComponent* PointLight1;
    class UStaticMeshComponent* SM_WallLamp_003;
    class USceneComponent* Center;
    class USceneComponent* CarverScaler;
    class URadarPointComponent* radarPoint;
    class UStaticMeshComponent* TerrainScannerMesh;
    class UPathfinderCollisionComponent* PathfinderCollision;
    class USceneComponent* CarvParticleLocation;
    class USingleUsableComponent* ActivateMachineUsable;
    class UContinuousUsableComponent* ContinuousUsable;
    float Timeline_MoveDrillOut_Delta_1A396ACD40DA3371D46E58AD5DAAFC92;
    TEnumAsByte<ETimelineDirection::Type> Timeline_MoveDrillOut__Direction_1A396ACD40DA3371D46E58AD5DAAFC92;
    class UTimelineComponent* Timeline_MoveDrillOut;
    float MoveCloser_Alpha_E35B04D84FB5313C58E2E18AE68DA5A2;
    TEnumAsByte<ETimelineDirection::Type> MoveCloser__Direction_E35B04D84FB5313C58E2E18AE68DA5A2;
    class UTimelineComponent* MoveCloser;
    FVector HammerDrillTest_DrillHead_MoveVectorV2_FAAD5F0B4630F8F53E3DFB9B966534B9;
    float HammerDrillTest_Hammer_FAAD5F0B4630F8F53E3DFB9B966534B9;
    TEnumAsByte<ETimelineDirection::Type> HammerDrillTest__Direction_FAAD5F0B4630F8F53E3DFB9B966534B9;
    class UTimelineComponent* HammerDrillTest;
    FBP_EscortMule_CResourceFull ResourceFull;
    void ResourceFull();
    class UEscortObjective* EscortObj;
    EEscortMissionState State;
    class UAudioComponent* Sound_Moving;
    class UAudioComponent* Sound_Drilling;
    bool UnderAttack;
    class UPrimitiveComponent* ActiveRepairCollider;
    FVector StartLoc;
    FVector EndLoc;
    EEscortMissionState oldState;
    float LastDamageSoundTime;
    bool DrillPaused;
    class UABP_DrillDozer_Drill_C* DrillHeadAnimBP;
    class USkeletalMeshComponent* ActiveRepairMesh;
    FTimerHandle NotRepairedEvent;
    class UHUDWarningWidget* HUDWarning;
    class UHUDWarningWidget* HUDCellDestroyWarning;
    bool LastHoverTest;
    int32 EnemiesKilled;
    class UFSDAchievement* DrillByShooting;
    class UMaterialInstanceDynamic* LeftBoxMaterial;
    class UMaterialInstanceDynamic* RightBoxMaterial;
    class UMaterialInstanceDynamic* BodyMaterial;
    bool DoRotateInterpOnServer;
    float DrillRotateSpeed;
    class UNiagaraComponent* EngineStopSmoke;
    FBP_EscortMule_CEscortStateChanged EscortStateChanged;
    void EscortStateChanged(EEscortMissionState State);
    int32 MaxAttackersOmoranFight;
    bool IsPathReady;

    void RepComponentDamage(int32 CallFunc_GetCurrentHealthSegment_segment, float CallFunc_GetCurrentHealthSegment_segmentHealth, float CallFunc_GetCurrentHealthSegment_segmentHealthPercent, bool K2Node_SwitchInteger_CmpSuccess);
    void UpdateRepairBoxLook(float Percent, bool CallFunc_K2_AttachToComponent_ReturnValue, bool CallFunc_K2_AttachToComponent_ReturnValue_1, float CallFunc_MapRangeClamped_ReturnValue, float CallFunc_MapRangeClamped_ReturnValue_1, int32 CallFunc_GetCurrentHealthSegment_segment, float CallFunc_GetCurrentHealthSegment_segmentHealth, float CallFunc_GetCurrentHealthSegment_segmentHealthPercent, bool K2Node_SwitchInteger_CmpSuccess, bool CallFunc_EqualEqual_FloatFloat_ReturnValue, float CallFunc_SelectFloat_ReturnValue, float CallFunc_SelectFloat_ReturnValue_1);
    void UpdateBoxDamageEmitter(class UNiagaraComponent* ParticlesLow, class UNiagaraComponent* ParticlesMedium, class UNiagaraComponent* ParticlesHigh, float HealthPercent, bool CallFunc_Less_FloatFloat_ReturnValue, bool CallFunc_IsActive_ReturnValue, bool CallFunc_Less_FloatFloat_ReturnValue_1, bool CallFunc_Less_FloatFloat_ReturnValue_2, bool CallFunc_IsActive_ReturnValue_1, bool CallFunc_IsActive_ReturnValue_2);
    void SetBothCannistersVisibility(bool IsVisible);
    void IsFriendlyFire(class AActor* Object, bool& bSuccess, class APlayerCharacter* K2Node_DynamicCast_AsPlayer_Character, bool K2Node_DynamicCast_bSuccess, bool CallFunc_IsValid_ReturnValue, class APlayerCharacter* K2Node_DynamicCast_AsPlayer_Character_1, bool K2Node_DynamicCast_bSuccess_1);
    void OnRep_DrillPaused();
    void TryPlayDamageSound(FVector Location, float CallFunc_GetTimeSeconds_ReturnValue, float CallFunc_TimeSince_ReturnValue, bool CallFunc_Greater_FloatFloat_ReturnValue, class UAudioComponent* CallFunc_SpawnSoundAttached_ReturnValue);
    void Update Moving FX(EEscortMissionState InState, bool CallFunc_EqualEqual_ByteByte_ReturnValue);
    void SetupParticleMaterials(class AProceduralSetup* CallFunc_GetProceduralSetup_ReturnValue, class UTerrainMaterial* CallFunc_GetRockMaterial_ReturnValue, class UMaterialInstance* CallFunc_GetDigParticlesMaterialOverride_ReturnValue);
    void HandleCannisterUsed(class APlayerCharacter* User, class UInstantUsable* Usable, EEscortExtractorState CallFunc_GetExtractorState_ReturnValue, bool K2Node_SwitchEnum_CmpSuccess, class AItem* CallFunc_GetEquippedItem_ReturnValue, class AExtractorItem* K2Node_DynamicCast_AsExtractor_Item, bool K2Node_DynamicCast_bSuccess, class AWPN_OilExtractor_C* CallFunc_PickupItem_ReturnValue, class AExtractorItem* K2Node_DynamicCast_AsExtractor_Item_1, bool K2Node_DynamicCast_bSuccess_1);
    void CreateCanister(class UInstantUsable* NewItem_Usable, class USkinnedMeshComponent* MeshComponent, class UWidgetComponent* Widget, FEscortMuleExtractorSlot K2Node_MakeStruct_EscortMuleExtractorSlot, int32 CallFunc_Array_Add_ReturnValue);
    bool GetIsTargetable();
    FVector GetTargetCenterMass(FVector CallFunc_K2_GetComponentLocation_ReturnValue);
    class UHealthComponentBase* GetTargetHealthComponent();
    void UserConstructionScript(class UMaterialInstanceDynamic* CallFunc_CreateDynamicMaterialInstance_ReturnValue, class UMaterialInstanceDynamic* CallFunc_CreateDynamicMaterialInstance_ReturnValue_1, class UMaterialInstanceDynamic* CallFunc_CreateDynamicMaterialInstance_ReturnValue_2);
    void HammerDrillTest__FinishedFunc();
    void HammerDrillTest__UpdateFunc();
    void HammerDrillTest__HitEvents__EventFunc();
    void MoveCloser__FinishedFunc();
    void MoveCloser__UpdateFunc();
    void Timeline_MoveDrillOut__FinishedFunc();
    void Timeline_MoveDrillOut__UpdateFunc();
    void OnNotifyEnd_654993624EF7011EBE481AB20B9D51EC(FName NotifyName);
    void OnNotifyBegin_654993624EF7011EBE481AB20B9D51EC(FName NotifyName);
    void OnInterrupted_654993624EF7011EBE481AB20B9D51EC(FName NotifyName);
    void OnBlendOut_654993624EF7011EBE481AB20B9D51EC(FName NotifyName);
    void OnCompleted_654993624EF7011EBE481AB20B9D51EC(FName NotifyName);
    void ReceiveBeginPlay();
    void ReceiveTick(float DeltaSeconds);
    void BndEvt__ContinuousUsable_K2Node_ComponentBoundEvent_1_UsedBySignature__DelegateSignature(class APlayerCharacter* User, EInputKeys Key);
    void OnObjectiveStateChanged(EEscortMissionState NewState);
    void BndEvt__StartMachineUsable_K2Node_ComponentBoundEvent_2_UsedBySignature__DelegateSignature(class APlayerCharacter* User, EInputKeys Key);
    void BndEvt__StartMachineUsable_K2Node_ComponentBoundEvent_3_UsableChangedSignature__DelegateSignature(bool CanUse);
    void StateChanged(EEscortMissionState State);
    void EngineStartFX();
    void EngineStopFX();
    void RefuelCompleteFx();
    void BndEvt__HealthComponent_K2Node_ComponentBoundEvent_5_DamageSig__DelegateSignature(float Amount);
    void DrillingAtDestinationFx();
    void ShellCrackedFx();
    void RefreshPathfindingCollision();
    void VehicleDestroyedFx();
    void BndEvt__HealthComponent_K2Node_ComponentBoundEvent_6_HealthChangedSig__DelegateSignature(float Health);
    void BndEvt__Cannister1Usable_K2Node_ComponentBoundEvent_7_UsedBySignature__DelegateSignature(class APlayerCharacter* User, EInputKeys Key);
    void BndEvt__Cannister2Usable_K2Node_ComponentBoundEvent_8_UsedBySignature__DelegateSignature(class APlayerCharacter* User, EInputKeys Key);
    void OnExtractorSlotChanged(const FEscortMuleExtractorSlot& Slot, int32 Index);
    void ChechHover();
    void BndEvt__HealthComponent_K2Node_ComponentBoundEvent_4_HealthSegmentChange__DelegateSignature(int32 currSegment, int32 prevSegment);
    void BndEvt__Sphere_K2Node_ComponentBoundEvent_11_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult);
    void SetActiveRepair(class UPrimitiveComponent* collider, class USkeletalMeshComponent* ActiveRepairMest);
    void ExplodeRepair(class USkeletalMeshComponent* collider);
    void ShellCracked(int32 numberOfShellsCracked);
    void OnRep_IsCarvingTunnel();
    void UpdateCarvingState();
    void SetDrillAtTargetActive(bool IsActive);
    void SetDrillCooldown(float Seconds);
    void BndEvt__Box_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult);
    void BndEvt__HealthComponent_K2Node_ComponentBoundEvent_10_BodypartHitSig__DelegateSignature(float Amount, float BaseAmount, class UPrimitiveComponent* Component, class UFSDPhysicalMaterial* PhysMat, const FName& BoneName);
    void TryDamageSound(class AActor* Attacker);
    void ShowDamageEffects(class UParticleSystem* Particles, FVector Location, FRotator Orientation);
    void BndEvt__HealthComponent_K2Node_ComponentBoundEvent_12_HitSig__DelegateSignature(float Damage, class UDamageClass* DamageClass, class AActor* DamageCauser, bool anyHealthLost);
    void All_PlayDamageSound(FVector_NetQuantize Location);
    void SpawnDamageEffects(class UParticleSystem* EmitterTemplate, FVector_NetQuantize Location, FRotator Rotation);
    void BndEvt__HealthComponent_K2Node_ComponentBoundEvent_9_DamageSig__DelegateSignature(float Amount);
    void CheckRepair();
    void BndEvt__Achievement_Collider_K2Node_ComponentBoundEvent_13_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult);
    void BndEvt__Achievement_Collider_K2Node_ComponentBoundEvent_14_ComponentEndOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex);
    void On Damage Enemy While Riding(const TScriptInterface<class IHealth>& EnemyHealth, float Damage, float DamageModifier, float HealthRemaining, bool IsWeakPoint, bool IsRadial);
    void BndEvt__PetDorettaUsable_K2Node_ComponentBoundEvent_15_UsedBySignature__DelegateSignature(class APlayerCharacter* User, EInputKeys Key);
    void All_PlayPetAnimation();
    void TestDorettaHead();
    void PathIsReady();
    void SetButtonUsable(bool CanUse);
    void OnCheat_SetMuleSpeed(float FloatValue);
    void ExecuteUbergraph_BP_EscortMule(int32 EntryPoint, bool Temp_bool_Variable, bool CallFunc_HasAuthority_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, bool CallFunc_HasAuthority_ReturnValue_1, FExecuteUbergraph_BP_EscortMuleK2Node_CreateDelegate_OutputDelegate K2Node_CreateDelegate_OutputDelegate, FTimerHandle CallFunc_K2_SetTimerDelegate_ReturnValue, bool Temp_bool_Has_Been_Initd_Variable, bool CallFunc_HasAuthority_ReturnValue_2, bool CallFunc_HasAuthority_ReturnValue_3, bool CallFunc_HasAuthority_ReturnValue_4, bool Temp_bool_IsClosed_Variable, bool CallFunc_HasAuthority_ReturnValue_5, float K2Node_Event_DeltaSeconds, class APlayerCharacter* K2Node_ComponentBoundEvent_user_4, EInputKeys K2Node_ComponentBoundEvent_key_4, class AFSDGameState* CallFunc_GetFSDGameState_ReturnValue, class UObjective* CallFunc_GetPrimaryObjective_ReturnValue, class UEscortObjective* K2Node_DynamicCast_AsEscort_Objective, bool K2Node_DynamicCast_bSuccess, EEscortMissionState K2Node_Event_newState, class APlayerCharacter* K2Node_ComponentBoundEvent_user_3, EInputKeys K2Node_ComponentBoundEvent_key_3, bool K2Node_ComponentBoundEvent_canUse, EEscortMissionState K2Node_CustomEvent_State, bool CallFunc_EqualEqual_ByteByte_ReturnValue, bool Temp_bool_Has_Been_Initd_Variable_1, FVector CallFunc_K2_GetActorLocation_ReturnValue, float K2Node_ComponentBoundEvent_Amount_2, FVector CallFunc_K2_GetActorLocation_ReturnValue_1, bool CallFunc_HasAuthority_ReturnValue_6, class ADeepCSGWorld* CallFunc_GetCSGWorld_ReturnValue, bool CallFunc_IsValid_ReturnValue, float K2Node_ComponentBoundEvent_health, int32 CallFunc_GetCurrentHealthSegment_segment, float CallFunc_GetCurrentHealthSegment_segmentHealth, float CallFunc_GetCurrentHealthSegment_segmentHealthPercent, bool CallFunc_Less_FloatFloat_ReturnValue, bool CallFunc_NearlyEqual_FloatFloat_ReturnValue, bool CallFunc_EqualEqual_IntInt_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue_1, bool CallFunc_BooleanAND_ReturnValue, const FTransform CallFunc_GetTransform_ReturnValue, FVector CallFunc_BreakTransform_Location, FRotator CallFunc_BreakTransform_Rotation, FVector CallFunc_BreakTransform_Scale, float CallFunc_BreakRotator_Roll, float CallFunc_BreakRotator_Pitch, float CallFunc_BreakRotator_Yaw, FRotator CallFunc_MakeRotator_ReturnValue, FTransform CallFunc_MakeTransform_ReturnValue, float CallFunc_SelectFloat_ReturnValue, bool CallFunc_TryHeal_ReturnValue, class APlayerCharacter* K2Node_ComponentBoundEvent_user_2, EInputKeys K2Node_ComponentBoundEvent_key_2, class APlayerCharacter* K2Node_ComponentBoundEvent_user_1, EInputKeys K2Node_ComponentBoundEvent_key_1, EEscortExtractorState CallFunc_GetExtractorState_ReturnValue, bool K2Node_SwitchEnum_CmpSuccess, const FEscortMuleExtractorSlot K2Node_Event_slot, int32 K2Node_Event_Index, class USceneComponent* CallFunc_GetChildComponent_ReturnValue, class UAudioComponent* CallFunc_SpawnSoundAttached_ReturnValue, class UPointLightComponent* K2Node_DynamicCast_AsPoint_Light_Component, bool K2Node_DynamicCast_bSuccess_1, class UAudioComponent* CallFunc_SpawnSoundAttached_ReturnValue_1, FRotator CallFunc_K2_GetComponentRotation_ReturnValue, FVector CallFunc_ComponentToWorldLocation_ReturnValue, class USkeletalMeshComponent* K2Node_DynamicCast_AsSkeletal_Mesh_Component, bool K2Node_DynamicCast_bSuccess_2, class UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue, class UAnimInstance* CallFunc_GetAnimInstance_ReturnValue, class UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue_1, class UFuelCannisterAttachedAnimInstance* K2Node_DynamicCast_AsFuel_Cannister_Attached_Anim_Instance, bool K2Node_DynamicCast_bSuccess_3, bool K2Node_SwitchEnum_CmpSuccess_1, bool CallFunc_IsValid_ReturnValue_1, bool CallFunc_IsValid_ReturnValue_2, EEscortExtractorState CallFunc_GetExtractorState_ReturnValue_1, bool K2Node_SwitchEnum_CmpSuccess_2, bool CallFunc_HasAuthority_ReturnValue_7, bool CallFunc_HasAuthority_ReturnValue_8, float CallFunc_Multiply_FloatFloat_ReturnValue, bool CallFunc_HasAuthority_ReturnValue_9, FVector CallFunc_Multiply_VectorFloat_ReturnValue, int32 K2Node_ComponentBoundEvent_currSegment, int32 K2Node_ComponentBoundEvent_prevSegment, class UPrimitiveComponent* K2Node_ComponentBoundEvent_OverlappedComponent_3, class AActor* K2Node_ComponentBoundEvent_OtherActor_3, class UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp_3, int32 K2Node_ComponentBoundEvent_OtherBodyIndex_3, bool K2Node_ComponentBoundEvent_bFromSweep_2, const FHitResult K2Node_ComponentBoundEvent_SweepResult_2, bool K2Node_SwitchInteger_CmpSuccess, FVector CallFunc_K2_GetComponentLocation_ReturnValue, FExecuteUbergraph_BP_EscortMuleK2Node_CreateDelegate_OutputDelegate_1 K2Node_CreateDelegate_OutputDelegate_1, FTimerHandle CallFunc_K2_SetTimerDelegate_ReturnValue_1, class UPrimitiveComponent* K2Node_CustomEvent_Collider_1, class USkeletalMeshComponent* K2Node_CustomEvent_ActiveRepairMest, class USkeletalMeshComponent* K2Node_CustomEvent_Collider, bool Temp_bool_IsClosed_Variable_1, TArray<class USceneComponent*>& CallFunc_GetChildrenComponents_Children, int32 CallFunc_Array_Length_ReturnValue, FVector CallFunc_K2_GetComponentLocation_ReturnValue_1, FVector CallFunc_K2_GetComponentLocation_ReturnValue_2, class UNiagaraComponent* CallFunc_SpawnSystemAtLocation_ReturnValue, bool CallFunc_HasAuthority_ReturnValue_10, bool CallFunc_HasAuthority_ReturnValue_11, bool CallFunc_HasAuthority_ReturnValue_12, FHitResult CallFunc_K2_SetRelativeLocation_SweepHitResult, FVector CallFunc_K2_GetComponentLocation_ReturnValue_3, FHitResult CallFunc_K2_SetRelativeLocation_SweepHitResult_1, int32 K2Node_CustomEvent_numberOfShellsCracked, bool K2Node_SwitchInteger_CmpSuccess_1, bool CallFunc_IsValid_ReturnValue_3, float CallFunc_Multiply_IntFloat_ReturnValue, FRotator CallFunc_MakeRotator_ReturnValue_1, bool CallFunc_EqualEqual_IntInt_ReturnValue_1, FExecuteUbergraph_BP_EscortMuleK2Node_CreateDelegate_OutputDelegate_2 K2Node_CreateDelegate_OutputDelegate_2, int32 CallFunc_SelectInt_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue_2, FVector CallFunc_GetClosestPointOnRadius_dirFromCenter, FVector CallFunc_GetClosestPointOnRadius_ReturnValue, FVector CallFunc_BreakTransform_Location_1, FRotator CallFunc_BreakTransform_Rotation_1, FVector CallFunc_BreakTransform_Scale_1, FVector CallFunc_VLerp_ReturnValue, FHitResult CallFunc_K2_SetActorTransform_SweepHitResult, bool CallFunc_K2_SetActorTransform_ReturnValue, FTransform CallFunc_MakeTransform_ReturnValue_1, bool CallFunc_HasAuthority_ReturnValue_13, bool K2Node_CustomEvent_isActive, int32 CallFunc_GetCurrentHealthSegment_segment_1, float CallFunc_GetCurrentHealthSegment_segmentHealth_1, float CallFunc_GetCurrentHealthSegment_segmentHealthPercent_1, bool CallFunc_EqualEqual_ByteByte_ReturnValue_1, bool CallFunc_Greater_FloatFloat_ReturnValue, bool CallFunc_HasAuthority_ReturnValue_14, bool CallFunc_EqualEqual_ByteByte_ReturnValue_2, bool K2Node_SwitchEnum_CmpSuccess_3, bool CallFunc_HasAuthority_ReturnValue_15, class UBP_BossFight_Heartstone_C* CallFunc_SpawnObject_ReturnValue, float K2Node_CustomEvent_Seconds, FExecuteUbergraph_BP_EscortMuleK2Node_CreateDelegate_OutputDelegate_3 K2Node_CreateDelegate_OutputDelegate_3, FTimerHandle CallFunc_K2_SetTimerDelegate_ReturnValue_2, class UPrimitiveComponent* K2Node_ComponentBoundEvent_OverlappedComponent_2, class AActor* K2Node_ComponentBoundEvent_OtherActor_2, class UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp_2, int32 K2Node_ComponentBoundEvent_OtherBodyIndex_2, bool K2Node_ComponentBoundEvent_bFromSweep_1, const FHitResult K2Node_ComponentBoundEvent_SweepResult_1, class USceneComponent* CallFunc_K2_GetRootComponent_ReturnValue, class AFSDPawn* K2Node_DynamicCast_AsFSDPawn, bool K2Node_DynamicCast_bSuccess_4, class UAudioComponent* CallFunc_SpawnSoundAttached_ReturnValue_2, FVector CallFunc_K2_GetComponentLocation_ReturnValue_4, float K2Node_ComponentBoundEvent_Amount_1, float K2Node_ComponentBoundEvent_BaseAmount, class UPrimitiveComponent* K2Node_ComponentBoundEvent_Component, class UFSDPhysicalMaterial* K2Node_ComponentBoundEvent_physmat, const FName K2Node_ComponentBoundEvent_boneName, class AActor* CallFunc_GetOwner_ReturnValue, float CallFunc_GetTimeSeconds_ReturnValue, bool CallFunc_IsFriendlyFire_bSuccess, class AActor* K2Node_CustomEvent_Attacker, float CallFunc_TimeSince_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue_3, bool CallFunc_Greater_FloatFloat_ReturnValue_1, class UParticleSystem* K2Node_Event_particles, FVector K2Node_Event_location, FRotator K2Node_Event_orientation, FVector CallFunc_GetForwardVector_ReturnValue, float K2Node_ComponentBoundEvent_Damage, class UDamageClass* K2Node_ComponentBoundEvent_damageClass, class AActor* K2Node_ComponentBoundEvent_DamageCauser, bool K2Node_ComponentBoundEvent_anyHealthLost, FVector CallFunc_Multiply_VectorFloat_ReturnValue_1, bool CallFunc_IsFriendlyFire_bSuccess_1, FVector CallFunc_Add_VectorVector_ReturnValue, FVector_NetQuantize CallFunc_VectorToNetQuantize_ReturnValue, FVector_NetQuantize K2Node_CustomEvent_Location_1, class UAudioComponent* CallFunc_SpawnSoundAttached_ReturnValue_3, FVector CallFunc_K2_GetComponentLocation_ReturnValue_5, class UParticleSystem* K2Node_CustomEvent_EmitterTemplate, FVector_NetQuantize K2Node_CustomEvent_Location, FRotator K2Node_CustomEvent_Rotation, FVector CallFunc_Subtract_VectorVector_ReturnValue, class UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue_2, FVector CallFunc_Normal_ReturnValue, FVector CallFunc_Multiply_VectorFloat_ReturnValue_2, bool CallFunc_HasAuthority_ReturnValue_16, bool CallFunc_HasAuthority_ReturnValue_17, float Temp_float_Variable, bool CallFunc_HasAuthority_ReturnValue_18, float Temp_float_Variable_1, class UAnimInstance* CallFunc_GetAnimInstance_ReturnValue_1, class UABP_DrillDozer_Drill_C* K2Node_DynamicCast_AsABP_Drill_Dozer_Drill, bool K2Node_DynamicCast_bSuccess_5, float CallFunc_Conv_IntToFloat_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue_4, float K2Node_ComponentBoundEvent_Amount, FVector CallFunc_K2_GetActorLocation_ReturnValue_5, bool CallFunc_K2_IsValidTimerHandle_ReturnValue, bool CallFunc_K2_IsTimerActiveHandle_ReturnValue, FTimerHandle CallFunc_K2_InvalidateTimerHandle_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue_6, bool CallFunc_K2_IsTimerActiveHandle_ReturnValue_1, bool CallFunc_K2_IsValidTimerHandle_ReturnValue_1, bool Temp_bool_Variable_1, bool CallFunc_Not_PreBool_ReturnValue_2, int32 CallFunc_GetCurrentHealthSegment_segment_2, float CallFunc_GetCurrentHealthSegment_segmentHealth_2, float CallFunc_GetCurrentHealthSegment_segmentHealthPercent_2, bool CallFunc_EqualEqual_FloatFloat_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue_7, int32 Temp_int_Array_Index_Variable, class UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue, class USceneComponent* CallFunc_Array_Get_Item, class UHUDWarningWidget* CallFunc_AddWarningToHUD_ReturnValue, class UPrimitiveComponent* K2Node_DynamicCast_AsPrimitive_Component, bool K2Node_DynamicCast_bSuccess_6, class UAudioComponent* CallFunc_SpawnSoundAttached_ReturnValue_4, bool Temp_bool_Variable_2, class UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_1, float K2Node_Select_Default, class UHUDWarningWidget* CallFunc_AddWarningToHUD_ReturnValue_1, bool CallFunc_HasAuthority_ReturnValue_19, bool CallFunc_IsValid_ReturnValue_4, bool CallFunc_NotEqual_ByteByte_ReturnValue, bool CallFunc_NotEqual_ByteByte_ReturnValue_1, bool CallFunc_BooleanOR_ReturnValue, bool CallFunc_NotEqual_ByteByte_ReturnValue_2, bool CallFunc_NotEqual_ByteByte_ReturnValue_3, int32 Temp_int_Loop_Counter_Variable, bool CallFunc_BooleanOR_ReturnValue_1, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_NotEqual_ByteByte_ReturnValue_4, FExecuteUbergraph_BP_EscortMuleK2Node_CreateDelegate_OutputDelegate_4 K2Node_CreateDelegate_OutputDelegate_4, bool CallFunc_NotEqual_ByteByte_ReturnValue_5, bool CallFunc_HasAuthority_ReturnValue_20, bool CallFunc_BooleanOR_ReturnValue_2, bool CallFunc_NotEqual_ByteByte_ReturnValue_6, bool CallFunc_NotEqual_ByteByte_ReturnValue_7, class UPrimitiveComponent* K2Node_ComponentBoundEvent_OverlappedComponent_1, class AActor* K2Node_ComponentBoundEvent_OtherActor_1, class UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp_1, int32 K2Node_ComponentBoundEvent_OtherBodyIndex_1, bool K2Node_ComponentBoundEvent_bFromSweep, const FHitResult K2Node_ComponentBoundEvent_SweepResult, bool CallFunc_BooleanOR_ReturnValue_3, class APlayerCharacter* K2Node_DynamicCast_AsPlayer_Character, bool K2Node_DynamicCast_bSuccess_7, bool CallFunc_IsLocallyControlled_ReturnValue, class UPrimitiveComponent* K2Node_ComponentBoundEvent_OverlappedComponent, class AActor* K2Node_ComponentBoundEvent_OtherActor, class UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp, int32 K2Node_ComponentBoundEvent_OtherBodyIndex, class APlayerCharacter* K2Node_DynamicCast_AsPlayer_Character_1, bool K2Node_DynamicCast_bSuccess_8, int32 CallFunc_Add_IntInt_ReturnValue_1, bool CallFunc_IsLocallyControlled_ReturnValue_1, class APlayerCharacter* CallFunc_GetLocalPlayerCharacter_ReturnValue, const TScriptInterface<class IHealth> K2Node_CustomEvent_EnemyHealth, float K2Node_CustomEvent_Damage, float K2Node_CustomEvent_DamageModifier, float K2Node_CustomEvent_HealthRemaining, bool K2Node_CustomEvent_IsWeakpoint, bool K2Node_CustomEvent_IsRadial, class AFSDPlayerController* CallFunc_GetPlayerController_ReturnValue, float CallFunc_Subtract_FloatFloat_ReturnValue, bool CallFunc_IsDead_ReturnValue, bool CallFunc_LessEqual_FloatFloat_ReturnValue, bool CallFunc_BooleanOR_ReturnValue_4, TArray<class AActor*>& CallFunc_GetOverlappingActors_OverlappingActors, int32 CallFunc_Array_Length_ReturnValue_1, bool CallFunc_GreaterEqual_IntInt_ReturnValue, FHitResult CallFunc_K2_SetRelativeLocation_SweepHitResult_2, FRotator CallFunc_K2_GetActorRotation_ReturnValue, FVector CallFunc_BreakTransform_Location_2, FRotator CallFunc_BreakTransform_Rotation_2, FVector CallFunc_BreakTransform_Scale_2, FRotator CallFunc_K2_GetActorRotation_ReturnValue_1, FRotator CallFunc_RInterpTo_Constant_ReturnValue, bool CallFunc_K2_SetActorRotation_ReturnValue, FVector CallFunc_BreakTransform_Location_3, FRotator CallFunc_BreakTransform_Rotation_3, FVector CallFunc_BreakTransform_Scale_3, bool CallFunc_EqualEqual_RotatorRotator_ReturnValue, class UBossFightSubSystem* CallFunc_GetGameInstanceSubsystem_ReturnValue, float CallFunc_Multiply_FloatFloat_ReturnValue_1, TScriptInterface<class IBossFightInterface> CallFunc_RegisterBossFight_BossFight_CastInput, FVector CallFunc_MakeVector_ReturnValue, class UBossFightSubSystem* CallFunc_GetGameInstanceSubsystem_ReturnValue_1, FExecuteUbergraph_BP_EscortMuleK2Node_CreateDelegate_OutputDelegate_5 K2Node_CreateDelegate_OutputDelegate_5, class UAnimInstance* CallFunc_GetAnimInstance_ReturnValue_2, class UABP_DrillDozer_C* K2Node_DynamicCast_AsABP_Drill_Dozer, bool K2Node_DynamicCast_bSuccess_9, FVector CallFunc_K2_GetComponentLocation_ReturnValue_6, class UNiagaraComponent* CallFunc_SpawnSystemAtLocation_ReturnValue_1, class APlayerCharacter* K2Node_ComponentBoundEvent_user, EInputKeys K2Node_ComponentBoundEvent_key, class UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue, bool CallFunc_IsValid_ReturnValue_5, bool CallFunc_HasAuthority_ReturnValue_21, class UAnimInstance* CallFunc_GetAnimInstance_ReturnValue_3, bool CallFunc_Montage_IsPlaying_ReturnValue, FHitResult CallFunc_K2_SetRelativeRotation_SweepHitResult, FTransform CallFunc_MakeTransform_ReturnValue_2, FVector CallFunc_K2_GetComponentLocation_ReturnValue_7, FVector CallFunc_K2_GetComponentLocation_ReturnValue_8, FVector CallFunc_Add_VectorVector_ReturnValue_1, FVector CallFunc_Add_VectorVector_ReturnValue_2, class UNiagaraComponent* CallFunc_SpawnSystemAtLocation_ReturnValue_2, class UNiagaraComponent* CallFunc_SpawnSystemAtLocation_ReturnValue_3, class UNiagaraComponent* CallFunc_SpawnSystemAttached_ReturnValue, class UNiagaraComponent* CallFunc_SpawnSystemAttached_ReturnValue_1, bool CallFunc_HasAuthority_ReturnValue_22, class USkeletalMeshComponent* CallFunc_GetComponentByClass_ReturnValue, class USkeletalMeshComponent* CallFunc_GetComponentByClass_ReturnValue_1, FName Temp_name_Variable, FVector CallFunc_K2_GetComponentLocation_ReturnValue_9, FTransform CallFunc_GetSocketTransform_ReturnValue, FVector CallFunc_Add_VectorVector_ReturnValue_3, FTransform CallFunc_ComposeTransforms_ReturnValue, FVector_NetQuantize CallFunc_VectorToNetQuantize_ReturnValue_1, class AActor* CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue, class ABP_DorettaHead_C* CallFunc_FinishSpawningActor_ReturnValue, bool CallFunc_HasAuthority_ReturnValue_23, bool K2Node_SwitchEnum_CmpSuccess_4, class UFSDGameUserSettings* CallFunc_GetFSDGameUserSettings_ReturnValue, bool CallFunc_GetPhotosensitiveMode_ReturnValue, bool CallFunc_IsActive_ReturnValue, FName K2Node_CustomEvent_NotifyName, FExecuteUbergraph_BP_EscortMuleK2Node_CreateDelegate_OutputDelegate_6 K2Node_CreateDelegate_OutputDelegate_6, bool K2Node_CustomEvent_canUse, bool CallFunc_NotEqual_ByteByte_ReturnValue_8, FName K2Node_CustomEvent_NotifyName_1, float K2Node_CustomEvent_floatValue, bool CallFunc_NearlyEqual_FloatFloat_ReturnValue_1, float CallFunc_SelectFloat_ReturnValue_1, FExecuteUbergraph_BP_EscortMuleK2Node_CreateDelegate_OutputDelegate_7 K2Node_CreateDelegate_OutputDelegate_7, FName K2Node_CustomEvent_NotifyName_2, FExecuteUbergraph_BP_EscortMuleK2Node_CreateDelegate_OutputDelegate_8 K2Node_CreateDelegate_OutputDelegate_8, bool CallFunc_NotEqual_ByteByte_ReturnValue_9, bool CallFunc_NotEqual_ByteByte_ReturnValue_10, FName K2Node_CustomEvent_NotifyName_3, bool CallFunc_BooleanAND_ReturnValue_1, bool CallFunc_NotEqual_ByteByte_ReturnValue_11, FExecuteUbergraph_BP_EscortMuleK2Node_CreateDelegate_OutputDelegate_9 K2Node_CreateDelegate_OutputDelegate_9, bool CallFunc_NotEqual_ByteByte_ReturnValue_12, bool CallFunc_BooleanAND_ReturnValue_2, bool CallFunc_EqualEqual_BoolBool_ReturnValue, bool CallFunc_EqualEqual_BoolBool_ReturnValue_1, FName K2Node_CustomEvent_NotifyName_4, bool K2Node_SwitchEnum_CmpSuccess_5, const TArray<class AActor*>& K2Node_MakeArray_Array, FRotator CallFunc_K2_GetActorRotation_ReturnValue_2, FRotator CallFunc_RLerp_ReturnValue, FHitResult CallFunc_K2_SetWorldRotation_SweepHitResult, FExecuteUbergraph_BP_EscortMuleK2Node_CreateDelegate_OutputDelegate_10 K2Node_CreateDelegate_OutputDelegate_10, FVector CallFunc_GetUpVector_ReturnValue, FVector CallFunc_Multiply_VectorFloat_ReturnValue_3, FVector CallFunc_Multiply_VectorFloat_ReturnValue_4, FVector CallFunc_K2_GetComponentLocation_ReturnValue_10, FVector CallFunc_Add_VectorVector_ReturnValue_4, FVector CallFunc_Add_VectorVector_ReturnValue_5, FHitResult CallFunc_LineTraceSingle_OutHit, bool CallFunc_LineTraceSingle_ReturnValue, FVector CallFunc_K2_GetComponentLocation_ReturnValue_11, FVector CallFunc_GetActorForwardVector_ReturnValue, class ADeepCSGWorld* CallFunc_GetCSGWorld_ReturnValue_1, FVector CallFunc_Multiply_VectorFloat_ReturnValue_5, FVector CallFunc_Add_VectorVector_ReturnValue_6, FVector CallFunc_K2_GetComponentLocation_ReturnValue_12, FCSGRaycastHitInfo CallFunc_Linecast_hitInfo, bool CallFunc_Linecast_ReturnValue, FVector CallFunc_Add_VectorVector_ReturnValue_7, FCSGRaycastHitInfo CallFunc_Linecast_hitInfo_1, bool CallFunc_Linecast_ReturnValue_1, bool CallFunc_BooleanOR_ReturnValue_5, bool CallFunc_NotEqual_BoolBool_ReturnValue, FHitResult CallFunc_K2_SetRelativeLocation_SweepHitResult_3, bool CallFunc_EqualEqual_ByteByte_ReturnValue_3, float CallFunc_Multiply_FloatFloat_ReturnValue_2, float CallFunc_Multiply_FloatFloat_ReturnValue_3, FRotator CallFunc_MakeRotator_ReturnValue_2, FHitResult CallFunc_K2_AddLocalRotation_SweepHitResult, FVector CallFunc_BreakTransform_Location_4, FRotator CallFunc_BreakTransform_Rotation_4, FVector CallFunc_BreakTransform_Scale_4, FRotator CallFunc_ComposeRotators_ReturnValue, FTransform CallFunc_MakeTransform_ReturnValue_3);
    void EscortStateChanged__DelegateSignature(EEscortMissionState State);
    void ResourceFull__DelegateSignature();
};

#endif
