#ifndef UE4SS_SDK_BP_EyeForEye_SYIHpassive_PerkComponent_HPP
#define UE4SS_SDK_BP_EyeForEye_SYIHpassive_PerkComponent_HPP

class UBP_EyeForEye_SYIHpassive_PerkComponent_C : public UEyeForEyePerkComponent
{
};

#endif
