#ifndef UE4SS_SDK_BP_FSDCameraManager_HPP
#define UE4SS_SDK_BP_FSDCameraManager_HPP

class ABP_FSDCameraManager_C : public AFSDPlayerCameraManager
{
    FPointerToUberGraphFrame UberGraphFrame;
    class UStaticMeshComponent* PhysicalSphere;
    bool SessionStarted;
    float MaxDistance;
    FBP_FSDCameraManager_CHideHUDForPhotography HideHUDForPhotography;
    void HideHUDForPhotography();
    FBP_FSDCameraManager_CShowHUDForPhotography ShowHUDForPhotography;
    void ShowHUDForPhotography();
    bool UserVisibility;
    ECharacterCameraMode PreviousCameraMode;
    bool PauseGame;
    float SphereReturnVelocity;
    float MaxDistanceTolerance;
    bool KeyDebug;
    float MaxSpeed;

    void ChangeMaxDistance(float MaxDistance);
    void ChangeSpeed(float MaxSpeed, FString CallFunc_Conv_FloatToString_ReturnValue, FString CallFunc_Concat_StrStr_ReturnValue);
    float SmoothReturnVelocity(FVector New Camera Locationclass APlayerController* CallFunc_GetOwningPlayerController_ReturnValue, class APawn* CallFunc_K2_GetPawn_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue, FVector CallFunc_Subtract_VectorVector_ReturnValue, float CallFunc_VSize_ReturnValue, float CallFunc_Multiply_FloatFloat_ReturnValue, float CallFunc_Subtract_FloatFloat_ReturnValue, float CallFunc_Subtract_FloatFloat_ReturnValue_1, float CallFunc_Divide_FloatFloat_ReturnValue, float CallFunc_Multiply_FloatFloat_ReturnValue_1);
    void SphereDirectionToPlayer(FVector& Direction, class APlayerController* CallFunc_GetOwningPlayerController_ReturnValue, FVector CallFunc_K2_GetComponentLocation_ReturnValue, class APawn* CallFunc_K2_GetPawn_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue, FVector CallFunc_Subtract_VectorVector_ReturnValue, FVector CallFunc_Normal_ReturnValue);
    void SetToThirdPersonCamera(FVector& New Camera Position, FVector CallFunc_K2_GetComponentLocation_ReturnValue, class APlayerController* CallFunc_GetOwningPlayerController_ReturnValue, class APawn* CallFunc_K2_GetPawn_ReturnValue, class APlayerCharacter* K2Node_DynamicCast_AsPlayer_Character, bool K2Node_DynamicCast_bSuccess, FVector CallFunc_K2_GetComponentLocation_ReturnValue_1, FVector CallFunc_K2_GetComponentLocation_ReturnValue_2, FHitResult CallFunc_K2_SetWorldLocation_SweepHitResult, FHitResult CallFunc_K2_SetWorldLocation_SweepHitResult_1);
    void ReturnCameraMode(class APlayerCharacter* Target, ECharacterCameraMode NewCameraMode, ECharacterState CallFunc_GetCurrentState_ReturnValue, bool K2Node_SwitchEnum_CmpSuccess);
    void PhotographyCameraModify(const FVector NewCameraLocation, const FVector PreviousCameraLocation, const FVector OriginalCameraLocation, FVector& ResultCameraLocation, float CallFunc_SmoothReturnVelocity_ReturnValue, FVector CallFunc_K2_GetComponentLocation_ReturnValue, FVector CallFunc_SetToThirdPersonCamera_New_Camera_Position, float CallFunc_Multiply_FloatFloat_ReturnValue, class APlayerController* CallFunc_GetOwningPlayerController_ReturnValue, class APawn* CallFunc_K2_GetPawn_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue, FVector CallFunc_K2_GetComponentLocation_ReturnValue_1, FVector CallFunc_Subtract_VectorVector_ReturnValue, float CallFunc_VSize_ReturnValue, FVector CallFunc_SetToThirdPersonCamera_New_Camera_Position_1, bool CallFunc_GreaterEqual_FloatFloat_ReturnValue, bool CallFunc_LessEqual_FloatFloat_ReturnValue, FVector CallFunc_K2_GetComponentLocation_ReturnValue_2, FHitResult CallFunc_K2_SetWorldLocation_SweepHitResult, const TArray<class AActor*>& K2Node_MakeArray_Array, FVector CallFunc_SphereDirectionToPlayer_Direction, FHitResult CallFunc_K2_SetWorldLocation_SweepHitResult_1, FVector CallFunc_Multiply_VectorFloat_ReturnValue, const TArray<TEnumAsByte<EObjectTypeQuery>>& K2Node_MakeArray_Array_1, FVector CallFunc_Add_VectorVector_ReturnValue, TArray<class UPrimitiveComponent*>& CallFunc_SphereOverlapComponents_OutComponents, bool CallFunc_SphereOverlapComponents_ReturnValue, FHitResult CallFunc_K2_SetWorldLocation_SweepHitResult_2);
    void ReceiveDestroyed();
    void OnPhotographySessionEnd();
    void OnPhotographySessionStart();
    void TogglePhotographyMode(bool Active);
    void Return Camera();
    void ReceiveTick(float DeltaSeconds);
    void LoaderStart(class ULevelSequence* LoaderLevelSequence);
    void ReceiveBeginPlay();
    void LoaderStop();
    void ExecuteUbergraph_BP_FSDCameraManager(int32 EntryPoint, class APlayerController* CallFunc_GetOwningPlayerController_ReturnValue, bool CallFunc_SetGamePaused_ReturnValue, bool CallFunc_SetGamePaused_ReturnValue_1, class APlayerController* CallFunc_GetOwningPlayerController_ReturnValue_1, bool CallFunc_SetGamePaused_ReturnValue_2, class ABP_PlayerControllerBase_C* K2Node_DynamicCast_AsBP_Player_Controller_Base, bool K2Node_DynamicCast_bSuccess, class APlayerController* CallFunc_GetOwningPlayerController_ReturnValue_2, class APlayerController* CallFunc_GetOwningPlayerController_ReturnValue_3, class APlayerController* CallFunc_GetOwningPlayerController_ReturnValue_4, class APawn* CallFunc_K2_GetPawn_ReturnValue, class ABP_PlayerControllerBase_C* K2Node_DynamicCast_AsBP_Player_Controller_Base_1, bool K2Node_DynamicCast_bSuccess_1, class APlayerCharacter* K2Node_DynamicCast_AsPlayer_Character, bool K2Node_DynamicCast_bSuccess_2, class UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue, class UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_1, class APlayerController* CallFunc_GetOwningPlayerController_ReturnValue_5, class APlayerController* CallFunc_GetOwningPlayerController_ReturnValue_6, bool CallFunc_IsLocalController_ReturnValue, class ABP_PlayerControllerBase_C* K2Node_DynamicCast_AsBP_Player_Controller_Base_2, bool K2Node_DynamicCast_bSuccess_3, class APawn* CallFunc_K2_GetPawn_ReturnValue_1, bool K2Node_CustomEvent_Active, class APlayerCharacter* K2Node_DynamicCast_AsPlayer_Character_1, bool K2Node_DynamicCast_bSuccess_4, ECharacterState CallFunc_GetCurrentState_ReturnValue, bool CallFunc_EqualEqual_ByteByte_ReturnValue, class APlayerController* CallFunc_GetOwningPlayerController_ReturnValue_7, class APawn* CallFunc_K2_GetPawn_ReturnValue_2, class APlayerCharacter* K2Node_DynamicCast_AsPlayer_Character_2, bool K2Node_DynamicCast_bSuccess_5, FString CallFunc_Conv_FloatToString_ReturnValue, FString CallFunc_Concat_StrStr_ReturnValue, FString CallFunc_Conv_FloatToString_ReturnValue_1, FString CallFunc_Concat_StrStr_ReturnValue_1, uint8 CallFunc_MakeLiteralByte_ReturnValue, bool CallFunc_NotEqual_ByteByte_ReturnValue, float K2Node_Event_DeltaSeconds, class ULevelSequence* K2Node_CustomEvent_LoaderLevelSequence, class APlayerController* CallFunc_GetOwningPlayerController_ReturnValue_8, class ABP_PlayerControllerBase_C* K2Node_DynamicCast_AsBP_Player_Controller_Base_3, bool K2Node_DynamicCast_bSuccess_6, class APlayerController* CallFunc_GetOwningPlayerController_ReturnValue_9, class ABP_PlayerControllerBase_C* K2Node_DynamicCast_AsBP_Player_Controller_Base_4, bool K2Node_DynamicCast_bSuccess_7, bool CallFunc_IsHUDVisibleFlagSet_ReturnValue, class APlayerController* CallFunc_GetOwningPlayerController_ReturnValue_10, class ABP_PlayerControllerBase_C* K2Node_DynamicCast_AsBP_Player_Controller_Base_5, bool K2Node_DynamicCast_bSuccess_8);
    void ShowHUDForPhotography__DelegateSignature();
    void HideHUDForPhotography__DelegateSignature();
};

#endif
