#ifndef UE4SS_SDK_BP_HackingPod_HPP
#define UE4SS_SDK_BP_HackingPod_HPP

class ABP_HackingPod_C : public AFacilityHackingPod
{
    FPointerToUberGraphFrame UberGraphFrame;
    class UInstantUsable* PettingUse;
    class UStaticMeshComponent* RangeSphere;
    class UChildActorComponent* BP_OxygenTankSound;
    class UChildActorComponent* BP_OxygenTank1;
    class UOxygenSourceComponent* OxygenSource;
    class UChildActorComponent* BP_OxygenTank;
    class USphereComponent* TriggerOnOffOutline;
    class UTerrainScannerStaticMesh* TerrainScannerStaticMesh;
    class UBillboardComponent* JunkSpawnPoint;
    class UPointLightComponent* PointLight1;
    class UPointLightComponent* PointLight3;
    class UPointLightComponent* PointLight2;
    class UPointLightComponent* PointLight;
    class USphereComponent* SaluteTrigger;
    class USphereComponent* PettingUseSphere;
    class USkeletalMeshComponent* Drill;
    class UAudioComponent* HackingPodHackingIdle;
    class USimpleObjectInfoComponent* SimpleObjectInfo;
    class UPointLightComponent* Light_FanRGB03;
    class UPointLightComponent* Light_FanRGB02;
    class UPointLightComponent* Light_FanRGB01;
    class UCapsuleComponent* BodyCollision;
    class UPointLightComponent* Light_Monitor;
    class UWidgetComponent* Widget_MonitorTop;
    class UWidgetComponent* Widget_MonitorRight;
    class UWidgetComponent* Widget_MonitorMiddle;
    class UWidgetComponent* Widget_MonitorLeft;
    class UWidgetComponent* UseButtonWidget;
    class UAutoCarverComponent* AutoCarver;
    class UDropToTerrainComponent* DropToTerrain;
    class UTerrainDetectComponent* TerrainDetect;
    class UTerrainPlacementComponent* terrainPlacement;
    class UOutlineComponent* outline;
    class UChildActorComponent* DispenserActor;
    class USkeletalMeshComponent* Base;
    class USingleUsableComponent* ActivateUsable;
    class USingleUsableComponent* ReviveUsable;
    class UCapsuleComponent* UseCapsule;
    class UObjectAttackerPositioning* ObjectAttackerPositioning;
    class UFriendlyHealthComponent* FriendlyHealth;
    class UTetherComponent* Tether;
    TArray<class AActor*> ChildTethers;
    TArray<FLinearColor> Fans_StartColor;
    TArray<FLinearColor> Fans_EndColor;
    TArray<FLinearColor> Fans_ColorArray;
    TArray<FLinearColor> LightColors;
    FTimerHandle ResizeCarverTimer;
    bool IsFacilityMission;
    float OutlineTime;
    float LightMonitorIntensity;
    FBP_HackingPod_COpenChanged OpenChanged;
    void OpenChanged(bool Open);
    bool Open;
    bool HackingStarted;
    bool HackingOver;
    TEnumAsByte<ETetherDispenserState::Type> DispenserState;
    FBP_HackingPod_CStateChanged StateChanged;
    void StateChanged(TEnumAsByte<ETetherDispenserState::Type> State);
    class USingleUsableComponent* NewVar_0;
    class UParticleSystemComponent* ThrusterParticles;
    class UAudioComponent* ThrusterSound;
    TArray<class APlayerCharacter*> PlayersInside;
    bool HasActivated;
    class UMaterialInstanceDynamic* CornerColors;
    TArray<class TSubclassOf<AActor>> JunkActors;
    int32 MaxJunkSpawns;
    bool ShowRange;
    bool ConnectedToGoal;

    bool GetIsTargetable();
    FVector GetTargetCenterMass(FVector CallFunc_K2_GetComponentLocation_ReturnValue);
    class UHealthComponentBase* GetTargetHealthComponent();
    void SetShowRange(bool ShowRange, class AFSDGameState* CallFunc_GetFSDGameState_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Greater_IntInt_ReturnValue, float CallFunc_SelectFloat_ReturnValue, FVector CallFunc_MakeVector_ReturnValue);
    void UpdatePlayerCount();
    void EnableScreens(bool ScreensActive, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, TArray<class UWidgetComponent*>& K2Node_MakeArray_Array, int32 CallFunc_Array_Length_ReturnValue, class UWidgetComponent* CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, class UUserWidget* CallFunc_GetUserWidgetObject_ReturnValue, class UUI_HackingPod_Screen_Base_C* K2Node_DynamicCast_AsUI_Hacking_Pod_Screen_Base, bool K2Node_DynamicCast_bSuccess);
    void FanColorsIntact(bool& FansIntact, bool CallFunc_IsValid_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, bool CallFunc_BooleanAND_ReturnValue, bool CallFunc_IsValid_ReturnValue_2, bool CallFunc_BooleanAND_ReturnValue_1);
    void HackingInProgress(bool& NewParam, EHackingPodState CallFunc_GetState_ReturnValue, bool CallFunc_NotEqual_ByteByte_ReturnValue, bool CallFunc_BooleanAND_ReturnValue);
    void ReconnectTethers(int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, bool Temp_bool_True_if_break_was_hit_Variable, int32 Temp_int_Array_Index_Variable, bool CallFunc_Not_PreBool_ReturnValue, bool Temp_bool_True_if_break_was_hit_Variable_1, bool CallFunc_IsConnected_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue_1, int32 Temp_int_Loop_Counter_Variable_1, int32 Temp_int_Array_Index_Variable_1, int32 CallFunc_Add_IntInt_ReturnValue_1, TArray<class UTetherComponent*>& CallFunc_GetConnectionHistory_ReturnValue, class UTetherComponent* CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_ConnectToTetherLine_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, TArray<class AActor*>& CallFunc_GetIgnoreTethers_ChildTethers, const TArray<TEnumAsByte<EObjectTypeQuery>>& K2Node_MakeArray_Array, FVector CallFunc_GetConnectionPoint_ReturnValue, TArray<class AActor*>& CallFunc_SphereOverlapActors_OutActors, bool CallFunc_SphereOverlapActors_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_1, class AActor* CallFunc_Array_Get_Item_1, bool CallFunc_Less_IntInt_ReturnValue_1, class UTetherComponent* CallFunc_GetComponentByClass_ReturnValue, bool CallFunc_BooleanAND_ReturnValue_1, bool CallFunc_IsActive_ReturnValue, bool CallFunc_ConnectToTetherLine_ReturnValue_1);
    void GetDispenser(class ABP_TetherDispenser_C*& AsBP Tether Dispenser, class ABP_TetherDispenser_C* K2Node_DynamicCast_AsBP_Tether_Dispenser, bool K2Node_DynamicCast_bSuccess);
    void GetIgnoreTethers(TArray<class AActor*>& ChildTethers, class ABP_TetherDispenser_C* K2Node_DynamicCast_AsBP_Tether_Dispenser, bool K2Node_DynamicCast_bSuccess, class AActor* CallFunc_GetItem_ReturnValue, int32 CallFunc_Array_Add_ReturnValue);
    void UserConstructionScript(class UMaterialInstanceDynamic* CallFunc_CreateDynamicMaterialInstance_ReturnValue);
    void OnTick_4437D92344C73CCB9F96AB832CABCA51(float DeltaTime, float NormalizedTime);
    void Completed_4437D92344C73CCB9F96AB832CABCA51(float DeltaTime, float NormalizedTime);
    void ShowDamageEffects(class UParticleSystem* Particles, FVector Location, FRotator Orientation);
    void ReceiveBeginPlay();
    void OnDroppodImpact();
    void BndEvt__Tether_K2Node_ComponentBoundEvent_0_TeherMessage_Delegate__DelegateSignature(const FName& Message);
    void BndEvt__FriendlyHealth_K2Node_ComponentBoundEvent_1_DeathSig__DelegateSignature(class UHealthComponentBase* HealthComponent);
    void BndEvt__SingleUsable_K2Node_ComponentBoundEvent_2_UsedBySignature__DelegateSignature(class APlayerCharacter* User, EInputKeys Key);
    void BndEvt__FriendlyHealth_K2Node_ComponentBoundEvent_3_DamageSig__DelegateSignature(float Amount);
    void BndEvt__ActivateUsable_K2Node_ComponentBoundEvent_6_UsedBySignature__DelegateSignature(class APlayerCharacter* User, EInputKeys Key);
    void SetLightColor(int32 Index);
    void BndEvt__DropToTerrain_K2Node_ComponentBoundEvent_7_OnIsFallingToTerrainChanged__DelegateSignature(bool IsFalling);
    void ManageOutlines();
    void OnDropStarted();
    void DeployAnimations();
    void OnDroppodCloseToImpact();
    void ResizeCarver();
    void UpdateUseIcon();
    void BndEvt__ReviveUsable_K2Node_ComponentBoundEvent_0_UsableChangedSignature__DelegateSignature(bool CanUse);
    void StartFanColoring();
    void BndEvt__ActivateUsable_K2Node_ComponentBoundEvent_9_UsableChangedSignature__DelegateSignature(bool CanUse);
    void TakeOff();
    void BndEvt__PettingUsable_K2Node_ComponentBoundEvent_4_UsedBySignature__DelegateSignature(class APlayerCharacter* User, EInputKeys Key);
    void BndEvt__Sphere_K2Node_ComponentBoundEvent_5_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult);
    void OnBoscoSalute_Event_0(class APlayerCharacter* ShoutingPlayer);
    void All_Pet();
    void OnEnterState(EHackingPodState NextState);
    void OnExitState(EHackingPodState oldState);
    void BndEvt__TriggerOutline_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult);
    void BndEvt__TriggerOutline_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex);
    void All_PlaySalute(class AActor* Saluter);
    void BndEvt__Tether_K2Node_ComponentBoundEvent_12_TetherConnectionChanged_Deletage__DelegateSignature(class UTetherComponent* frontConnection, class UTetherComponent* backConnection);
    void ItemTaken(class AActor* spawnedItem);
    void OnPlayerJoined_Event_0(class AFSDPlayerState* PlayerState);
    void OnPlayerLeave_Event_0(class AFSDPlayerState* PlayerState);
    void BndEvt__PettingUse_K2Node_ComponentBoundEvent_13_UsedBySignature__DelegateSignature(class APlayerCharacter* User, EInputKeys Key);
    void ExecuteUbergraph_BP_HackingPod(int32 EntryPoint, class APlayerCharacter* K2Node_ComponentBoundEvent_user, EInputKeys K2Node_ComponentBoundEvent_key, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, bool Temp_bool_True_if_break_was_hit_Variable, int32 Temp_int_Array_Index_Variable, bool CallFunc_Not_PreBool_ReturnValue, bool Temp_bool_Has_Been_Initd_Variable, bool Temp_bool_IsClosed_Variable, bool Temp_bool_Has_Been_Initd_Variable_1, bool Temp_bool_Has_Been_Initd_Variable_2, bool Temp_bool_IsClosed_Variable_1, bool Temp_bool_Has_Been_Initd_Variable_3, bool Temp_bool_IsClosed_Variable_2, FExecuteUbergraph_BP_HackingPodK2Node_CreateDelegate_OutputDelegate K2Node_CreateDelegate_OutputDelegate, FTimerHandle CallFunc_K2_SetTimerDelegate_ReturnValue, bool Temp_bool_Has_Been_Initd_Variable_4, bool Temp_bool_IsClosed_Variable_3, int32 Temp_int_Variable, int32 CallFunc_Add_IntInt_ReturnValue_1, bool CallFunc_HasAuthority_ReturnValue, class UParticleSystem* K2Node_Event_particles, FVector K2Node_Event_location, FRotator K2Node_Event_orientation, class AFSDGameMode* CallFunc_GetFSDGameMode_ReturnValue, const FName K2Node_ComponentBoundEvent_message, bool K2Node_SwitchName_CmpSuccess, class UObjective* CallFunc_GetPrimaryObjective_ReturnValue, class UHealthComponentBase* K2Node_ComponentBoundEvent_HealthComponent, class UFacilityObjective* K2Node_DynamicCast_AsFacility_Objective, bool K2Node_DynamicCast_bSuccess, class APlayerCharacter* K2Node_ComponentBoundEvent_user_3, EInputKeys K2Node_ComponentBoundEvent_key_3, FVector CallFunc_K2_GetComponentLocation_ReturnValue, class UAudioComponent* CallFunc_SpawnSoundAtLocation_ReturnValue, float Temp_float_Variable, bool CallFunc_HasAuthority_ReturnValue_1, float K2Node_ComponentBoundEvent_Amount, FName CallFunc_MakeLiteralName_ReturnValue, class APlayerCharacter* K2Node_ComponentBoundEvent_user_2, EInputKeys K2Node_ComponentBoundEvent_key_2, FName CallFunc_MakeLiteralName_ReturnValue_1, int32 K2Node_CustomEvent_Index, FLinearColor CallFunc_Array_Get_Item, FTransform CallFunc_MakeTransform_ReturnValue, class AActor* CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue, class ABP_TetherDispenserBeacon_C* CallFunc_FinishSpawningActor_ReturnValue, bool K2Node_ComponentBoundEvent_IsFalling, bool CallFunc_ConnectToTetherLine_ReturnValue, float Temp_float_Variable_1, class ABP_BarrelDispenser_C* K2Node_DynamicCast_AsBP_Barrel_Dispenser, bool K2Node_DynamicCast_bSuccess_1, FVector CallFunc_K2_GetActorLocation_ReturnValue, class UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue, class UAudioComponent* CallFunc_SpawnSoundAtLocation_ReturnValue_1, class UAudioComponent* CallFunc_SpawnSoundAttached_ReturnValue, class UParticleSystemComponent* CallFunc_SpawnEmitterAttached_ReturnValue, class UParticleSystemComponent* CallFunc_SpawnEmitterAttached_ReturnValue_1, bool CallFunc_HasAuthority_ReturnValue_2, FExecuteUbergraph_BP_HackingPodK2Node_CreateDelegate_OutputDelegate_1 K2Node_CreateDelegate_OutputDelegate_1, FExecuteUbergraph_BP_HackingPodK2Node_CreateDelegate_OutputDelegate_2 K2Node_CreateDelegate_OutputDelegate_2, FExecuteUbergraph_BP_HackingPodK2Node_CreateDelegate_OutputDelegate_3 K2Node_CreateDelegate_OutputDelegate_3, bool CallFunc_K2_IsTimerActiveHandle_ReturnValue, float CallFunc_RandomFloatInRange_ReturnValue, bool CallFunc_HasAuthority_ReturnValue_3, float CallFunc_BreakVector_X, float CallFunc_BreakVector_Y, float CallFunc_BreakVector_Z, FVector CallFunc_MakeVector_ReturnValue, float CallFunc_RandomFloatInRange_ReturnValue_1, FRotator CallFunc_MakeRotator_ReturnValue, FHitResult CallFunc_K2_SetRelativeRotation_SweepHitResult, FExecuteUbergraph_BP_HackingPodK2Node_CreateDelegate_OutputDelegate_4 K2Node_CreateDelegate_OutputDelegate_4, bool K2Node_ComponentBoundEvent_canUse_1, FLinearColor CallFunc_Array_Get_Item_1, FLinearColor CallFunc_Array_Get_Item_2, TArray<class UPointLightComponent*>& K2Node_MakeArray_Array, class UPointLightComponent* CallFunc_Array_Get_Item_3, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_IsValid_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, FLinearColor CallFunc_Array_GetRandom_Item, FLinearColor CallFunc_Array_GetRandom_Item_1, FLinearColor CallFunc_Array_GetRandom_Item_2, FLinearColor CallFunc_Array_GetRandom_Item_3, TArray<FLinearColor>& K2Node_MakeArray_Array_1, FLinearColor CallFunc_Array_GetRandom_Item_4, FLinearColor CallFunc_Array_GetRandom_Item_5, TArray<FLinearColor>& K2Node_MakeArray_Array_2, bool CallFunc_BooleanOR_ReturnValue, bool K2Node_ComponentBoundEvent_canUse, EHackingPodState Temp_byte_Variable, class AFSDGameMode* CallFunc_GetFSDGameMode_ReturnValue_1, class UDifficultyManager* CallFunc_GetDifficultyManager_ReturnValue, float CallFunc_GetPointExtractionScaler_ReturnValue, float CallFunc_Divide_FloatFloat_ReturnValue, bool Temp_bool_IsClosed_Variable_4, bool Temp_bool_Variable, bool CallFunc_IsAlive_ReturnValue, float K2Node_Select_Default, bool CallFunc_HasAuthority_ReturnValue_4, bool CallFunc_HackingInProgress_NewParam, bool CallFunc_HackingInProgress_NewParam_1, float CallFunc_MakeLiteralFloat_ReturnValue, FVector CallFunc_MakeVector_ReturnValue_1, class UParticleSystemComponent* CallFunc_SpawnEmitterAttached_ReturnValue_2, class UAudioComponent* CallFunc_SpawnSoundAttached_ReturnValue_1, bool CallFunc_FanColorsIntact_FansIntact, bool CallFunc_HasAuthority_ReturnValue_5, EHackingPodState Temp_byte_Variable_1, class APlayerCharacter* K2Node_ComponentBoundEvent_user_1, EInputKeys K2Node_ComponentBoundEvent_key_1, class UPrimitiveComponent* K2Node_ComponentBoundEvent_OverlappedComponent_2, class AActor* K2Node_ComponentBoundEvent_OtherActor_2, class UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp_2, int32 K2Node_ComponentBoundEvent_OtherBodyIndex_2, bool K2Node_ComponentBoundEvent_bFromSweep_1, const FHitResult K2Node_ComponentBoundEvent_SweepResult_1, class UAnimInstance* CallFunc_GetAnimInstance_ReturnValue, class APlayerCharacter* K2Node_DynamicCast_AsPlayer_Character, bool K2Node_DynamicCast_bSuccess_2, float CallFunc_PlaySlotAnimation_ReturnValue, class APlayerCharacter* K2Node_CustomEvent_ShoutingPlayer, FVector CallFunc_GetActorGroundLocation_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue_1, float CallFunc_Square_ReturnValue, float CallFunc_Vector_DistanceSquared_ReturnValue, bool CallFunc_Less_FloatFloat_ReturnValue, bool CallFunc_Array_Contains_ReturnValue, int32 CallFunc_Array_Add_ReturnValue, bool Temp_bool_Variable_1, EHackingPodState K2Node_Select_Default_1, EHackingPodState K2Node_Event_nextState, EHackingPodState K2Node_Event_oldState, bool K2Node_SwitchEnum_CmpSuccess, bool K2Node_SwitchEnum_CmpSuccess_1, class ABP_TetherDispenser_C* CallFunc_GetDispenser_AsBP_Tether_Dispenser, class ABP_TetherDispenser_C* CallFunc_GetDispenser_AsBP_Tether_Dispenser_1, EHackingPodState CallFunc_GetState_ReturnValue, bool CallFunc_EqualEqual_ByteByte_ReturnValue, FExecuteUbergraph_BP_HackingPodK2Node_CreateDelegate_OutputDelegate_5 K2Node_CreateDelegate_OutputDelegate_5, bool CallFunc_IsConnected_ReturnValue, EHackingPodState CallFunc_GetState_ReturnValue_1, bool CallFunc_EqualEqual_ByteByte_ReturnValue_1, TEnumAsByte<EMoveComponentAction::Type> Temp_byte_Variable_2, float K2Node_CustomEvent_DeltaTime_1, float K2Node_CustomEvent_NormalizedTime_1, bool CallFunc_HasAuthority_ReturnValue_6, TSubclassOf<class AActor> CallFunc_Array_GetRandom_Item_6, int32 CallFunc_Subtract_IntInt_ReturnValue, FTransform CallFunc_K2_GetComponentToWorld_ReturnValue, int32 CallFunc_RandomIntegerInRange_ReturnValue, class AActor* CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_1, bool CallFunc_LessEqual_IntInt_ReturnValue, class AActor* CallFunc_FinishSpawningActor_ReturnValue_1, bool CallFunc_RandomBoolWithWeight_ReturnValue, EHackingPodState CallFunc_GetState_ReturnValue_2, bool CallFunc_EqualEqual_ByteByte_ReturnValue_2, class UPrimitiveComponent* K2Node_ComponentBoundEvent_OverlappedComponent_1, class AActor* K2Node_ComponentBoundEvent_OtherActor_1, class UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp_1, int32 K2Node_ComponentBoundEvent_OtherBodyIndex_1, bool K2Node_ComponentBoundEvent_bFromSweep, const FHitResult K2Node_ComponentBoundEvent_SweepResult, class UPrimitiveComponent* K2Node_ComponentBoundEvent_OverlappedComponent, class AActor* K2Node_ComponentBoundEvent_OtherActor, class UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp, int32 K2Node_ComponentBoundEvent_OtherBodyIndex, class APlayerCharacter* K2Node_DynamicCast_AsPlayer_Character_1, bool K2Node_DynamicCast_bSuccess_3, class APlayerCharacter* K2Node_DynamicCast_AsPlayer_Character_2, bool K2Node_DynamicCast_bSuccess_4, bool CallFunc_IsLocallyControlled_ReturnValue, bool CallFunc_IsLocallyControlled_ReturnValue_1, bool CallFunc_HasAuthority_ReturnValue_7, bool CallFunc_Not_PreBool_ReturnValue_1, bool CallFunc_BooleanAND_ReturnValue_1, FVector CallFunc_K2_GetComponentLocation_ReturnValue_1, EHackingPodState CallFunc_GetState_ReturnValue_3, bool CallFunc_EqualEqual_ByteByte_ReturnValue_3, class UMiniTimerAction* CallFunc_MiniTimer_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, bool CallFunc_IsAlive_ReturnValue_1, float Temp_float_Variable_2, class AActor* K2Node_CustomEvent_Saluter, class UAnimInstance* CallFunc_GetAnimInstance_ReturnValue_1, EHackingPodState CallFunc_GetState_ReturnValue_4, class UFacilityHackingPodAnimInstance* K2Node_DynamicCast_AsFacility_Hacking_Pod_Anim_Instance, bool K2Node_DynamicCast_bSuccess_5, bool CallFunc_EqualEqual_ByteByte_ReturnValue_4, float CallFunc_PlaySlotAnimation_ReturnValue_1, float Temp_float_Variable_3, FLinearColor CallFunc_LinearColorLerp_ReturnValue, float K2Node_CustomEvent_DeltaTime, float K2Node_CustomEvent_NormalizedTime, FVector CallFunc_MakeVector_ReturnValue_2, class UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue_1, FTransform CallFunc_K2_GetComponentToWorld_ReturnValue_1, class UTetherComponent* CallFunc_GetForwardConnection_ReturnValue, class AActor* CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_2, bool CallFunc_IsValid_ReturnValue_2, class ABP_HackingPodDrillDebris_C* CallFunc_FinishSpawningActor_ReturnValue_2, bool CallFunc_Not_PreBool_ReturnValue_2, class UTetherComponent* K2Node_ComponentBoundEvent_frontConnection, class UTetherComponent* K2Node_ComponentBoundEvent_backConnection, bool CallFunc_BooleanAND_ReturnValue_2, bool CallFunc_IsValid_ReturnValue_3, bool CallFunc_Not_PreBool_ReturnValue_3, EHackingPodState CallFunc_GetState_ReturnValue_5, bool CallFunc_EqualEqual_ByteByte_ReturnValue_5, FExecuteUbergraph_BP_HackingPodK2Node_CreateDelegate_OutputDelegate_6 K2Node_CreateDelegate_OutputDelegate_6, bool CallFunc_BooleanAND_ReturnValue_3, class ABP_TetherDispenser_C* CallFunc_GetDispenser_AsBP_Tether_Dispenser_2, class AActor* K2Node_CustomEvent_spawnedItem, EHackingPodState CallFunc_GetState_ReturnValue_6, bool CallFunc_EqualEqual_ByteByte_ReturnValue_6, bool CallFunc_Not_PreBool_ReturnValue_4, bool CallFunc_BooleanAND_ReturnValue_4, EHackingPodState CallFunc_GetState_ReturnValue_7, class AFSDGameState* CallFunc_GetFSDGameState_ReturnValue, bool CallFunc_NotEqual_ByteByte_ReturnValue, bool CallFunc_IsValid_ReturnValue_4, class AFSDPlayerState* K2Node_CustomEvent_PlayerState_1, class AFSDPlayerState* K2Node_CustomEvent_PlayerState);
    void StateChanged__DelegateSignature(TEnumAsByte<ETetherDispenserState::Type> State);
    void OpenChanged__DelegateSignature(bool Open);
};

#endif
