#ifndef UE4SS_SDK_BP_Pipeline_Segment_HPP
#define UE4SS_SDK_BP_Pipeline_Segment_HPP

class ABP_Pipeline_Segment_C : public APipelineSegment
{
    FPointerToUberGraphFrame UberGraphFrame;
    class UTerrainScannerStaticMesh* TerrainScannerStaticMesh;
    class UTerrainScannerSplineMesh* TerrainScannerSplineMesh;
    class UStaticMeshComponent* ActivateLightCone;
    class UPointLightComponent* ActivatePointLight ;
    class UParticleSystemComponent* BrokenParticleSystem_Decals;
    class UChildActorComponent* ActivateHologram;
    class UAudioComponent* PipeLeakingMorkiteSprayingOut_Cue;
    class UAudioComponent* PipeLeakingAlarm_Cue;
    class UStaticMeshComponent* SM_LightCone_Red;
    class UParticleSystemComponent* BrokenParticleSystem 05;
    class UParticleSystemComponent* BrokenParticleSystem 04;
    class UParticleSystemComponent* BrokenParticleSystem 03;
    class UParticleSystemComponent* BrokenParticleSystem 02;
    class UChildActorComponent* BP_StatusLamp;
    class USceneComponent* BrokenNode;
    class USphereComponent* RepairCollider;
    class USphereComponent* ActivateSegmentCollider;
    class UParticleSystemComponent* ConnectedParticleSystem;
    class USphereComponent* NextSegmentCollider;
    class USplineDecoratorComponent* RingDecorator;
    class UPointLightComponent* PointLight Red;
    class UParticleSystemComponent* BrokenParticleSystem 01;
    class UTerrainScannerStaticMesh* TerrainScanner_Broken;
    class UAudioComponent* AudioActivating;
    class USimpleObjectInfoComponent* SimpleObjectInfo;
    class UBP_Pipeline_Movement_C* BP_Pipeline_Movement;
    class UArrowComponent* Arrow;
    float Timeline_0_Progress_DAE98DA44362821170C92FBA184208DB;
    TEnumAsByte<ETimelineDirection::Type> Timeline_0__Direction_DAE98DA44362821170C92FBA184208DB;
    class UTimelineComponent* Timeline_0;
    float BuildTimeline_Progress_6223F38446980B06F3713AAB20D1CEB4;
    TEnumAsByte<ETimelineDirection::Type> BuildTimeline__Direction_6223F38446980B06F3713AAB20D1CEB4;
    class UTimelineComponent* BuildTimeline;
    TArray<class UMaterialInterface*> MaterialsEndPost;
    class UMaterialInterface* MaterialPipe;
    class UMaterialInterface* MaterialBlueprintValid;
    class UMaterialInterface* MaterialBlueprintInvalid;
    float Scale;
    float Height;
    float MinValidDistance;
    float MaxValidDistance;
    float SplineMeshDistance;
    class UAudioComponent* BuildingAudioComponent;
    ETrackBuildPlacementState LastState;
    bool SegmentValid;
    class ABP_AttackablePiplinesegmentActor_C* AttackableActor;
    float MaxLightIntensity;
    FSimpleObjectInfoData PipelineObjectInfo;
    FSimpleObjectInfoData PipelineObjectInfoBroken;
    FSimpleObjectInfoData ConnectorObjectInfo;
    FSimpleObjectInfoData ConnectorObjectInfoBroken;

    bool IsPhotosensitiveMode(class UFSDGameUserSettings* CallFunc_GetFSDGameUserSettings_ReturnValue, bool CallFunc_GetPhotosensitiveMode_ReturnValue);
    void HandlePhotosensitivity(bool CallFunc_IsPhotosensitiveMode_ReturnValue);
    void UpdatePipelineNumber(class UMaterialInterface* Material, int32 Temp_int_Variable, class UMaterialInterface* Temp_object_Variable, class UMaterialInterface* Temp_object_Variable_1, class UMaterialInterface* Temp_object_Variable_2, ETrackBuildPlacementState CallFunc_GetPlacementState_ReturnValue, bool CallFunc_EqualEqual_ByteByte_ReturnValue, class APipelineStart* CallFunc_GetPipelineStart_ReturnValue, class APipelineStart* CallFunc_GetPipelineStart_ReturnValue_1, bool CallFunc_IsValid_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, bool CallFunc_Greater_IntInt_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue, int32 CallFunc_Clamp_ReturnValue, class UMaterialInterface* K2Node_Select_Default);
    void OverrideEndPostMaterial(class UMaterialInterface* Material, bool Temp_bool_Variable, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_IsValid_ReturnValue, class UMaterialInterface* CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, class UMaterialInterface* K2Node_Select_Default, bool CallFunc_Less_IntInt_ReturnValue);
    void UpdateConnectableGFX(bool Temp_bool_Variable, class UMaterialInterface* Temp_object_Variable, class UMaterialInterface* Temp_object_Variable_1, bool Temp_bool_Variable_1, class UFSDGameUserSettings* CallFunc_GetFSDGameUserSettings_ReturnValue, bool CallFunc_GetPhotosensitiveMode_ReturnValue, class UMaterialInterface* K2Node_Select_Default, int32 CallFunc_GetMaterialIndex_ReturnValue, class UMaterialInterface* CallFunc_GetMaterial_ReturnValue, class UMaterialInterface* K2Node_Select_Default_1);
    void UpdatePlacementState(ETrackBuildPlacementState InState, bool Finished, class UMaterialInterface* BlueprintMaterial, bool Temp_bool_Variable, TEnumAsByte<ECollisionEnabled::Type> Temp_byte_Variable, TEnumAsByte<ECollisionEnabled::Type> Temp_byte_Variable_1, bool Temp_bool_Variable_1, bool Temp_bool_Variable_2, class UMaterialInterface* Temp_object_Variable, bool K2Node_SwitchEnum_CmpSuccess, class UTrackBuilderConnectPoint* CallFunc_GetConnectPoint_ReturnValue, bool Temp_bool_Variable_3, bool CallFunc_IsValid_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, bool CallFunc_EqualEqual_ByteByte_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, bool CallFunc_GetIsSegmentEndTransformValid_ReturnValue, bool CallFunc_NotEqual_ByteByte_ReturnValue, bool CallFunc_NotEqual_ByteByte_ReturnValue_1, bool CallFunc_EqualEqual_ByteByte_ReturnValue_1, bool CallFunc_EqualEqual_ByteByte_ReturnValue_2, bool CallFunc_GetIsSegmentEndTransformValid_ReturnValue_1, bool CallFunc_NotEqual_BoolBool_ReturnValue, bool CallFunc_BooleanOR_ReturnValue, class UMaterialInterface* K2Node_Select_Default, class UMaterialInterface* K2Node_Select_Default_1, bool CallFunc_EqualEqual_ByteByte_ReturnValue_3, bool CallFunc_EqualEqual_ByteByte_ReturnValue_4, TEnumAsByte<ECollisionEnabled::Type> K2Node_Select_Default_2, class UMaterialInterface* K2Node_Select_Default_3);
    void UserConstructionScript(float RelativeScale, TArray<class UMaterialInterface*>& CallFunc_GetMaterials_ReturnValue, class UMaterialInterface* CallFunc_GetMaterial_ReturnValue, FVector CallFunc_Conv_FloatToVector_ReturnValue, float CallFunc_Divide_FloatFloat_ReturnValue, FVector2D CallFunc_MakeVector2D_ReturnValue, FVector2D CallFunc_MakeVector2D_ReturnValue_1);
    void BuildTimeline__FinishedFunc();
    void BuildTimeline__UpdateFunc();
    void Timeline_0__FinishedFunc();
    void Timeline_0__UpdateFunc();
    void ReceiveBeginPlay();
    void ReceivPlacementValidChanged(bool InIsValid);
    void ReceivePlacementStateChanged(ETrackBuildPlacementState NewState);
    void BndEvt__SegmentHealthComponent_K2Node_ComponentBoundEvent_1_DeathSig__DelegateSignature(class UHealthComponentBase* HealthComponent);
    void ReversePipelineAnim();
    void BndEvt__SegmentHealthComponent_K2Node_ComponentBoundEvent_2_DamageSig__DelegateSignature(float Amount);
    void Update Can Undo();
    void BndEvt__NextSegmentUsable_K2Node_ComponentBoundEvent_0_UsableChangedSignature__DelegateSignature(bool CanUse);
    void ReceiveSegmentBrokenChanged(bool InSegmentBroken);
    void ReceivePlacementFinished();
    void BndEvt__ActivateSegmentUsable_K2Node_ComponentBoundEvent_5_UsableChangedSignature__DelegateSignature(bool CanUse);
    void UpdateCanActivateSegmentGFX();
    void BndEvt__ActivateSegmentUsable_K2Node_ComponentBoundEvent_4_UsedBySignature__DelegateSignature(class APlayerCharacter* User, EInputKeys Key);
    void ScheduleUpdatePlacementState();
    void CarveAroundSegment();
    void ReceiveSegmentActivatedProgress(float InProgress);
    void OnRepaired(class APlayerCharacter* InUser);
    void Hide Endpost Items();
    void SetupPipelineNumber();
    void SegmentBrokenGFX();
    void SegmentBrokenLocalWave();
    void SegmentBrokenLaserpointerInfo();
    void SegmentBrokenAudio();
    void BndEvt__BrokenParticleSystem_Decals_K2Node_ComponentBoundEvent_6_ParticleCollisionSignature__DelegateSignature(FName EventName, float EmitterTime, int32 ParticleTime, FVector Location, FVector Velocity, FVector Direction, FVector Normal, FName BoneName, class UPhysicalMaterial* PhysMat);
    void ReceivePlacementBegin();
    void ParticlesOnPlaced();
    void ExecuteUbergraph_BP_Pipeline_Segment(int32 EntryPoint, bool Temp_bool_Variable, bool Temp_bool_Variable_1, float Temp_float_Variable, float Temp_float_Variable_1, bool Temp_bool_IsClosed_Variable, bool Temp_bool_Has_Been_Initd_Variable, bool K2Node_Event_InIsValid, bool CallFunc_HasAuthority_ReturnValue, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, ETrackBuildPlacementState K2Node_Event_newState, FVector CallFunc_K2_GetComponentLocation_ReturnValue, class UHealthComponentBase* K2Node_ComponentBoundEvent_HealthComponent, class UAudioComponent* CallFunc_SpawnSoundAtLocation_ReturnValue, bool CallFunc_IsValid_ReturnValue, float CallFunc_Multiply_FloatFloat_ReturnValue, FVector CallFunc_MakeVector_ReturnValue, bool K2Node_SwitchEnum_CmpSuccess, float K2Node_ComponentBoundEvent_Amount, bool CallFunc_HasAuthority_ReturnValue_1, bool CallFunc_IsAlive_ReturnValue, float CallFunc_GetHealth_ReturnValue, float CallFunc_Subtract_FloatFloat_ReturnValue, float CallFunc_Heal_ReturnValue, bool K2Node_ComponentBoundEvent_canUse_1, bool CallFunc_HasAuthority_ReturnValue_2, bool K2Node_Event_InSegmentBroken, bool K2Node_ComponentBoundEvent_canUse, class APlayerCharacter* K2Node_ComponentBoundEvent_user, EInputKeys K2Node_ComponentBoundEvent_key, bool CallFunc_IsPlaying_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, bool CallFunc_HasAuthority_ReturnValue_3, class ADeepCSGWorld* CallFunc_GetCSGWorld_ReturnValue, class ADeepCSGWorld* CallFunc_GetCSGWorld_ReturnValue_1, bool CallFunc_IsValid_ReturnValue_1, bool CallFunc_BooleanAND_ReturnValue, float K2Node_Event_InProgress, FVector CallFunc_GetLocationAndTangentsAtSplinePoint_Location, FVector CallFunc_GetLocationAndTangentsAtSplinePoint_ArriveTangent, FVector CallFunc_GetLocationAndTangentsAtSplinePoint_LeaveTangent, FVector CallFunc_GetLocationAndTangentsAtSplinePoint_Location_1, FVector CallFunc_GetLocationAndTangentsAtSplinePoint_ArriveTangent_1, FVector CallFunc_GetLocationAndTangentsAtSplinePoint_LeaveTangent_1, FVector CallFunc_Add_VectorVector_ReturnValue, FVector CallFunc_Add_VectorVector_ReturnValue_1, bool CallFunc_IsValid_ReturnValue_2, float CallFunc_Multiply_FloatFloat_ReturnValue_1, bool CallFunc_GetIsSegmentActivated_ReturnValue, class APlayerCharacter* K2Node_Event_InUser, FVector CallFunc_K2_GetComponentLocation_ReturnValue_1, class UAudioComponent* CallFunc_SpawnSoundAtLocation_ReturnValue_1, TArray<class USceneComponent*>& CallFunc_GetChildrenComponents_Children, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable, class USceneComponent* CallFunc_Array_Get_Item, FTransform CallFunc_GetSegmentEndTransform_ReturnValue, FTransform CallFunc_GetSegmentEndTransform_ReturnValue_1, class AActor* CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue, class ABP_LocalWaveTrigger_C* CallFunc_FinishSpawningActor_ReturnValue, FName K2Node_ComponentBoundEvent_EventName, float K2Node_ComponentBoundEvent_EmitterTime, int32 K2Node_ComponentBoundEvent_ParticleTime, FVector K2Node_ComponentBoundEvent_location, FVector K2Node_ComponentBoundEvent_Velocity, FVector K2Node_ComponentBoundEvent_Direction, FVector K2Node_ComponentBoundEvent_Normal, FName K2Node_ComponentBoundEvent_boneName, class UPhysicalMaterial* K2Node_ComponentBoundEvent_physmat, FVector CallFunc_ComponentToWorldLocation_ReturnValue, class UAudioComponent* CallFunc_SpawnSoundAtLocation_ReturnValue_2, class APipelineStart* CallFunc_GetPipelineStart_ReturnValue, bool CallFunc_HasAuthority_ReturnValue_4, bool CallFunc_IsValid_ReturnValue_3, FVector CallFunc_K2_GetActorLocation_ReturnValue, class UAudioComponent* CallFunc_SpawnSoundAtLocation_ReturnValue_3, class UTrackBuilderConnectPoint* CallFunc_GetConnectPoint_ReturnValue, FVector CallFunc_ComponentToWorldLocation_ReturnValue_1, bool CallFunc_IsValid_ReturnValue_4, class UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue, ETrackBuildPlacementState CallFunc_GetPlacementState_ReturnValue, ETrackBuildPlacementState CallFunc_GetPlacementState_ReturnValue_1, bool CallFunc_IsPhotosensitiveMode_ReturnValue, bool CallFunc_HasAuthority_ReturnValue_5, float K2Node_Select_Default, FVector CallFunc_K2_GetActorLocation_ReturnValue_1, class UAudioComponent* CallFunc_SpawnSoundAtLocation_ReturnValue_4, FVector CallFunc_K2_GetComponentLocation_ReturnValue_2, bool CallFunc_NotEqual_ObjectObject_ReturnValue, float CallFunc_BreakVector_X, float CallFunc_BreakVector_Y, float CallFunc_BreakVector_Z, float CallFunc_Add_FloatFloat_ReturnValue, FVector CallFunc_MakeVector_ReturnValue_1, class UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue_1, class AActor* CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_1, class ABP_AttackablePiplinesegmentActor_C* CallFunc_FinishSpawningActor_ReturnValue_1, float CallFunc_Ease_ReturnValue, bool CallFunc_Less_FloatFloat_ReturnValue, class UTrackBuilderConnectPoint* CallFunc_GetConnectPoint_ReturnValue_1, bool CallFunc_IsValid_ReturnValue_5, bool CallFunc_Not_PreBool_ReturnValue_1, class UTrackBuilderConnectPoint* CallFunc_GetConnectPoint_ReturnValue_2, float CallFunc_GetDistanceAlongSplineAtSplinePoint_ReturnValue, bool CallFunc_IsValid_ReturnValue_6, float K2Node_Select_Default_1);
};

#endif
