#ifndef UE4SS_SDK_BP_PlayerCharacter_HPP
#define UE4SS_SDK_BP_PlayerCharacter_HPP

class ABP_PlayerCharacter_C : public APlayerCharacter
{
    FPointerToUberGraphFrame UberGraphFrame;
    class UBP_EnemyControlState_C* BP_EnemyControlState;
    class UPointLightComponent* FilmFaceLight;
    class UBP_PushingState_C* BP_PushingState;
    class UBP_TrackMovementState_C* BP_TrackMovementState;
    class UBP_SelfiePoint_C* SelfieSpringArmPoint;
    class USpringArmComponent* SelfieSpringArm;
    class USceneComponent* Fixed_Selfie_Points;
    class USceneComponent* SelfieCameraSetup;
    class UShieldBoostUsable* ShieldBoostUsable;
    class UBP_AudioControl_LowHealth_C* BP_AudioControl;
    class UBP_AttachedState_C* BP_AttachedState;
    class UBP_PilotingState_C* BP_PilotingState;
    class UBP_DeadState_C* BP_DeadState;
    class UBP_PhotographyState_C* BP_PhotographyState;
    class UBP_PassedOut_C* BP_PassedOut;
    class UBP_IntoxicationComponent_C* BP_IntoxicationComponent;
    class UBP_FrozenState_C* BP_FrozenState;
    class UStaticMeshComponent* ScannerArrow;
    class UBP_GrabbedState_C* BP_GrabbedState;
    class UPointLightComponent* PointLight;
    class USpotLightComponent* SpotLight;
    class UPointLightComponent* FP_PointLight_CloseShine_Ground;
    class USceneComponent* ShoulderCamLocation;
    class USpringArmComponent* ShoulderCamArm;
    class UPointLightComponent* DebugPointLight;
    class UBP_SelfiePoint_C* BP_SelfiePoint6;
    class UBP_SelfiePoint_C* BP_SelfiePoint5;
    class UBP_SelfiePoint_C* BP_SelfiePoint4;
    class UBP_SelfiePoint_C* BP_SelfiePoint3;
    class UBP_SelfiePoint_C* BP_SelfiePoint2;
    class UBP_SelfiePoint_C* BP_SelfiePoint1;
    class UBP_SelfiePoint_C* BP_SelfiePoint;
    class UBP_SelfiePoint_C* BP_SelfiePoint8;
    class UStaticMeshComponent* DropShadow;
    class UFragileDebrisCleaner* FragileDebrisCleanerCore;
    class UFragileDebrisCleaner* FragileDebrisCleanerFeet;
    class UParticleSystemComponent* P_Ambient_Dust;
    class UBP_FlyingState_C* BP_FlyingState;
    class USpotLightComponent* TP_SpotLight_shadow;
    class USceneComponent* TP_SpotLight;
    class USpotLightComponent* FP_SpotLight_Light;
    class USceneComponent* FP_SpotLight;
    class UPointLightComponent* EmergencyLight;
    class UPointLightComponent* FP_PointLight_CloseShine;
    class UBP_NoMovementState_C* BP_NoMovementState;
    class UBP_ZipLineState_C* BP_ZipLineState;
    class UBP_UsingState_C* BP_UsingState;
    class UAudioComponent* ShieldRegenAudio;
    class URadarPointComponent* radarPoint;
    class UBP_ParalyzedState_C* BP_ParalyzedState;
    class UPointLightComponent* PointLight_SpotCloseShine;
    class UBP_DownedState_C* BP_DownedState;
    class UBP_FallingState_C* BP_FallingState;
    class UBP_WalkingState_C* BP_WalkingState;
    class UStaticMeshComponent* SM_LightCone;
    class UStaticMeshComponent* Mesh_Lamp_rim;
    class UStaticMeshComponent* Mesh_Lamp;
    class USphereComponent* UsableCollision;
    float Emergency_Timeline_Light_Intensity_49385F0B40EDFCE34D2340AC7114B889;
    TEnumAsByte<ETimelineDirection::Type> Emergency_Timeline__Direction_49385F0B40EDFCE34D2340AC7114B889;
    class UTimelineComponent* Emergency Timeline;
    float ShieldRegenTimeline_Volume_007E924B43B618D88D08859A06A1CF61;
    float ShieldRegenTimeline_Pitch_007E924B43B618D88D08859A06A1CF61;
    TEnumAsByte<ETimelineDirection::Type> ShieldRegenTimeline__Direction_007E924B43B618D88D08859A06A1CF61;
    class UTimelineComponent* ShieldRegenTimeline;
    float ShieldRegenTime;
    float LastDamageTime;
    TArray<class UBP_SelfiePoint_C*> FixedSelfiePointList;
    class UBP_SelfiePoint_C* ActiveSelfiePoint;
    bool WasHUDVisible;
    class UReverbEffect* PreDownReverb;
    FScaledEffect MixerConfetti;
    class UParticleSystem* InstantReviveParticles;
    class USoundBase* InstantReviveCue;
    bool LeftShiftPressed;
    bool LeftCtrPressed;
    FTimerHandle SelfieZoomTimer;
    FTimerHandle SelfieMoveRightTimer;
    FTimerHandle SelfieMoveUpTimer;

    void GotoNextSelfiePoint(bool ForceExitSelfieMode, int32 NextIndex, int32 CallFunc_Array_Length_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, FString CallFunc_Conv_IntToString_ReturnValue, FString CallFunc_Conv_IntToString_ReturnValue_1, FString CallFunc_Concat_StrStr_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, FString CallFunc_Concat_StrStr_ReturnValue_1, FString CallFunc_Concat_StrStr_ReturnValue_2, int32 CallFunc_Array_Find_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_1, int32 CallFunc_Add_IntInt_ReturnValue_1, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, class UBP_SelfiePoint_C* CallFunc_Array_Get_Item);
    void SetActiveSelfiePoint(class UBP_SelfiePoint_C* InSelfiePoint, bool CallFunc_IsValid_ReturnValue, class AFSDPlayerController* CallFunc_GetPlayerController_ReturnValue, class AHUD* CallFunc_GetHUD_ReturnValue, class ABP_HUD_C* K2Node_DynamicCast_AsBP_HUD, bool K2Node_DynamicCast_bSuccess, bool CallFunc_IsValid_ReturnValue_1, class AFSDPlayerController* CallFunc_GetPlayerController_ReturnValue_1, bool CallFunc_IsValid_ReturnValue_2, class AHUD* CallFunc_GetHUD_ReturnValue_1, class AFSDHUD* K2Node_DynamicCast_AsFSDHUD, bool K2Node_DynamicCast_bSuccess_1, bool CallFunc_GetHUDVisible_ReturnValue, bool CallFunc_NotEqual_ObjectObject_ReturnValue);
    bool DamageCausesReaction(class UDamageClass* DamageClassbool CallFunc_NotEqual_ObjectObject_ReturnValue);
    class USceneComponent* GetDownCameraAttachPoint();
    class USceneComponent* GetDownCameraRotationPoint();
    void ChromaEffect(uint8 effect);
    void CharacterAudioThrottled(class UDialogDataAsset* Shout, float CallFunc_GetGameTimeInSeconds_ReturnValue, float CallFunc_TimeSince_ReturnValue, bool CallFunc_Greater_FloatFloat_ReturnValue);
    void UpdateHeadLight(bool Temp_bool_Variable, class USoundBase* Temp_object_Variable, class USoundBase* Temp_object_Variable_1, class USoundBase* K2Node_Select_Default, bool CallFunc_IsFirstPerson_ReturnValue, FVector CallFunc_K2_GetComponentLocation_ReturnValue);
    void ShieldRegenTimeline__FinishedFunc();
    void ShieldRegenTimeline__UpdateFunc();
    void Emergency Timeline__FinishedFunc();
    void Emergency Timeline__UpdateFunc();
    void InpActEvt_P_K2Node_InputKeyEvent_16(FKey Key);
    void InpActEvt_LeftShift_K2Node_InputKeyEvent_15(FKey Key);
    void InpActEvt_LeftShift_K2Node_InputKeyEvent_14(FKey Key);
    void InpActEvt_LeftControl_K2Node_InputKeyEvent_13(FKey Key);
    void InpActEvt_LeftControl_K2Node_InputKeyEvent_12(FKey Key);
    void InpActEvt_PageDown_K2Node_InputKeyEvent_11(FKey Key);
    void InpActEvt_PageDown_K2Node_InputKeyEvent_10(FKey Key);
    void InpActEvt_PageUp_K2Node_InputKeyEvent_9(FKey Key);
    void InpActEvt_PageUp_K2Node_InputKeyEvent_8(FKey Key);
    void InpActEvt_Home_K2Node_InputKeyEvent_7(FKey Key);
    void InpActEvt_Home_K2Node_InputKeyEvent_6(FKey Key);
    void InpActEvt_End_K2Node_InputKeyEvent_5(FKey Key);
    void InpActEvt_End_K2Node_InputKeyEvent_4(FKey Key);
    void InpActEvt_Insert_K2Node_InputKeyEvent_3(FKey Key);
    void InpActEvt_Insert_K2Node_InputKeyEvent_2(FKey Key);
    void InpActEvt_Delete_K2Node_InputKeyEvent_1(FKey Key);
    void InpActEvt_Delete_K2Node_InputKeyEvent_0(FKey Key);
    void BP_OnControllerReady();
    void ReceiveBeginPlay();
    void BndEvt__HealthComponent_K2Node_ComponentBoundEvent_0_ArmorHealedSig__DelegateSignature(float Amount);
    void StopRegenAudio();
    void BP_OnUpdateMeshes();
    void CharacterState Changed(ECharacterState NewState);
    void BndEvt__HealthComponent_K2Node_ComponentBoundEvent_0_DamageSig__DelegateSignature(float Amount);
    void BndEvt__HealthComponent_K2Node_ComponentBoundEvent_2_DamageSig__DelegateSignature(float Amount);
    void Init Selfie Cam();
    void SetDustVisible(bool Visible);
    void ReceiveOnHeadlightOn();
    void ResetSaveGameIDInEditor();
    void On Temporary Buff Changed(class UTemporaryBuff* buff, class APlayerCharacter* AffectedPlayer);
    void MixerClientSpawnConfettii(FVector Location, FRotator Rotation);
    void MixerServerSpawnConfettii(FVector Location, FRotator Rotation);
    void MixerSpawnConfetti(FVector Location, FRotator Rotation);
    void PrepareForEndScreen();
    void BndEvt__HealthComponent_K2Node_ComponentBoundEvent_0_HitSig__DelegateSignature(float Damage, class UDamageClass* DamageClass, class AActor* DamageCauser, bool anyHealthLost);
    void BndEvt__HealthComponent_K2Node_ComponentBoundEvent_1_HitSig__DelegateSignature(float Damage, class UDamageClass* DamageClass, class AActor* DamageCauser, bool anyHealthLost);
    void Activate Temporary buff on server(class UTemporaryBuff* buff, class APlayerCharacter* Player);
    void Receive_ShowFieldMedicInstantReviveEffects();
    void InpAxisKeyEvt_MouseX_K2Node_InputAxisKeyEvent_0(float AxisValue);
    void InpAxisKeyEvt_MouseY_K2Node_InputAxisKeyEvent_1(float AxisValue);
    void SelfieZoom(float InDelta);
    void TickSelfieZoom();
    void SelfieMoveUp(float InDirection);
    void TickSelfieMoveUp();
    void SelfieMoveRight(float InDirection);
    void TickSelfieMoveRight();
    void ExecuteUbergraph_BP_PlayerCharacter(int32 EntryPoint, FKey K2Node_InputKeyEvent_Key_8, FKey Temp_struct_Variable, FExecuteUbergraph_BP_PlayerCharacterK2Node_CreateDelegate_OutputDelegate K2Node_CreateDelegate_OutputDelegate, FKey K2Node_InputKeyEvent_Key_7, FTimerHandle CallFunc_K2_SetTimerDelegate_ReturnValue, FKey K2Node_InputKeyEvent_Key_6, FKey Temp_struct_Variable_1, FKey K2Node_InputKeyEvent_Key_5, FKey K2Node_InputKeyEvent_Key_4, FKey Temp_struct_Variable_2, FExecuteUbergraph_BP_PlayerCharacterK2Node_CreateDelegate_OutputDelegate_1 K2Node_CreateDelegate_OutputDelegate_1, FTimerHandle CallFunc_K2_SetTimerDelegate_ReturnValue_1, FExecuteUbergraph_BP_PlayerCharacterK2Node_CreateDelegate_OutputDelegate_2 K2Node_CreateDelegate_OutputDelegate_2, FKey K2Node_InputKeyEvent_Key_3, FTimerHandle CallFunc_K2_SetTimerDelegate_ReturnValue_2, FKey K2Node_InputKeyEvent_Key_2, FKey Temp_struct_Variable_3, FKey K2Node_InputKeyEvent_Key_1, FKey K2Node_InputKeyEvent_Key, FKey Temp_struct_Variable_4, FKey Temp_struct_Variable_5, FKey K2Node_InputKeyEvent_Key_14, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_HasAuthority_ReturnValue, FKey K2Node_InputKeyEvent_Key_15, class UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue, class UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue_1, bool CallFunc_IsValid_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, class UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue_2, FKey K2Node_InputKeyEvent_Key_16, bool CallFunc_IsValid_ReturnValue_2, class UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue_3, bool CallFunc_IsValid_ReturnValue_3, FExecuteUbergraph_BP_PlayerCharacterK2Node_CreateDelegate_OutputDelegate_3 K2Node_CreateDelegate_OutputDelegate_3, class UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue_4, class UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue_5, bool CallFunc_IsValid_ReturnValue_4, bool CallFunc_IsValid_ReturnValue_5, class AFSDPlayerController* CallFunc_GetPlayerController_ReturnValue, FKey K2Node_InputKeyEvent_Key_9, float CallFunc_Multiply_FloatFloat_ReturnValue, bool CallFunc_HasAuthority_ReturnValue_1, float K2Node_ComponentBoundEvent_Amount_2, float CallFunc_GetMaxArmor_ReturnValue, float CallFunc_GetArmorPct_ReturnValue, float CallFunc_Divide_FloatFloat_ReturnValue, bool CallFunc_GreaterEqual_FloatFloat_ReturnValue, bool CallFunc_IsPlaying_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, float CallFunc_Add_FloatFloat_ReturnValue, FKey Temp_struct_Variable_6, bool CallFunc_IsLocallyControlled_ReturnValue, bool CallFunc_IsFirstPerson_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue_1, ECharacterState K2Node_CustomEvent_newState, FKey K2Node_InputKeyEvent_Key_10, bool CallFunc_EqualEqual_ByteByte_ReturnValue, FKey K2Node_InputKeyEvent_Key_11, bool CallFunc_BooleanAND_ReturnValue, float K2Node_ComponentBoundEvent_Amount_1, bool CallFunc_BooleanAND_ReturnValue_1, float K2Node_ComponentBoundEvent_Amount, FVector CallFunc_K2_GetActorLocation_ReturnValue, class UAudioComponent* CallFunc_SpawnSoundAtLocation_ReturnValue, class AProceduralSetup* CallFunc_GetProceduralSetup_ReturnValue, bool CallFunc_IsValid_ReturnValue_6, FExecuteUbergraph_BP_PlayerCharacterK2Node_CreateDelegate_OutputDelegate_4 K2Node_CreateDelegate_OutputDelegate_4, class UParticleSystem* CallFunc_GetAtmosphericParticles_ReturnValue, bool K2Node_CustomEvent_Visible, bool CallFunc_IsValid_ReturnValue_7, bool CallFunc_IsLocallyControlled_ReturnValue_1, class UReverbEffect* CallFunc_GetCurrentReverbEffect_ReturnValue, class UBP_SelfiePoint_C* Temp_object_Variable, TArray<class USceneComponent*>& CallFunc_GetChildrenComponents_Children, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_IsLocallyControlled_ReturnValue_2, bool CallFunc_IsLocallyControlled_ReturnValue_3, bool CallFunc_IsDown_ReturnValue, class ADeepCSGWorld* CallFunc_GetCSGWorld_ReturnValue, bool CallFunc_IsValid_ReturnValue_8, class UMaterialInterface* CallFunc_GetMaterial_ReturnValue, class UMaterialInstanceDynamic* CallFunc_CreateDynamicMaterialInstance_ReturnValue, const FLinearColor CallFunc_GetHeroColor_ReturnValue, bool Temp_bool_Variable, class UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue, class UTemporaryBuff* K2Node_CustomEvent_buff_1, class APlayerCharacter* K2Node_CustomEvent_AffectedPlayer, bool CallFunc_IsValid_ReturnValue_9, class AController* CallFunc_GetController_ReturnValue, class AFSDPlayerController* CallFunc_GetPlayerController_ReturnValue_1, class AFSDPlayerController* K2Node_DynamicCast_AsFSDPlayer_Controller, bool K2Node_DynamicCast_bSuccess, FVector K2Node_CustomEvent_Location_2, FRotator K2Node_CustomEvent_Rotation_2, class UAudioComponent* CallFunc_SpawnSoundAtLocation_ReturnValue_1, class UFXSystemComponent* CallFunc_SpawnScaledEmitterAtLocation_ReturnValue, class USceneComponent* CallFunc_K2_GetRootComponent_ReturnValue, FVector K2Node_CustomEvent_Location_1, FRotator K2Node_CustomEvent_Rotation_1, FVector K2Node_CustomEvent_Location, FRotator K2Node_CustomEvent_Rotation, FKey Temp_struct_Variable_7, float K2Node_ComponentBoundEvent_Damage_1, class UDamageClass* K2Node_ComponentBoundEvent_damageClass_1, class AActor* K2Node_ComponentBoundEvent_DamageCauser_1, bool K2Node_ComponentBoundEvent_anyHealthLost_1, FKey K2Node_InputKeyEvent_Key_12, TScriptInterface<class IIOnDamagedPlayer_C> K2Node_DynamicCast_AsIOn_Damaged_Player, bool K2Node_DynamicCast_bSuccess_1, float K2Node_ComponentBoundEvent_Damage, class UDamageClass* K2Node_ComponentBoundEvent_damageClass, class AActor* K2Node_ComponentBoundEvent_DamageCauser, bool K2Node_ComponentBoundEvent_anyHealthLost, bool CallFunc_NotEqual_ObjectObject_ReturnValue, bool CallFunc_Greater_FloatFloat_ReturnValue, class UTemporaryBuff* K2Node_CustomEvent_buff, class APlayerCharacter* K2Node_CustomEvent_player, bool CallFunc_IsLocallyControlled_ReturnValue_4, bool CallFunc_IsLocallyControlled_ReturnValue_5, bool CallFunc_BooleanAND_ReturnValue_2, class AFSDPlayerController* CallFunc_GetPlayerController_ReturnValue_2, class AFSDPlayerController* CallFunc_GetPlayerController_ReturnValue_3, int32 Temp_int_Array_Index_Variable, FVector CallFunc_K2_GetActorLocation_ReturnValue_1, class USceneComponent* CallFunc_Array_Get_Item, class UBP_SelfiePoint_C* K2Node_DynamicCast_AsBP_Selfie_Point, bool K2Node_DynamicCast_bSuccess_2, int32 CallFunc_Array_Add_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue_2, class UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue, class UAudioComponent* CallFunc_SpawnSoundAtLocation_ReturnValue_2, float K2Node_InputAxisKeyEvent_AxisValue_1, float K2Node_InputAxisKeyEvent_AxisValue, float CallFunc_Multiply_FloatFloat_ReturnValue_1, float CallFunc_Multiply_FloatFloat_ReturnValue_2, bool CallFunc_K2_AttachToComponent_ReturnValue, class UBP_SelfiePoint_C* K2Node_Select_Default, float CallFunc_GetWorldDeltaSeconds_ReturnValue, float CallFunc_Multiply_FloatFloat_ReturnValue_3, FRotator CallFunc_MakeRotator_ReturnValue, float CallFunc_GetWorldDeltaSeconds_ReturnValue_1, FHitResult CallFunc_K2_AddRelativeRotation_SweepHitResult, float CallFunc_Multiply_FloatFloat_ReturnValue_4, FKey K2Node_InputKeyEvent_Key_13, FRotator CallFunc_MakeRotator_ReturnValue_1, FHitResult CallFunc_K2_AddRelativeRotation_SweepHitResult_1, FVector CallFunc_K2_GetActorLocation_ReturnValue_3, class UAudioComponent* CallFunc_SpawnSoundAtLocation_ReturnValue_3, float K2Node_CustomEvent_InDelta, float CallFunc_Abs_ReturnValue, float CallFunc_Multiply_FloatFloat_ReturnValue_5, bool CallFunc_Greater_FloatFloat_ReturnValue_1, float CallFunc_Add_FloatFloat_ReturnValue_1, float K2Node_CustomEvent_InDirection_1, float CallFunc_SignOfFloat_ReturnValue, float CallFunc_Abs_ReturnValue_1, float CallFunc_Multiply_FloatFloat_ReturnValue_6, bool CallFunc_Greater_FloatFloat_ReturnValue_2, float CallFunc_Multiply_FloatFloat_ReturnValue_7, FVector CallFunc_MakeVector_ReturnValue, float K2Node_CustomEvent_InDirection, FHitResult CallFunc_K2_AddRelativeLocation_SweepHitResult, float CallFunc_SignOfFloat_ReturnValue_1, float CallFunc_Abs_ReturnValue_2, float CallFunc_Multiply_FloatFloat_ReturnValue_8, bool CallFunc_Greater_FloatFloat_ReturnValue_3, float CallFunc_Multiply_FloatFloat_ReturnValue_9, FVector CallFunc_MakeVector_ReturnValue_1, FHitResult CallFunc_K2_AddRelativeLocation_SweepHitResult_1, class UCharacterVanityComponent* CallFunc_GetCharacterVanity_ReturnValue, class UAudioComponent* CallFunc_SpawnSound2D_ReturnValue, class UAudioComponent* CallFunc_SpawnSound2D_ReturnValue_1, class UAudioComponent* CallFunc_SpawnSound2D_ReturnValue_2);
};

#endif
