#ifndef UE4SS_SDK_BP_Refinery_HPP
#define UE4SS_SDK_BP_Refinery_HPP

class ABP_Refinery_C : public AFSDRefinery
{
    FPointerToUberGraphFrame UberGraphFrame;
    class UPathfinderCollisionComponent* PB_ButtonConsole;
    class UPathfinderCollisionComponent* PB_UnderMainPlatform2;
    class USkeletalMeshComponent* Refinery;
    class USceneComponent* RespawnPoint;
    class UCapsuleComponent* Capsule;
    class USpotLightComponent* SpotLight;
    class USphereComponent* HeatSource;
    class UOutlineComponent* outline;
    class UChildActorComponent* BP_Refinery_RocketLamp06;
    class UChildActorComponent* BP_Refinery_RocketLamp08;
    class UChildActorComponent* BP_Refinery_RocketLamp07;
    class UChildActorComponent* BP_Refinery_RocketLamp05;
    class UChildActorComponent* BP_Refinery_RocketLamp02;
    class UChildActorComponent* BP_Refinery_RocketLamp04;
    class UChildActorComponent* BP_Refinery_RocketLamp03;
    class UChildActorComponent* BP_Refinery_RocketLamp01;
    class UChildActorComponent* BP_Refinery_Lamp04;
    class UPointLightComponent* PointLight4;
    class UChildActorComponent* BP_Refinery_Lamp03;
    class UChildActorComponent* BP_Refinery_Lamp02;
    class UChildActorComponent* BP_Refinery_Lamp01;
    class UChildActorComponent* OxygenTank01;
    class UChildActorComponent* OxygenTank03;
    class UChildActorComponent* OxygenAudio;
    class UChildActorComponent* OxygenTank02;
    class UOxygenSourceComponent* OxygenSource;
    class USphereComponent* KillSphere;
    class UWidgetComponent* UseButtonWidget;
    class UWidgetComponent* UseButtonMonitor;
    class UStaticMeshComponent* UseButton;
    class UChildActorComponent* BP_Refinery_ProjectorLight3;
    class UChildActorComponent* BP_Refinery_ProjectorLight2;
    class UChildActorComponent* BP_Refinery_ProjectorLight1;
    class UAudioComponent* AudioDropStarted;
    class USceneComponent* AudioRoot;
    class UChildActorComponent* BP_Depositor_02;
    class UChildActorComponent* BP_Depositor_01;
    class USceneComponent* Active Refining Particles;
    class UPathfinderCollisionComponent* PB_BottomPlatform;
    class UPathfinderCollisionComponent* PB_Ramp03;
    class UPathfinderCollisionComponent* PB_Ramp02;
    class UPathfinderCollisionComponent* PB_Ramp01;
    class UPathfinderCollisionComponent* PB_UnderMainPlatform;
    class UPathfinderCollisionComponent* PB_Rocket;
    class UPathfinderCollisionComponent* PC_BottomPlatform;
    class UPathfinderCollisionComponent* PC_Ramp03;
    class UPathfinderCollisionComponent* PC_Ramp02;
    class UPathfinderCollisionComponent* PC_Ramp01;
    class UPathfinderCollisionComponent* PC_MainPlatform;
    class USceneComponent* PathfinderBlockers;
    class UChildActorComponent* BP_Refinery_WarningLight3;
    class UChildActorComponent* BP_Refinery_WarningLight2;
    class UChildActorComponent* BP_Refinery_WarningLight1;
    class UChildActorComponent* ProgressBar03;
    class UChildActorComponent* ProgressBar02;
    class UChildActorComponent* ProgressBar01;
    class UTerrainScannerStaticMesh* TerrainScannerStaticMesh;
    class UTerrainPlacementComponent* TerrainPlacement1;
    class USphereComponent* UseButtonCollider;
    class UMeshCarverComponent* MeshCarver;
    class UChildActorComponent* PipeStart03;
    class UChildActorComponent* PipeStart02;
    class UChildActorComponent* PipeStart01;
    class USpawnActorWithDebrisPosComponent* SpawnTarget;
    class UPointLightComponent* PointLight3;
    class UPointLightComponent* PointLight2;
    class UPointLightComponent* PointLight1;
    class UPointLightComponent* PointLight;
    class USimpleObjectInfoComponent* SimpleObjectInfo;
    class UActorTrackingComponent* ActorTracking;
    class UTerrainPlacementComponent* terrainPlacement;
    class USkeletalMeshComponent* Drill;
    class UEnemyWaveController* ActiveRefiningWave;
    TArray<class APipelineStart*> CompletedPipelines;
    class UEnemyWaveController* ActiveRefiningWaveConstant;
    class ABP_Refinery_LandingZone_C* LandinZoneInstance;
    class UAudioComponent* DrillingSoundInstance;
    class UParticleSystemComponent* DrillParticles01;
    class UParticleSystemComponent* DrillParticles02;
    TArray<class APlayerCharacter*> DeadPlayers;

    bool IsDeepDive(class UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue, class UGeneratedMission* CallFunc_GetGeneratedMission_ReturnValue, bool CallFunc_IsDeepDive_ReturnValue, bool CallFunc_IsValid_ReturnValue);
    void Spawn Landing Zone(FRotator CallFunc_K2_GetActorRotation_ReturnValue, FTransform CallFunc_MakeTransform_ReturnValue, class AActor* CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue, class ABP_Refinery_LandingZone_C* CallFunc_FinishSpawningActor_ReturnValue);
    void CheckPipelineMissionShout(class APipelineStart* InPipelineStart, EPipelineBuildState InPipelineState, bool CallFunc_HasAuthority_ReturnValue, bool CallFunc_EqualEqual_ByteByte_ReturnValue, int32 CallFunc_Array_Add_ReturnValue, bool K2Node_SwitchInteger_CmpSuccess, bool CallFunc_Array_Contains_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, bool K2Node_SwitchEnum_CmpSuccess);
    void ActivatePathfinderBlockers(int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, TArray<class USceneComponent*>& CallFunc_GetChildrenComponents_Children, int32 CallFunc_Array_Length_ReturnValue, class USceneComponent* CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, class UPathfinderCollisionComponent* K2Node_DynamicCast_AsPathfinder_Collision_Component, bool K2Node_DynamicCast_bSuccess);
    void UserConstructionScript();
    void OnDroppodImpact();
    void ReceiveRefineryStateChanged(ERefineryState InState);
    void EnemiesOnStateChanged();
    void ReceiveBeginPlay();
    void Mission Shouts on State Changed();
    void ReceivePipelineStateChanged(class APipelineStart* InPipeline, EPipelineBuildState InState);
    void BndEvt__UsableStartRefining_K2Node_ComponentBoundEvent_0_UsedBySignature__DelegateSignature(class APlayerCharacter* User, EInputKeys Key);
    void OnDrillingStarted();
    void AudioOnStateChanged();
    void OnDropStartedGFX();
    void OnDropImpactGFX();
    void SetupUseButtonUI();
    void BndEvt__KillSphere_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult);
    void BndEvt__HeatSource_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult);
    void BndEvt__HeatSource_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex);
    void CameraShakeOnStateChange();
    void OnObjectivesCompleted_Event_0();
    void BndEvt__UsableStartRefining_K2Node_ComponentBoundEvent_2_UsableChangedSignature__DelegateSignature(bool CanUse);
    void BndEvt__UsableLaunchRocket_K2Node_ComponentBoundEvent_3_UsableChangedSignature__DelegateSignature(bool CanUse);
    void UpdateUseIcon();
    void ExecuteUbergraph_BP_Refinery(int32 EntryPoint, int32 Temp_int_Array_Index_Variable, bool CallFunc_HasAuthority_ReturnValue, bool CallFunc_IsValid_ReturnValue, bool Temp_bool_IsClosed_Variable, bool CallFunc_HasAuthority_ReturnValue_1, bool Temp_bool_Has_Been_Initd_Variable, bool CallFunc_IsValid_ReturnValue_1, ERefineryState K2Node_Event_InState_1, bool K2Node_SwitchEnum_CmpSuccess, bool K2Node_SwitchEnum_CmpSuccess_1, class APipelineStart* K2Node_Event_InPipeline, EPipelineBuildState K2Node_Event_InState, class APlayerCharacter* K2Node_ComponentBoundEvent_user, EInputKeys K2Node_ComponentBoundEvent_key, bool Temp_bool_Has_Been_Initd_Variable_1, class AFSDGameMode* CallFunc_GetFSDGameMode_ReturnValue, class UEnemyWaveManager* CallFunc_GetWaveManager_ReturnValue, class UEWC_PumpSequence_Wave_Refinery_C* CallFunc_TriggerWave_ReturnValue, bool K2Node_SwitchEnum_CmpSuccess_2, FVector CallFunc_K2_GetComponentLocation_ReturnValue, float CallFunc_RandomFloatInRange_ReturnValue, class UUserWidget* CallFunc_GetUserWidgetObject_ReturnValue, bool Temp_bool_IsClosed_Variable_1, class UHUD_RefineryUseButton_C* K2Node_DynamicCast_AsHUD_Refinery_Use_Button, bool K2Node_DynamicCast_bSuccess, FVector CallFunc_K2_GetActorLocation_ReturnValue, bool CallFunc_IsValid_ReturnValue_2, FVector CallFunc_Add_VectorVector_ReturnValue, class UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue, class UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue_1, class UAudioComponent* CallFunc_SpawnSoundAttached_ReturnValue, int32 Temp_int_Array_Index_Variable_1, bool CallFunc_HasAuthority_ReturnValue_2, class AFSDGameState* CallFunc_GetFSDGameState_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue_1, FVector CallFunc_Add_VectorVector_ReturnValue_1, bool CallFunc_IsValid_ReturnValue_3, FTransform CallFunc_MakeTransform_ReturnValue, FVector CallFunc_K2_GetComponentLocation_ReturnValue_1, FVector CallFunc_Add_VectorVector_ReturnValue_2, bool CallFunc_IsValid_ReturnValue_4, class UAudioComponent* CallFunc_SpawnSoundAtLocation_ReturnValue, class UPrimitiveComponent* K2Node_ComponentBoundEvent_OverlappedComponent_2, class AActor* K2Node_ComponentBoundEvent_OtherActor_2, class UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp_2, int32 K2Node_ComponentBoundEvent_OtherBodyIndex_2, bool K2Node_ComponentBoundEvent_bFromSweep_1, const FHitResult K2Node_ComponentBoundEvent_SweepResult_1, bool CallFunc_HasAuthority_ReturnValue_3, class UHealthComponentBase* CallFunc_GetComponentByClass_ReturnValue, bool CallFunc_IsValid_ReturnValue_5, class AActor* CallFunc_GetOwner_ReturnValue, class APlayerCharacter* K2Node_DynamicCast_AsPlayer_Character, bool K2Node_DynamicCast_bSuccess_1, int32 CallFunc_Array_AddUnique_ReturnValue, class AActor* CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_IsValid_ReturnValue_6, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_HasAuthority_ReturnValue_4, class UDialogDataAsset* Temp_object_Variable, class UDialogDataAsset* Temp_object_Variable_1, TArray<class USceneComponent*>& CallFunc_GetChildrenComponents_Children, class USceneComponent* CallFunc_Array_Get_Item_1, int32 CallFunc_Array_Length_ReturnValue_1, class UPathfinderCollisionComponent* K2Node_DynamicCast_AsPathfinder_Collision_Component, bool K2Node_DynamicCast_bSuccess_2, bool CallFunc_Less_IntInt_ReturnValue, bool Temp_bool_Variable, bool CallFunc_EqualEqual_ByteByte_ReturnValue, bool CallFunc_HasAuthority_ReturnValue_5, class AFSDGameMode* CallFunc_GetFSDGameMode_ReturnValue_1, bool CallFunc_BooleanAND_ReturnValue, class UEnemyWaveManager* CallFunc_GetWaveManager_ReturnValue_1, class UEWC_PumpSequence_ConstantPresure_Refinery_C* CallFunc_TriggerWave_ReturnValue_1, FRotator CallFunc_K2_GetActorRotation_ReturnValue, class UPrimitiveComponent* K2Node_ComponentBoundEvent_OverlappedComponent_1, class AActor* K2Node_ComponentBoundEvent_OtherActor_1, class UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp_1, int32 K2Node_ComponentBoundEvent_OtherBodyIndex_1, bool K2Node_ComponentBoundEvent_bFromSweep, const FHitResult K2Node_ComponentBoundEvent_SweepResult, class UPrimitiveComponent* K2Node_ComponentBoundEvent_OverlappedComponent, class AActor* K2Node_ComponentBoundEvent_OtherActor, class UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp, int32 K2Node_ComponentBoundEvent_OtherBodyIndex, bool CallFunc_TryPopActiveStatusEffect_ReturnValue, bool CallFunc_TryPushActiveStatusEffect_ReturnValue, bool K2Node_SwitchEnum_CmpSuccess_3, FVector CallFunc_GetSocketLocation_ReturnValue, FVector CallFunc_K2_GetComponentLocation_ReturnValue_2, class AFSDGameMode* CallFunc_GetFSDGameMode_ReturnValue_2, FHitResult CallFunc_K2_SetActorLocation_SweepHitResult, bool CallFunc_K2_SetActorLocation_ReturnValue, class UEnemyWaveManager* CallFunc_GetWaveManager_ReturnValue_2, bool CallFunc_HasAuthority_ReturnValue_6, class AFSDGameMode* CallFunc_GetFSDGameMode_ReturnValue_3, bool CallFunc_IsDeepDive_ReturnValue, bool K2Node_ComponentBoundEvent_canUse_1, bool K2Node_ComponentBoundEvent_canUse, bool CallFunc_BooleanOR_ReturnValue, bool CallFunc_HasAuthority_ReturnValue_7, bool CallFunc_BooleanAND_ReturnValue_1, bool CallFunc_EqualEqual_ByteByte_ReturnValue_1, bool CallFunc_IsDeepDive_ReturnValue_1, bool CallFunc_BooleanAND_ReturnValue_2, int32 Temp_int_Loop_Counter_Variable_1, bool CallFunc_Less_IntInt_ReturnValue_1, int32 CallFunc_Add_IntInt_ReturnValue_1, bool CallFunc_IsDeepDive_ReturnValue_2, FExecuteUbergraph_BP_RefineryK2Node_CreateDelegate_OutputDelegate K2Node_CreateDelegate_OutputDelegate, class UDialogDataAsset* K2Node_Select_Default, class AFSDGameMode* CallFunc_GetFSDGameMode_ReturnValue_4, class UEnemyWaveManager* CallFunc_GetWaveManager_ReturnValue_3, bool CallFunc_IsValid_ReturnValue_7);
};

#endif
