#ifndef UE4SS_SDK_BP_Spacerig_Spaceball_HPP
#define UE4SS_SDK_BP_Spacerig_Spaceball_HPP

class ABP_Spacerig_Spaceball_C : public AGem
{
    FPointerToUberGraphFrame UberGraphFrame;
    class USingleUsableComponent* SingleUsable;
    class USpotLightComponent* SpotLight12;
    class USpotLightComponent* SpotLight11;
    class USpotLightComponent* SpotLight10;
    class USpotLightComponent* SpotLight9;
    class USpotLightComponent* SpotLight8;
    class USpotLightComponent* SpotLight7;
    class USpotLightComponent* SpotLight6;
    class USpotLightComponent* SpotLight5;
    class USpotLightComponent* SpotLight4;
    class USpotLightComponent* SpotLight3;
    class USpotLightComponent* SpotLight1;
    class USpotLightComponent* SpotLight2;
    class USphereComponent* UseSphere;
    class UStaticMeshComponent* SM_spaceball_01;
    class USphereComponent* Collision;
    class UCarriableComponent* Carriable;
    class APlayerCharacter* KickedBy;
    FVector ImpactNormal;
    FVector ImpactPoint;
    FVector TraceDirection;
    class USoundBase* ImpactSound;
    FVector throwForce;
    bool HasShowedTutorial;
    class UActorComponent* LastBounce;
    FName LastUseKey;

    void ShootBall(float ChipValue);
    void PlayKickAnim(class APlayerCharacter* Kicker);
    void BndEvt__Carriable_K2Node_ComponentBoundEvent_4_CarriableEvent__DelegateSignature();
    void BndEvt__Carriable_K2Node_ComponentBoundEvent_1_CarriableEvent__DelegateSignature();
    void Throw(FVector force);
    void BndEvt__Collision_K2Node_ComponentBoundEvent_10_ComponentHitSignature__DelegateSignature(class UPrimitiveComponent* HitComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, FVector NormalImpulse, const FHitResult& Hit);
    void BndEvt__Collision_K2Node_ComponentBoundEvent_11_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult);
    void BndEvt__SingleUsable_K2Node_ComponentBoundEvent_2_UsedBySignature__DelegateSignature(class APlayerCharacter* User, EInputKeys Key);
    void BndEvt__SingleUsable_K2Node_ComponentBoundEvent_6_UsedBySignature__DelegateSignature(class APlayerCharacter* User, EInputKeys Key);
    void BndEvt__SingleUsable_K2Node_ComponentBoundEvent_7_UsedBySignature__DelegateSignature(class APlayerCharacter* User, EInputKeys Key);
    void BndEvt__SingleUsable_K2Node_ComponentBoundEvent_8_UsableChangedSignature__DelegateSignature(bool CanUse);
    void ExecuteUbergraph_BP_Spacerig_Spaceball(int32 EntryPoint, FRotator CallFunc_GetControlRotation_ReturnValue, float CallFunc_GetStatValue_ReturnValue, FVector CallFunc_GetForwardVector_ReturnValue, TArray<class UCameraComponent*>& CallFunc_GetComponentsByTag_ReturnValue, float CallFunc_BreakVector_X, float CallFunc_BreakVector_Y, float CallFunc_BreakVector_Z, class UCameraComponent* CallFunc_Array_Get_Item, FVector CallFunc_MakeVector_ReturnValue, FVector CallFunc_K2_GetComponentLocation_ReturnValue, FVector CallFunc_Normal_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue, FVector CallFunc_Subtract_VectorVector_ReturnValue, FRotator CallFunc_GetControlRotation_ReturnValue_1, FVector CallFunc_Normal_ReturnValue_1, FVector CallFunc_GetForwardVector_ReturnValue_1, FVector CallFunc_Multiply_VectorFloat_ReturnValue, float CallFunc_VSize_ReturnValue, float CallFunc_Multiply_FloatFloat_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue_1, FVector CallFunc_Multiply_VectorFloat_ReturnValue_1, FVector CallFunc_Add_VectorVector_ReturnValue, FVector CallFunc_Add_VectorVector_ReturnValue_1, class APlayerCharacter* K2Node_CustomEvent_Kicker, FVector CallFunc_K2_GetActorLocation_ReturnValue_2, class UPlayerTPAnimInstance* CallFunc_GetTPAnimInstance_ReturnValue, float CallFunc_Montage_Play_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue_3, FVector CallFunc_MakeVector_ReturnValue_1, float K2Node_CustomEvent_ChipValue, float CallFunc_Multiply_FloatFloat_ReturnValue_1, FVector CallFunc_MakeVector_ReturnValue_2, float CallFunc_Add_FloatFloat_ReturnValue, FVector CallFunc_Add_VectorVector_ReturnValue_2, float CallFunc_Multiply_FloatFloat_ReturnValue_2, FVector CallFunc_Normal_ReturnValue_2, FVector CallFunc_Multiply_VectorFloat_ReturnValue_2, FVector_NetQuantize CallFunc_VectorToNetQuantize_ReturnValue, bool CallFunc_K2_SetActorRotation_ReturnValue, bool Temp_bool_IsClosed_Variable, FVector K2Node_Event_force, FVector CallFunc_K2_GetActorLocation_ReturnValue_4, FVector CallFunc_K2_GetActorLocation_ReturnValue_5, float CallFunc_BreakVector_X_1, float CallFunc_BreakVector_Y_1, float CallFunc_BreakVector_Z_1, float CallFunc_Add_FloatFloat_ReturnValue_1, class UPrimitiveComponent* K2Node_ComponentBoundEvent_HitComponent, class AActor* K2Node_ComponentBoundEvent_OtherActor_1, class UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp_1, FVector K2Node_ComponentBoundEvent_NormalImpulse, const FHitResult K2Node_ComponentBoundEvent_Hit, FVector CallFunc_GetComponentVelocity_ReturnValue, bool CallFunc_BreakHitResult_bBlockingHit, bool CallFunc_BreakHitResult_bInitialOverlap, float CallFunc_BreakHitResult_Time, float CallFunc_BreakHitResult_Distance, FVector CallFunc_BreakHitResult_Location, FVector CallFunc_BreakHitResult_ImpactPoint, FVector CallFunc_BreakHitResult_Normal, FVector CallFunc_BreakHitResult_ImpactNormal, class UPhysicalMaterial* CallFunc_BreakHitResult_PhysMat, class AActor* CallFunc_BreakHitResult_HitActor, class UPrimitiveComponent* CallFunc_BreakHitResult_HitComponent, FName CallFunc_BreakHitResult_HitBoneName, int32 CallFunc_BreakHitResult_HitItem, int32 CallFunc_BreakHitResult_FaceIndex, FVector CallFunc_BreakHitResult_TraceStart, FVector CallFunc_BreakHitResult_TraceEnd, float CallFunc_VSize_ReturnValue_1, bool CallFunc_Greater_FloatFloat_ReturnValue, float CallFunc_Divide_FloatFloat_ReturnValue, float CallFunc_Multiply_FloatFloat_ReturnValue_3, float CallFunc_Multiply_FloatFloat_ReturnValue_4, float CallFunc_FClamp_ReturnValue, bool CallFunc_Greater_FloatFloat_ReturnValue_1, FVector CallFunc_K2_GetActorLocation_ReturnValue_6, FVector CallFunc_K2_GetActorLocation_ReturnValue_7, float CallFunc_BreakVector_X_2, float CallFunc_BreakVector_Y_2, float CallFunc_BreakVector_Z_2, FVector CallFunc_Subtract_VectorVector_ReturnValue_1, bool CallFunc_Greater_FloatFloat_ReturnValue_2, float CallFunc_BreakVector_X_3, float CallFunc_BreakVector_Y_3, float CallFunc_BreakVector_Z_3, FVector CallFunc_MakeVector_ReturnValue_3, class APlayerCharacter* K2Node_DynamicCast_AsPlayer_Character, bool K2Node_DynamicCast_bSuccess, FVector CallFunc_Normal_ReturnValue_3, FVector CallFunc_Multiply_VectorFloat_ReturnValue_3, bool CallFunc_NotEqual_ObjectObject_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, class UPrimitiveComponent* K2Node_ComponentBoundEvent_OverlappedComponent, class AActor* K2Node_ComponentBoundEvent_OtherActor, class UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp, int32 K2Node_ComponentBoundEvent_OtherBodyIndex, bool K2Node_ComponentBoundEvent_bFromSweep, const FHitResult K2Node_ComponentBoundEvent_SweepResult, class APlayerCharacter* K2Node_ComponentBoundEvent_user_2, EInputKeys K2Node_ComponentBoundEvent_key_2, class APlayerCharacter* K2Node_ComponentBoundEvent_user_1, EInputKeys K2Node_ComponentBoundEvent_key_1, bool CallFunc_EqualEqual_ByteByte_ReturnValue, bool CallFunc_EqualEqual_ByteByte_ReturnValue_1, bool CallFunc_PickupItem_ReturnValue, class APlayerCharacter* K2Node_ComponentBoundEvent_user, EInputKeys K2Node_ComponentBoundEvent_key, bool CallFunc_EqualEqual_ByteByte_ReturnValue_2, bool CallFunc_EqualEqual_ByteByte_ReturnValue_3, FName CallFunc_GetEnumeratorName_ReturnValue, bool K2Node_ComponentBoundEvent_canUse, bool CallFunc_HasAuthority_ReturnValue, bool Temp_bool_Has_Been_Initd_Variable, const TArray<class AActor*>& Temp_object_Variable, FHitResult CallFunc_LineTraceSingle_OutHit, bool CallFunc_LineTraceSingle_ReturnValue, bool CallFunc_BreakHitResult_bBlockingHit_1, bool CallFunc_BreakHitResult_bInitialOverlap_1, float CallFunc_BreakHitResult_Time_1, float CallFunc_BreakHitResult_Distance_1, FVector CallFunc_BreakHitResult_Location_1, FVector CallFunc_BreakHitResult_ImpactPoint_1, FVector CallFunc_BreakHitResult_Normal_1, FVector CallFunc_BreakHitResult_ImpactNormal_1, class UPhysicalMaterial* CallFunc_BreakHitResult_PhysMat_1, class AActor* CallFunc_BreakHitResult_HitActor_1, class UPrimitiveComponent* CallFunc_BreakHitResult_HitComponent_1, FName CallFunc_BreakHitResult_HitBoneName_1, int32 CallFunc_BreakHitResult_HitItem_1, int32 CallFunc_BreakHitResult_FaceIndex_1, FVector CallFunc_BreakHitResult_TraceStart_1, FVector CallFunc_BreakHitResult_TraceEnd_1, float CallFunc_Dot_VectorVector_ReturnValue, bool CallFunc_Less_FloatFloat_ReturnValue, bool CallFunc_BooleanAND_ReturnValue_1, FVector CallFunc_K2_GetActorLocation_ReturnValue_8, FVector CallFunc_Subtract_VectorVector_ReturnValue_2, FVector CallFunc_Cross_VectorVector_ReturnValue, FVector CallFunc_Multiply_VectorFloat_ReturnValue_4, FVector_NetQuantize CallFunc_VectorToNetQuantize_ReturnValue_1);
};

#endif
