#ifndef UE4SS_SDK_BPL_Armor_HPP
#define UE4SS_SDK_BPL_Armor_HPP

class UBPL_Armor_C : public UBlueprintFunctionLibrary
{

    void AddBaseArmorStats(class AFSDPlayerState* Player, TArray<FGearStatEntry>& Stats, TSubclassOf<class AArmorPiece> armorClass, class UObject* __WorldContext, FGearStatEntry CallFunc_UPGDESC_ArmorStat_GearStatEntry, bool CallFunc_UPGDESC_ArmorStat_Changed, int32 CallFunc_Array_Add_ReturnValue, FGearStatEntry CallFunc_UPGDESC_ArmorStat_GearStatEntry_1, bool CallFunc_UPGDESC_ArmorStat_Changed_1, int32 CallFunc_Array_Add_ReturnValue_1, FGearStatEntry CallFunc_UPGDESC_ArmorStat_GearStatEntry_2, bool CallFunc_UPGDESC_ArmorStat_Changed_2, int32 CallFunc_Array_Add_ReturnValue_2, FGearStatEntry CallFunc_UPGDESC_ArmorStat_GearStatEntry_3, bool CallFunc_UPGDESC_ArmorStat_Changed_3, int32 CallFunc_Array_Add_ReturnValue_3, FGearStatEntry CallFunc_UPGDESC_TriggeredStat_gear_stat_entry, bool CallFunc_UPGDESC_TriggeredStat_is_upgraded, FGearStatEntry CallFunc_UPGDESC_TriggeredStat_gear_stat_entry_1, bool CallFunc_UPGDESC_TriggeredStat_is_upgraded_1, int32 CallFunc_Array_Add_ReturnValue_4, int32 CallFunc_Array_Add_ReturnValue_5, FGearStatEntry CallFunc_UPGDESC_Armor_GearStatEntry, int32 CallFunc_Array_Add_ReturnValue_6, FGearStatEntry CallFunc_UPGDESC_ArmorStat_GearStatEntry_4, bool CallFunc_UPGDESC_ArmorStat_Changed_4, int32 CallFunc_Array_Add_ReturnValue_7, FGearStatEntry CallFunc_UPGDESC_Armor_GearStatEntry_1, int32 CallFunc_Array_Add_ReturnValue_8, FGearStatEntry CallFunc_UPGDESC_Armor_GearStatEntry_2, int32 CallFunc_Array_Add_ReturnValue_9, FGearStatEntry CallFunc_UPGDESC_ArmorStat_GearStatEntry_5, bool CallFunc_UPGDESC_ArmorStat_Changed_5, FGearStatEntry CallFunc_UPGDESC_ArmorStat_GearStatEntry_6, bool CallFunc_UPGDESC_ArmorStat_Changed_6, int32 CallFunc_Array_Add_ReturnValue_10, int32 CallFunc_Array_Add_ReturnValue_11);
};

#endif
