#ifndef UE4SS_SDK_BPL_ProceduralLevelSetup_HPP
#define UE4SS_SDK_BPL_ProceduralLevelSetup_HPP

class UBPL_ProceduralLevelSetup_C : public UBlueprintFunctionLibrary
{

    void CreateLinearPathFromDNA(class APLS_Base_C* ProceduralSetup, FVector Origin, FVector PathDirection, float horizontalDeviation, float verticalDeviation, FRandRange PathRoomDistance, bool PlaceFirstRoomAtOrigin, bool AddRoomRadiusToRoomDistance, class UMissionDNA*& DNA, FRoomGeneratorGroupInstance& groupInstance, class UObject* __WorldContext, FVector& LastOrigin, int32& LastRoomID, class URoomGenerator*& LastRoomGenerator, class URoomGenerator* RoomGen, float PrevRoomBounds, class APLS_Base_C* Procedural_Setup, FVector CurrentOrigin, int32 CallFunc_Array_LastIndex_ReturnValue, float CallFunc_Add_FloatFloat_ReturnValue, float CallFunc_SelectFloat_ReturnValue, int32 CallFunc_Array_LastIndex_ReturnValue_1, FVector CallFunc_AddRoom_outCenter, FRoomNode CallFunc_AddRoom_outRoom, int32 CallFunc_AddRoom_ReturnValue, FVector CallFunc_FindLocationInDirection_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue, int32 CallFunc_ConnectRoomIds_ReturnValue, int32 Temp_int_Variable, int32 CallFunc_Add_IntInt_ReturnValue, class URoomGenerator* CallFunc_GetRandomRoomWithTags_ReturnValue, bool CallFunc_EqualEqual_IntInt_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, FString CallFunc_GetDisplayName_ReturnValue, FString CallFunc_Concat_StrStr_ReturnValue, bool CallFunc_LessEqual_IntInt_ReturnValue);
    void CreateLinearPath(class APLS_Base_C* ProceduralSetup, FVector Origin, FVector& PathDirection, FVector2D& GraphDeviation, int32 RoomCount, TArray<class URoomGenerator*>& PathRooms, FRandRange& PathRoomDistance, bool PlaceFirstRoomAtOrigin, class UObject* __WorldContext, FVector& LastOrigin, int32& LastRoomID, class APLS_Base_C* Procedural_Setup, FVector CurrentOrigin, FWeightedRoomSelector WeightedRooms, int32 CallFunc_Subtract_IntInt_ReturnValue, float CallFunc_BreakVector2D_X, float CallFunc_BreakVector2D_Y, int32 Temp_int_Variable, bool CallFunc_EqualEqual_IntInt_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, int32 CallFunc_Array_LastIndex_ReturnValue, FRoomNode CallFunc_Array_Get_Item, bool CallFunc_LessEqual_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, class URoomGenerator* CallFunc_SelectRandomRoom_ReturnValue, FVector CallFunc_FindLocationInDirection_ReturnValue, FVector CallFunc_AddRoom_outCenter, FRoomNode CallFunc_AddRoom_outRoom, int32 CallFunc_AddRoom_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue_1, int32 CallFunc_ConnectRoomIds_ReturnValue);
    void CreateLinearPathGrouped(class APLS_Base_C* ProceduralSetup, FVector Origin, FVector PathDirection, int32 RoomCount, float horizontalDeviation, float verticalDeviation, FRandRange PathRoomDistance, TArray<class URoomGeneratorGroup*>& RoomGroups, bool PlaceFirstRoomAtOrigin, bool AddRoomRadiusToRoomDistance, class UObject* __WorldContext, FVector& LastOrigin, int32& LastRoomID, class URoomGenerator*& LastRoomGenerator, float PrevRoomBounds, int32 roomIndex, TArray<class URoomGeneratorGroup*> Room_Groups, class APLS_Base_C* Procedural_Setup, FVector CurrentOrigin, int32 CallFunc_Subtract_IntInt_ReturnValue, int32 Temp_int_Variable, bool CallFunc_EqualEqual_IntInt_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, bool CallFunc_LessEqual_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Array_LastIndex_ReturnValue, int32 CallFunc_RandomIntegerInRangeFromStream_ReturnValue, int32 CallFunc_Array_LastIndex_ReturnValue_1, class URoomGeneratorGroup* CallFunc_Array_Get_Item, class URoomGenerator* CallFunc_GetRandomRoom_ReturnValue, FVector CallFunc_AddRoom_outCenter, FRoomNode CallFunc_AddRoom_outRoom, int32 CallFunc_AddRoom_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue_1, int32 CallFunc_ConnectRoomIds_ReturnValue, float CallFunc_Add_FloatFloat_ReturnValue, float CallFunc_SelectFloat_ReturnValue, FVector CallFunc_FindLocationInDirection_ReturnValue);
};

#endif
