#ifndef UE4SS_SDK_Cheat_List_Pickaxe_HPP
#define UE4SS_SDK_Cheat_List_Pickaxe_HPP

class UCheat_List_Pickaxe_C : public UCheat_EquipList_C
{
    TArray<EPickaxePartLocation> PickaxeParts;

    void GetPickaxeID(class UItemID*& ItemID, class APlayerCharacter* CallFunc_GetCharacter_OutCharacter, bool CallFunc_IsValid_ReturnValue, class AItem* CallFunc_GetItem_ReturnValue);
    void Refresh(int32 Index, bool Owned, bool Equipped, class UPickaxePart* PickaxePart, EPickaxePartLocation Location, FText Category, class UCheat_EquipList_Entry_C* Entry, class UItemID* pickaxeID, FText Temp_text_Variable, bool CallFunc_IsValid_ReturnValue, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable_1, bool Temp_bool_Variable, class UItemID* CallFunc_GetPickaxeID_ItemID, class UCheat_EquipList_Entry_C* CallFunc_AddEntry_OutEntryWidget, bool CallFunc_GetIsPickAxePartAcquired_ReturnValue, int32 Temp_int_Loop_Counter_Variable_1, bool CallFunc_IsPickaxePartEquipped_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_1, FString CallFunc_GetEnumeratorUserFriendlyName_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, FText CallFunc_Conv_StringToText_ReturnValue, bool CallFunc_Greater_IntInt_ReturnValue, TArray<class UPickaxePart*>& CallFunc_GetPickaxeParts_ReturnValue, FText K2Node_Select_Default, class UPickaxePart* CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue_1, bool CallFunc_Less_IntInt_ReturnValue, EPickaxePartLocation CallFunc_Array_Get_Item_1, int32 CallFunc_Array_Length_ReturnValue_2, bool CallFunc_Less_IntInt_ReturnValue_1, FRefreshK2Node_CreateDelegate_OutputDelegate K2Node_CreateDelegate_OutputDelegate, FRefreshK2Node_CreateDelegate_OutputDelegate_1 K2Node_CreateDelegate_OutputDelegate_1);
    void GetCharacter(class APlayerCharacter*& OutCharacter, class APawn* CallFunc_GetOwningPlayerPawn_ReturnValue, class APlayerCharacter* K2Node_DynamicCast_AsPlayer_Character, bool K2Node_DynamicCast_bSuccess);
    void ReceiveEntryOwnedClick(class UCheat_EquipList_Entry_C* InEntryWidget, class UObject* InData, bool InOwned, class UPickaxePart* K2Node_DynamicCast_AsPickaxe_Part, bool K2Node_DynamicCast_bSuccess, bool CallFunc_RemovePickaxePartFromOwned_ReturnValue);
    void ReceiveEntryEquipClick(class UCheat_EquipList_Entry_C* InEntryWidget, class UObject* InData, bool InEquipped, class UCheat_EquipList_Entry_C* OtherEntry, bool CallFunc_Not_PreBool_ReturnValue, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, class UItemID* CallFunc_GetPickaxeID_ItemID, int32 CallFunc_Add_IntInt_ReturnValue, EPickaxePartLocation CallFunc_Array_Get_Item, class UPickaxePart* K2Node_DynamicCast_AsPickaxe_Part, bool K2Node_DynamicCast_bSuccess, TArray<class UCheat_EquipList_Entry_C*>& CallFunc_GetEntries_OutEntries, class UCheat_EquipList_Entry_C* CallFunc_Array_Get_Item_1, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_EqualEqual_ObjectObject_ReturnValue, bool CallFunc_EqualEqual_IntInt_ReturnValue);
    void GetCharacterID(class UPlayerCharacterID*& characterID, class APawn* CallFunc_GetOwningPlayerPawn_ReturnValue, class APlayerCharacter* K2Node_DynamicCast_AsPlayer_Character, bool K2Node_DynamicCast_bSuccess);
};

#endif
