#ifndef UE4SS_SDK_Cheat_OverclockSelection_HPP
#define UE4SS_SDK_Cheat_OverclockSelection_HPP

class UCheat_OverclockSelection_C : public UUserWidget
{
    FPointerToUberGraphFrame UberGraphFrame;
    class UBorder* Border_0;
    class UScrollBox* SB_OverclockList;
    TArray<class UCheat_PerkListItem_C*> perklistItems;

    void Initiate widget(EItemCategory ItemCategory);
    void On state change(bool is Checked, class UItemUpgrade* Item, EItemCategory Item Category);
    void ExecuteUbergraph_Cheat_OverclockSelection(int32 EntryPoint, class UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue, FExecuteUbergraph_Cheat_OverclockSelectionK2Node_CreateDelegate_OutputDelegate K2Node_CreateDelegate_OutputDelegate, class AFSDPlayerState* CallFunc_GetPlayerState_ReturnValue, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable_1, int32 Temp_int_Loop_Counter_Variable_1, int32 CallFunc_Add_IntInt_ReturnValue_1, EItemCategory K2Node_CustomEvent_ItemCategory, class APlayerController* CallFunc_GetOwningPlayer_ReturnValue, class UFSDSaveGame* CallFunc_GetFSDSaveGame_ReturnValue, class UCheat_PerkListItem_C* CallFunc_Create_ReturnValue, class UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_1, TSubclassOf<class APlayerCharacter> CallFunc_GetObjectClass_ReturnValue, class UPlayerCharacterID* CallFunc_GetCharacterID_ReturnValue, class UPanelSlot* CallFunc_AddChild_ReturnValue, TSubclassOf<class AActor> CallFunc_GetEquippedItem_ReturnValue, class UItemUpgrade* CallFunc_GetEquippedOverclock_ReturnValue, class UUpgradableGearComponent* CallFunc_GetComponentFromClass_ReturnValue, bool K2Node_CustomEvent_Is_Checked, class UItemUpgrade* K2Node_CustomEvent_Item, EItemCategory K2Node_CustomEvent_item_category, bool CallFunc_IsValid_ReturnValue, const TArray<class UItemUpgrade*>& CallFunc_GetOverClocks_ReturnValue, class UFSDSaveGame* CallFunc_GetFSDSaveGame_ReturnValue_1, class UItemUpgrade* CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_EqualEqual_ObjectObject_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_1, class UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_2, bool CallFunc_LessEqual_IntInt_ReturnValue, TSubclassOf<class AActor> CallFunc_GetEquippedItem_ReturnValue_1, int32 CallFunc_Array_AddUnique_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_2, class UCheat_PerkListItem_C* CallFunc_Array_Get_Item_1, bool CallFunc_Less_IntInt_ReturnValue_1, bool CallFunc_NotEqual_ObjectObject_ReturnValue);
};

#endif
