#ifndef UE4SS_SDK_EndScreenSetups_HPP
#define UE4SS_SDK_EndScreenSetups_HPP

class UEndScreenSetups_C : public UActorComponent
{
    TArray<FEndScreenMoveSet> VictorySets;
    TArray<FEndScreenMoveSet> DefeatSets;
    TArray<FEndScreenMoveSet> AvailableVictorySets;
    TArray<FEndScreenMoveSet> AvailableDefeatSets;
    FRandomStream RandStream;

    void GetRandomWalkAnim(class UVictoryPose* VicPose, FRandomStream& RandStream, TSoftObjectPtr<UAnimSequence>& Walk, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_EqualEqual_IntInt_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue, int32 CallFunc_RandomIntegerInRangeFromStream_ReturnValue, TSoftObjectPtr<UAnimSequence> CallFunc_Array_Get_Item);
    void LoadVictoryAnims(class UVictoryPose* InputPin, FRandomStream& RandStream, FEndScreenMove& EndScreenMove, TSoftObjectPtr<UAnimSequence> CallFunc_GetRandomWalkAnim_Walk, class UAnimSequence* CallFunc_LoadAnimSeq_Hard, TArray<class UAnimSequence*>& CallFunc_LoadAnimSeqArray_Hard, class UAnimSequence* CallFunc_LoadAnimSeq_Hard_1, class UAnimSequence* CallFunc_LoadAnimSeq_Hard_2, class UAnimSequence* CallFunc_LoadAnimSeq_Hard_3, class UAnimSequence* CallFunc_LoadAnimSeq_Hard_4, TSubclassOf<class AActor> CallFunc_LoadActorClass_Hard, class UAnimSequence* CallFunc_LoadAnimSeq_Hard_5, FEndScreenMove K2Node_MakeStruct_EndScreenMove);
    void LoadActorClass(TSoftClassPtr<AActor> Soft, TSubclassOf<class AActor>& Hard, UClass* CallFunc_LoadClass_ReturnValue, bool CallFunc_IsValidSoftClassReference_ReturnValue, TSubclassOf<class AActor> K2Node_ClassDynamicCast_AsActor, bool K2Node_ClassDynamicCast_bSuccess);
    void LoadAnimSeqArray(TArray<TSoftObjectPtr<UAnimSequence>>& Soft, TArray<class UAnimSequence*>& Hard, class UAnimSequence* element, TArray<class UAnimSequence*> Result, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Array_Length_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable, TSoftObjectPtr<UAnimSequence> CallFunc_Array_Get_Item, bool CallFunc_IsValid_ReturnValue, class UAnimSequence* CallFunc_LoadAnimSeq_Hard, int32 CallFunc_Array_Add_ReturnValue, TArray<class UAnimSequence*>& K2Node_MakeArray_Array);
    void LoadAnimSeq(TSoftObjectPtr<UAnimSequence> Soft, class UAnimSequence*& Hard, class UObject* CallFunc_LoadAsset_Blocking_ReturnValue, bool CallFunc_IsValidSoftObjectReference_ReturnValue, class UAnimSequence* K2Node_DynamicCast_AsAnim_Sequence, bool K2Node_DynamicCast_bSuccess);
    void SplitMoveSetAnims(const TArray<TSoftObjectPtr<UAnimSequence>>& TargetArray, class UAnimSequence*& Selected1, TArray<TSoftObjectPtr<UAnimSequence>>& Rest1, int32 SelectedIdx, TArray<TSoftObjectPtr<UAnimSequence>> Rest, class UAnimSequence* Selected, int32 CallFunc_Array_Length_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue, int32 Temp_int_Variable, bool CallFunc_EqualEqual_IntInt_ReturnValue, bool CallFunc_LessEqual_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_RandomIntegerInRangeFromStream_ReturnValue, TSoftObjectPtr<UAnimSequence> CallFunc_Array_Get_Item, class UAnimSequence* CallFunc_LoadAnimSeq_Hard, int32 CallFunc_Array_Add_ReturnValue);
    void ResetMovesets(int32 NewSeed);
    void RandomWeightedMoveSet(TArray<FEndScreenMoveSet>& Array, FEndScreenMove& Selected, int32 SelectedSoFar, float TotalWeight, int32 CallFunc_Array_Length_ReturnValue, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, FEndScreenMoveSet CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_1, bool CallFunc_Greater_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, float CallFunc_RandomFloatFromStream_ReturnValue, FEndScreenMoveSet CallFunc_Array_Get_Item_1, float CallFunc_Multiply_FloatFloat_ReturnValue, bool CallFunc_LessEqual_FloatFloat_ReturnValue, class UAnimSequence* CallFunc_LoadAnimSeq_Hard, class UAnimSequence* CallFunc_LoadAnimSeq_Hard_1, class UAnimSequence* CallFunc_LoadAnimSeq_Hard_2, TSubclassOf<class AActor> CallFunc_LoadActorClass_Hard, TArray<class UAnimSequence*>& CallFunc_LoadAnimSeqArray_Hard, class UAnimSequence* CallFunc_LoadAnimSeq_Hard_3, class UAnimSequence* CallFunc_SplitMoveSetAnims_Selected1, TArray<TSoftObjectPtr<UAnimSequence>>& CallFunc_SplitMoveSetAnims_Rest1, class UAnimSequence* CallFunc_SplitMoveSetAnims_Selected1_1, TArray<TSoftObjectPtr<UAnimSequence>>& CallFunc_SplitMoveSetAnims_Rest1_1, FString CallFunc_GetDisplayName_ReturnValue, FEndScreenMoveSet K2Node_MakeStruct_EndScreenMoveSet, FString CallFunc_Concat_StrStr_ReturnValue, FEndScreenMove K2Node_MakeStruct_EndScreenMove, float CallFunc_Add_FloatFloat_ReturnValue);
    void GetEndScreenMoveSet(bool Survived, class UVictoryPose* VictPose, FRandomStream& RandStream, FEndScreenMove& Selected, FEndScreenMove CallFunc_LoadVictoryAnims_EndScreenMove, FEndScreenMove CallFunc_RandomWeightedMoveSet_Selected, bool CallFunc_IsValid_ReturnValue, FEndScreenMove CallFunc_RandomWeightedMoveSet_Selected_1);
    void RandomAnimElement(TArray<class UAnimSequence*>& Array, class UAnimSequence*& Output, int32 CallFunc_Array_Length_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue, int32 CallFunc_RandomIntegerInRangeFromStream_ReturnValue, class UAnimSequence* CallFunc_Array_Get_Item);
};

#endif
