#ifndef UE4SS_SDK_EWC_Spiders_Motherlode_HPP
#define UE4SS_SDK_EWC_Spiders_Motherlode_HPP

class UEWC_Spiders_Motherlode_C : public UEWC_Base_C
{
    FPointerToUberGraphFrame UberGraphFrame;
    int32 WaveCountConstantPressure;
    int32 WaveCountWaves;

    class UEnemyWaveManager* GetWaveManager(class AFSDGameMode* CallFunc_GetFSDGameMode_ReturnValue, class UEnemyWaveManager* CallFunc_GetWaveManager_ReturnValue);
    void StartWave();
    void ExecuteUbergraph_EWC_Spiders_Motherlode(int32 EntryPoint, float CallFunc_RandomFloatInRange_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, float CallFunc_Multiply_IntFloat_ReturnValue, float CallFunc_Add_FloatFloat_ReturnValue, float CallFunc_Multiply_IntFloat_ReturnValue_1, float CallFunc_FMax_ReturnValue, float CallFunc_Subtract_FloatFloat_ReturnValue, float CallFunc_Multiply_IntFloat_ReturnValue_2, float CallFunc_Multiply_IntFloat_ReturnValue_3, float CallFunc_Subtract_FloatFloat_ReturnValue_1, float CallFunc_Add_FloatFloat_ReturnValue_1, float CallFunc_FMax_ReturnValue_1, float CallFunc_Add_FloatFloat_ReturnValue_2, float CallFunc_Add_FloatFloat_ReturnValue_3, int32 CallFunc_Add_IntInt_ReturnValue_1, FVector CallFunc_GetSpawnPointInRange_ReturnValue, float CallFunc_RandomFloatInRange_ReturnValue_1, int32 Temp_int_Variable, float CallFunc_Add_FloatFloat_ReturnValue_4, TArray<FVector>& CallFunc_GetSpawnPointsInRange_ReturnValue, float CallFunc_RandomFloatInRange_ReturnValue_2, bool CallFunc_Less_FloatFloat_ReturnValue, TArray<FVector>& CallFunc_GetSpawnPointsInRange_ReturnValue_1, TArray<FVector>& CallFunc_GetSpawnPointsInRange_ReturnValue_2, TArray<FVector>& CallFunc_GetSpawnPointsInRange_ReturnValue_3, TArray<FVector>& CallFunc_GetSpawnPointsInRange_ReturnValue_4, class AFSDGameMode* CallFunc_GetFSDGameMode_ReturnValue, class AFSDGameMode* CallFunc_GetFSDGameMode_ReturnValue_1, class UDifficultyManager* CallFunc_GetDifficultyManager_ReturnValue, class UDifficultyManager* CallFunc_GetDifficultyManager_ReturnValue_1, float CallFunc_GetPointExtractionScaler_ReturnValue, float CallFunc_GetPointExtractionScaler_ReturnValue_1, float CallFunc_FMin_ReturnValue, float CallFunc_Divide_FloatFloat_ReturnValue, float CallFunc_Divide_FloatFloat_ReturnValue_1, float CallFunc_FMax_ReturnValue_2, float CallFunc_FMax_ReturnValue_3, class AFSDGameMode* CallFunc_GetFSDGameMode_ReturnValue_2, class UDifficultyManager* CallFunc_GetDifficultyManager_ReturnValue_2, int32 Temp_int_Variable_1, float CallFunc_GetPointExtractionScaler_ReturnValue_2, bool CallFunc_LessEqual_FloatFloat_ReturnValue, class AFSDGameMode* CallFunc_GetFSDGameMode_ReturnValue_3, class UDifficultyManager* CallFunc_GetDifficultyManager_ReturnValue_3, float CallFunc_GetPointExtractionScaler_ReturnValue_3, class UEnemyWaveManager* CallFunc_GetWaveManager_ReturnValue, bool CallFunc_LessEqual_FloatFloat_ReturnValue_1, class UEnemyWaveManager* CallFunc_GetWaveManager_ReturnValue_1, bool CallFunc_AreScriptedWavesBlocked_ReturnValue);
};

#endif
