#ifndef UE4SS_SDK_HUD_Directional_Damage_IndicatorV2_HPP
#define UE4SS_SDK_HUD_Directional_Damage_IndicatorV2_HPP

class UHUD_Directional_Damage_IndicatorV2_C : public UUserWidget
{
    FPointerToUberGraphFrame UberGraphFrame;
    class UImage* DamageImage;
    class AActor* DamageCauser;
    FVector DamageOrigin;
    class APlayerCharacter* Character;
    TArray<FVector> DamagePoints;
    class UMaterialInstanceDynamic* DamageIndicatorMat;
    float TotalPointTime;
    float FadeTime;
    int32 MaxNumberOfPoints;
    TArray<class AActor*> Enemies;

    void UpdatePoints(int32 Index, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_Array_IsValidIndex_ReturnValue, bool CallFunc_Array_IsValidIndex_ReturnValue_1, FVector CallFunc_K2_GetActorLocation_ReturnValue, class AActor* CallFunc_Array_Get_Item, FVector CallFunc_Array_Get_Item_1, FVector CallFunc_K2_GetActorLocation_ReturnValue_1, float CallFunc_BreakVector_X, float CallFunc_BreakVector_Y, float CallFunc_BreakVector_Z, FVector CallFunc_Subtract_VectorVector_ReturnValue, bool CallFunc_IsValid_ReturnValue, float CallFunc_Vector_HeadingAngle_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Array_IsValidIndex_ReturnValue_2, bool CallFunc_Less_IntInt_ReturnValue, float CallFunc_GetWorldDeltaSeconds_ReturnValue, float CallFunc_Subtract_FloatFloat_ReturnValue, bool CallFunc_LessEqual_FloatFloat_ReturnValue, FVector CallFunc_MakeVector_ReturnValue, FVector CallFunc_MakeVector_ReturnValue_1);
    float CalcFadeStrength(float TimeLeft, float HitSizefloat CallFunc_Divide_FloatFloat_ReturnValue, float CallFunc_FClamp_ReturnValue, float CallFunc_Multiply_FloatFloat_ReturnValue);
    void OnHit(float Damage, class UDamageClass* DamageClass, class AActor* DamageCauser, bool anyHealthLost, float HitSize, bool CallFunc_IsValid_ReturnValue, FLinearColor Temp_struct_Variable, FVector CallFunc_K2_GetActorLocation_ReturnValue, FLinearColor Temp_struct_Variable_1, FVector CallFunc_K2_GetActorLocation_ReturnValue_1, FVector CallFunc_Subtract_VectorVector_ReturnValue, int32 CallFunc_Array_Add_ReturnValue, float CallFunc_Vector_HeadingAngle_ReturnValue, FVector CallFunc_MakeVector_ReturnValue, bool CallFunc_Array_IsValidIndex_ReturnValue, bool Temp_bool_Variable, class AFSDGameState* CallFunc_GetFSDGameState_ReturnValue, int32 CallFunc_Array_LastIndex_ReturnValue, float CallFunc_Array_Get_Item, float CallFunc_Divide_FloatFloat_ReturnValue, bool CallFunc_Greater_FloatFloat_ReturnValue, FLinearColor K2Node_Select_Default, bool CallFunc_Less_FloatFloat_ReturnValue, float CallFunc_SelectFloat_ReturnValue, float CallFunc_SelectFloat_ReturnValue_1, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_EqualEqual_IntInt_ReturnValue, bool CallFunc_Array_IsValidIndex_ReturnValue_1, int32 CallFunc_Array_Add_ReturnValue_1, bool CallFunc_IsParalyzed_ReturnValue, bool CallFunc_NotEqual_ObjectObject_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, bool CallFunc_IsAlive_ReturnValue, bool CallFunc_BooleanAND_ReturnValue_1, bool CallFunc_BooleanAND_ReturnValue_2);
    void Tick(FGeometry MyGeometry, float InDeltaTime);
    void Construct();
    void ExecuteUbergraph_HUD_Directional_Damage_IndicatorV2(int32 EntryPoint, bool Temp_bool_Variable, bool CallFunc_Not_PreBool_ReturnValue, FGeometry K2Node_Event_MyGeometry, float K2Node_Event_InDeltaTime, class APawn* CallFunc_GetOwningPlayerPawn_ReturnValue, class APlayerCharacter* K2Node_DynamicCast_AsPlayer_Character, bool K2Node_DynamicCast_bSuccess, bool CallFunc_IsValid_ReturnValue, FRotator CallFunc_K2_GetActorRotation_ReturnValue, float CallFunc_BreakRotator_Roll, float CallFunc_BreakRotator_Pitch, float CallFunc_BreakRotator_Yaw, int32 CallFunc_Array_Length_ReturnValue, float CallFunc_Multiply_FloatFloat_ReturnValue, float CallFunc_Add_FloatFloat_ReturnValue, FExecuteUbergraph_HUD_Directional_Damage_IndicatorV2K2Node_CreateDelegate_OutputDelegate K2Node_CreateDelegate_OutputDelegate, class UMaterialInstanceDynamic* CallFunc_GetDynamicMaterial_ReturnValue, int32 Temp_int_Variable, int32 CallFunc_Subtract_IntInt_ReturnValue, FVector CallFunc_Array_Get_Item, bool CallFunc_LessEqual_IntInt_ReturnValue, float CallFunc_BreakVector_X, float CallFunc_BreakVector_Y, float CallFunc_BreakVector_Z, bool CallFunc_BooleanAND_ReturnValue, float CallFunc_CalcFadeStrength_ReturnValue, bool CallFunc_Greater_IntInt_ReturnValue, FString CallFunc_Conv_IntToString_ReturnValue, FString CallFunc_Concat_StrStr_ReturnValue, FString CallFunc_Concat_StrStr_ReturnValue_1, FName CallFunc_Conv_StringToName_ReturnValue, FName CallFunc_Conv_StringToName_ReturnValue_1, int32 CallFunc_Add_IntInt_ReturnValue);
};

#endif
