#ifndef UE4SS_SDK_HUD_TabPlayerList_InteractableV2_HPP
#define UE4SS_SDK_HUD_TabPlayerList_InteractableV2_HPP

class UHUD_TabPlayerList_InteractableV2_C : public UFSDUserWidget
{
    FPointerToUberGraphFrame UberGraphFrame;
    class UButton* Button_InviteFriends1;
    class UButton* Button_InviteFriends2;
    class UButton* Button_InviteFriends3;
    class UHorizontalBox* HorizontalBox_InviteFriend;
    class UHUD_TabPlayerListEntry_InteractableV2_C* HUD_TabPlayerListEntry_Interactable1;
    class UUI_AdvancedLabel_C* LabelInviteFriend;
    class UHorizontalBox* ParentPanel;
    class UHorizontalBox* PlayersPanel;
    class USizeBox* SizeBox_InviteFriends1;
    class USizeBox* SizeBox_InviteFriends2;
    class USizeBox* SizeBox_InviteFriends3;
    class USpacer* Spacer_InviteButtons;
    class USpacer* Spacer_IsInMission;
    TArray<class UButton*> InviteButtons;

    void FindPlayerList(TArray<class AFSDPlayerState*>& OutPlayers, TArray<class AFSDPlayerState*> Players, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, class AFSDGameState* CallFunc_GetFSDGameState_ReturnValue, bool CallFunc_IsValid_ReturnValue, class APlayerState* CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, class AFSDPlayerState* K2Node_DynamicCast_AsFSDPlayer_State, bool K2Node_DynamicCast_bSuccess, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Array_Add_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue);
    void OnFailure_BB3F54234323B8FC909E35A9D25E3656();
    void OnSuccess_BB3F54234323B8FC909E35A9D25E3656();
    void Construct();
    void AddPlayer(class AFSDPlayerState* Player);
    void Update();
    void OnPlayerJoined_Event(class AFSDPlayerState* PlayerState);
    void OnPlayerLeave_Event(class AFSDPlayerState* PlayerState);
    void BndEvt__Button_Invite_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
    void InviteFriends();
    void BndEvt__Button_InviteFriends2_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__SizeBox_InviteFriends03_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature();
    void ExecuteUbergraph_HUD_TabPlayerList_InteractableV2(int32 EntryPoint, int32 Temp_int_Variable, FExecuteUbergraph_HUD_TabPlayerList_InteractableV2K2Node_CreateDelegate_OutputDelegate K2Node_CreateDelegate_OutputDelegate, int32 CallFunc_Add_IntInt_ReturnValue, bool Temp_bool_Variable, ESlateVisibility Temp_byte_Variable, ESlateVisibility Temp_byte_Variable_1, bool Temp_bool_Variable_1, ESlateVisibility Temp_byte_Variable_2, ESlateVisibility Temp_byte_Variable_3, int32 Temp_int_Variable_1, int32 CallFunc_Add_IntInt_ReturnValue_1, FExecuteUbergraph_HUD_TabPlayerList_InteractableV2K2Node_CreateDelegate_OutputDelegate_1 K2Node_CreateDelegate_OutputDelegate_1, FExecuteUbergraph_HUD_TabPlayerList_InteractableV2K2Node_CreateDelegate_OutputDelegate_2 K2Node_CreateDelegate_OutputDelegate_2, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue_2, int32 Temp_int_Array_Index_Variable_1, int32 CallFunc_Add_IntInt_ReturnValue_3, class AFSDPlayerState* K2Node_CustomEvent_player, class AFSDGameState* CallFunc_GetFSDGameState_ReturnValue, class APlayerController* CallFunc_GetOwningPlayer_ReturnValue, class UHUD_TabPlayerListEntry_InteractableV2_C* CallFunc_Create_ReturnValue, class APlayerState* CallFunc_Array_Get_Item, class AFSDPlayerState* K2Node_DynamicCast_AsFSDPlayer_State, bool K2Node_DynamicCast_bSuccess, int32 CallFunc_Array_Length_ReturnValue, int32 Temp_int_Loop_Counter_Variable_1, class APlayerController* CallFunc_GetOwningPlayer_ReturnValue_1, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_NotEqual_ObjectObject_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_4, ESlateVisibility Temp_byte_Variable_4, ESlateVisibility Temp_byte_Variable_5, class AFSDGameState* CallFunc_GetFSDGameState_ReturnValue_1, class AFSDPlayerState* K2Node_CustomEvent_PlayerState_1, class AFSDGameState* CallFunc_GetFSDGameState_ReturnValue_2, class AFSDPlayerState* K2Node_CustomEvent_PlayerState, bool CallFunc_IsInActiveSession_ReturnValue, bool CallFunc_IsInActiveSession_ReturnValue_1, class AFSDGameState* CallFunc_GetFSDGameState_ReturnValue_3, int32 CallFunc_Array_LastIndex_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue_1, TArray<class UButton*>& K2Node_MakeArray_Array, class UButton* CallFunc_Array_Get_Item_1, int32 CallFunc_Array_Length_ReturnValue_1, bool Temp_bool_Variable_2, bool CallFunc_Less_IntInt_ReturnValue_2, ESlateVisibility K2Node_Select_Default, FExecuteUbergraph_HUD_TabPlayerList_InteractableV2K2Node_CreateDelegate_OutputDelegate_3 K2Node_CreateDelegate_OutputDelegate_3, class UHorizontalBoxSlot* CallFunc_AddChildToHorizontalBoxEx_OutSlot, class UHorizontalBox* CallFunc_AddChildToHorizontalBoxEx_OutHorizontalBox, class UHUD_TabPlayerListEntry_InteractableV2_C* CallFunc_AddChildToHorizontalBoxEx_ReturnValue, class UButton* CallFunc_Array_Get_Item_2, int32 CallFunc_Array_Length_ReturnValue_2, bool CallFunc_Less_IntInt_ReturnValue_3, class AFSDGameState* CallFunc_GetFSDGameState_ReturnValue_4, int32 CallFunc_Array_Length_ReturnValue_3, class AFSDPlayerState* CallFunc_GetFSDPlayerState_ReturnValue, bool CallFunc_EqualEqual_IntInt_ReturnValue, ESlateVisibility K2Node_Select_Default_1, ESlateVisibility K2Node_Select_Default_2, FLinearColor CallFunc_MenuColors_OutputColor, FLinearColor CallFunc_MenuColors_OutputColor_1, class UButton* CallFunc_Array_Get_Item_3, int32 CallFunc_Array_Length_ReturnValue_4, bool CallFunc_Less_IntInt_ReturnValue_4, bool CallFunc_IsTearingDown_isTearingDown, bool CallFunc_Not_PreBool_ReturnValue, class APlayerController* CallFunc_GetOwningPlayer_ReturnValue_2, class UFSDCreateSessionCallbackProxy* CallFunc_FSDCreateSession_ReturnValue, bool CallFunc_IsValid_ReturnValue, EInviteBlockReason CallFunc_CanPlayerInvite_ReturnValue, bool CallFunc_NotEqual_ByteByte_ReturnValue, FText CallFunc_GetInviteFeatureBlockReason_ReturnValue, EInviteBlockReason CallFunc_CanPlayerInvite_ReturnValue_1, bool CallFunc_EqualEqual_ByteByte_ReturnValue, bool CallFunc_BooleanAND_ReturnValue);
};

#endif
