#ifndef UE4SS_SDK_HUD_CrosshairManager_HPP
#define UE4SS_SDK_HUD_CrosshairManager_HPP

class UHUD_CrosshairManager_C : public UUserWidget
{
    FPointerToUberGraphFrame UberGraphFrame;
    class UWidgetAnimation* AnimIntro;
    class UWidgetSwitcher* CrosshairSwitcher;
    class UHUD_HitIndicator_C* HUD_HitIndicator;
    class UCanvasPanel* MainCanvas;
    class UImage* NoCrosshair;
    class UOnScreen_Indicator_UsableZipLine_C* OnScreen_Indicator_UsableZipLine;
    class UUserWidget* CurrentCrosshair;
    bool PlayIntroAnim;
    class APlayerCharacter* Character;
    TMap<class AItem*, class UUserWidget*> CrosshairCache;

    void UnregisterEvents(FUnregisterEventsK2Node_CreateDelegate_OutputDelegate K2Node_CreateDelegate_OutputDelegate, bool CallFunc_IsValid_ReturnValue, FUnregisterEventsK2Node_CreateDelegate_OutputDelegate_1 K2Node_CreateDelegate_OutputDelegate_1, FUnregisterEventsK2Node_CreateDelegate_OutputDelegate_2 K2Node_CreateDelegate_OutputDelegate_2, FUnregisterEventsK2Node_CreateDelegate_OutputDelegate_3 K2Node_CreateDelegate_OutputDelegate_3, FUnregisterEventsK2Node_CreateDelegate_OutputDelegate_4 K2Node_CreateDelegate_OutputDelegate_4, FUnregisterEventsK2Node_CreateDelegate_OutputDelegate_5 K2Node_CreateDelegate_OutputDelegate_5, FUnregisterEventsK2Node_CreateDelegate_OutputDelegate_6 K2Node_CreateDelegate_OutputDelegate_6, bool CallFunc_IsValid_ReturnValue_1, bool CallFunc_IsValid_ReturnValue_2);
    void UpdateVisibility(bool CallFunc_IsTerrainScannerEquipped_ReturnValue, bool CallFunc_GetIsDepositing_ReturnValue, bool CallFunc_IsParalyzed_ReturnValue, bool CallFunc_NotEqual_ByteByte_ReturnValue, bool CallFunc_IsDown_ReturnValue, bool CallFunc_BooleanOR_ReturnValue, bool CallFunc_BooleanOR_ReturnValue_1, bool CallFunc_BooleanOR_ReturnValue_2, bool CallFunc_BooleanOR_ReturnValue_3, bool CallFunc_SelectVisibility_IsVisible, bool CallFunc_SelectVisibility_VisibilityChanged, ESlateVisibility CallFunc_SelectVisibility_New_Visibility);
    void SetCrosshair(class AItem* InEquippedItem, class UUserWidget* NewCrosshair, class UCrosshairAggregator* Aggregator, bool CallFunc_IsValid_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, class UUserWidget* CallFunc_GetOrCreateCrosshair_ReturnValue, bool CallFunc_IsValid_ReturnValue_2, bool CallFunc_IsValid_ReturnValue_3, class UUMGSequencePlayer* CallFunc_PlayAnimationForward_ReturnValue, class UPanelSlot* CallFunc_AddChild_ReturnValue, class UWidgetSwitcherSlot* K2Node_DynamicCast_AsWidget_Switcher_Slot, bool K2Node_DynamicCast_bSuccess, bool CallFunc_HasChild_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, bool CallFunc_IsValid_ReturnValue_4, class UCrosshairAggregator* CallFunc_GetComponentByClass_ReturnValue, class UUserWidget* CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue);
    void OnToggleMapTool(bool Visible);
    void OnDepositingEnd_Event(class UResourceBank* ResourceBank);
    void OnDepositingBegin_Event(class UResourceBank* ResourceBank);
    void OnCameraModeChanged_Event(ECharacterCameraMode NewCameraMode, ECharacterCameraMode OldCameraMode);
    void OnCharacterStateChanged(ECharacterState NewState);
    void Destruct();
    void Construct();
    void On Inventory Ready();
    void OnItemsLoaded();
    void ExecuteUbergraph_HUD_CrosshairManager(int32 EntryPoint, FExecuteUbergraph_HUD_CrosshairManagerK2Node_CreateDelegate_OutputDelegate K2Node_CreateDelegate_OutputDelegate, FExecuteUbergraph_HUD_CrosshairManagerK2Node_CreateDelegate_OutputDelegate_1 K2Node_CreateDelegate_OutputDelegate_1, FExecuteUbergraph_HUD_CrosshairManagerK2Node_CreateDelegate_OutputDelegate_2 K2Node_CreateDelegate_OutputDelegate_2, FExecuteUbergraph_HUD_CrosshairManagerK2Node_CreateDelegate_OutputDelegate_3 K2Node_CreateDelegate_OutputDelegate_3, FExecuteUbergraph_HUD_CrosshairManagerK2Node_CreateDelegate_OutputDelegate_4 K2Node_CreateDelegate_OutputDelegate_4, FExecuteUbergraph_HUD_CrosshairManagerK2Node_CreateDelegate_OutputDelegate_5 K2Node_CreateDelegate_OutputDelegate_5, bool K2Node_CustomEvent_Visible, class UResourceBank* K2Node_CustomEvent_ResourceBank_1, class UResourceBank* K2Node_CustomEvent_ResourceBank, ECharacterCameraMode K2Node_CustomEvent_NewCameraMode, ECharacterCameraMode K2Node_CustomEvent_OldCameraMode, ECharacterState K2Node_CustomEvent_newState, class APawn* CallFunc_GetOwningPlayerPawn_ReturnValue, class APlayerCharacter* K2Node_DynamicCast_AsPlayer_Character, bool K2Node_DynamicCast_bSuccess, FExecuteUbergraph_HUD_CrosshairManagerK2Node_CreateDelegate_OutputDelegate_6 K2Node_CreateDelegate_OutputDelegate_6, FExecuteUbergraph_HUD_CrosshairManagerK2Node_CreateDelegate_OutputDelegate_7 K2Node_CreateDelegate_OutputDelegate_7);
};

#endif
