#ifndef UE4SS_SDK_ITM_GrenadeThrow_HPP
#define UE4SS_SDK_ITM_GrenadeThrow_HPP

class AITM_GrenadeThrow_C : public AThrownGrenadeItem
{
    FPointerToUberGraphFrame UberGraphFrame;
    class UBillboardComponent* Billboard;
    class USceneComponent* EndPoint;
    class USplineMeshComponent* SplineMesh;
    class USceneComponent* DefaultSceneRoot;
    FVector StartTangent;
    FVector EndTangent;
    FVector EndLocation;
    FRuntimeFloatCurve ScaleCurve;

    void UpdateSpline(TArray<FVector>& Array, float& DeltaTime, float Dist, FVector LastPoint, FVector FirstPoint, int32 Temp_int_Variable, FHitResult CallFunc_K2_SetRelativeLocation_SweepHitResult, int32 CallFunc_Subtract_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, float CallFunc_EvaluateRuntimeCurve_ReturnValue, FVector2D CallFunc_MakeVector2D_ReturnValue, float CallFunc_Multiply_FloatFloat_ReturnValue, float CallFunc_Multiply_FloatFloat_ReturnValue_1, FTransform CallFunc_K2_GetComponentToWorld_ReturnValue, FTransform CallFunc_K2_GetComponentToWorld_ReturnValue_1, int32 CallFunc_Array_LastIndex_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue_1, FVector CallFunc_Array_Get_Item, FVector CallFunc_Array_Get_Item_1, FVector CallFunc_Subtract_VectorVector_ReturnValue, FVector CallFunc_Subtract_VectorVector_ReturnValue_1, FVector CallFunc_Normal_ReturnValue, FVector CallFunc_Normal_ReturnValue_1, FVector CallFunc_InverseTransformDirection_ReturnValue, FVector CallFunc_InverseTransformDirection_ReturnValue_1, FVector CallFunc_Multiply_VectorFloat_ReturnValue, FVector CallFunc_Multiply_VectorFloat_ReturnValue_1, FVector CallFunc_VLerp_ReturnValue, FVector CallFunc_VLerp_ReturnValue_1, FVector CallFunc_Array_Get_Item_2, FVector CallFunc_Array_Get_Item_3, FVector CallFunc_Subtract_VectorVector_ReturnValue_2, float CallFunc_VSize_ReturnValue, float CallFunc_Add_FloatFloat_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue_2, bool CallFunc_LessEqual_IntInt_ReturnValue, FTransform CallFunc_K2_GetComponentToWorld_ReturnValue_2, FTransform CallFunc_K2_GetComponentToWorld_ReturnValue_3, FVector CallFunc_InverseTransformLocation_ReturnValue, FVector CallFunc_VLerp_ReturnValue_2, FVector CallFunc_InverseTransformLocation_ReturnValue_1, int32 CallFunc_Array_LastIndex_ReturnValue_1, FVector CallFunc_Array_Get_Item_4, FVector CallFunc_Array_Get_Item_5);
    void ReceiveTick(float DeltaSeconds);
    void RecieveEquipped();
    void RecieveUnequipped();
    void ReceiveBeginPlay();
    void Set Is Visible(bool Visible);
    void GrenadeThrown();
    void ExecuteUbergraph_ITM_GrenadeThrow(int32 EntryPoint, FExecuteUbergraph_ITM_GrenadeThrowK2Node_CreateDelegate_OutputDelegate K2Node_CreateDelegate_OutputDelegate, FVector CallFunc_K2_GetComponentLocation_ReturnValue, const TArray<class AActor*>& K2Node_MakeArray_Array, float K2Node_Event_DeltaSeconds, FRotator CallFunc_GetGrenadeThrowRotation_ReturnValue, FVector CallFunc_GetForwardVector_ReturnValue, FRotator CallFunc_K2_GetActorRotation_ReturnValue, bool CallFunc_IsFirstPerson_ReturnValue, FVector CallFunc_GreaterGreater_VectorRotator_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, FVector CallFunc_Add_VectorVector_ReturnValue, bool CallFunc_IsLocallyControlled_ReturnValue, float CallFunc_GetGrenadeThrowVelocity_ReturnValue, float CallFunc_Multiply_FloatFloat_ReturnValue, FVector CallFunc_Multiply_VectorFloat_ReturnValue, float CallFunc_GetGrenadeDuration_ReturnValue, float CallFunc_FMin_ReturnValue, bool K2Node_CustomEvent_Visible, float CallFunc_GetGrenadeGravity_ReturnValue, FHitResult CallFunc_Blueprint_PredictProjectilePath_ByTraceChannel_OutHit, TArray<FVector>& CallFunc_Blueprint_PredictProjectilePath_ByTraceChannel_OutPathPositions, FVector CallFunc_Blueprint_PredictProjectilePath_ByTraceChannel_OutLastTraceDestination, bool CallFunc_Blueprint_PredictProjectilePath_ByTraceChannel_ReturnValue);
};

#endif
