#ifndef UE4SS_SDK_LCD_MissionReadout_HazCompLen_HPP
#define UE4SS_SDK_LCD_MissionReadout_HazCompLen_HPP

class ULCD_MissionReadout_HazCompLen_C : public UUserWidget
{
    FPointerToUberGraphFrame UberGraphFrame;
    class UBasic_Menu_ColorBar_C* Basic_Menu_ColorBar;
    class UWidget_DropPod_DangerLevel_TextString_C* BP_DropPodScreenTextWidget;
    class UWidget_DropPod_DangerLevel_TextString_C* BP_DropPodScreenTextWidget_C_0;
    class UWidget_DropPod_DangerLevel_TextString_C* BP_DropPodScreenTextWidget_C_1;
    class UWidget_DropPod_DangerLevel_TextString_C* BP_DropPodScreenTextWidget_C_2;
    class UWidget_DropPod_DangerLevel_TextString_C* BP_DropPodScreenTextWidget_C_3;
    class UWidget_DropPod_DangerLevel_TextString_C* BP_DropPodScreenTextWidget_C_4;
    class UWidget_DropPod_DangerLevel_TextString_C* BP_DropPodScreenTextWidget_C_5;
    class UWidget_DropPod_DangerLevel_TextString_C* BP_DropPodScreenTextWidget_C_6;
    class UWidget_DropPod_DangerLevel_TextString_C* BP_DropPodScreenTextWidget_C_7;
    class UWidget_DropPod_DangerLevel_TextString_C* BP_DropPodScreenTextWidget_C_8;
    class UWidget_DropPod_DangerLevel_TextString_C* BP_DropPodScreenTextWidget_C_9;
    class UVerticalBox* ComplexityLevels;
    class UTextBlock* DATA_PlanetaryRegionName;
    class UVerticalBox* HazardLevels;
    class UImage* Image_41;
    class UVerticalBox* LenghtLevels;
    class UProgressBar* ProgressBar_Complexity;
    class UProgressBar* ProgressBar_Haz;
    class UProgressBar* ProgressBar_Length;
    class UUI_MissionReadOut_Base_C* UI_MissionReadOut_Base;
    class UVerticalBox* VerticalBox_MissionData;
    TArray<FText> Names;
    int32 Index;
    float TimePassed;
    int32 MissionComplexity;
    int32 missionLength;

    void AdjustCLBar(float InputPin, float CallFunc_Conv_IntToFloat_ReturnValue, float CallFunc_Conv_IntToFloat_ReturnValue_1, float CallFunc_Divide_FloatFloat_ReturnValue, float CallFunc_Conv_IntToFloat_ReturnValue_2, float CallFunc_Conv_IntToFloat_ReturnValue_3, float CallFunc_Conv_IntToFloat_ReturnValue_4, float CallFunc_Divide_FloatFloat_ReturnValue_1, float CallFunc_Divide_FloatFloat_ReturnValue_2, float CallFunc_Multiply_FloatFloat_ReturnValue, float CallFunc_Conv_IntToFloat_ReturnValue_5, float CallFunc_Conv_IntToFloat_ReturnValue_6, float CallFunc_Divide_FloatFloat_ReturnValue_3, float CallFunc_Conv_IntToFloat_ReturnValue_7, float CallFunc_Divide_FloatFloat_ReturnValue_4, float CallFunc_Divide_FloatFloat_ReturnValue_5, bool CallFunc_GreaterEqual_FloatFloat_ReturnValue, float CallFunc_Multiply_FloatFloat_ReturnValue_1, bool CallFunc_LessEqual_FloatFloat_ReturnValue, float CallFunc_Add_FloatFloat_ReturnValue);
    void AdjustBar(float InputPin, bool CallFunc_LessEqual_FloatFloat_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, float CallFunc_Conv_IntToFloat_ReturnValue, float CallFunc_Conv_IntToFloat_ReturnValue_1, float CallFunc_Divide_FloatFloat_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_1, int32 CallFunc_Add_IntInt_ReturnValue_1, float CallFunc_Conv_IntToFloat_ReturnValue_2, float CallFunc_Conv_IntToFloat_ReturnValue_3, float CallFunc_Divide_FloatFloat_ReturnValue_1, float CallFunc_Divide_FloatFloat_ReturnValue_2, float CallFunc_Multiply_FloatFloat_ReturnValue, bool CallFunc_GreaterEqual_FloatFloat_ReturnValue, float CallFunc_Add_FloatFloat_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_2, bool CallFunc_Greater_IntInt_ReturnValue);
    void SetGeneratedMission(class UGeneratedMission* In Mission, int32 MissionComplexityIndex, int32 MissionLenghtIndex, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable_1, int32 Temp_int_Variable, int32 CallFunc_Add_IntInt_ReturnValue_1, int32 CallFunc_GetChildrenCount_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue_1, int32 CallFunc_GetChildrenCount_ReturnValue_1, int32 CallFunc_Subtract_IntInt_ReturnValue_2, int32 CallFunc_GetChildrenCount_ReturnValue_2, FSlateColor K2Node_MakeStruct_SlateColor, int32 CallFunc_Subtract_IntInt_ReturnValue_3, FSlateColor K2Node_MakeStruct_SlateColor_1, FSlateColor K2Node_MakeStruct_SlateColor_2, FSlateColor K2Node_MakeStruct_SlateColor_3, bool CallFunc_EqualEqual_IntInt_ReturnValue, int32 CallFunc_GetChildrenCount_ReturnValue_3, int32 CallFunc_Subtract_IntInt_ReturnValue_4, bool CallFunc_LessEqual_IntInt_ReturnValue, class UWidget* CallFunc_GetChildAt_ReturnValue, class UWidget_DropPod_DangerLevel_TextString_C* K2Node_DynamicCast_AsWidget_Drop_Pod_Danger_Level_Text_String, bool K2Node_DynamicCast_bSuccess, int32 CallFunc_GetChildrenCount_ReturnValue_4, int32 CallFunc_Subtract_IntInt_ReturnValue_5, class UMissionDNA* CallFunc_GetMissionDNA_ReturnValue, class UMissionDNA* CallFunc_GetMissionDNA_ReturnValue_1, class UWidget* CallFunc_GetChildAt_ReturnValue_1, class AFSDGameState* CallFunc_GetFSDGameState_ReturnValue, class UWidget_DropPod_DangerLevel_TextString_C* K2Node_DynamicCast_AsWidget_Drop_Pod_Danger_Level_Text_String_1, bool K2Node_DynamicCast_bSuccess_1, FSlateColor K2Node_MakeStruct_SlateColor_4, FSlateColor K2Node_MakeStruct_SlateColor_5, int32 Temp_int_Variable_1, class UWidget* CallFunc_GetChildAt_ReturnValue_2, bool CallFunc_EqualEqual_IntInt_ReturnValue_1, class UWidget_DropPod_DangerLevel_TextString_C* K2Node_DynamicCast_AsWidget_Drop_Pod_Danger_Level_Text_String_2, bool K2Node_DynamicCast_bSuccess_2, bool CallFunc_LessEqual_IntInt_ReturnValue_1, int32 CallFunc_Add_IntInt_ReturnValue_2, FText CallFunc_Array_Get_Item, bool CallFunc_EqualEqual_TextText_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue_6, int32 CallFunc_Max_ReturnValue, class UGameData* CallFunc_GetFSDGameData_ReturnValue, int32 Temp_int_Loop_Counter_Variable_1, int32 CallFunc_Subtract_IntInt_ReturnValue_7, class UDifficultySetting* CallFunc_Array_Get_Item_1, int32 CallFunc_Array_Length_ReturnValue_1, int32 CallFunc_Array_Add_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_GreaterEqual_IntInt_ReturnValue);
    void Tick(FGeometry MyGeometry, float InDeltaTime);
    void BndEvt__UI_MissionReadOut_Base_K2Node_ComponentBoundEvent_0_OnMissionSelected__DelegateSignature(class UGeneratedMission* InMission);
    void ExecuteUbergraph_LCD_MissionReadout_HazCompLen(int32 EntryPoint, class UGeneratedMission* K2Node_ComponentBoundEvent_InMission, FGeometry K2Node_Event_MyGeometry, float K2Node_Event_InDeltaTime);
};

#endif
