#ifndef UE4SS_SDK_LVL_Loading_StartMission01_HPP
#define UE4SS_SDK_LVL_Loading_StartMission01_HPP

class ALVL_Loading_StartMission01_C : public ALevelScriptActor
{
    FPointerToUberGraphFrame UberGraphFrame;
    class ULevelSequencePlayer* Player;
    class AEmitter* P_E3trailer_DropPod_Exhaust_4_ExecuteUbergraph_LVL_Loading_StartMission01_RefProperty;

    void OnFinshed(class UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue);
    void StopPlayer(bool CallFunc_IsValid_ReturnValue);
    void StartPlayer(class ULevelSequence* LevelSequence, class UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue, FString CallFunc_GetPathName_ReturnValue, FString CallFunc_Concat_StrStr_ReturnValue, FStartPlayerK2Node_CreateDelegate_OutputDelegate K2Node_CreateDelegate_OutputDelegate, FMovieSceneSequencePlaybackSettings K2Node_MakeStruct_MovieSceneSequencePlaybackSettings, class ALevelSequenceActor* CallFunc_CreateLevelSequencePlayer_OutActor, class ULevelSequencePlayer* CallFunc_CreateLevelSequencePlayer_ReturnValue);
    void ReceiveBeginPlay();
    void PlayerStart(class ULevelSequence* LoaderLevelSequence);
    void PlayerStop();
    void ExecuteUbergraph_LVL_Loading_StartMission01(int32 EntryPoint, FExecuteUbergraph_LVL_Loading_StartMission01K2Node_CreateDelegate_OutputDelegate K2Node_CreateDelegate_OutputDelegate, FExecuteUbergraph_LVL_Loading_StartMission01K2Node_CreateDelegate_OutputDelegate_1 K2Node_CreateDelegate_OutputDelegate_1, class UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue, class ULevelSequence* K2Node_CustomEvent_LoaderLevelSequence, class UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_1, bool CallFunc_IsPlayInEditor_ReturnValue, bool CallFunc_IsWorldTickEnabled_ReturnValue, bool CallFunc_IsWorldTickEnabled_ReturnValue_1);
};

#endif
