#ifndef UE4SS_SDK_LVL_CharacterSelection_HPP
#define UE4SS_SDK_LVL_CharacterSelection_HPP

class ALVL_CharacterSelection_C : public ALevelScriptActor
{
    FPointerToUberGraphFrame UberGraphFrame;
    class ULevelSequencePlayer* Player;
    class ACharacterSelectionSwitcher_C* switcher;
    TArray<FCharacterViewInfo> CharViewerList;
    class ACharacterSelectionSwitcher_C* CharacterSelectionSwitcher_186_ExecuteUbergraph_LVL_CharacterSelection_RefProperty;
    class ACameraActor* CameraActor_1_ExecuteUbergraph_LVL_CharacterSelection_RefProperty;

    void PlaySpecificSequence(class ULevelSequence* LevelSequence, FMovieSceneSequencePlaybackSettings K2Node_MakeStruct_MovieSceneSequencePlaybackSettings, class ALevelSequenceActor* CallFunc_CreateLevelSequencePlayer_OutActor, class ULevelSequencePlayer* CallFunc_CreateLevelSequencePlayer_ReturnValue);
    void StopPlayer(bool CallFunc_IsValid_ReturnValue);
    void StartPlayer(ECharselectionCameraLocation CamSetting, class ULevelSequence* Temp_object_Variable, class ULevelSequence* Temp_object_Variable_1, class ULevelSequence* Temp_object_Variable_2, class ULevelSequence* Temp_object_Variable_3, class ULevelSequence* Temp_object_Variable_4, class ULevelSequence* Temp_object_Variable_5, class ULevelSequence* Temp_object_Variable_6, ECharselectionCameraLocation Temp_byte_Variable, FMovieSceneSequencePlaybackSettings K2Node_MakeStruct_MovieSceneSequencePlaybackSettings, class ULevelSequence* K2Node_Select_Default, class ALevelSequenceActor* CallFunc_CreateLevelSequencePlayer_OutActor, class ULevelSequencePlayer* CallFunc_CreateLevelSequencePlayer_ReturnValue);
    void StopPlay();
    void StartLevelSeq(class ULevelSequence* CharacterLevelSequence);
    void StartPlay(ECharselectionCameraLocation selectionLocation);
    void ReceiveBeginPlay();
    void ReceiveDestroyed();
    void ExecuteUbergraph_LVL_CharacterSelection(int32 EntryPoint, FExecuteUbergraph_LVL_CharacterSelectionK2Node_CreateDelegate_OutputDelegate K2Node_CreateDelegate_OutputDelegate, ECharselectionCameraLocation Temp_byte_Variable, FExecuteUbergraph_LVL_CharacterSelectionK2Node_CreateDelegate_OutputDelegate_1 K2Node_CreateDelegate_OutputDelegate_1, bool Temp_bool_Variable, bool Temp_bool_Variable_1, bool Temp_bool_Variable_2, bool Temp_bool_Variable_3, bool Temp_bool_Variable_4, bool Temp_bool_Variable_5, bool Temp_bool_Variable_6, FExecuteUbergraph_LVL_CharacterSelectionK2Node_CreateDelegate_OutputDelegate_2 K2Node_CreateDelegate_OutputDelegate_2, UClass* CallFunc_LoadClass_ReturnValue, TArray<class UVanityItem*>& K2Node_MakeArray_Array, TSubclassOf<class APlayerCharacter> K2Node_ClassDynamicCast_AsPlayer_Character, bool K2Node_ClassDynamicCast_bSuccess, TArray<class UVanityItem*>& K2Node_MakeArray_Array_1, bool CallFunc_IsPlayInEditor_ReturnValue, FCharacterViewInfo K2Node_MakeStruct_CharacterViewInfo, UClass* CallFunc_LoadClass_ReturnValue_1, TSubclassOf<class APlayerCharacter> K2Node_ClassDynamicCast_AsPlayer_Character_1, bool K2Node_ClassDynamicCast_bSuccess_1, FCharacterViewInfo K2Node_MakeStruct_CharacterViewInfo_1, bool CallFunc_IsPlayInEditor_ReturnValue_1, int32 CallFunc_Array_Add_ReturnValue, class UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue, class ULevelSequence* K2Node_CustomEvent_CharacterLevelSequence, class UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_1, FCharacterViewScene K2Node_MakeStruct_CharacterViewScene, ECharselectionCameraLocation K2Node_CustomEvent_selectionLocation, bool K2Node_Select_Default, class UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_2, int32 CallFunc_Array_Add_ReturnValue_1);
};

#endif
