#ifndef UE4SS_SDK_Menu_QuickCheats_HPP
#define UE4SS_SDK_Menu_QuickCheats_HPP

class UMenu_QuickCheats_C : public UWindowWidget
{
    FPointerToUberGraphFrame UberGraphFrame;
    class UButton* Button_Close;
    class UButton* Button_CompleteMission;
    class UButton* Button_CompleteObjectives;
    class UButton* Button_Driller;
    class UButton* Button_EnemySpawning;
    class UButton* Button_Engineer;
    class UButton* Button_FastMovement;
    class UButton* Button_FlyMode;
    class UButton* Button_GiveNitra;
    class UButton* Button_GodMode;
    class UButton* Button_Gunner;
    class UButton* Button_KillEverything;
    class UButton* Button_MaxLighting;
    class UButton* Button_OpenDifficulty;
    class UButton* Button_QuadPickaxe;
    class UButton* Button_Resupply;
    class UButton* Button_Scout;
    class UButton* Button_SpawnLootBugs;
    class UButton* Button_SpawnWaveFromPool;
    class UButton* Button_SwapPrimary;
    class UButton* Button_SwapSecondary;
    class UButton* Button_ToggleBosco;
    class USlider* HealthSlider;
    class UImage* Image_95;
    class UImage* Image_97;
    class UImage* Image_98;
    class UImage* Image_99;
    class UImage* Image_100;
    class UImage* Image_318;
    class UImage* Image_320;
    class UImage* Image_321;
    class UImage* Image_322;
    class UImage* Image_324;
    class UImage* Image_325;
    class UMenuAnchor* MenuAnchor_53;
    class UMenuAnchor* MenuAnchor_advSpawn;
    class UComboBoxString* PlayerCountBox;
    class UCanvasPanel* TopCanvasPanel;
    class UCheckBox* UsingSavedCheats;
    int32 Current Tab Index;
    int32 Amount of main tabs;
    bool GodmodeActive;
    bool FastMovementActive;
    bool FlyingActive;
    bool QuadPickaxeActive;
    bool MaxLightingActive;
    bool AmmoCostEnabled;
    class UCheat_SpawnEnemyAdvanced_C* Advanced Spawn Menu;
    class UPlayerCharacterID* ActiveCharac;

    class UWidget* On_MenuAnchor_advSpawn_GetMenuContent_0(bool CallFunc_IsValid_ReturnValue, class APlayerController* CallFunc_GetOwningPlayer_ReturnValue, class UCheat_SpawnEnemyAdvanced_C* CallFunc_Create_ReturnValue);
    FLinearColor GetColorAndOpacity_NoAmmoCost();
    FLinearColor GetColorAndOpacity_MaxLightningActive();
    FLinearColor GetColorAndOpacity_QuadPickaxe();
    FLinearColor GetColorAndOpacity_Flying();
    FLinearColor GetColorAndOpacity_FastMovement();
    FLinearColor GetColorAndOpacity_Godmode();
    class UUpgradableBoscoComponent* GetBoscoUpgradeComponent(class ABosco*& Droneclass UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue, class UUpgradableBoscoComponent* CallFunc_GetUpgradeComponent_ReturnValue, bool CallFunc_IsValid_ReturnValue);
    class UWidget* OnGetMenuContent_0(class APlayerController* CallFunc_GetOwningPlayer_ReturnValue, class UCheat_OverclockSelection_C* CallFunc_Create_ReturnValue);
    ESlateVisibility Get_ActivateCommonCheatsButton_Visibility_0(bool Temp_bool_Variable, ESlateVisibility Temp_byte_Variable, ESlateVisibility Temp_byte_Variable_1, class APlayerController* CallFunc_GetOwningPlayer_ReturnValue, bool CallFunc_HasAuthority_ReturnValue, ESlateVisibility K2Node_Select_Default);
    float Get_HealthSlider_Value_0(class ACharacter* CallFunc_GetPlayerCharacter_ReturnValue, class APlayerCharacter* K2Node_DynamicCast_AsPlayer_Character, bool K2Node_DynamicCast_bSuccess, float CallFunc_GetHealth_ReturnValue, float CallFunc_Divide_FloatFloat_ReturnValue);
    FEventReply OnKeyDown(FGeometry MyGeometry, FKeyEvent InKeyEventFKey CallFunc_GetKey_ReturnValue, bool CallFunc_EqualEqual_KeyKey_ReturnValue, bool CallFunc_EqualEqual_KeyKey_ReturnValue_1, FText CallFunc_Key_GetDisplayName_ReturnValue, FString CallFunc_Conv_TextToString_ReturnValue, bool K2Node_SwitchString_CmpSuccess, FEventReply CallFunc_Handled_ReturnValue, class UWindowManager* CallFunc_GetWindowManager_ReturnValue, FEventReply CallFunc_Handled_ReturnValue_1);
    void BndEvt__Button_Close_K2Node_ComponentBoundEvent_62_OnButtonClickedEvent__DelegateSignature();
    void OnShown();
    void OnClosed();
    void BndEvt__Button_Gunner_K2Node_ComponentBoundEvent_683_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_Engineer_K2Node_ComponentBoundEvent_735_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_Driller_K2Node_ComponentBoundEvent_758_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_Scout_K2Node_ComponentBoundEvent_782_OnButtonClickedEvent__DelegateSignature();
    void Construct();
    void Swap Weapon to next(EItemCategory Item Category);
    void HotKey Interaction change character();
    void BndEvt__HealthSlider_K2Node_ComponentBoundEvent_2_OnFloatValueChangedEvent__DelegateSignature(float Value);
    void BndEvt__Button_Resupply_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_GodMode_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_FastMovement_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_KillEverything_K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_FlyMode_K2Node_ComponentBoundEvent_6_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_CompleteMission_K2Node_ComponentBoundEvent_7_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_QuadPickaxe_K2Node_ComponentBoundEvent_8_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_96_K2Node_ComponentBoundEvent_9_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_SwapPrimary_K2Node_ComponentBoundEvent_10_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_SwapSecondary_K2Node_ComponentBoundEvent_11_OnButtonClickedEvent__DelegateSignature();
    void Set Cheats from setting();
    void BndEvt__Button_OpenDifficulty_K2Node_ComponentBoundEvent_12_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_CompleteObjectives_K2Node_ComponentBoundEvent_13_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_GiveNitra_K2Node_ComponentBoundEvent_14_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_SpawnLootBugs_K2Node_ComponentBoundEvent_15_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_SpawnWaveFromPool_K2Node_ComponentBoundEvent_16_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_ToggleBosco_K2Node_ComponentBoundEvent_17_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__ComboBoxString_138_K2Node_ComponentBoundEvent_18_OnSelectionChangedEvent__DelegateSignature(FString SelectedItem, TEnumAsByte<ESelectInfo::Type> SelectionType);
    void Close Advanced spawning();
    void BndEvt__Button_EnemySpawning_K2Node_ComponentBoundEvent_19_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__MenuAnchor_advSpawn_K2Node_ComponentBoundEvent_20_OnMenuOpenChangedEvent__DelegateSignature(bool bIsOpen);
    void BndEvt__UsingSavedCheats_K2Node_ComponentBoundEvent_9_OnCheckBoxComponentStateChanged__DelegateSignature(bool bIsChecked);
    void ExecuteUbergraph_Menu_QuickCheats(int32 EntryPoint, class UWindowManager* CallFunc_GetWindowManager_ReturnValue, class UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue, class UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue, bool CallFunc_IsValid_ReturnValue, class UInventoryList* CallFunc_GetInventoryList_ReturnValue, class UFSDSaveGame* CallFunc_GetFSDSaveGame_ReturnValue, class UFSDSaveGame* CallFunc_GetFSDSaveGame_ReturnValue_1, EItemCategory K2Node_CustomEvent_item_category, TSubclassOf<class AActor> CallFunc_GetEquippedItem_ReturnValue, class APlayerController* CallFunc_GetPlayerController_ReturnValue, class UItemID* CallFunc_GetItemID_ReturnValue, class AFSDPlayerControllerBase* K2Node_DynamicCast_AsFSDPlayer_Controller_Base, bool K2Node_DynamicCast_bSuccess, class UItemID* CallFunc_GetNextItem_ReturnValue, TSubclassOf<class AActor> CallFunc_GetActorClass_ReturnValue, class APlayerController* CallFunc_GetPlayerController_ReturnValue_1, class AFSDPlayerControllerBase* K2Node_DynamicCast_AsFSDPlayer_Controller_Base_1, bool K2Node_DynamicCast_bSuccess_1, float K2Node_ComponentBoundEvent_Value, class UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue_1, class ACharacter* CallFunc_GetPlayerCharacter_ReturnValue, class APlayerCharacter* K2Node_DynamicCast_AsPlayer_Character, bool K2Node_DynamicCast_bSuccess_2, float CallFunc_Multiply_FloatFloat_ReturnValue, class UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue_2, class UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue_3, bool CallFunc_IsInGodMode_ReturnValue, class UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue_4, class UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue_5, class UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue_6, class UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue_7, class UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue_8, bool CallFunc_Not_PreBool_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue_1, bool CallFunc_Not_PreBool_ReturnValue_2, class APawn* CallFunc_GetOwningPlayerPawn_ReturnValue, class APlayerController* CallFunc_GetPlayerController_ReturnValue_2, class ABP_PlayerCharacter_C* K2Node_DynamicCast_AsBP_Player_Character, bool K2Node_DynamicCast_bSuccess_3, bool CallFunc_Not_PreBool_ReturnValue_3, bool CallFunc_Not_PreBool_ReturnValue_4, class UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue_9, class UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue_10, class APlayerController* CallFunc_GetPlayerController_ReturnValue_3, class UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue_11, class UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue_12, FExecuteUbergraph_Menu_QuickCheatsK2Node_CreateDelegate_OutputDelegate K2Node_CreateDelegate_OutputDelegate, class APawn* CallFunc_GetOwningPlayerPawn_ReturnValue_1, class ABP_PlayerCharacter_C* K2Node_DynamicCast_AsBP_Player_Character_1, bool K2Node_DynamicCast_bSuccess_4, bool CallFunc_Not_PreBool_ReturnValue_5, class UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_1, class UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue_13, bool CallFunc_IsInGodMode_ReturnValue_1, bool CallFunc_EqualEqual_BoolBool_ReturnValue, class UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue_14, class UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue_15, class UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue_16, class ACharacter* CallFunc_GetPlayerCharacter_ReturnValue_1, class UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue_17, FVector CallFunc_K2_GetActorLocation_ReturnValue, TArray<FVector>& CallFunc_GetSpawnPointsFromLocation_ReturnValue, class AFSDGameMode* CallFunc_GetFSDGameMode_ReturnValue, FString K2Node_ComponentBoundEvent_SelectedItem, TEnumAsByte<ESelectInfo::Type> K2Node_ComponentBoundEvent_SelectionType, class UDifficultyManager* CallFunc_GetDifficultyManager_ReturnValue, int32 CallFunc_Conv_StringToInt_ReturnValue, class UDifficultySetting* CallFunc_GetCurrentDifficulty_ReturnValue, bool CallFunc_Greater_IntInt_ReturnValue, float CallFunc_GetFloatValue_ReturnValue, class UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue_18, class AFSDGameMode* CallFunc_GetFSDGameMode_ReturnValue_1, class UDifficultyManager* CallFunc_GetDifficultyManager_ReturnValue_1, FString CallFunc_Conv_IntToString_ReturnValue, bool K2Node_ComponentBoundEvent_bIsOpen, class UWidget* CallFunc_On_MenuAnchor_advSpawn_GetMenuContent_0_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, bool K2Node_ComponentBoundEvent_bIsChecked, class UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue_19, class UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue_20);
};

#endif
