#ifndef UE4SS_SDK_Menu_Cheats_HPP
#define UE4SS_SDK_Menu_Cheats_HPP

class UMenu_Cheats_C : public UWindowWidget
{
    FPointerToUberGraphFrame UberGraphFrame;
    class UButton* ActivateCommonCheatsButton;
    class UMenuAnchor* AdvEnemySpawn;
    class USpinBox* AnselDistanceSpinBox;
    class USpinBox* AnselSpeedSpinBox;
    class UScrollBox* BoscoUpgradePanel;
    class UButton* Button_AdvancedEnemyspawn;
    class UButton* Button_Bosco;
    class UButton* Button_Character;
    class UButton* Button_Close;
    class UButton* Button_Driller;
    class UButton* Button_Engineer;
    class UButton* Button_General;
    class UButton* Button_Gunner;
    class UButton* Button_Info;
    class UButton* Button_Mission;
    class UButton* Button_ReloadChar;
    class UButton* Button_Scout;
    class UButton* Button_SpawnMinimule;
    class UButton* Button_Vanity;
    class UCheat_AddGold_C* Cheat_AddGold;
    class UCheat_AddMorkite_C* Cheat_AddMorkite;
    class UCheat_AddNitra_C* Cheat_AddNitra;
    class UCheat_CharacterPointLight_C* Cheat_CharacterPointLight;
    class UCheat_CompleteMission_C* Cheat_CompleteMission;
    class UCheat_ConsoleCmd_C* Cheat_ConsoleCmd;
    class UCheat_ConsoleCmd_C* Cheat_ConsoleCmd_C_0;
    class UCheat_FlyMode_C* Cheat_DebugCam;
    class UCheat_DestroyAllFlares_C* Cheat_DestroyAllFlares;
    class UCheat_DestroyMolly_C* Cheat_DestroyMolly;
    class UCheat_FastMovement_C* Cheat_FastMovement;
    class UCheat_MiscUpgradesItem_C* Cheat_FifthItem;
    class UCheat_MiscUpgradesItem_C* Cheat_FirstItem;
    class UCheat_MiscUpgradesItem_C* Cheat_FourthItem;
    class UCheat_GiveBeerBuff_C* Cheat_GiveBeerBuff;
    class UCheat_God_C* Cheat_God;
    class UCheat_JumpToNextRoom_C* Cheat_JumpToNextRoom;
    class UCheat_KillAll_C* Cheat_KillAll_20;
    class UCheat_LevelScale_C* Cheat_LevelScale;
    class UCheat_MaterialInfo_C* Cheat_MaterialInfo_C_2;
    class UCheat_MaterialInfo_C* Cheat_MaterialInfo_C_3;
    class UCheat_MaterialInfo_C* Cheat_MaterialInfo_C_4;
    class UCheat_QuadPickAxe_C* Cheat_QuadPickAxe;
    class UCheat_QuickLight_C* Cheat_QuickLight;
    class UButton* Cheat_ResetAchievement;
    class UCheat_Resupply_C* Cheat_Resupply;
    class UCheat_RoomList_C* Cheat_RoomList;
    class UCheat_MiscUpgradesItem_C* Cheat_SecondItem;
    class UCheat_SetDifficulty_C* Cheat_SetDifficulty;
    class UCheat_SetFastFlares_C* Cheat_SetFastFlares;
    class UCheat_SetPerk_C* Cheat_SetPerk;
    class UCheat_ShowHUD_C* Cheat_ShowHUD;
    class UCheat_ShowPathfinder_C* Cheat_ShowPathfinder;
    class UCheat_SimulateLateJoin_C* Cheat_SimulateLateJoin;
    class UCheat_SimulatePlayerCount_C* Cheat_SimulatePlayerCount;
    class UCheat_MiscUpgradesItem_C* Cheat_SixthItem;
    class UCheat_SpawnBosco_C* Cheat_SpawnBosco;
    class UCheat_SpawnCritter_C* Cheat_SpawnCritter;
    class UCheat_SpawnEarthQuake_C* Cheat_SpawnEarthQuake;
    class UCheat_SpawnEnemy_C* Cheat_SpawnEnemy_C_0;
    class UCheat_SpawnEnemies_C* Cheat_SpawnOnOff;
    class UCheat_SpawnSandStorm_C* Cheat_SpawnSnowStorm;
    class UCheat_SpawnSnowStorm_C* Cheat_SpawnSnowStorm_456;
    class UCheat_ScriptedWave_C* Cheat_SpawnWave;
    class UCheat_StandingDown_C* Cheat_StandingDown;
    class UCheat_StopAIMovement_C* Cheat_StopAIMovement;
    class UCheat_MiscUpgradesItem_C* Cheat_ThirdItem;
    class UCheat_VanityTab_C* Cheat_VanityTab;
    class UButton* CleanSpawnPos;
    class UHorizontalBox* Content_Mission;
    class UWidgetSwitcher* ContentSwitcher;
    class UTextBlock* CritterPoolList;
    class UTextBlock* EnemyPool;
    class UCheckBox* FastPowerAttack;
    class USlider* HealthSlider;
    class UComboBoxString* mainWeaponselector;
    class USpinBox* MinimuleAmountselect;
    class UButton* PlaceSpawnpos;
    class UButton* RespawnboscoBTN;
    class UTextBlock* SavedCheatsActiveText;
    class UScrollBox* SB_ColorSkinMain;
    class UScrollBox* SB_ColorSkinSecondary;
    class UScrollBox* SB_MeshSkinMain;
    class UScrollBox* SB_MeshSkinSecondary;
    class UScrollBox* SB_SecWepPerks;
    class UScrollBox* SB_WeaponPerkList;
    class UComboBoxString* SecondaryWeaponSelector;
    class UTextBlock* StationaryPool;
    class UCanvasPanel* TopCanvasPanel;
    class UButton* UseSavedCheatsButton;
    class UVerticalBox* VerticalBox_Materials;
    class UButton* ActiveTab;
    class UButton* ActiveCharacterTab;
    int32 Current Tab Index;
    int32 Amount of main tabs;
    bool Fast Select Enabled;
    bool Power User Mode Active;
    class UCheat_SpawnEnemyAdvanced_C* advancedSpawnMenu;
    class UPlayerCharacterID* ActiveCharacter;

    void CountResources(int32 Temp_int_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue_1, int32 Temp_int_Array_Index_Variable, class AProceduralSetup* CallFunc_GetProceduralSetup_ReturnValue, bool CallFunc_IsValid_ReturnValue, int32 CallFunc_GetChildrenCount_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue, class UWidget* CallFunc_GetChildAt_ReturnValue, bool CallFunc_LessEqual_IntInt_ReturnValue, class UCheat_MaterialInfo_C* K2Node_DynamicCast_AsCheat_Material_Info, bool K2Node_DynamicCast_bSuccess, class APlayerController* CallFunc_GetOwningPlayer_ReturnValue, class UResourceData* CallFunc_Array_Get_Item, class UCheat_Collectible_C* CallFunc_Create_ReturnValue, class UCollectableResourceData* K2Node_DynamicCast_AsCollectable_Resource_Data, bool K2Node_DynamicCast_bSuccess_1, class UGemResourceData* K2Node_DynamicCast_AsGem_Resource_Data, bool K2Node_DynamicCast_bSuccess_2, class UCarvedResourceData* K2Node_DynamicCast_AsCarved_Resource_Data, bool K2Node_DynamicCast_bSuccess_3, class UVeinResourceData* K2Node_DynamicCast_AsVein_Resource_Data, bool K2Node_DynamicCast_bSuccess_4, class UCarvedResourceCreator* CallFunc_LoadResourceCreator_ReturnValue, class UTerrainMaterial* CallFunc_GetTerrainMaterial_ReturnValue, class UCheat_GemInfo_C* CallFunc_Create_ReturnValue_1, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, class UVerticalBoxSlot* CallFunc_AddChildToVerticalBox_ReturnValue, class UVerticalBoxSlot* CallFunc_AddChildToVerticalBox_ReturnValue_1, class APlayerController* CallFunc_GetOwningPlayer_ReturnValue_1, class UCheat_MaterialInfo_C* CallFunc_Create_ReturnValue_2, class UCheat_MaterialInfo_C* CallFunc_Create_ReturnValue_3, class UVerticalBoxSlot* CallFunc_AddChildToVerticalBox_ReturnValue_2, class UVerticalBoxSlot* CallFunc_AddChildToVerticalBox_ReturnValue_3);
    class UWidget* On_AdvEnemySpawn_GetMenuContent(bool CallFunc_IsValid_ReturnValue, class APlayerController* CallFunc_GetOwningPlayer_ReturnValue, class UCheat_SpawnEnemyAdvanced_C* CallFunc_Create_ReturnValue);
    class UUpgradableBoscoComponent* GetBoscoUpgradeComponent(class ABosco*& Droneclass UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue, class UUpgradableBoscoComponent* CallFunc_GetUpgradeComponent_ReturnValue, bool CallFunc_IsValid_ReturnValue);
    void InitiateAnselSpinBox(class APlayerCameraManager* CallFunc_GetPlayerCameraManager_ReturnValue, class ABP_FSDCameraManager_C* K2Node_DynamicCast_AsBP_FSDCamera_Manager, bool K2Node_DynamicCast_bSuccess);
    class UWidget* OnGetMenuContent_0(class APlayerController* CallFunc_GetOwningPlayer_ReturnValue, class UCheat_OverclockSelection_C* CallFunc_Create_ReturnValue);
    ESlateVisibility Get_ActivateCommonCheatsButton_Visibility_0(bool Temp_bool_Variable, ESlateVisibility Temp_byte_Variable, ESlateVisibility Temp_byte_Variable_1, class APlayerController* CallFunc_GetOwningPlayer_ReturnValue, bool CallFunc_HasAuthority_ReturnValue, ESlateVisibility K2Node_Select_Default);
    float Get_HealthSlider_Value_0(class ACharacter* CallFunc_GetPlayerCharacter_ReturnValue, class APlayerCharacter* K2Node_DynamicCast_AsPlayer_Character, bool K2Node_DynamicCast_bSuccess, float CallFunc_GetHealth_ReturnValue, float CallFunc_Divide_FloatFloat_ReturnValue);
    FEventReply OnKeyDown(FGeometry MyGeometry, FKeyEvent InKeyEventFKey CallFunc_GetKey_ReturnValue, FText CallFunc_Key_GetDisplayName_ReturnValue, FString CallFunc_Conv_TextToString_ReturnValue, bool K2Node_SwitchString_CmpSuccess, class UWindowManager* CallFunc_GetWindowManager_ReturnValue, FEventReply CallFunc_Handled_ReturnValue);
    void Get Character to change(FText Character, class UPlayerCharacterID*& character out, FString CallFunc_Conv_TextToString_ReturnValue, int32 Temp_int_Array_Index_Variable, FString CallFunc_RightChop_ReturnValue, FText CallFunc_Conv_StringToText_ReturnValue, class AFSDGameState* CallFunc_GetFSDGameState_ReturnValue, FText CallFunc_TextToUpper_ReturnValue, TArray<class UPlayerCharacterID*>& CallFunc_GetPlayableCharacterIDs_ReturnValue, int32 Temp_int_Loop_Counter_Variable, class UPlayerCharacterID* CallFunc_Array_Get_Item, int32 CallFunc_Add_IntInt_ReturnValue, class AFSDGameState* CallFunc_GetFSDGameState_ReturnValue_1, TArray<class UPlayerCharacterID*>& CallFunc_GetPlayableCharacterIDs_ReturnValue_1, int32 CallFunc_Array_Length_ReturnValue, class UPlayerCharacterID* CallFunc_Array_Get_Item_1, bool CallFunc_Less_IntInt_ReturnValue, const FText CallFunc_GetName_ReturnValue, bool CallFunc_EqualEqual_TextText_ReturnValue);
    void DeselectTab(class UButton* Tab, bool CallFunc_EqualEqual_ObjectObject_ReturnValue, bool CallFunc_IsValid_ReturnValue);
    void SelectTab(int32 Index, class UButton* TabButton, bool CallFunc_EqualEqual_ObjectObject_ReturnValue);
    void OnLoaded_A7093BF7410CE2BD47E9B6A07D503818(UClass* Loaded);
    void BndEvt__Button_Close_K2Node_ComponentBoundEvent_62_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_General_K2Node_ComponentBoundEvent_323_OnButtonClickedEvent__DelegateSignature();
    void SelectFirstTab();
    void Init Tabs();
    void BndEvt__Button_Controls_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_UI_K2Node_ComponentBoundEvent_107_OnButtonClickedEvent__DelegateSignature();
    void OnShown();
    void OnClosed();
    void BndEvt__Button_539_K2Node_ComponentBoundEvent_140_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_Gunner_K2Node_ComponentBoundEvent_683_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_Engineer_K2Node_ComponentBoundEvent_735_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_Driller_K2Node_ComponentBoundEvent_758_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_Scout_K2Node_ComponentBoundEvent_782_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_0_K2Node_ComponentBoundEvent_20_OnButtonClickedEvent__DelegateSignature();
    void Update weapon info(EItemCategory categoryType, class UComboBoxString* ComboBoxToFill);
    void Set new weapon(FString Weapon name, EItemCategory Category);
    void Construct();
    void update selected upgrade();
    void Reload lists();
    void Fill Perk list(EItemCategory ItemSlotType, class UScrollBox* scrollbox to change);
    void BndEvt__mainWeaponselector_K2Node_ComponentBoundEvent_1369_OnSelectionChangedEvent__DelegateSignature(FString SelectedItem, TEnumAsByte<ESelectInfo::Type> SelectionType);
    void BndEvt__SecondaryWeaponSelector_K2Node_ComponentBoundEvent_1395_OnSelectionChangedEvent__DelegateSignature(FString SelectedItem, TEnumAsByte<ESelectInfo::Type> SelectionType);
    void Swap Weapon to next(EItemCategory Item Category);
    void HotKey Interaction change character();
    void Select Next Tab();
    void Select previous tab();
    void Select current tab();
    void BndEvt__CheckBox_QuickSelect_K2Node_ComponentBoundEvent_777_OnCheckBoxComponentStateChanged__DelegateSignature(bool bIsChecked);
    void Fill Misc Upgrades(EItemCategory Item Slot type, class UCheat_MiscUpgradesItem_C* CheatBoxToFill);
    void Set player misc upgrades();
    void Reload Character();
    void Build Bosco abilities();
    void BndEvt__RespawnboscoBTN_K2Node_ComponentBoundEvent_172_OnButtonClickedEvent__DelegateSignature();
    void Initiate Pool lists();
    void BndEvt__Button_Vanity_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Cheat_ResetAchievement_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__HealthSlider_K2Node_ComponentBoundEvent_2_OnFloatValueChangedEvent__DelegateSignature(float Value);
    void BndEvt__FastPowerAttack_K2Node_ComponentBoundEvent_5_OnCheckBoxComponentStateChanged__DelegateSignature(bool bIsChecked);
    void BndEvt__ActivateCommonCheatsButton_K2Node_ComponentBoundEvent_6_OnButtonClickedEvent__DelegateSignature();
    void Power user key pressed();
    void BndEvt__AnselSpeedSpinBox_K2Node_ComponentBoundEvent_3_OnSpinBoxValueChangedEvent__DelegateSignature(float InValue);
    void BndEvt__AnselDistanceSpinBox_K2Node_ComponentBoundEvent_4_OnSpinBoxValueChangedEvent__DelegateSignature(float InValue);
    void BndEvt__Button_SpawnMinimule_K2Node_ComponentBoundEvent_7_OnButtonClickedEvent__DelegateSignature();
    void Fill Weapon skin SB(class UScrollBox* SkinScrollBox, EItemCategory Item Slot, EItemSkinType SkinType);
    void Reload skin list(EItemCategory Category);
    void BndEvt__Button_AdvancedEnemyspawn_K2Node_ComponentBoundEvent_8_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__AdvEnemySpawn_K2Node_ComponentBoundEvent_9_OnMenuOpenChangedEvent__DelegateSignature(bool bIsOpen);
    void Close Advanced spawning();
    void BndEvt__PlaceSpawnpos_K2Node_ComponentBoundEvent_10_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__CleanSpawnPos_K2Node_ComponentBoundEvent_11_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__UseSavedCheatsButton_K2Node_ComponentBoundEvent_12_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_Mission_K2Node_ComponentBoundEvent_13_OnButtonClickedEvent__DelegateSignature();
    void ExecuteUbergraph_Menu_Cheats(int32 EntryPoint, UClass* Temp_class_Variable, TSubclassOf<class UUserWidget> K2Node_ClassDynamicCast_AsUser_Widget, bool K2Node_ClassDynamicCast_bSuccess, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable_1, UClass* K2Node_CustomEvent_Loaded, int32 Temp_int_Loop_Counter_Variable_1, int32 CallFunc_Add_IntInt_ReturnValue_1, int32 Temp_int_Loop_Counter_Variable_2, int32 CallFunc_Add_IntInt_ReturnValue_2, int32 Temp_int_Array_Index_Variable_2, FText Temp_text_Variable, int32 Temp_int_Array_Index_Variable_3, int32 Temp_int_Variable, int32 CallFunc_Add_IntInt_ReturnValue_3, int32 Temp_int_Array_Index_Variable_4, int32 Temp_int_Loop_Counter_Variable_3, int32 CallFunc_Add_IntInt_ReturnValue_4, int32 CallFunc_Add_IntInt_ReturnValue_5, FString CallFunc_Conv_IntToString_ReturnValue, FString CallFunc_Concat_StrStr_ReturnValue, FText CallFunc_Conv_StringToText_ReturnValue, int32 Temp_int_Array_Index_Variable_5, FText Temp_text_Variable_1, FExecuteUbergraph_Menu_CheatsK2Node_CreateDelegate_OutputDelegate K2Node_CreateDelegate_OutputDelegate, int32 Temp_int_Loop_Counter_Variable_4, int32 CallFunc_Add_IntInt_ReturnValue_6, int32 Temp_int_Array_Index_Variable_6, int32 Temp_int_Loop_Counter_Variable_5, int32 CallFunc_Add_IntInt_ReturnValue_7, int32 Temp_int_Variable_1, int32 Temp_int_Loop_Counter_Variable_6, int32 CallFunc_Add_IntInt_ReturnValue_8, int32 Temp_int_Array_Index_Variable_7, bool Temp_bool_Variable, int32 Temp_int_Loop_Counter_Variable_7, int32 CallFunc_Add_IntInt_ReturnValue_9, int32 Temp_int_Array_Index_Variable_8, FText Temp_text_Variable_2, int32 Temp_int_Loop_Counter_Variable_8, FExecuteUbergraph_Menu_CheatsK2Node_CreateDelegate_OutputDelegate_1 K2Node_CreateDelegate_OutputDelegate_1, FTimerHandle CallFunc_K2_SetTimerDelegate_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_10, bool Temp_bool_IsClosed_Variable, int32 Temp_int_Array_Index_Variable_9, int32 CallFunc_Add_IntInt_ReturnValue_11, FString CallFunc_Conv_IntToString_ReturnValue_1, FString CallFunc_Concat_StrStr_ReturnValue_1, FText CallFunc_Conv_StringToText_ReturnValue_1, bool Temp_bool_Has_Been_Initd_Variable, TArray<class UButton*>& K2Node_MakeArray_Array, class UButton* CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, class APlayerController* CallFunc_GetPlayerController_ReturnValue, class APlayerController* CallFunc_GetPlayerController_ReturnValue_1, class UWindowManager* CallFunc_GetWindowManager_ReturnValue, class UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue, bool CallFunc_IsValid_ReturnValue, class UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue, class UFSDSaveGame* CallFunc_GetFSDSaveGame_ReturnValue, class UInventoryList* CallFunc_GetInventoryList_ReturnValue, class UFSDSaveGame* CallFunc_GetFSDSaveGame_ReturnValue_1, class UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_1, class UWindowManager* CallFunc_GetWindowManager_ReturnValue_1, class UPlayerCharacterID* CallFunc_GetCharacterIDFromCharacter_ReturnValue, EItemCategory K2Node_CustomEvent_categoryType, class UComboBoxString* K2Node_CustomEvent_ComboBoxToFill, class UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_2, class UFSDSaveGame* CallFunc_GetFSDSaveGame_ReturnValue_2, class UInventoryList* CallFunc_GetHeroInventoryList_ReturnValue, class UItemID* CallFunc_GetEquippedItemID_ReturnValue, class UInventoryList* CallFunc_GetHeroInventoryList_ReturnValue_1, FString CallFunc_GetDisplayName_ReturnValue, const TArray<class UItemID*>& CallFunc_GetItemList_ReturnValue, class UItemID* CallFunc_Array_Get_Item_1, int32 CallFunc_Array_Length_ReturnValue_1, FString CallFunc_GetDisplayName_ReturnValue_1, bool CallFunc_Less_IntInt_ReturnValue_1, int32 CallFunc_FindOptionIndex_ReturnValue, FString K2Node_CustomEvent_Weapon_name, EItemCategory K2Node_CustomEvent_category_1, bool CallFunc_NotEqual_IntInt_ReturnValue, bool K2Node_SwitchEnum_CmpSuccess, const TArray<class UItemID*>& CallFunc_GetItemList_ReturnValue_1, class UFSDSaveGame* CallFunc_GetFSDSaveGame_ReturnValue_3, class UItemID* CallFunc_Array_Get_Item_2, int32 CallFunc_Array_Length_ReturnValue_2, TSubclassOf<class AItem> CallFunc_GetItemClass_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue_2, FString CallFunc_GetDisplayName_ReturnValue_2, bool CallFunc_EqualEqual_StrStr_ReturnValue, FString CallFunc_GetSelectedOption_ReturnValue, FString CallFunc_GetSelectedOption_ReturnValue_1, EItemCategory K2Node_CustomEvent_ItemSlotType, class UScrollBox* K2Node_CustomEvent_scrollbox_to_change, class UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_3, class UFSDSaveGame* CallFunc_GetFSDSaveGame_ReturnValue_4, FString K2Node_ComponentBoundEvent_SelectedItem_1, TEnumAsByte<ESelectInfo::Type> K2Node_ComponentBoundEvent_SelectionType_1, TSubclassOf<class AActor> CallFunc_GetEquippedItem_ReturnValue, FString K2Node_ComponentBoundEvent_SelectedItem, TEnumAsByte<ESelectInfo::Type> K2Node_ComponentBoundEvent_SelectionType, const TArray<FUpgradeTier>& CallFunc_GetItemUpgradeTiers_ReturnValue, FUpgradeTier CallFunc_Array_Get_Item_3, int32 CallFunc_Array_Length_ReturnValue_3, FText Temp_text_Variable_3, int32 Temp_int_Loop_Counter_Variable_9, bool CallFunc_Less_IntInt_ReturnValue_3, int32 CallFunc_Add_IntInt_ReturnValue_12, class APlayerController* CallFunc_GetPlayerController_ReturnValue_2, EItemCategory K2Node_CustomEvent_item_category, class UCheat_PerkListTier_C* CallFunc_Create_ReturnValue, TSubclassOf<class AActor> CallFunc_GetEquippedItem_ReturnValue_1, class UItemID* CallFunc_GetItemID_ReturnValue, class UItemID* CallFunc_GetNextItem_ReturnValue, TSubclassOf<class AActor> CallFunc_GetActorClass_ReturnValue, class UPanelSlot* CallFunc_AddChild_ReturnValue, bool Temp_bool_Variable_1, int32 CallFunc_Subtract_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_13, int32 CallFunc_Subtract_IntInt_ReturnValue_1, bool K2Node_ComponentBoundEvent_bIsChecked_1, class APlayerController* CallFunc_GetPlayerController_ReturnValue_3, class AFSDPlayerControllerBase* K2Node_DynamicCast_AsFSDPlayer_Controller_Base, bool K2Node_DynamicCast_bSuccess, class APlayerController* CallFunc_GetPlayerController_ReturnValue_4, class AFSDPlayerControllerBase* K2Node_DynamicCast_AsFSDPlayer_Controller_Base_1, bool K2Node_DynamicCast_bSuccess_1, EItemCategory K2Node_CustomEvent_Item_Slot_type, class UCheat_MiscUpgradesItem_C* K2Node_CustomEvent_CheatBoxToFill, class APlayerController* CallFunc_GetPlayerController_ReturnValue_5, class UCheat_PerkListTier_C* CallFunc_Create_ReturnValue_1, class UCheat_SpawnBosco_C* CallFunc_Create_ReturnValue_2, class UPanelSlot* CallFunc_AddChild_ReturnValue_1, class UPanelSlot* CallFunc_AddChild_ReturnValue_2, class UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue_1, class AFSDGameMode* CallFunc_GetFSDGameMode_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, class UEncounterManager* CallFunc_GetEncounterManager_ReturnValue, const TArray<class UCritterDescriptor*>& CallFunc_GetCritterPool_ReturnValue, const TArray<class UEnemyDescriptor*>& CallFunc_GetEnemyPool_ReturnValue, class UCritterDescriptor* CallFunc_Array_Get_Item_4, class UEnemyDescriptor* CallFunc_Array_Get_Item_5, FString CallFunc_GetObjectName_ReturnValue, FString CallFunc_GetObjectName_ReturnValue_1, int32 CallFunc_Array_Length_ReturnValue_4, int32 CallFunc_Array_Length_ReturnValue_5, bool CallFunc_Less_IntInt_ReturnValue_4, bool CallFunc_Less_IntInt_ReturnValue_5, const TArray<class UEnemyDescriptor*>& CallFunc_GetEncounterPool_ReturnValue, class UEnemyDescriptor* CallFunc_Array_Get_Item_6, FExecuteUbergraph_Menu_CheatsK2Node_CreateDelegate_OutputDelegate_2 K2Node_CreateDelegate_OutputDelegate_2, FString CallFunc_GetObjectName_ReturnValue_2, int32 CallFunc_Array_Length_ReturnValue_6, bool CallFunc_Less_IntInt_ReturnValue_6, FText CallFunc_GetText_ReturnValue, FString CallFunc_Conv_TextToString_ReturnValue, FString CallFunc_Concat_StrStr_ReturnValue_2, FText CallFunc_GetText_ReturnValue_1, FString CallFunc_Concat_StrStr_ReturnValue_3, FString CallFunc_Conv_TextToString_ReturnValue_1, FText CallFunc_Conv_StringToText_ReturnValue_2, FString CallFunc_Concat_StrStr_ReturnValue_4, FString CallFunc_Concat_StrStr_ReturnValue_5, FText CallFunc_Conv_StringToText_ReturnValue_3, FExecuteUbergraph_Menu_CheatsK2Node_CreateDelegate_OutputDelegate_3 K2Node_CreateDelegate_OutputDelegate_3, int32 Temp_int_Variable_2, bool CallFunc_Greater_IntInt_ReturnValue, FText CallFunc_GetText_ReturnValue_2, FString CallFunc_Conv_TextToString_ReturnValue_2, FString CallFunc_Concat_StrStr_ReturnValue_6, FString CallFunc_Concat_StrStr_ReturnValue_7, FText CallFunc_Conv_StringToText_ReturnValue_4, class UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue_2, float K2Node_ComponentBoundEvent_Value, class UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue_3, class ACharacter* CallFunc_GetPlayerCharacter_ReturnValue, bool K2Node_ComponentBoundEvent_bIsChecked, class APlayerCharacter* K2Node_DynamicCast_AsPlayer_Character, bool K2Node_DynamicCast_bSuccess_2, float CallFunc_SelectFloat_ReturnValue, class ACharacter* CallFunc_GetPlayerCharacter_ReturnValue_1, class APlayerCharacter* K2Node_DynamicCast_AsPlayer_Character_1, bool K2Node_DynamicCast_bSuccess_3, float CallFunc_Multiply_FloatFloat_ReturnValue, class UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue_4, class APlayerController* CallFunc_GetOwningPlayer_ReturnValue, class APlayerController* CallFunc_GetOwningPlayer_ReturnValue_1, bool CallFunc_HasAuthority_ReturnValue, class UCheat_OverclockSelection_C* CallFunc_Create_ReturnValue_3, class UPanelSlot* CallFunc_AddChild_ReturnValue_3, class UPanelSlot* CallFunc_AddChild_ReturnValue_4, float K2Node_ComponentBoundEvent_InValue_1, class APlayerCameraManager* CallFunc_GetPlayerCameraManager_ReturnValue, float K2Node_ComponentBoundEvent_InValue, class ABP_FSDCameraManager_C* K2Node_DynamicCast_AsBP_FSDCamera_Manager, bool K2Node_DynamicCast_bSuccess_4, class APlayerCameraManager* CallFunc_GetPlayerCameraManager_ReturnValue_1, class ABP_FSDCameraManager_C* K2Node_DynamicCast_AsBP_FSDCamera_Manager_1, bool K2Node_DynamicCast_bSuccess_5, class APlayerCharacter* CallFunc_GetLocalPlayerCharacter_ReturnValue, float CallFunc_GetValue_ReturnValue, const FTransform CallFunc_GetTransform_ReturnValue, int32 CallFunc_FTrunc_ReturnValue, FVector CallFunc_BreakTransform_Location, FRotator CallFunc_BreakTransform_Rotation, FVector CallFunc_BreakTransform_Scale, bool CallFunc_LessEqual_IntInt_ReturnValue, float CallFunc_BreakVector_X, float CallFunc_BreakVector_Y, float CallFunc_BreakVector_Z, float CallFunc_Multiply_IntFloat_ReturnValue, FVector CallFunc_MakeVector_ReturnValue, FTransform CallFunc_MakeTransform_ReturnValue, class UScrollBox* K2Node_CustomEvent_SkinScrollBox, EItemCategory K2Node_CustomEvent_Item_Slot, EItemSkinType K2Node_CustomEvent_skinType, class UFSDSaveGame* CallFunc_GetFSDSaveGame_ReturnValue_5, class UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_4, class APlayerController* CallFunc_GetOwningPlayer_ReturnValue_2, class UCheat_SkinListItem_C* CallFunc_Create_ReturnValue_4, TSubclassOf<class AActor> CallFunc_GetEquippedItem_ReturnValue_2, class UItemID* CallFunc_GetItemID_ReturnValue_1, TArray<class UItemSkin*>& CallFunc_GetSkinsForItem_ReturnValue, class UPanelSlot* CallFunc_AddChild_ReturnValue_5, class UItemSkin* CallFunc_Array_Get_Item_7, int32 CallFunc_Array_Length_ReturnValue_7, bool CallFunc_Less_IntInt_ReturnValue_7, EItemCategory K2Node_CustomEvent_category, bool K2Node_SwitchEnum_CmpSuccess_1, class ABosco* CallFunc_GetBoscoUpgradeComponent_Drone, class UUpgradableBoscoComponent* CallFunc_GetBoscoUpgradeComponent_ReturnValue, bool CallFunc_IsValid_ReturnValue_2, FUpgradeTier CallFunc_Array_Get_Item_8, int32 CallFunc_Array_Length_ReturnValue_8, TSubclassOf<class ABosco> CallFunc_GetObjectClass_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue_8, bool K2Node_ComponentBoundEvent_bIsOpen, class UWidget* CallFunc_On_AdvEnemySpawn_GetMenuContent_ReturnValue, bool CallFunc_IsValid_ReturnValue_3, class APawn* CallFunc_GetPlayerPawn_ReturnValue, bool CallFunc_IsServer_ReturnValue, bool CallFunc_IsValid_ReturnValue_4, const FTransform CallFunc_GetTransform_ReturnValue_1, class UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue_5, class AActor* CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue, class ASpawnPosMarker_C* CallFunc_FinishSpawningActor_ReturnValue, TArray<class ASpawnPosMarker_C*>& CallFunc_GetAllActorsOfClass_OutActors, class ASpawnPosMarker_C* CallFunc_Array_Get_Item_9, int32 CallFunc_Array_Length_ReturnValue_9, bool CallFunc_Less_IntInt_ReturnValue_9, class UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue_6, class UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue_7, bool CallFunc_Not_PreBool_ReturnValue, FText K2Node_Select_Default, class UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue_8, FText K2Node_Select_Default_1, UClass* CallFunc_LoadClass_ReturnValue, TSubclassOf<class AMiniMule> K2Node_ClassDynamicCast_AsMini_Mule, bool K2Node_ClassDynamicCast_bSuccess_1, class AActor* CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_1, class AMiniMule* CallFunc_FinishSpawningActor_ReturnValue_1, class URepairableComponent* CallFunc_GetComponentByClass_ReturnValue, class UButton* K2Node_Select_Default_2, class AFSDGameMode* CallFunc_GetFSDGameMode_ReturnValue_1, int32 Temp_int_Variable_3, bool CallFunc_IsValid_ReturnValue_5, bool CallFunc_Less_IntInt_ReturnValue_10, class AFSDGameMode* CallFunc_GetFSDGameMode_ReturnValue_2, FExecuteUbergraph_Menu_CheatsK2Node_CreateDelegate_OutputDelegate_4 K2Node_CreateDelegate_OutputDelegate_4, bool CallFunc_IsValidSoftClassReference_ReturnValue, class APlayerController* CallFunc_GetOwningPlayer_ReturnValue_3, class UUserWidget* CallFunc_Create_ReturnValue_5, class UHorizontalBoxSlot* CallFunc_AddChildToHorizontalBoxEx_OutSlot, class UHorizontalBox* CallFunc_AddChildToHorizontalBoxEx_OutHorizontalBox, class UUserWidget* CallFunc_AddChildToHorizontalBoxEx_ReturnValue);
};

#endif
