#ifndef UE4SS_SDK_Menu_MovieMode_HPP
#define UE4SS_SDK_Menu_MovieMode_HPP

class UMenu_MovieMode_C : public UWindowWidget
{
    FPointerToUberGraphFrame UberGraphFrame;
    class USlider* BloomSlider;
    class UTextBlock* BloomText;
    class UButton* Button_Close;
    class UButton* Button_General;
    class UButton* Button_Hotkeys;
    class UButton* Button_Light;
    class UButton* Button_PostProcess;
    class UButton* Button_Tracking;
    class UTextBlock* CameraFovText;
    class USlider* CameraShakeSlider;
    class UTextBlock* CameraShakeText;
    class USlider* ChromaSlider;
    class UTextBlock* ChromaText;
    class UButton* ClearAllLights;
    class UWidgetSwitcher* ContentSwitcher;
    class USlider* DOFAmountSlider;
    class UTextBlock* DOFAmountText;
    class USlider* FoV_Slider_1;
    class UButton* LoadLightSettings;
    class USlider* MotionBlurSlider;
    class UTextBlock* MotionBlurText;
    class USlider* MouseSensSlider;
    class UTextBlock* MouseSensText;
    class UMovieMode_DronePointLight_C* MovieMode_DronePointLight;
    class UMovieMode_FlareLight_C* MovieMode_FlareLight;
    class UMovieMode_ScoutFlareLight_C* MovieMode_ScoutFlareLight;
    class UTextBlock* OffText;
    class UTextBlock* OffText_1;
    class UTextBlock* OffText_2;
    class UTextBlock* OffText_DOF;
    class UTextBlock* OffText_FreeRot;
    class UTextBlock* OnText;
    class UTextBlock* OnText_1;
    class UTextBlock* OnText_2;
    class UTextBlock* OnText_DOF;
    class UTextBlock* OnText_FreeRot;
    class UButton* PivotOffsetButton;
    class UButton* PostionalOffsetReset;
    class UButton* ResetFocusButton;
    class UButton* ResetFocusButton_1;
    class UButton* SaveLightSettings;
    class USlider* Spline_Speed;
    class UButton* ToggleDOF;
    class UButton* ToggleFreeRotation;
    class UButton* TogglePlayerMeshButton;
    class UButton* TogglePlayerMeshButton_1;
    class UButton* TogglePlayerMeshButton_2;
    class UCanvasPanel* TopCanvasPanel;
    class USlider* VignetteSlider;
    class UTextBlock* VignetteText;
    class UButton* ActiveTab;
    bool PlayerMeshToggled;
    class UButton* TabButtonInFocus;
    bool UseDepthOfField;
    FPostProcessSettings PostProcessingSettings;
    int32 PP_FilterComboIndex;

    void SetOnOffTexts(bool Condition, class UTextBlock* OffText, class UTextBlock* OnText);
    void DeselectTab(class UButton* Active Tab, bool CallFunc_EqualEqual_ObjectObject_ReturnValue, bool CallFunc_IsValid_ReturnValue);
    void SelectTab(int32 Index, class UButton* Tab Button);
    FEventReply OnKeyDown(FGeometry MyGeometry, FKeyEvent InKeyEventFKey CallFunc_GetKey_ReturnValue, class UWindowManager* CallFunc_GetWindowManager_ReturnValue, FText CallFunc_Key_GetDisplayName_ReturnValue, FString CallFunc_Conv_TextToString_ReturnValue, FEventReply CallFunc_Handled_ReturnValue, bool K2Node_SwitchString_CmpSuccess);
    void BndEvt__Button_General_K2Node_ComponentBoundEvent_323_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_Light_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_165_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__TogglePlayerMeshButton_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__TogglePlayerMeshButton_1_K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__TogglePlayerMeshButton_2_K2Node_ComponentBoundEvent_5_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__FoV_Slider_1_K2Node_ComponentBoundEvent_7_OnFloatValueChangedEvent__DelegateSignature(float Value);
    void BndEvt__Button_Tracking_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__TogglePlayerMeshButton_5_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__TogglePlayerMeshButton_4_K2Node_ComponentBoundEvent_8_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__ClearAllLights_K2Node_ComponentBoundEvent_10_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__LoadLightSettings_K2Node_ComponentBoundEvent_13_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Spline_Speed_K2Node_ComponentBoundEvent_1_OnFloatValueChangedEvent__DelegateSignature(float Value);
    void BndEvt__MouseSensSlider_K2Node_ComponentBoundEvent_12_OnFloatValueChangedEvent__DelegateSignature(float Value);
    void BndEvt__Button_PostProcess_K2Node_ComponentBoundEvent_12_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_Close_K2Node_ComponentBoundEvent_62_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__MotionBlurSlider_K2Node_ComponentBoundEvent_16_OnFloatValueChangedEvent__DelegateSignature(float Value);
    void BndEvt__VignetteSlider_K2Node_ComponentBoundEvent_17_OnFloatValueChangedEvent__DelegateSignature(float Value);
    void BndEvt__ChromaSlider_K2Node_ComponentBoundEvent_18_OnFloatValueChangedEvent__DelegateSignature(float Value);
    void BndEvt__ToggleDOF_K2Node_ComponentBoundEvent_19_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__ChromaSlider_1_K2Node_ComponentBoundEvent_22_OnFloatValueChangedEvent__DelegateSignature(float Value);
    void BndEvt__BloomSlider_K2Node_ComponentBoundEvent_24_OnFloatValueChangedEvent__DelegateSignature(float Value);
    void BndEvt__DOFAmountSlider_K2Node_ComponentBoundEvent_21_OnMouseCaptureBeginEvent__DelegateSignature();
    void BndEvt__ToggleFreeRotation_K2Node_ComponentBoundEvent_9_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__ResetFocusButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__ResetFocusButton_1_K2Node_ComponentBoundEvent_9_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_Hotkeys_K2Node_ComponentBoundEvent_23_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__CameraShakeSlider_K2Node_ComponentBoundEvent_26_OnFloatValueChangedEvent__DelegateSignature(float Value);
    void ExecuteUbergraph_Menu_MovieMode(int32 EntryPoint, class APawn* CallFunc_GetOwningPlayerPawn_ReturnValue, class APawn* CallFunc_GetOwningPlayerPawn_ReturnValue_1, class ABP_PlayerCameraDrone_C* K2Node_DynamicCast_AsBP_Player_Camera_Drone, bool K2Node_DynamicCast_bSuccess, class ABP_PlayerCameraDrone_C* K2Node_DynamicCast_AsBP_Player_Camera_Drone_1, bool K2Node_DynamicCast_bSuccess_1, class APawn* CallFunc_GetOwningPlayerPawn_ReturnValue_2, class APawn* CallFunc_GetOwningPlayerPawn_ReturnValue_3, bool CallFunc_Not_PreBool_ReturnValue, bool CallFunc_GetActorEnableCollision_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue_1, class APawn* CallFunc_GetOwningPlayerPawn_ReturnValue_4, class APlayerCameraDrone* K2Node_DynamicCast_AsPlayer_Camera_Drone, bool K2Node_DynamicCast_bSuccess_2, bool CallFunc_ToggleSplineMeshVisibility_ReturnValue, float K2Node_ComponentBoundEvent_Value_8, FText CallFunc_Conv_FloatToText_ReturnValue, class APawn* CallFunc_GetOwningPlayerPawn_ReturnValue_5, class APawn* CallFunc_GetOwningPlayerPawn_ReturnValue_6, class ABP_PlayerCameraDrone_C* K2Node_DynamicCast_AsBP_Player_Camera_Drone_2, bool K2Node_DynamicCast_bSuccess_3, class ABP_PlayerCameraDrone_C* K2Node_DynamicCast_AsBP_Player_Camera_Drone_3, bool K2Node_DynamicCast_bSuccess_4, class APawn* CallFunc_GetOwningPlayerPawn_ReturnValue_7, class APawn* CallFunc_GetOwningPlayerPawn_ReturnValue_8, class ABP_PlayerCameraDrone_C* K2Node_DynamicCast_AsBP_Player_Camera_Drone_4, bool K2Node_DynamicCast_bSuccess_5, class ABP_PlayerCameraDrone_C* K2Node_DynamicCast_AsBP_Player_Camera_Drone_5, bool K2Node_DynamicCast_bSuccess_6, float K2Node_ComponentBoundEvent_Value_7, class APawn* CallFunc_GetOwningPlayerPawn_ReturnValue_9, class APawn* CallFunc_GetOwningPlayerPawn_ReturnValue_10, class ABP_PlayerCameraDrone_C* K2Node_DynamicCast_AsBP_Player_Camera_Drone_6, bool K2Node_DynamicCast_bSuccess_7, class APlayerCameraDrone* K2Node_DynamicCast_AsPlayer_Camera_Drone_1, bool K2Node_DynamicCast_bSuccess_8, class APawn* CallFunc_GetOwningPlayerPawn_ReturnValue_11, class APawn* CallFunc_GetOwningPlayerPawn_ReturnValue_12, class APlayerCameraDrone* K2Node_DynamicCast_AsPlayer_Camera_Drone_2, bool K2Node_DynamicCast_bSuccess_9, class APlayerCameraDrone* K2Node_DynamicCast_AsPlayer_Camera_Drone_3, bool K2Node_DynamicCast_bSuccess_10, float K2Node_ComponentBoundEvent_Value_6, class APawn* CallFunc_GetOwningPlayerPawn_ReturnValue_13, class ABP_PlayerCameraDrone_C* K2Node_DynamicCast_AsBP_Player_Camera_Drone_7, bool K2Node_DynamicCast_bSuccess_11, FText CallFunc_Conv_FloatToText_ReturnValue_1, class APawn* CallFunc_GetOwningPlayerPawn_ReturnValue_14, class APlayerCameraDrone* K2Node_DynamicCast_AsPlayer_Camera_Drone_4, bool K2Node_DynamicCast_bSuccess_12, class UWindowManager* CallFunc_GetWindowManager_ReturnValue, float K2Node_ComponentBoundEvent_Value_5, FText CallFunc_Conv_FloatToText_ReturnValue_2, float K2Node_ComponentBoundEvent_Value_4, float K2Node_ComponentBoundEvent_Value_3, FText CallFunc_Conv_FloatToText_ReturnValue_3, FText CallFunc_Conv_FloatToText_ReturnValue_4, class APawn* CallFunc_GetOwningPlayerPawn_ReturnValue_15, class UCameraComponent* CallFunc_GetComponentByClass_ReturnValue, class APawn* CallFunc_GetOwningPlayerPawn_ReturnValue_16, class UCameraComponent* CallFunc_GetComponentByClass_ReturnValue_1, class APlayerCameraDrone* K2Node_DynamicCast_AsPlayer_Camera_Drone_5, bool K2Node_DynamicCast_bSuccess_13, bool CallFunc_Not_PreBool_ReturnValue_2, float K2Node_ComponentBoundEvent_Value_2, float K2Node_ComponentBoundEvent_Value_1, FText CallFunc_Conv_FloatToText_ReturnValue_5, bool CallFunc_Not_PreBool_ReturnValue_3, class APawn* CallFunc_GetOwningPlayerPawn_ReturnValue_17, class APlayerCameraDrone* K2Node_DynamicCast_AsPlayer_Camera_Drone_6, bool K2Node_DynamicCast_bSuccess_14, float Temp_float_Variable, bool Temp_bool_Variable, float K2Node_Select_Default, class APawn* CallFunc_GetOwningPlayerPawn_ReturnValue_18, FText CallFunc_Conv_FloatToText_ReturnValue_6, class APlayerCameraDrone* K2Node_DynamicCast_AsPlayer_Camera_Drone_7, bool K2Node_DynamicCast_bSuccess_15, bool CallFunc_Not_PreBool_ReturnValue_4, class APawn* CallFunc_GetOwningPlayerPawn_ReturnValue_19, class ABP_PlayerCameraDrone_C* K2Node_DynamicCast_AsBP_Player_Camera_Drone_8, bool K2Node_DynamicCast_bSuccess_16, class APawn* CallFunc_GetOwningPlayerPawn_ReturnValue_20, class ABP_PlayerCameraDrone_C* K2Node_DynamicCast_AsBP_Player_Camera_Drone_9, bool K2Node_DynamicCast_bSuccess_17, class APawn* CallFunc_GetOwningPlayerPawn_ReturnValue_21, class APlayerCameraDrone* K2Node_DynamicCast_AsPlayer_Camera_Drone_8, bool K2Node_DynamicCast_bSuccess_18, float K2Node_ComponentBoundEvent_Value, FText CallFunc_Conv_FloatToText_ReturnValue_7, class APawn* CallFunc_GetOwningPlayerPawn_ReturnValue_22, class ABP_PlayerCameraDrone_C* K2Node_DynamicCast_AsBP_Player_Camera_Drone_10, bool K2Node_DynamicCast_bSuccess_19, bool CallFunc_SetCameraShakeAmount_ReturnValue);
};

#endif
