#ifndef UE4SS_SDK_Options_ResetProgress_HPP
#define UE4SS_SDK_Options_ResetProgress_HPP

class UOptions_ResetProgress_C : public UUserWidget
{
    FPointerToUberGraphFrame UberGraphFrame;
    class UBasic_ButtonWithControls_C* Basic_ButtonWithControls;

    void OnFailure_E60EC8DB4E80DB2E20AA1A9F09A53224();
    void OnSuccess_E60EC8DB4E80DB2E20AA1A9F09A53224();
    void BndEvt__Basic_ButtonWithControls_K2Node_ComponentBoundEvent_21_OnClicked__DelegateSignature();
    void Answer(bool Yes);
    void TutorialAnswer(bool Yes);
    void ExecuteUbergraph_Options_ResetProgress(int32 EntryPoint, class UWindowManager* CallFunc_GetWindowManager_ReturnValue, FExecuteUbergraph_Options_ResetProgressK2Node_CreateDelegate_OutputDelegate K2Node_CreateDelegate_OutputDelegate, FExecuteUbergraph_Options_ResetProgressK2Node_CreateDelegate_OutputDelegate_1 K2Node_CreateDelegate_OutputDelegate_1, bool K2Node_CustomEvent_Yes_1, class UWindowManager* CallFunc_GetWindowManager_ReturnValue_1, class UBasic_Popup_YesNoPrompt_C* CallFunc_OpenSingleUseWindow_ReturnValue, class APlayerController* CallFunc_GetOwningPlayer_ReturnValue, class UFSDGameUserSettings* CallFunc_GetFSDGameUserSettings_ReturnValue, class UDestroySessionCallbackProxy* CallFunc_DestroySession_ReturnValue, FString CallFunc_GetCurrentUserSaveSlotName_ReturnValue, bool CallFunc_IsEmpty_ReturnValue, bool CallFunc_IsValid_ReturnValue, class UFSDSaveGame* CallFunc_GetFSDSaveGame_ReturnValue, class UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue, int32 CallFunc_GetAvailableUserSlotIndex_ReturnValue, FExecuteUbergraph_Options_ResetProgressK2Node_CreateDelegate_OutputDelegate_2 K2Node_CreateDelegate_OutputDelegate_2, class UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_1, class UWindowManager* CallFunc_GetWindowManager_ReturnValue_2, class UBasic_Popup_YesNoPrompt_C* CallFunc_OpenSingleUseWindow_ReturnValue_1, bool K2Node_CustomEvent_Yes, bool CallFunc_Not_PreBool_ReturnValue, class UFSDSaveGame* CallFunc_GetFSDSaveGame_ReturnValue_1, FExecuteUbergraph_Options_ResetProgressK2Node_CreateDelegate_OutputDelegate_3 K2Node_CreateDelegate_OutputDelegate_3);
};

#endif
