#ifndef UE4SS_SDK_Options_Scalability_ResolutioScale_HPP
#define UE4SS_SDK_Options_Scalability_ResolutioScale_HPP

class UOptions_Scalability_ResolutioScale_C : public UUserWidget
{
    FPointerToUberGraphFrame UberGraphFrame;
    class UBasic_Slider_C* Basic_Slider;

    void Construct();
    void UINeedsUpdate();
    void ShowUI();
    void BndEvt__Basic_Slider_K2Node_ComponentBoundEvent_1_OnPercentChanged__DelegateSignature(float Percent);
    void ExecuteUbergraph_Options_Scalability_ResolutioScale(int32 EntryPoint, class UFSDGameUserSettings* CallFunc_GetFSDGameUserSettings_ReturnValue, bool CallFunc_GetTemporalAAUpscalingEnabled_ReturnValue, FExecuteUbergraph_Options_Scalability_ResolutioScaleK2Node_CreateDelegate_OutputDelegate K2Node_CreateDelegate_OutputDelegate, class UGameUserSettings* CallFunc_GetGameUserSettings_ReturnValue, class UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue, float CallFunc_GetResolutionScaleInformationEx_CurrentScaleNormalized, float CallFunc_GetResolutionScaleInformationEx_CurrentScaleValue, float CallFunc_GetResolutionScaleInformationEx_MinScaleValue, float CallFunc_GetResolutionScaleInformationEx_MaxScaleValue, bool CallFunc_InRange_FloatFloat_ReturnValue, bool CallFunc_BooleanXOR_ReturnValue, float K2Node_ComponentBoundEvent_Percent, class UGameUserSettings* CallFunc_GetGameUserSettings_ReturnValue_1, class UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_1, class UFSDGameUserSettings* CallFunc_GetFSDGameUserSettings_ReturnValue_1);
};

#endif
