#ifndef UE4SS_SDK_WND_SeasonChallenges_HPP
#define UE4SS_SDK_WND_SeasonChallenges_HPP

class UWND_SeasonChallenges_C : public UUserWidget
{
    FPointerToUberGraphFrame UberGraphFrame;
    class UBasic_Menu_ColorBar_C* Basic_Menu_ColorBar;
    class UGridPanel* Grid_Challenges;
    class UITM_Season_ChallengeTimer_C* ChallengeTimer;

    void OnNewChallenge(int32 SwapIndex, int32 CallFunc_Add_IntInt_ReturnValue, class USeasonsSubsystem* CallFunc_GetGameInstanceSubsystem_ReturnValue, class UGridSlot* CallFunc_AddChildToGrid_ReturnValue, TArray<FChallengeInfo>& CallFunc_GetActiveChallenges_ReturnValue, class UGameData* CallFunc_GetFSDGameData_ReturnValue, class UGridSlot* CallFunc_SlotAsGridSlot_ReturnValue, FChallengeInfo CallFunc_Array_Get_Item, class USeasonsSubsystem* CallFunc_GetGameInstanceSubsystem_ReturnValue_1, bool CallFunc_CanRerollChallenge_ReturnValue, class UITM_Season_Challenge_C* CallFunc_AddChallengeToGrid_W_Challenge, class USeasonsSubsystem* CallFunc_GetGameInstanceSubsystem_ReturnValue_2, TArray<FChallengeInfo>& CallFunc_GetActiveChallenges_ReturnValue_1, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue);
    void AddChallengeToGrid(FChallengeInfo ChallengeInfo, bool CanReroll, int32 Column, class UITM_Season_Challenge_C*& W_Challenge, FMargin K2Node_MakeStruct_Margin, class UITM_Season_Challenge_C* CallFunc_Create_ReturnValue, class UGridSlot* CallFunc_AddChildToGrid_ReturnValue);
    void OnReroll(class UITM_Season_Challenge_C* W_Challenge, bool CanReroll, int32 Index, class UGridSlot* CallFunc_SlotAsGridSlot_ReturnValue, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, class USeasonsSubsystem* CallFunc_GetGameInstanceSubsystem_ReturnValue, bool CallFunc_CanRerollChallenge_ReturnValue, TArray<class UWidget*>& CallFunc_GetAllChildren_ReturnValue, class USeasonsSubsystem* CallFunc_GetGameInstanceSubsystem_ReturnValue_1, class UWidget* CallFunc_Array_Get_Item, TArray<FChallengeInfo>& CallFunc_GetActiveChallenges_ReturnValue, class UITM_Season_Challenge_C* K2Node_DynamicCast_AsITM_Season_Challenge, bool K2Node_DynamicCast_bSuccess, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue);
    void PreConstruct(bool IsDesignTime);
    void Refresh();
    void ExecuteUbergraph_WND_SeasonChallenges(int32 EntryPoint, FExecuteUbergraph_WND_SeasonChallengesK2Node_CreateDelegate_OutputDelegate K2Node_CreateDelegate_OutputDelegate, class UITM_Season_ChallengeTimer_C* CallFunc_Create_ReturnValue, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable, bool K2Node_Event_IsDesignTime, int32 Temp_int_Variable, class UITM_Season_Challenge_C* CallFunc_AddChallengeToGrid_W_Challenge, bool CallFunc_LessEqual_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_1, class USeasonsSubsystem* CallFunc_GetGameInstanceSubsystem_ReturnValue, class UGameData* CallFunc_GetFSDGameData_ReturnValue, bool CallFunc_CanRerollChallenge_ReturnValue, TArray<FChallengeInfo>& CallFunc_GetActiveChallenges_ReturnValue, FChallengeInfo CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, class UITM_Season_Challenge_C* CallFunc_AddChallengeToGrid_W_Challenge_1, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_1, bool CallFunc_Less_IntInt_ReturnValue_1, FMargin K2Node_MakeStruct_Margin, FExecuteUbergraph_WND_SeasonChallengesK2Node_CreateDelegate_OutputDelegate_1 K2Node_CreateDelegate_OutputDelegate_1, int32 CallFunc_GetChildrenCount_ReturnValue, class UGridSlot* CallFunc_AddChildToGrid_ReturnValue);
};

#endif
