#ifndef UE4SS_SDK_WPN_Pistol_A_HPP
#define UE4SS_SDK_WPN_Pistol_A_HPP

class AWPN_Pistol_A_C : public ABasicPistol
{
    FPointerToUberGraphFrame UberGraphFrame;
    class UStaticMeshComponent* TP_Animation_Mag;
    class UFirstPersonStaticMeshComponent* FP_Animation_Mag;
    class UFirstPersonWidgetComponent* FirstPersonWidget;
    class UFirstPersonStaticMeshComponent* FirstPersonStaticMesh;
    class UDamageComponent* Damage;
    class UFirstPersonStaticMeshComponent* FP_Mag;
    class UStaticMeshComponent* TP_Mag;
    class UPointLightComponent* MuzzlePointLight;
    class UCrosshairAggregator* CrosshairAggregator;
    class UHitscanComponent* HitScan;

    class UStaticMeshComponent* Receive_GetTPAnimationEventMesh();
    class UFirstPersonStaticMeshComponent* Receive_GetFPAnimationEventMesh();
    void GetGearStatEntry(class AFSDPlayerState* PlayerState, TArray<FGearStatEntry>& Stats, TSubclassOf<class AWPN_Pistol_A_C> CallFunc_GetObjectClass_ReturnValue, FGearStatEntry CallFunc_UPGDESC_Damage_GearStatEntry, bool CallFunc_UPGDESC_Damage_HasUpgradedValue, FGearStatEntry CallFunc_UPGDESC_Damage_GearStatEntry_1, bool CallFunc_UPGDESC_Damage_HasUpgradedValue_1, TSubclassOf<class AWPN_Pistol_A_C> CallFunc_GetObjectClass_ReturnValue_1, FGearStatEntry CallFunc_UPGDESC_DamageBonus_Random_GearStatEntry, bool CallFunc_UPGDESC_DamageBonus_Random_HasUpgradedValue, int32 CallFunc_Array_Add_ReturnValue, int32 CallFunc_Array_Add_ReturnValue_1, FText CallFunc_GetUpgradeName_ReturnValue, TSubclassOf<class AWPN_Pistol_A_C> CallFunc_GetObjectClass_ReturnValue_2, FGearStatEntry CallFunc_UPGDESC_HitScan_GearStatEntry, bool CallFunc_UPGDESC_HitScan_HasAnyUpgrades, int32 CallFunc_Array_Add_ReturnValue_2, int32 CallFunc_Array_Add_ReturnValue_3, TSubclassOf<class AWPN_Pistol_A_C> CallFunc_GetObjectClass_ReturnValue_3, FText CallFunc_GetUpgradeName_ReturnValue_1, FGearStatEntry CallFunc_UPGDESC_Generic_GearStatEntry, bool CallFunc_UPGDESC_Generic_HasUpgradedValue, int32 CallFunc_Array_Add_ReturnValue_4, TSubclassOf<class AWPN_Pistol_A_C> CallFunc_GetObjectClass_ReturnValue_4, FGearStatEntry CallFunc_UPGDESC_Generic_GearStatEntry_1, bool CallFunc_UPGDESC_Generic_HasUpgradedValue_1, int32 CallFunc_Array_Add_ReturnValue_5, TSubclassOf<class AWPN_Pistol_A_C> CallFunc_GetObjectClass_ReturnValue_5, FGearStatEntry CallFunc_UPGDESC_Damage_GearStatEntry_2, bool CallFunc_UPGDESC_Damage_HasUpgradedValue_2, FGearStatEntry CallFunc_UPGDESC_HitScan_GearStatEntry_1, bool CallFunc_UPGDESC_HitScan_HasAnyUpgrades_1, int32 CallFunc_Array_Add_ReturnValue_6, int32 CallFunc_Array_Add_ReturnValue_7, FGearStatEntry CallFunc_UPGDESC_HitScan_GearStatEntry_2, bool CallFunc_UPGDESC_HitScan_HasAnyUpgrades_2, FGearStatEntry CallFunc_UPGDESC_Damage_GearStatEntry_3, bool CallFunc_UPGDESC_Damage_HasUpgradedValue_3, int32 CallFunc_Array_Add_ReturnValue_8, int32 CallFunc_Array_Add_ReturnValue_9, FGearStatEntry CallFunc_UPGDESC_DamageBonus_TargetStateBonus_GearStatEntry, bool CallFunc_UPGDESC_DamageBonus_TargetStateBonus_HasUpgradedValue, FGearStatEntry CallFunc_UPGDESC_DamageBonus_TargetTypeBonus_GearStatEntry, bool CallFunc_UPGDESC_DamageBonus_TargetTypeBonus_HasUpgradedValue, int32 CallFunc_Array_Add_ReturnValue_10, int32 CallFunc_Array_Add_ReturnValue_11, FGearStatEntry CallFunc_UPGDESC_AmmoDriven_GearStatEntry, bool CallFunc_UPGDESC_AmmoDriven_HasAnyUpgrades, FGearStatEntry CallFunc_UPGDESC_AmmoDriven_GearStatEntry_1, bool CallFunc_UPGDESC_AmmoDriven_HasAnyUpgrades_1, int32 CallFunc_Array_Add_ReturnValue_12, int32 CallFunc_Array_Add_ReturnValue_13, FGearStatEntry CallFunc_UPGDESC_AmmoDriven_GearStatEntry_2, bool CallFunc_UPGDESC_AmmoDriven_HasAnyUpgrades_2, FGearStatEntry CallFunc_UPGDESC_AmmoDriven_GearStatEntry_3, bool CallFunc_UPGDESC_AmmoDriven_HasAnyUpgrades_3, int32 CallFunc_Array_Add_ReturnValue_14, int32 CallFunc_Array_Add_ReturnValue_15);
    void UserConstructionScript();
    void ReceiveBeginPlay();
    void Receive_ReloadBegin();
    void Receive_ReloadEnd();
    void OnSkinChanged(class USkinEffect* Skin);
    void ExecuteUbergraph_WPN_Pistol_A(int32 EntryPoint, class UUserWidget* CallFunc_GetUserWidgetObject_ReturnValue, class UWeaponDisplay_Base_AmmoCount_C* K2Node_DynamicCast_AsWeapon_Display_Base_Ammo_Count, bool K2Node_DynamicCast_bSuccess, bool CallFunc_IsFirstPerson_ReturnValue, class USkinEffect* K2Node_Event_skin);
};

#endif
