#ifndef UE4SS_SDK_WPN_Pickaxe_HPP
#define UE4SS_SDK_WPN_Pickaxe_HPP

class AWPN_Pickaxe_C : public APickaxeItem
{
    FPointerToUberGraphFrame UberGraphFrame;
    class UCrosshairAggregator* CrosshairAggregator;
    float NextHitTime;

    void GetGearStatEntry(class AFSDPlayerState* PlayerState, TArray<FGearStatEntry>& Stats, bool PowerAttack Enabled, TSubclassOf<class AWPN_Pickaxe_C> SelfClass, FGearStatEntry CallFunc_UPGDESC_Damage_GearStatEntry, bool CallFunc_UPGDESC_Damage_HasUpgradedValue, int32 CallFunc_Array_Add_ReturnValue, FGearStatEntry CallFunc_UPGDESC_Damage_GearStatEntry_1, bool CallFunc_UPGDESC_Damage_HasUpgradedValue_1, FGearStatEntry K2Node_MakeStruct_GearStatEntry, int32 CallFunc_Array_Add_ReturnValue_1, FGearStatEntry CallFunc_UPGDESC_Damage_GearStatEntry_2, bool CallFunc_UPGDESC_Damage_HasUpgradedValue_2, int32 CallFunc_Array_Add_ReturnValue_2, FGearStatEntry CallFunc_UPGDESC_Pickaxe_GearStatEntry, bool CallFunc_UPGDESC_Pickaxe_HasUpgradedValue, FGearStatEntry CallFunc_UPGDESC_Pickaxe_GearStatEntry_1, bool CallFunc_UPGDESC_Pickaxe_HasUpgradedValue_1, FGearStatEntry CallFunc_UPGDESC_Pickaxe_GearStatEntry_2, bool CallFunc_UPGDESC_Pickaxe_HasUpgradedValue_2, FGearStatEntry CallFunc_UPGDESC_Pickaxe_GearStatEntry_3, bool CallFunc_UPGDESC_Pickaxe_HasUpgradedValue_3, FGearStatEntry CallFunc_UPGDESC_Damage_GearStatEntry_3, bool CallFunc_UPGDESC_Damage_HasUpgradedValue_3, FGearStatEntry CallFunc_UPGDESC_Damage_GearStatEntry_4, bool CallFunc_UPGDESC_Damage_HasUpgradedValue_4, FGearStatEntry CallFunc_UPGDESC_Pickaxe_GearStatEntry_4, bool CallFunc_UPGDESC_Pickaxe_HasUpgradedValue_4, FGearStatEntry CallFunc_UPGDESC_Damage_GearStatEntry_5, bool CallFunc_UPGDESC_Damage_HasUpgradedValue_5, int32 CallFunc_Array_Add_ReturnValue_3, int32 CallFunc_Array_Add_ReturnValue_4, int32 CallFunc_Array_Add_ReturnValue_5, int32 CallFunc_Array_Add_ReturnValue_6, int32 CallFunc_Array_Add_ReturnValue_7, int32 CallFunc_Array_Add_ReturnValue_8, TSubclassOf<class AWPN_Pickaxe_C> CallFunc_GetObjectClass_ReturnValue, FGearStatEntry CallFunc_UPGDESC_Pickaxe_GearStatEntry_5, bool CallFunc_UPGDESC_Pickaxe_HasUpgradedValue_5, int32 CallFunc_Array_Add_ReturnValue_9, int32 CallFunc_Array_Add_ReturnValue_10);
    void SpecialTargetDamageEffects(const FVector& ImpactPoint, const FVector& ImpactNormal);
    void ReceiveBeginPlay();
    void ExecuteUbergraph_WPN_Pickaxe(int32 EntryPoint, const FVector K2Node_Event_impactPoint, const FVector K2Node_Event_impactNormal, FRotator CallFunc_Conv_VectorToRotator_ReturnValue, class UAudioComponent* CallFunc_SpawnSoundAtLocation_ReturnValue, class UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue, class UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue_1, class UHUD_CrossHair_PickAxe_C* K2Node_DynamicCast_AsHUD_Cross_Hair_Pick_Axe, bool K2Node_DynamicCast_bSuccess);
};

#endif
