#ifndef UE4SS_SDK_WPN_LineCutter_HPP
#define UE4SS_SDK_WPN_LineCutter_HPP

class AWPN_LineCutter_C : public ALineCutter
{
    FPointerToUberGraphFrame UberGraphFrame;
    class UFirstPersonWidgetComponent* Widget_TotalAmmo;
    class UFirstPersonWidgetComponent* Widget_CurrentClip;
    class UFirstPersonParticleSystemComponent* FP_P_Plasma_Beam_Right;
    class UPointLightComponent* MuzzleLight;
    class UPointLightComponent* Line_Light;
    class UFirstPersonParticleSystemComponent* FP_P_Plasma_Beam;
    class UCrosshairAggregator* CrosshairAggregator;
    class UProjectileLauncherComponent* ProjectileLauncher;
    float Flicker_Brightness_Intensity_E04C79F0493C5086E3B612961CA53D93;
    TEnumAsByte<ETimelineDirection::Type> Flicker_Brightness__Direction_E04C79F0493C5086E3B612961CA53D93;
    class UTimelineComponent* Flicker Brightness;
    float DamageFrequency;

    void GetGearStatEntry(class AFSDPlayerState* PlayerState, TArray<FGearStatEntry>& Stats, FText CallFunc_GetUpgradeName_ReturnValue, FText CallFunc_GetUpgradeName_ReturnValue_1, TSubclassOf<class AWPN_LineCutter_C> CallFunc_GetObjectClass_ReturnValue, FGearStatEntry CallFunc_UPGDESC_Generic_GearStatEntry, bool CallFunc_UPGDESC_Generic_HasUpgradedValue, FGearStatEntry CallFunc_UPGDESC_Generic_GearStatEntry_1, bool CallFunc_UPGDESC_Generic_HasUpgradedValue_1, int32 CallFunc_Array_Add_ReturnValue, int32 CallFunc_Array_Add_ReturnValue_1, FText CallFunc_GetUpgradeName_ReturnValue_2, FText CallFunc_GetUpgradeName_ReturnValue_3, FText CallFunc_GetUpgradeName_ReturnValue_4, TSubclassOf<class AWPN_LineCutter_C> CallFunc_GetObjectClass_ReturnValue_1, FGearStatEntry CallFunc_UPGDESC_Generic_GearStatEntry_2, bool CallFunc_UPGDESC_Generic_HasUpgradedValue_2, FGearStatEntry CallFunc_UPGDESC_Generic_GearStatEntry_3, bool CallFunc_UPGDESC_Generic_HasUpgradedValue_3, int32 CallFunc_Array_Add_ReturnValue_2, int32 CallFunc_Array_Add_ReturnValue_3, FGearStatEntry CallFunc_UPGDESC_Generic_GearStatEntry_4, bool CallFunc_UPGDESC_Generic_HasUpgradedValue_4, FGearStatEntry CallFunc_UPGDESC_LineCutterProjectile_GearStatEntry, bool CallFunc_UPGDESC_LineCutterProjectile_HasUpgradedValue, int32 CallFunc_Array_Add_ReturnValue_4, FGearStatEntry CallFunc_UPGDESC_LineCutterProjectile_GearStatEntry_1, bool CallFunc_UPGDESC_LineCutterProjectile_HasUpgradedValue_1, FGearStatEntry CallFunc_UPGDESC_LineCutterProjectile_GearStatEntry_2, bool CallFunc_UPGDESC_LineCutterProjectile_HasUpgradedValue_2, FGearStatEntry CallFunc_UPGDESC_LineCutterProjectile_GearStatEntry_3, bool CallFunc_UPGDESC_LineCutterProjectile_HasUpgradedValue_3, FGearStatEntry CallFunc_UPGDESC_LineCutterProjectile_GearStatEntry_4, bool CallFunc_UPGDESC_LineCutterProjectile_HasUpgradedValue_4, int32 CallFunc_Array_Add_ReturnValue_5, int32 CallFunc_Array_Add_ReturnValue_6, int32 CallFunc_Array_Add_ReturnValue_7, int32 CallFunc_Array_Add_ReturnValue_8, int32 CallFunc_Array_Add_ReturnValue_9, TSubclassOf<class AWPN_LineCutter_C> CallFunc_GetObjectClass_ReturnValue_2, FGearStatEntry CallFunc_UPGDESC_AmmoDriven_GearStatEntry, bool CallFunc_UPGDESC_AmmoDriven_HasAnyUpgrades, FGearStatEntry CallFunc_UPGDESC_AmmoDriven_GearStatEntry_1, bool CallFunc_UPGDESC_AmmoDriven_HasAnyUpgrades_1, FGearStatEntry CallFunc_UPGDESC_AmmoDriven_GearStatEntry_2, bool CallFunc_UPGDESC_AmmoDriven_HasAnyUpgrades_2, FGearStatEntry CallFunc_UPGDESC_AmmoDriven_GearStatEntry_3, bool CallFunc_UPGDESC_AmmoDriven_HasAnyUpgrades_3, int32 CallFunc_Array_Add_ReturnValue_10, int32 CallFunc_Array_Add_ReturnValue_11, int32 CallFunc_Array_Add_ReturnValue_12, int32 CallFunc_Array_Add_ReturnValue_13, TSubclassOf<class AWPN_LineCutter_C> CallFunc_GetObjectClass_ReturnValue_3, class UProjectileLauncherComponent* CallFunc_GetComponentFromClass_ReturnValue, FGearStatEntry CallFunc_UPGDESC_Damage_GearStatEntry, bool CallFunc_UPGDESC_Damage_HasUpgradedValue, TSubclassOf<class ALineCutterProjectile> K2Node_ClassDynamicCast_AsLine_Cutter_Projectile, bool K2Node_ClassDynamicCast_bSuccess, int32 CallFunc_Array_Add_ReturnValue_14, FGearStatEntry CallFunc_UPGDESC_DPS_GearStatEntry, bool CallFunc_UPGDESC_DPS_HasUpgradedValue, FGearStatEntry CallFunc_UPGDESC_Projectile_GearStatEntry, bool CallFunc_UPGDESC_Projectile_HasUpgradedValue, int32 CallFunc_Array_Add_ReturnValue_15, int32 CallFunc_Array_Add_ReturnValue_16, FGearStatEntry CallFunc_UPGDESC_Damage_GearStatEntry_1, bool CallFunc_UPGDESC_Damage_HasUpgradedValue_1, FGearStatEntry CallFunc_UPGDESC_Damage_GearStatEntry_2, bool CallFunc_UPGDESC_Damage_HasUpgradedValue_2, int32 CallFunc_Array_Add_ReturnValue_17, int32 CallFunc_Array_Add_ReturnValue_18);
    void UserConstructionScript();
    void Flicker Brightness__FinishedFunc();
    void Flicker Brightness__UpdateFunc();
    void ReceiveBeginPlay();
    void OnFireWhileLastProjectileAlive(class ALineCutterProjectile* Projectile);
    void ExecuteUbergraph_WPN_LineCutter(int32 EntryPoint, class ALineCutterProjectile* K2Node_Event_projectile, class APRJ_LineCutter2_C* K2Node_DynamicCast_AsPRJ_Line_Cutter_2, bool K2Node_DynamicCast_bSuccess, float CallFunc_Multiply_FloatFloat_ReturnValue, class UUserWidget* CallFunc_GetUserWidgetObject_ReturnValue, class UWeaponDisplay_Base_AmmoCount_C* K2Node_DynamicCast_AsWeapon_Display_Base_Ammo_Count, bool K2Node_DynamicCast_bSuccess_1, class UUserWidget* CallFunc_GetUserWidgetObject_ReturnValue_1, class UWeaponDisplay_Base_AmmoCount_C* K2Node_DynamicCast_AsWeapon_Display_Base_Ammo_Count_1, bool K2Node_DynamicCast_bSuccess_2);
};

#endif
