#ifndef UE4SS_SDK__SCREEN_MissionSelectionMK3_HPP
#define UE4SS_SDK__SCREEN_MissionSelectionMK3_HPP

class U_SCREEN_MissionSelectionMK3_C : UWindowWidget
{
    FPointerToUberGraphFrame UberGraphFrame;
    UAnimatedStaticOverlay_WithScanlines_C* AnimatedStaticOverlay_WithScanlines;
    UBasic_ButtonScalable2_C* BTN_Close;
    UBasic_ButtonScalable2_C* BTN_Join;
    UBasic_ButtonScalable2_C* BTN_ServerList;
    UCanvasPanel* CanvasPanel_PannerOuter;
    UImage* ImageAsteroids01;
    UImage* ImageAsteroids02;
    UImage* ImageClouds01;
    UImage* ImageClouds02;
    UITM_MisSel_Biome_C* ITEM_Biome_AzureWeald;
    UITM_MisSel_Biome_C* ITEM_Biome_Crystal;
    UITM_MisSel_Biome_C* ITEM_Biome_Dense;
    UITM_MisSel_Biome_C* ITEM_Biome_Fungus;
    UITM_MisSel_Biome_C* ITEM_Biome_Glacial;
    UITM_MisSel_Biome_C* ITEM_Biome_HollowBough;
    UITM_MisSel_Biome_C* ITEM_Biome_Magma;
    UITM_MisSel_Biome_C* ITEM_Biome_Radioactive;
    UITM_MisSel_Biome_C* ITEM_Biome_Salt;
    UITM_MisSel_Biome_C* ITEM_Biome_Sandblasted;
    UITM_MisSel_BG_Planet_C* ITEM_MissionSelection_BG;
    UITM_MisSel_FullBiome_C* ITEM_MissionSelection_FullBiome;
    UITM_MisSel_Timer_C* ITEM_MissionSelection_Timer;
    UITM_CampaignProgress_C* ITM_CampaignProgressMain;
    UITM_Challenge_InfoBox_C* ITM_Challenge_InfoBox;
    UITM_MisSel_ZoneLock_C* ITM_LockZone_2;
    UITM_MisSel_ZoneLock_C* ITM_LockZone_3;
    UITM_MisSel_ZoneLock_C* ITM_LockZone_4;
    ULobby_BarTop_Countdown_C* Lobby_BarTop_Countdown;
    USafeZone* PlatformSafeZone;
    UITM_MisSel_ZoneImage_C* Region_AzureWeald;
    UITM_MisSel_ZoneImage_C* Region_CrystallineCaverns;
    UITM_MisSel_ZoneImage_C* Region_DenseBiozone;
    UITM_MisSel_ZoneImage_C* Region_FungusBogs;
    UITM_MisSel_ZoneImage_C* Region_GlacialStrata;
    UITM_MisSel_ZoneImage_C* Region_HollowBough;
    UITM_MisSel_ZoneImage_C* Region_MagmaCore;
    UITM_MisSel_ZoneImage_C* Region_Radioactive;
    UITM_MisSel_ZoneImage_C* Region_SaltPits;
    UITM_MisSel_ZoneImage_C* Region_Sandblasted;
    UHorizontalBox* SelectionBox_Active;
    UUI_AdvancedLabel_C* UI_AdvancedLabel;
    UUI_PlayerSpeaking_List_C* UI_PlayerSpeaking_List;
    UWND_MisSel_BiomeDescription_C* WINDOW_MissionSelection_BiomeDescription;
    UWND_MisSel_MissionDescription_C* WINDOW_MissionSelection_MissionDescription;
    UWND_MisSel_MissionOptions_C* WINDOW_MissionSelection_MissionOptions;
    UImage* Zone_Outlines;
    UImage* ZoneBorders;
    TArray<UITM_MisSel_Biome_C*> Biomes;
    UITM_MisSel_MissionMapIcon_C* SelectedMissionIcon;
    UITM_MisSel_Biome_C* SelectedBiome;
    TArray<UITM_MisSel_ZoneLock_C*> ZoneLocks;
    TArray<UBiome*> NewBiomes;
    FVector2D CurrPos;
    FVector2D TargetPos;
    bool IsBiomeHovered;
    bool CanParalaxCamera;
    float BiomeHoverStartTime;

    void HighlightChallenges(const TArray<UObject*>& assetReferences, bool ShouldHighlight, USeasonChallenge* challenge, int32 Temp_int_Loop_Counter_Variable, UMissionGenerationManager* CallFunc_GetGameInstanceSubsystem_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, TArray<UGeneratedMission*>& CallFunc_GetAvailableMissions_ReturnValue, int32 Temp_int_Loop_Counter_Variable_1, int32 CallFunc_Add_IntInt_ReturnValue_1, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Array_Index_Variable_1, int32 Temp_int_Loop_Counter_Variable_2, int32 CallFunc_Add_IntInt_ReturnValue_2, int32 Temp_int_Array_Index_Variable_2, UTexture2D* CallFunc_GetIconOutlined_ReturnValue, UTexture2D* CallFunc_GetIconOutlined_ReturnValue_1, int32 Temp_int_Loop_Counter_Variable_3, UObject* CallFunc_Array_Get_Item, UMissionTemplate* K2Node_DynamicCast_AsMission_Template, bool K2Node_DynamicCast_bSuccess, UBiome* K2Node_DynamicCast_AsBiome, bool K2Node_DynamicCast_bSuccess_1, int32 CallFunc_Add_IntInt_ReturnValue_3, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_IsValid_ReturnValue, int32 Temp_int_Array_Index_Variable_3, bool Temp_bool_True_if_break_was_hit_Variable, bool CallFunc_Not_PreBool_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_1, UITM_MisSel_Biome_C* CallFunc_Array_Get_Item_1, bool CallFunc_Less_IntInt_ReturnValue_1, UITM_MisSel_Biome_C* CallFunc_Array_Get_Item_2, int32 CallFunc_Array_Length_ReturnValue_2, bool CallFunc_Less_IntInt_ReturnValue_2, TArray<UGeneratedMission*>& CallFunc_GetMissionsForBiome_Missions, UGeneratedMission* CallFunc_Array_Get_Item_3, bool CallFunc_EqualEqual_ObjectObject_ReturnValue, bool CallFunc_EqualEqual_ObjectObject_ReturnValue_1, int32 CallFunc_Array_Length_ReturnValue_3, bool CallFunc_Less_IntInt_ReturnValue_3, bool CallFunc_BooleanAND_ReturnValue);
    FEventReply OnKeyDown(FGeometry MyGeometry, FKeyEvent InKeyEventbool CallFunc_HandleKeyDown_OutHandled, FEventReply CallFunc_HandleKeyDown_OutReply);
    void ClearServerListMissionRestrictions(UPlayerController* CallFunc_GetPlayerController_ReturnValue, UBP_PlayerController_SpaceRig_C* K2Node_DynamicCast_AsBP_Player_Controller_Space_Rig, bool K2Node_DynamicCast_bSuccess, U_MENU_ServerList_C* K2Node_DynamicCast_As_MENU_Server_List, bool K2Node_DynamicCast_bSuccess_1);
    FEventReply OnMouseButtonUp(FGeometry MyGeometry, const FPointerEvent& MouseEventFEventReply CallFunc_Unhandled_ReturnValue, bool CallFunc_IsBackMenuMouse_ReturnValue, FEventReply CallFunc_Handled_ReturnValue);
    void UpdateMapPan(bool SnapToMouse, float NewLocalVar_1, float SpeedFactor, bool IsMissSelected, FVector2D BG_OriginalOffset, FVector2D MaxPanDistance, float Delta, FVector2D Diff, bool Temp_bool_Variable, FVector2D CallFunc_Multiply_Vector2DFloat_ReturnValue, UCanvasPanelSlot* CallFunc_SlotAsCanvasSlot_ReturnValue, FVector2D CallFunc_Multiply_Vector2DFloat_ReturnValue_1, UCanvasPanelSlot* CallFunc_SlotAsCanvasSlot_ReturnValue_1, FVector2D CallFunc_Multiply_Vector2DFloat_ReturnValue_2, UFSDGameUserSettings* CallFunc_FSDGameUserSettings_ReturnValue, UCanvasPanelSlot* CallFunc_SlotAsCanvasSlot_ReturnValue_2, bool CallFunc_GetShowUIAnimations_ReturnValue, float CallFunc_GetRealTimeSeconds_ReturnValue, float CallFunc_GetRealTimeSeconds_ReturnValue_1, float CallFunc_Subtract_FloatFloat_ReturnValue, float CallFunc_Divide_FloatFloat_ReturnValue, float CallFunc_Subtract_FloatFloat_ReturnValue_1, float CallFunc_Multiply_FloatFloat_ReturnValue, bool CallFunc_GreaterEqual_FloatFloat_ReturnValue, float CallFunc_FClamp_ReturnValue, float CallFunc_SelectFloat_ReturnValue, float CallFunc_SelectFloat_ReturnValue_1, bool CallFunc_IsValid_ReturnValue, FVector2D CallFunc_Subtract_Vector2DVector2D_ReturnValue, FVector2D CallFunc_Multiply_Vector2DFloat_ReturnValue_3, float CallFunc_BreakVector2D_X, float CallFunc_BreakVector2D_Y, FVector2D CallFunc_Add_Vector2DVector2D_ReturnValue, float CallFunc_BreakVector2D_X_1, float CallFunc_BreakVector2D_Y_1, FMargin K2Node_MakeStruct_Margin, bool CallFunc_IsVisible_ReturnValue, UCanvasPanelSlot* CallFunc_SlotAsCanvasSlot_ReturnValue_3, float CallFunc_VSize2D_ReturnValue, bool CallFunc_LessEqual_FloatFloat_ReturnValue, bool CallFunc_BooleanOR_ReturnValue, FVector2D CallFunc_Normal2D_ReturnValue, FVector2D CallFunc_Multiply_Vector2DFloat_ReturnValue_4, float CallFunc_VSize2D_ReturnValue_1, float CallFunc_Multiply_FloatFloat_ReturnValue_1, FVector2D CallFunc_Add_Vector2DVector2D_ReturnValue_1, float CallFunc_FClamp_ReturnValue_1, FVector2D K2Node_Select_Default, FVector2D CallFunc_Subtract_Vector2DVector2D_ReturnValue_1, FVector2D CallFunc_Multiply_Vector2DFloat_ReturnValue_5, float CallFunc_GetWorldDeltaSeconds_ReturnValue, UCanvasPanelSlot* CallFunc_SlotAsCanvasSlot_ReturnValue_4, float CallFunc_Multiply_FloatFloat_ReturnValue_2, float CallFunc_Multiply_FloatFloat_ReturnValue_3, FVector2D CallFunc_Multiply_Vector2DFloat_ReturnValue_6, FVector2D CallFunc_GetViewportSize_ReturnValue, float CallFunc_BreakVector2D_X_2, float CallFunc_BreakVector2D_Y_2, UCanvasPanelSlot* CallFunc_SlotAsCanvasSlot_ReturnValue_5, UPlayerController* CallFunc_GetPlayerController_ReturnValue, float CallFunc_GetMousePosition_LocationX, float CallFunc_GetMousePosition_LocationY, bool CallFunc_GetMousePosition_ReturnValue, float CallFunc_Divide_FloatFloat_ReturnValue_1, float CallFunc_Divide_FloatFloat_ReturnValue_2, FVector2D CallFunc_MakeVector2D_ReturnValue, FVector2D CallFunc_Subtract_Vector2DFloat_ReturnValue, FVector2D CallFunc_Multiply_Vector2DFloat_ReturnValue_7, FVector2D CallFunc_Multiply_Vector2DFloat_ReturnValue_8, FVector2D CallFunc_ClampAxes2D_ReturnValue, FVector2D CallFunc_Multiply_Vector2DVector2D_ReturnValue);
    void CheckForNewZones(TArray<UBiome*> NewLocalVar_0, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, UITM_MisSel_ZoneLock_C* CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, TArray<UObject*>& K2Node_MakeArray_Array, const TArray<UBiome*>& CallFunc_GetBiomes_ReturnValue, bool CallFunc_CheckItemUINotification_HasNotification);
    void GetAvailableBiomes(TArray<UITM_MisSel_Biome_C*>& AvailableBiomes1, TArray<UITM_MisSel_Biome_C*> AvailableBiomes, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable, bool Temp_bool_True_if_break_was_hit_Variable, int32 Temp_int_Array_Index_Variable_1, bool CallFunc_Not_PreBool_ReturnValue, UMissionGenerationManager* CallFunc_GetGameInstanceSubsystem_ReturnValue, TArray<UGeneratedMission*>& CallFunc_GetAvailableMissions_ReturnValue, UGeneratedMission* CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, int32 Temp_int_Loop_Counter_Variable_1, UITM_MisSel_Biome_C* CallFunc_Array_Get_Item_1, int32 CallFunc_Array_Length_ReturnValue_1, int32 CallFunc_Array_Add_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_EqualEqual_ObjectObject_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue_1, int32 CallFunc_Add_IntInt_ReturnValue_1, bool CallFunc_BooleanAND_ReturnValue);
    void GetMode(uint8& Mode);
    void ShouldEnableQuickJoin(bool& Show, EFSDTargetPlatform Temp_byte_Variable, bool Temp_bool_Variable, bool Temp_bool_Variable_1, bool Temp_bool_Variable_2, bool Temp_bool_Variable_3, bool Temp_bool_Variable_4, EFSDTargetPlatform CallFunc_FSDTargetPlatform_ReturnValue, bool K2Node_Select_Default, bool CallFunc_IsPlayingOffline_ReturnValue, UGameModeBase* CallFunc_GetGameMode_ReturnValue, UFSDGameModeSpaceRig* K2Node_DynamicCast_AsFSDGame_Mode_Space_Rig, bool K2Node_DynamicCast_bSuccess, bool CallFunc_Not_PreBool_ReturnValue, bool CallFunc_BooleanOR_ReturnValue);
    void HandleButtonVisibility(EFSDTargetPlatform Temp_byte_Variable, bool Temp_bool_Variable, bool Temp_bool_Variable_1, bool Temp_bool_Variable_2, bool Temp_bool_Variable_3, bool Temp_bool_Variable_4, EFSDTargetPlatform Temp_byte_Variable_1, bool Temp_bool_Variable_5, bool Temp_bool_Variable_6, bool Temp_bool_Variable_7, bool Temp_bool_Variable_8, bool Temp_bool_Variable_9, bool Temp_bool_Variable_10, ESlateVisibility Temp_byte_Variable_2, ESlateVisibility Temp_byte_Variable_3, EFSDTargetPlatform Temp_byte_Variable_4, ESlateVisibility Temp_byte_Variable_5, ESlateVisibility Temp_byte_Variable_6, ESlateVisibility Temp_byte_Variable_7, ESlateVisibility Temp_byte_Variable_8, ESlateVisibility Temp_byte_Variable_9, bool CallFunc_ShouldEnableQuickJoin_show, EFSDTargetPlatform CallFunc_FSDTargetPlatform_ReturnValue, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue, bool K2Node_Select_Default, EFSDTargetPlatform CallFunc_FSDTargetPlatform_ReturnValue_1, bool K2Node_Select_Default_1, ESlateVisibility K2Node_Select_Default_2, bool CallFunc_BooleanAND_ReturnValue, bool CallFunc_BooleanOR_ReturnValue, ESlateVisibility K2Node_Select_Default_3);
    void GetMission_CheckBiome(UGeneratedMission*& mission, bool CallFunc_IsValid_ReturnValue, bool CallFunc_EqualEqual_ObjectObject_ReturnValue);
    FEventReply OnKeyUp(FGeometry MyGeometry, FKeyEvent InKeyEventFEventReply CallFunc_Handled_ReturnValue, FKey CallFunc_GetKey_ReturnValue, bool CallFunc_EqualEqual_KeyKey_ReturnValue, bool CallFunc_IsCloseOrBackMenu_ReturnValue, FEventReply CallFunc_Unhandled_ReturnValue, FEventReply CallFunc_Handled_ReturnValue_1);
    void GetMission(UGeneratedMission*& mission, bool CallFunc_IsValid_ReturnValue);
    bool IsMissionLocked(UGeneratedMission* missionUBP_PlayerController_SpaceRig_C* CallFunc_GetController_AsBP_Player_Controller_Space_Rig, bool CallFunc_IsLocked_ReturnValue);
    void GetActiveSelectionMode(uint8& NewParam, bool Temp_bool_Variable, uint8 Temp_byte_Variable, uint8 Temp_byte_Variable_1, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue, uint8 K2Node_Select_Default, UGameModeBase* CallFunc_GetGameMode_ReturnValue, UFSDGameModeSpaceRig* K2Node_DynamicCast_AsFSDGame_Mode_Space_Rig, bool K2Node_DynamicCast_bSuccess, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_1, UFSDGameState* CallFunc_GetFSDGameState_ReturnValue, bool CallFunc_HasAuthority_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue);
    void GetController(UBP_PlayerController_SpaceRig_C*& AsBP Player Controller Space Rig, UPlayerController* CallFunc_GetPlayerController_ReturnValue, UBP_PlayerController_SpaceRig_C* K2Node_DynamicCast_AsBP_Player_Controller_Space_Rig, bool K2Node_DynamicCast_bSuccess);
    void GetMissionBiome(UBiome* Biome, UITM_MisSel_Biome_C*& Array Element, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, UITM_MisSel_Biome_C* CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_EqualEqual_ObjectObject_ReturnValue);
    void OnFailure_ED6FBDF64F71976389535788275C482E();
    void OnSuccess_ED6FBDF64F71976389535788275C482E();
    void PreConstruct(bool IsDesignTime);
    void Construct();
    void BndEvt__CheckBox_Solo_K2Node_ComponentBoundEvent_22_OnCheckBoxComponentStateChanged__DelegateSignature(bool bIsChecked);
    void BiomeHovered(UITM_MisSel_Biome_C* Biome);
    void BiomeSelected(UITM_MisSel_Biome_C* Biome);
    void ShowMission();
    void ShowPlanet();
    void MissionHover(UGeneratedMission* mission, bool IsHovering);
    void StartMission();
    void OnStartMission_Event_0();
    void ShowMode(uint8 Mode);
    void Back();
    void ShowServerBrowser();
    void BndEvt__BTN_ServerList_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature();
    void BndEvt__BTN_Close_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature();
    void InputSourceChanged(EFSDInputSource InputSource);
    void OnShown();
    void Tick(FGeometry MyGeometry, float InDeltaTime);
    void MissionSelected(UITM_MisSel_MissionMapIcon_C* mission);
    void StartSoloMission();
    void OnClosed();
    void DifficultyChanged(UDifficultySetting* NewDifficulty, UGeneratedMission* mission);
    void StartupCameraPan();
    void OnStartSoloMission();
    void BndEvt__ITM_Challenge_InfoBox_K2Node_ComponentBoundEvent_1_OnChallengeHovered__DelegateSignature(TArray<UObject*>& assetReferences, bool InHovered, USeasonChallenge* challenge);
    void ExecuteUbergraph__SCREEN_MissionSelectionMK3(int32 EntryPoint, TArray<UObject*>& K2Node_ComponentBoundEvent_assetReferences, bool K2Node_ComponentBoundEvent_InHovered, USeasonChallenge* K2Node_ComponentBoundEvent_challenge, UMissionGenerationManager* CallFunc_GetGameInstanceSubsystem_ReturnValue, TArray<UGeneratedMission*>& CallFunc_GetAvailableMissions_ReturnValue, EmptyOnlineDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate, UMissionGenerationManager* CallFunc_GetGameInstanceSubsystem_ReturnValue_1, int32 Temp_int_Loop_Counter_Variable, TArray<UGeneratedMission*>& CallFunc_GetAvailableMissions_ReturnValue_1, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Array_Index_Variable_1, OnStartSoloMission__DelegateSignature K2Node_CreateDelegate_OutputDelegate_1, EmptyOnlineDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_2, bool K2Node_Event_IsDesignTime, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, UPlayerController* CallFunc_GetPlayerController_ReturnValue, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_1, bool CallFunc_FSDUpdateSessionInfo_ReturnValue, UFSDGameState* CallFunc_GetFSDGameState_ReturnValue, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_2, bool K2Node_ComponentBoundEvent_bIsChecked, bool CallFunc_HasTooManyModsEnabled_ReturnValue, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_3, bool CallFunc_BooleanOR_ReturnValue, UITM_MisSel_Biome_C* K2Node_CustomEvent_Biome_1, bool CallFunc_IsValid_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, UITM_MisSel_Biome_C* K2Node_CustomEvent_Biome, int32 Temp_int_Loop_Counter_Variable_1, UITM_MisSel_Biome_C* CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_1, int32 CallFunc_Array_Length_ReturnValue_1, UITM_MisSel_Biome_C* CallFunc_Array_Get_Item_1, int32 CallFunc_Array_Length_ReturnValue_2, bool CallFunc_Less_IntInt_ReturnValue_1, UGeneratedMission* K2Node_CustomEvent_Mission_2, bool K2Node_CustomEvent_IsHovering, bool CallFunc_IsValid_ReturnValue_2, uint8 K2Node_CustomEvent_Mode, FText CallFunc_GetPassword_Password, bool CallFunc_GetPassword_HasPassword, bool CallFunc_IsFriendsOnly_ReturnValue, FString CallFunc_Conv_TextToString_ReturnValue, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_4, int32 CallFunc_RandomInteger_ReturnValue, UGeneratedMission* CallFunc_GetMission_Mission, int32 Temp_int_Loop_Counter_Variable_2, bool CallFunc_IsValid_ReturnValue_3, bool CallFunc_Less_IntInt_ReturnValue_2, int32 CallFunc_Add_IntInt_ReturnValue_2, UBP_PlayerController_SpaceRig_C* CallFunc_GetController_AsBP_Player_Controller_Space_Rig, UGeneratedMission* CallFunc_GetMission_CheckBiome_Mission, bool CallFunc_IsValid_ReturnValue_4, UFSDGameUserSettings* CallFunc_FSDGameUserSettings_ReturnValue, EFSDInputSource K2Node_CustomEvent_InputSource, EFSDInputSource CallFunc_GetCurrentInputSource_ReturnValue, UWindowManager* CallFunc_GetWindowManager_ReturnValue, UWindowManager* CallFunc_GetWindowManager_ReturnValue_1, bool CallFunc_IsFriendsOnly_ReturnValue_1, int32 Temp_int_Array_Index_Variable_2, UITM_MisSel_Biome_C* CallFunc_Array_Get_Item_2, FGeometry K2Node_Event_MyGeometry, float K2Node_Event_InDeltaTime, UITM_MisSel_MissionMapIcon_C* K2Node_CustomEvent_Mission_1, bool CallFunc_IsValid_ReturnValue_5, FLinearColor CallFunc_MenuColorsAndOpacity_OutputColor, FLinearColor CallFunc_MenuColorsAndOpacity_OutputColor_1, UCampaignManager* CallFunc_GetCampaingManager_ReturnValue, UPlayerController* CallFunc_GetOwningPlayer_ReturnValue, UBP_PlayerControllerBase_C* K2Node_DynamicCast_AsBP_Player_Controller_Base, bool K2Node_DynamicCast_bSuccess, UDifficultySetting* K2Node_CustomEvent_NewDifficulty, UGeneratedMission* K2Node_CustomEvent_Mission, UDifficultySetting* CallFunc_GetSelectedDifficulty_ReturnValue, UPlayerController* CallFunc_GetOwningPlayer_ReturnValue_1, UFSDPlayerState* CallFunc_GetOwningFSDPlayerState_ReturnValue, UBP_PlayerControllerBase_C* K2Node_DynamicCast_AsBP_Player_Controller_Base_1, bool K2Node_DynamicCast_bSuccess_1, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_5, UFSDGameModeSpaceRig* CallFunc_GetFSDSRGameMode_ReturnValue, ESlateVisibility Temp_byte_Variable, ESlateVisibility Temp_byte_Variable_1, ESlateVisibility Temp_byte_Variable_2, EFSDInputSource Temp_byte_Variable_3, ESlateVisibility K2Node_Select_Default, OnDifficultyChanged__DelegateSignature K2Node_CreateDelegate_OutputDelegate_3, UGeneratedMission* Temp_object_Variable, bool Temp_bool_Variable, TArray<UITM_MisSel_ZoneLock_C*>& K2Node_MakeArray_Array, bool CallFunc_Array_Contains_ReturnValue, bool CallFunc_IsValid_ReturnValue_6, InputSourceChangedSignature__DelegateSignature K2Node_CreateDelegate_OutputDelegate_4, UGeneratedMission* K2Node_Select_Default_1, OnStartMission__DelegateSignature K2Node_CreateDelegate_OutputDelegate_5, BiomeSelected__DelegateSignature K2Node_CreateDelegate_OutputDelegate_6, bool CallFunc_Not_PreBool_ReturnValue, UWindowManager* CallFunc_GetWindowManager_ReturnValue_2, bool CallFunc_IsTopWindow_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue_1, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_6, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_7, TArray<UITM_MisSel_Biome_C*>& K2Node_MakeArray_Array_1, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_8, int32 CallFunc_GetMaxPublicConnections_ReturnValue, UFSDCreateSessionCallbackProxy* CallFunc_FSDCreateSession_ReturnValue, bool CallFunc_IsValid_ReturnValue_7);
}

#endif
