#ifndef UE4SS_SDK_AIC_Spider_Tank_Boss_HPP
#define UE4SS_SDK_AIC_Spider_Tank_Boss_HPP

class AAIC_Spider_Tank_Boss_C : UAIC_Spider_C
{
    FPointerToUberGraphFrame UberGraphFrame;

    void OnArmorDestroyed(float EnrageDuration);
    void ReceivePossess(APawn* PossessedPawn);
    void ReceiveBeginPlay();
    void StartSpeedModifier();
    void ExecuteUbergraph_AIC_Spider_Tank_Boss(int32 EntryPoint, OnArmorDestroyed__DelegateSignature K2Node_CreateDelegate_OutputDelegate, float K2Node_CustomEvent_EnrageDuration, APawn* K2Node_Event_PossessedPawn, UENE_Spider_Tank_Boss_C* K2Node_DynamicCast_AsENE_Spider_Tank_Boss, bool K2Node_DynamicCast_bSuccess, FName CallFunc_MakeLiteralName_ReturnValue, FName CallFunc_MakeLiteralName_ReturnValue_1, FName CallFunc_MakeLiteralName_ReturnValue_2, APawn* CallFunc_K2_GetPawn_ReturnValue, USpiderEnemy* K2Node_DynamicCast_AsSpider_Enemy, bool K2Node_DynamicCast_bSuccess_1, UFSDGameState* CallFunc_GetFSDGameState_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, UFSDGameMode* CallFunc_GetFSDGameMode_ReturnValue, bool CallFunc_LessEqual_IntInt_ReturnValue, UDifficultyManager* CallFunc_GetDifficultyManager_ReturnValue, float CallFunc_GetBossDifficultyScaler_ReturnValue, APawn* CallFunc_K2_GetPawn_ReturnValue_1, float CallFunc_Multiply_FloatFloat_ReturnValue, USpiderEnemy* K2Node_DynamicCast_AsSpider_Enemy_1, bool K2Node_DynamicCast_bSuccess_2, float CallFunc_Subtract_FloatFloat_ReturnValue, int32 CallFunc_AddModifier_ReturnValue, UFSDGameMode* CallFunc_GetFSDGameMode_ReturnValue_1, UDifficultyManager* CallFunc_GetDifficultyManager_ReturnValue_1, float CallFunc_GetBossDifficultyScaler_ReturnValue_1, float CallFunc_Multiply_FloatFloat_ReturnValue_1, float CallFunc_Subtract_FloatFloat_ReturnValue_1, int32 CallFunc_AddModifier_ReturnValue_1);
}

#endif
