#ifndef UE4SS_SDK_BP_CrystalFormations_SlantedPillars_03_Small_HPP
#define UE4SS_SDK_BP_CrystalFormations_SlantedPillars_03_Small_HPP

class ABP_CrystalFormations_SlantedPillars_03_Small_C : ABP_CrystalFormations_SlantedPillars_Base_C
{
}

#endif
