#ifndef UE4SS_SDK_BP_CrystalFormation_SpikyBunch_04_HPP
#define UE4SS_SDK_BP_CrystalFormation_SpikyBunch_04_HPP

class ABP_CrystalFormation_SpikyBunch_04_C : ABP_CrystalFormationsSpikyBunch_Base_C
{
}

#endif
