#ifndef UE4SS_SDK_BP_CaretakerMortarAction_HPP
#define UE4SS_SDK_BP_CaretakerMortarAction_HPP

class UBP_CaretakerMortarAction_C : UBP_CaretakerActionBase_C
{
    FPointerToUberGraphFrame UberGraphFrame;
    int32 BurstCount;
    float TimeBetweenShots;
    int32 BaseBurstSize;
    FTransform Origin;
    FName LastSelectedSocket;
    FVector LastSelectedTargetLocation;
    APlayerCharacter* LastSelectedTarget;
    int32 ExtraBurstSizePerAditionalPlayer;

    void GetEstimatedStartDuration(float& StartDuration, int32 CallFunc_GetNumAdditionalPlayers_ReturnValue, int32 CallFunc_Multiply_IntInt_ReturnValue, UFSDGameMode* CallFunc_GetFSDGameMode_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, UDifficultyManager* CallFunc_GetDifficultyManager_ReturnValue, float CallFunc_Multiply_IntFloat_ReturnValue, float CallFunc_GetBossDifficultyScaler_ReturnValue, float CallFunc_Multiply_FloatFloat_ReturnValue, float CallFunc_Multiply_FloatFloat_ReturnValue_1, float CallFunc_Add_FloatFloat_ReturnValue);
    void LaunchProjectile(FVector TargetLocation, FVector SpawnLocation, FTransform CallFunc_MakeTransform_ReturnValue, AActor* CallFunc_GetOwner_ReturnValue, AActor* CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue, APawn* K2Node_DynamicCast_AsPawn, bool K2Node_DynamicCast_bSuccess, ABP_PhaseBomb_C* CallFunc_FinishSpawningActor_ReturnValue);
    void OnStarted();
    void FireMortar();
    void OnTriggered();
    void OnStopped();
    void FireBurst();
    void All_ShowPhaseBombLaunch(FName AttachPointName);
    void ExecuteUbergraph_BP_CaretakerMortarAction(int32 EntryPoint, UFSDGameMode* CallFunc_GetFSDGameMode_ReturnValue, UDifficultyManager* CallFunc_GetDifficultyManager_ReturnValue, float CallFunc_GetBossDifficultyScaler_ReturnValue, ADeepCSGWorld* CallFunc_GetCSGWorld_ReturnValue, float CallFunc_RandomFloatInRange_ReturnValue, float CallFunc_RandomFloatInRange_ReturnValue_1, AActor* CallFunc_GetOwner_ReturnValue, FVector CallFunc_MakeVector_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue, TArray<UPlayerCharacter*>& CallFunc_GetPlayersInRange_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, UPlayerCharacter* CallFunc_Array_GetRandom_Item, bool CallFunc_Greater_IntInt_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue_1, FVector CallFunc_Add_VectorVector_ReturnValue, FCSGRaycastHitInfo CallFunc_Raycast_hitInfo, bool CallFunc_Raycast_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, FName CallFunc_GetClosestPhaseBombSocket_Result, bool Temp_bool_Has_Been_Initd_Variable, int32 Temp_int_Variable, bool Temp_bool_IsClosed_Variable, UCaretaker* CallFunc_GetCaretaker_ReturnValue, UCaretaker* CallFunc_GetCaretaker_ReturnValue_1, bool CallFunc_HasAutority_ReturnValue, UPlayerCharacter* CallFunc_GetLocalPlayerCharacter_ReturnValue, FName K2Node_CustomEvent_AttachPointName, AActor* CallFunc_GetOwner_ReturnValue_1, UFSDGameMode* CallFunc_GetFSDGameMode_ReturnValue_1, UCaretaker* K2Node_DynamicCast_AsCaretaker, bool K2Node_DynamicCast_bSuccess, UDifficultyManager* CallFunc_GetDifficultyManager_ReturnValue_1, float CallFunc_GetBossDifficultyScaler_ReturnValue_1, UNiagaraComponent* CallFunc_SpawnSystemAttached_ReturnValue, float CallFunc_Multiply_FloatFloat_ReturnValue, UFSDGameMode* CallFunc_GetFSDGameMode_ReturnValue_2, UDifficultyManager* CallFunc_GetDifficultyManager_ReturnValue_2, float CallFunc_GetBossDifficultyScaler_ReturnValue_2, float CallFunc_Subtract_FloatFloat_ReturnValue, AActor* CallFunc_GetOwner_ReturnValue_2, UCaretaker* K2Node_DynamicCast_AsCaretaker_1, bool K2Node_DynamicCast_bSuccess_1, int32 CallFunc_GetNumAdditionalPlayers_ReturnValue, FVector CallFunc_GetSocketLocation_ReturnValue, int32 CallFunc_Multiply_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_1, float CallFunc_Conv_IntToFloat_ReturnValue, int32 CallFunc_Multiply_IntInt_ReturnValue_1, float CallFunc_Divide_FloatFloat_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_2, int32 CallFunc_FCeil_ReturnValue, float CallFunc_Multiply_IntFloat_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, float CallFunc_Multiply_FloatFloat_ReturnValue_1, float CallFunc_Multiply_FloatFloat_ReturnValue_2, UTracerManager* CallFunc_GetWorldSubsystem_ReturnValue, float CallFunc_RandomFloatInRange_ReturnValue_2, float CallFunc_RandomFloatInRange_ReturnValue_3, float CallFunc_Add_FloatFloat_ReturnValue);
}

#endif
