#ifndef UE4SS_SDK_BP_CrystalFormation_SpikyBunch_02_HPP
#define UE4SS_SDK_BP_CrystalFormation_SpikyBunch_02_HPP

class ABP_CrystalFormation_SpikyBunch_02_C : ABP_CrystalFormationsSpikyBunch_Base_C
{
}

#endif
