#ifndef UE4SS_SDK_BP_DiscordConsole_HPP
#define UE4SS_SDK_BP_DiscordConsole_HPP

class ABP_DiscordConsole_C : AActor
{
    FPointerToUberGraphFrame UberGraphFrame;
    UStaticMeshComponent* Cube1;
    UBP_DiscordInstantUsable_C* BP_DiscordInstantUsable;
    UBoxComponent* ProxmityTrigger;
    UWidgetComponent* PSA;
    UBoxComponent* Box;
    UWidgetComponent* Widget;
    USceneComponent* DefaultSceneRoot;
    float LastUpdate;
    bool IsUserIn;
    int32 OverlapCount;
    UConsole_DiscordScreen_C* DiscordConsole;
    ABP_PlayerController_SpaceRig_C* Player;

    void ValidGetPlayer(UBP_PlayerController_SpaceRig_C*& Player, UPlayerController* CallFunc_GetPlayerController_ReturnValue, bool CallFunc_IsValid_ReturnValue, UBP_PlayerController_SpaceRig_C* K2Node_DynamicCast_AsBP_Player_Controller_Space_Rig, bool K2Node_DynamicCast_bSuccess);
    void SetUsable(bool Usable, UBP_PlayerController_SpaceRig_C* CallFunc_ValidGetPlayer_Player, bool CallFunc_IsValid_ReturnValue);
    void Answer(bool Yes);
    void ReceiveBeginPlay();
    void ReceiveTick(float DeltaSeconds);
    void UserIn(bool isInServer);
    void BndEvt__ProxmityTrigger_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult);
    void BndEvt__ProxmityTrigger_K2Node_ComponentBoundEvent_2_ComponentEndOverlapSignature__DelegateSignature(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, int32 OtherBodyIndex);
    void RefreshUsable();
    void OnUsedClient(UBP_PlayerControllerBase_C* User);
    void callRefreshUsable();
    void BndEvt__BP_DiscordInstantUsable_K2Node_ComponentBoundEvent_3_UsedBySignature__DelegateSignature(UPlayerCharacter* User, EInputKeys Key);
    void ExecuteUbergraph_BP_DiscordConsole(int32 EntryPoint, UPresenceSubSystem* CallFunc_GetGameInstanceSubsystem_ReturnValue, bool K2Node_CustomEvent_Yes, FString CallFunc_Conv_IntToString_ReturnValue, UWindowManager* CallFunc_GetWindowManager_ReturnValue, FString CallFunc_Concat_StrStr_ReturnValue, UDiscord_Popup_YesNoPrompt_C* CallFunc_OpenSingleUseWindow_ReturnValue, float K2Node_Event_DeltaSeconds, bool K2Node_CustomEvent_isInServer, float CallFunc_Add_FloatFloat_ReturnValue, UFSDSaveGame* CallFunc_GetFSDSaveGame_ReturnValue, FText CallFunc_MakeLiteralText_ReturnValue, bool CallFunc_RecievedDiscordReward_ReturnValue, FText CallFunc_MakeLiteralText_ReturnValue_1, UFSDSaveGame* CallFunc_GetFSDSaveGame_ReturnValue_1, UFSDSaveGame* CallFunc_GetFSDSaveGame_ReturnValue_2, bool CallFunc_RecievedDiscordReward_ReturnValue_1, OnYesNoClickedDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate, UPrimitiveComponent* K2Node_ComponentBoundEvent_OverlappedComponent_1, AActor* K2Node_ComponentBoundEvent_OtherActor_1, UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp_1, int32 K2Node_ComponentBoundEvent_OtherBodyIndex_1, bool K2Node_ComponentBoundEvent_bFromSweep, const FHitResult K2Node_ComponentBoundEvent_SweepResult, UPlayerCharacter* K2Node_DynamicCast_AsPlayer_Character, bool K2Node_DynamicCast_bSuccess, UPrimitiveComponent* K2Node_ComponentBoundEvent_OverlappedComponent, AActor* K2Node_ComponentBoundEvent_OtherActor, UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp, int32 K2Node_ComponentBoundEvent_OtherBodyIndex, UPlayerCharacter* K2Node_DynamicCast_AsPlayer_Character_1, bool K2Node_DynamicCast_bSuccess_1, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_Greater_FloatFloat_ReturnValue, bool CallFunc_IsVisible_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue, bool CallFunc_IsVisible_ReturnValue_1, bool CallFunc_LessEqual_IntInt_ReturnValue, UGoogleAnalyticsWrapper* CallFunc_GetGoogleAnalyticsWrapper_ReturnValue, bool CallFunc_IsValid_ReturnValue, int32 Temp_int_Variable, UGoogleAnalyticsWrapper* CallFunc_GetGoogleAnalyticsWrapper_ReturnValue_1, UUserWidget* CallFunc_GetUserWidgetObject_ReturnValue, UConsole_DiscordScreen_C* K2Node_DynamicCast_AsConsole_Discord_Screen, bool K2Node_DynamicCast_bSuccess_2, bool CallFunc_IsVisible_ReturnValue_2, bool CallFunc_Not_PreBool_ReturnValue, bool CallFunc_IsVisible_ReturnValue_3, bool CallFunc_BooleanOR_ReturnValue, bool CallFunc_IsVisible_ReturnValue_4, bool CallFunc_IsVisible_ReturnValue_5, bool CallFunc_Greater_IntInt_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue_1, bool CallFunc_BooleanOR_ReturnValue_1, UGoogleAnalyticsWrapper* CallFunc_GetGoogleAnalyticsWrapper_ReturnValue_2, bool CallFunc_IsVisible_ReturnValue_6, int32 Temp_int_Variable_1, OnDiscordUserInServer__DelegateSignature K2Node_CreateDelegate_OutputDelegate_1, UFSDSaveGame* CallFunc_GetFSDSaveGame_ReturnValue_3, int32 CallFunc_AddCredits_ReturnValue, UBP_PlayerControllerBase_C* K2Node_CustomEvent_User, FDiscordRewardNotification K2Node_MakeStruct_DiscordRewardNotification, ScreenChanged__DelegateSignature K2Node_CreateDelegate_OutputDelegate_2, UPlayerController* CallFunc_GetPlayerController_ReturnValue, UPlayerCharacter* K2Node_ComponentBoundEvent_user, EInputKeys K2Node_ComponentBoundEvent_key, UBP_PlayerController_SpaceRig_C* K2Node_DynamicCast_AsBP_Player_Controller_Space_Rig, bool K2Node_DynamicCast_bSuccess_3, UFSDPlayerController* CallFunc_GetPlayerController_ReturnValue_1, UBP_PlayerController_SpaceRig_C* K2Node_DynamicCast_AsBP_Player_Controller_Space_Rig_1, bool K2Node_DynamicCast_bSuccess_4, FText CallFunc_MakeLiteralText_ReturnValue_2, UFSDSaveGame* CallFunc_GetFSDSaveGame_ReturnValue_4, EFSDFaction CallFunc_GetFaction_ReturnValue, FText CallFunc_MakeLiteralText_ReturnValue_3, bool CallFunc_NotEqual_ByteByte_ReturnValue, FText CallFunc_MakeLiteralText_ReturnValue_4, FText CallFunc_MakeLiteralText_ReturnValue_5, UBP_PlayerController_SpaceRig_C* CallFunc_ValidGetPlayer_Player, UPresenceSubSystem* CallFunc_GetGameInstanceSubsystem_ReturnValue_1, bool CallFunc_IsValid_ReturnValue_1, bool CallFunc_IsValid_ReturnValue_2, UPresenceSubSystem* CallFunc_GetGameInstanceSubsystem_ReturnValue_2, bool CallFunc_IsValid_ReturnValue_3, bool CallFunc_IsValid_ReturnValue_4, UPresenceSubSystem* CallFunc_GetGameInstanceSubsystem_ReturnValue_3, UPresenceSubSystem* CallFunc_GetGameInstanceSubsystem_ReturnValue_4, bool CallFunc_RewardReceived_ReturnValue, UPresenceSubSystem* CallFunc_GetGameInstanceSubsystem_ReturnValue_5);
}

#endif
