#ifndef UE4SS_SDK_BP_DropPod_Base_HPP
#define UE4SS_SDK_BP_DropPod_Base_HPP

class ABP_DropPod_Base_C : AMiningPod
{
    FPointerToUberGraphFrame UberGraphFrame;
    UAutoCarverComponent* AutoCarverArm;
    UAudioComponent* Audio_Molly_Loadbeam;
    USkeletalMeshComponent* SK_DropPod_DroneBay;
    USkeletalMeshComponent* SK_DropPod_MuleBay;
    UBoxComponent* Ramp_DwarfDetector;
    UPathfinderCollisionComponent* PathfinderWalkable;
    UPathfinderCollisionComponent* PathfinderBlockerDrill_Walk;
    UPathfinderCollisionComponent* PathfinderBlockerDrill_Block;
    UStaticMeshComponent* Monitor_Right;
    UStaticMeshComponent* Monitor_Left;
    UStaticMeshComponent* DrillBlocker;
    UPointLightComponent* light_filler2;
    UPointLightComponent* light_filler1;
    UChildActorComponent* Widget_RandomCode6;
    UChildActorComponent* Widget_RandomCode5;
    UChildActorComponent* Widget_RandomCode4;
    UChildActorComponent* Widget_RandomCode3;
    UChildActorComponent* Widget_RandomCode1;
    UPointLightComponent* light_readySign1;
    USceneComponent* RedLights;
    UStaticMeshComponent* StaticMesh17;
    UPointLightComponent* light_display4;
    UPointLightComponent* light_display3;
    UStaticMeshComponent* SM_DropPod_ClimbTread;
    UStaticMeshComponent* SM_DropPod_ClimbTread3;
    UStaticMeshComponent* SM_DropPod_ClimbTread2;
    UStaticMeshComponent* SM_DropPod_ClimbTread1;
    USkeletalMeshComponent* OreBox_Left;
    USkeletalMeshComponent* OreBox_Right;
    USkeletalMeshComponent* OreBox_Back;
    UChildActorComponent* BP_TruckerBalls1;
    UChildActorComponent* BP_TruckerBalls;
    UStaticMeshComponent* StaticMesh16;
    UStaticMeshComponent* StaticMesh15;
    UStaticMeshComponent* StaticMesh14;
    UStaticMeshComponent* StaticMesh13;
    UStaticMeshComponent* StaticMesh12;
    UStaticMeshComponent* StaticMesh11;
    UPointLightComponent* PointLight15;
    UPointLightComponent* PointLight14;
    UPointLightComponent* PointLight13;
    UPointLightComponent* PointLight12;
    UPointLightComponent* PointLight11;
    UPointLightComponent* PointLight10;
    UPointLightComponent* PointLight9;
    UPointLightComponent* PointLight8;
    UPointLightComponent* PointLight7;
    UPointLightComponent* PointLight6;
    UPointLightComponent* PointLight5;
    UPointLightComponent* PointLight4;
    UBoxComponent* InSidePodArea;
    UOxygenSourceComponent* OxygenSource;
    UChildActorComponent* Widget_RandomCode2;
    UChildActorComponent* Widget_RandomCode;
    UChildActorComponent* Widget_MissionData;
    UChildActorComponent* Widget_CaveData;
    UChildActorComponent* Widget_DangerLevel2;
    UChildActorComponent* Widget_DangerLevel;
    UChildActorComponent* Widget_ResourceScreen2;
    UChildActorComponent* Widget_ResourceScreen;
    UAudioComponent* AudioCenter;
    UAudioComponent* AudioBack;
    UAudioComponent* AudioFront;
    UAudioComponent* AudioRight;
    UAudioComponent* AudioLeft;
    UAutoCarverComponent* PrettyCarver;
    UChildActorComponent* Widget_CountDown02;
    UChildActorComponent* Widget_CountDown01;
    UTerrainPlacementComponent* terrainPlacement;
    USphereComponent* KillSphere;
    UBoxComponent* DwarfChecker;
    UStaticMeshComponent* StaticMesh6;
    UStaticMeshComponent* StaticMesh10;
    UStaticMeshComponent* StaticMesh9;
    UStaticMeshComponent* StaticMesh8;
    UStaticMeshComponent* StaticMesh7;
    UPathfinderCollisionComponent* PathfinderBlocker;
    UBoxComponent* Box;
    USceneComponent* DonkeyReturnDropPosition;
    USceneComponent* DonkeySpawnPosition;
    USkeletalMeshComponent* Ramp;
    UChildActorComponent* BP_Drop_CamShake;
    UChildActorComponent* Spawn2;
    UChildActorComponent* Spawn1;
    UChildActorComponent* Spawn4;
    USkeletalMeshComponent* SK_DropPod_Drill;
    UWidgetComponent* Widget_SeatMonitorRight;
    UWidgetComponent* Widget_SeatMonitorLeft;
    UPointLightComponent* PointLight1;
    UPointLightComponent* PointLight;
    USceneComponent* floorCollision;
    UStaticMeshComponent* Spot2;
    UStaticMeshComponent* Spot1;
    USceneComponent* hull;
    USceneComponent* seats;
    USceneComponent* lights_interior;
    USkeletalMeshComponent* SK_DropPod_Airlock;
    UChildActorComponent* Spawn3;
    USimpleObjectInfoComponent* SimpleObjectInfo;
    UStaticMeshComponent* StaticMesh5;
    UStaticMeshComponent* StaticMesh4;
    UStaticMeshComponent* StaticMesh3;
    UStaticMeshComponent* StaticMesh2;
    UStaticMeshComponent* StaticMesh1;
    UStaticMeshComponent* StaticMesh;
    UStaticMeshComponent* Cone2;
    USpotLightComponent* SpotLight2;
    USpotLightComponent* SpotLight1;
    UStaticMeshComponent* Cone1;
    UStaticMeshComponent* SM_DropPod_Hull;
    UStaticMeshComponent* SM_DropPod_Hull_NoCol;
    UStaticMeshComponent* Seat_Empty4;
    UStaticMeshComponent* Seat_Empty3;
    UStaticMeshComponent* Seat_Empty2;
    UStaticMeshComponent* Seat_Empty1;
    UPointLightComponent* light_display2;
    UPointLightComponent* light_display1;
    float Timeline_1_LerpDelay_3C91DA044E3AE316CFE9988822F28BC8;
    float Timeline_1_Lerp_3C91DA044E3AE316CFE9988822F28BC8;
    TEnumAsByte<ETimelineDirection::Type> Timeline_1__Direction_3C91DA044E3AE316CFE9988822F28BC8;
    UTimelineComponent* Timeline_1;
    float Timeline_5_LerpDelay_BD4E08A7452DF28657A134A2565D0A25;
    float Timeline_5_Lerp_BD4E08A7452DF28657A134A2565D0A25;
    TEnumAsByte<ETimelineDirection::Type> Timeline_5__Direction_BD4E08A7452DF28657A134A2565D0A25;
    UTimelineComponent* Timeline_5;
    float Timeline_0_RedLightIntensity_2F2B1CD4469260DD2E665FA77E175746;
    TEnumAsByte<ETimelineDirection::Type> Timeline_0__Direction_2F2B1CD4469260DD2E665FA77E175746;
    UTimelineComponent* Timeline_0;
    float light_readysign_intensity;
    UAudioComponent* DrillSound;
    AMULE* MuleInstance;
    FTransform MuleTransform;
    bool MuleSequenceComplete;
    bool OpenDoorsOnLanding;
    bool UnloadMule;
    FTimerHandle CarverRotationTimer;
    bool ShouldTurnOnHeadlight;
    bool CanControlHeadlight;
    TEnumAsByte<DroppodDoorState::Type> DoorState;
    UMaterialInstanceDynamic* LightFlickerMaterial;
    UParticleSystemComponent* MulebayParticle;
    FBP_DropPod_Base_CDoorStateChanged DoorStateChanged;
    void DoorStateChanged(uint8 DoorState);
    FTransform MuleUnloadTransform;
    bool MuleBayOpen;
    FBP_DropPod_Base_COnMuleBayOpenedDispatch OnMuleBayOpenedDispatch;
    void OnMuleBayOpenedDispatch();
    TArray<AMULE*> MulesToCollect;
    bool CarvingComplete;
    bool MuleWasLoaded;

    void OnRep_MuleSequenceComplete();
    void CollectMule(UMULE* MULE, int32 CallFunc_Array_AddUnique_ReturnValue, bool CallFunc_IsValid_ReturnValue, bool CallFunc_HasAuthority_ReturnValue);
    void OnRep_MuleUnloadTransform();
    void GetMuleUnloadTarget(UMULE*& MULE, FTransform& RelativeTransform, USceneComponent* CallFunc_K2_GetRootComponent_ReturnValue, FVector CallFunc_GetActorForwardVector_ReturnValue, FTransform CallFunc_K2_GetComponentToWorld_ReturnValue, FVector CallFunc_GetActorUpVector_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue, FVector CallFunc_Multiply_VectorFloat_ReturnValue, const TArray<AActor*>& Temp_object_Variable, FVector CallFunc_Add_VectorVector_ReturnValue, FHitResult CallFunc_SphereTraceSingle_OutHit, bool CallFunc_SphereTraceSingle_ReturnValue, bool CallFunc_BreakHitResult_bBlockingHit, bool CallFunc_BreakHitResult_bInitialOverlap, float CallFunc_BreakHitResult_Time, float CallFunc_BreakHitResult_Distance, FVector CallFunc_BreakHitResult_Location, FVector CallFunc_BreakHitResult_ImpactPoint, FVector CallFunc_BreakHitResult_Normal, FVector CallFunc_BreakHitResult_ImpactNormal, UPhysicalMaterial* CallFunc_BreakHitResult_PhysMat, AActor* CallFunc_BreakHitResult_HitActor, UPrimitiveComponent* CallFunc_BreakHitResult_HitComponent, FName CallFunc_BreakHitResult_HitBoneName, int32 CallFunc_BreakHitResult_HitItem, int32 CallFunc_BreakHitResult_FaceIndex, FVector CallFunc_BreakHitResult_TraceStart, FVector CallFunc_BreakHitResult_TraceEnd, bool Temp_bool_Variable, const FVector K2Node_Select_Default, FVector CallFunc_FindNearestPathfinderPoint_ReturnValue, FQuat CallFunc_CalcPathfinderOrientation_ReturnValue, FRotator CallFunc_QuatToRotator_ReturnValue, FTransform CallFunc_MakeTransform_ReturnValue, FTransform CallFunc_ConvertTransformToRelative_ReturnValue);
    void EnableMulebay();
    void OnRep_DoorState();
    float OperateMuleBay(bool OpenUAnimMontage*& Montage, UAnimMontage* Temp_object_Variable, UAnimMontage* Temp_object_Variable_1, bool Temp_bool_Variable, UAnimMontage* K2Node_Select_Default, UAnimInstance* CallFunc_GetAnimInstance_ReturnValue, float CallFunc_Montage_Play_ReturnValue);
    bool AnyPlayersOnRamp(TArray<AActor*>& CallFunc_GetOverlappingActors_OverlappingActors, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Greater_IntInt_ReturnValue);
    void HandleRampPhotosensitivity(UFSDGameUserSettings* CallFunc_GetFSDGameUserSettings_ReturnValue, bool CallFunc_GetPhotosensitiveMode_ReturnValue);
    void SetPathBlockersEnabled(bool Enable);
    void DestroyIfClose(TArray<AActor*>& Actors, float DistanceSQ, int32 CallFunc_Array_Length_ReturnValue, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, AActor* CallFunc_Array_Get_Item, FVector CallFunc_K2_GetActorLocation_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue_1, FVector CallFunc_Subtract_VectorVector_ReturnValue, float CallFunc_VSizeSquared_ReturnValue, bool CallFunc_Less_FloatFloat_ReturnValue);
    void RemoveDangerousCaveItems(float Distance, float DistanceSQ, float CallFunc_Square_ReturnValue, TArray<ABP_Geyser_Base_C*>& CallFunc_GetAllActorsOfClass_OutActors);
    void SetAllPlayersAnsel(bool Active, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, FString CallFunc_MakeLiteralString_ReturnValue, FString CallFunc_MakeLiteralString_ReturnValue_1, TArray<UBP_PlayerControllerBase_C*>& CallFunc_GetAllActorsOfClass_OutActors, int32 CallFunc_Array_Length_ReturnValue, UBP_PlayerControllerBase_C* CallFunc_Array_Get_Item, FString CallFunc_Conv_IntToString_ReturnValue, FString CallFunc_Concat_StrStr_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_1, int32 CallFunc_Array_Length_ReturnValue_2, bool CallFunc_Less_IntInt_ReturnValue, FString CallFunc_Conv_IntToString_ReturnValue_1, FString CallFunc_Concat_StrStr_ReturnValue_1);
    FVector GetDonkeyReturnPickupLocation(FVector CallFunc_K2_GetComponentLocation_ReturnValue);
    void SetDoorState(uint8 DoorState, bool CallFunc_HasAuthority_ReturnValue);
    void GetCountDown(bool First, ABP_Widget_DropPod_AltitudeMeter_C*& AsBP Count Down Actor, bool Temp_bool_Variable, AActor* K2Node_Select_Default, ABP_Widget_DropPod_AltitudeMeter_C* K2Node_DynamicCast_AsBP_Widget_Drop_Pod_Altitude_Meter, bool K2Node_DynamicCast_bSuccess);
    void OnRep_MuleInstance(bool CallFunc_HasAuthority_ReturnValue, bool CallFunc_IsValid_ReturnValue);
    void OnMuleLoaded();
    void GetMule(UMolly*& Donkey, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue);
    void SetStandingDown(bool IsStandingDown, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, TArray<UPlayerCharacter*>& CallFunc_GetAllActorsOfClass_OutActors, int32 CallFunc_Array_Length_ReturnValue, UPlayerCharacter* CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue);
    void CloseRamp(bool CallFunc_HasAuthority_ReturnValue);
    void OpenRamp(bool CallFunc_HasAuthority_ReturnValue);
    void OnAllPlayersLeftPod();
    void SetPreferredCharacter(UChildActorComponent* Spawn, UPlayerCharacterID* Class, bool CallFunc_IsValid_ReturnValue, UBP_PlayerStart_C* K2Node_DynamicCast_AsBP_Player_Start, bool K2Node_DynamicCast_bSuccess, bool CallFunc_IsValid_ReturnValue_1);
    void UserConstructionScript(ABP_Widget_DropPod_AltitudeMeter_C* K2Node_DynamicCast_AsBP_Widget_Drop_Pod_Altitude_Meter, bool K2Node_DynamicCast_bSuccess);
    void Timeline_5__FinishedFunc();
    void Timeline_5__UpdateFunc();
    void Timeline_1__FinishedFunc();
    void Timeline_1__UpdateFunc();
    void Timeline_0__FinishedFunc();
    void Timeline_0__UpdateFunc();
    void ReceiveBeginPlay();
    void ReceiveActorBeginOverlap(AActor* OtherActor);
    void ReceiveActorEndOverlap(AActor* OtherActor);
    void StartDeparture();
    void OnDroppodImpact();
    void Start Donkey Unload Sequence();
    void Unload Donkey();
    void OnDrillingStarted();
    void Load Donkey(UMULE* MULE);
    void BndEvt__DwarfChecker_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult);
    void BndEvt__DwarfChecker_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, int32 OtherBodyIndex);
    void BndEvt__KillSphere_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult);
    void DrillRotate();
    void OnCharacterEnter(UPlayerCharacter* Character);
    void OnCharacterExit(UPlayerCharacter* Character);
    void SetMuleInstance(UMolly* Donkey);
    void DropPodSetAnsel(bool Active);
    void AllSetAnsel(bool Active);
    void BndEvt__InSidePodArea_K2Node_ComponentBoundEvent_4_ComponentBeginOverlapSignature__DelegateSignature(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult);
    void BndEvt__InSidePodArea_K2Node_ComponentBoundEvent_5_ComponentEndOverlapSignature__DelegateSignature(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, int32 OtherBodyIndex);
    void MakeTruckerDicesMove();
    void OnRep_RampState();
    void OnFirstPlayerLeftPod();
    void ReceiveDestroyed();
    void OnRepDoorState();
    void LowerMuleToGround();
    void OpenMuleBay();
    void OnMuleBayOpenedDispatch_Event_0();
    void OnGeneratedMissionChanged(UGeneratedMission* OutGeneratedMission);
    void ExecuteUbergraph_BP_DropPod_Base(int32 EntryPoint, bool CallFunc_HasAuthority_ReturnValue, uint8 Temp_byte_Variable, bool Temp_bool_Variable, bool CallFunc_HasAuthority_ReturnValue_1, bool CallFunc_HasAuthority_ReturnValue_2, bool CallFunc_HasAuthority_ReturnValue_3, bool CallFunc_HasAuthority_ReturnValue_4, bool CallFunc_HasAuthority_ReturnValue_5, TimerDynamicDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate, bool CallFunc_HasAuthority_ReturnValue_6, FTimerHandle CallFunc_K2_SetTimerDelegate_ReturnValue, AActor* K2Node_Event_OtherActor_1, AActor* K2Node_Event_OtherActor, UPlayerCharacter* K2Node_DynamicCast_AsPlayer_Character, bool K2Node_DynamicCast_bSuccess, UPlayerCharacter* K2Node_DynamicCast_AsPlayer_Character_1, bool K2Node_DynamicCast_bSuccess_1, bool CallFunc_IsLocallyControlled_ReturnValue, bool CallFunc_HasAuthority_ReturnValue_7, UAudioComponent* CallFunc_SpawnSoundAttached_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue_1, UAudioComponent* CallFunc_SpawnSoundAtLocation_ReturnValue, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue, FTransform CallFunc_K2_GetComponentToWorld_ReturnValue, UMULE* K2Node_CustomEvent_Mule, USceneComponent* CallFunc_K2_GetRootComponent_ReturnValue, USceneComponent* CallFunc_K2_GetRootComponent_ReturnValue_1, FTransform CallFunc_GetRelativeTransform_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue_2, FVector CallFunc_GetSocketLocation_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue_3, UPrimitiveComponent* K2Node_ComponentBoundEvent_OverlappedComponent_4, AActor* K2Node_ComponentBoundEvent_OtherActor_4, UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp_4, int32 K2Node_ComponentBoundEvent_OtherBodyIndex_4, bool K2Node_ComponentBoundEvent_bFromSweep_2, const FHitResult K2Node_ComponentBoundEvent_SweepResult_2, UPrimitiveComponent* K2Node_ComponentBoundEvent_OverlappedComponent_3, AActor* K2Node_ComponentBoundEvent_OtherActor_3, UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp_3, int32 K2Node_ComponentBoundEvent_OtherBodyIndex_3, UPlayerCharacter* K2Node_DynamicCast_AsPlayer_Character_2, bool K2Node_DynamicCast_bSuccess_2, UPlayerCharacter* K2Node_DynamicCast_AsPlayer_Character_3, bool K2Node_DynamicCast_bSuccess_3, UPrimitiveComponent* K2Node_ComponentBoundEvent_OverlappedComponent_2, AActor* K2Node_ComponentBoundEvent_OtherActor_2, UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp_2, int32 K2Node_ComponentBoundEvent_OtherBodyIndex_2, bool K2Node_ComponentBoundEvent_bFromSweep_1, const FHitResult K2Node_ComponentBoundEvent_SweepResult_1, bool CallFunc_IsValid_ReturnValue, UPipelineSegment* K2Node_DynamicCast_AsPipeline_Segment, bool K2Node_DynamicCast_bSuccess_4, UHealthComponentBase* CallFunc_GetComponentByClass_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, UPlayerHealthComponent* K2Node_DynamicCast_AsPlayer_Health_Component, bool K2Node_DynamicCast_bSuccess_5, bool CallFunc_IsValid_ReturnValue_2, FHitResult CallFunc_K2_AddRelativeRotation_SweepHitResult, UPlayerCharacter* K2Node_CustomEvent_character_1, UPlayerCharacter* K2Node_CustomEvent_character, bool CallFunc_IsLocallyControlled_ReturnValue_1, UFSDGameState* CallFunc_GetFSDGameState_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue_4, FVector CallFunc_Add_VectorVector_ReturnValue, bool CallFunc_IsValid_ReturnValue_3, FTransform CallFunc_MakeTransform_ReturnValue, UMolly* K2Node_Event_donkey, bool K2Node_CustomEvent_Active_1, bool K2Node_CustomEvent_Active, bool Temp_bool_IsClosed_Variable, UPlayerController* CallFunc_GetPlayerController_ReturnValue, UPrimitiveComponent* K2Node_ComponentBoundEvent_OverlappedComponent_1, AActor* K2Node_ComponentBoundEvent_OtherActor_1, UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp_1, int32 K2Node_ComponentBoundEvent_OtherBodyIndex_1, bool K2Node_ComponentBoundEvent_bFromSweep, const FHitResult K2Node_ComponentBoundEvent_SweepResult, UBP_PlayerControllerBase_C* K2Node_DynamicCast_AsBP_Player_Controller_Base, bool K2Node_DynamicCast_bSuccess_6, UPrimitiveComponent* K2Node_ComponentBoundEvent_OverlappedComponent, AActor* K2Node_ComponentBoundEvent_OtherActor, UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp, int32 K2Node_ComponentBoundEvent_OtherBodyIndex, bool CallFunc_TryPushActiveStatusEffect_ReturnValue, bool CallFunc_TryPopActiveStatusEffect_ReturnValue, bool Temp_bool_Has_Been_Initd_Variable, float CallFunc_RandomFloatInRange_ReturnValue, FVector CallFunc_MakeVector_ReturnValue, ABP_TruckerBalls_C* K2Node_DynamicCast_AsBP_Trucker_Balls, bool K2Node_DynamicCast_bSuccess_7, ABP_TruckerBalls_C* K2Node_DynamicCast_AsBP_Trucker_Balls_1, bool K2Node_DynamicCast_bSuccess_8, float CallFunc_RandomFloatInRange_ReturnValue_1, FVector CallFunc_MakeVector_ReturnValue_1, bool CallFunc_EqualEqual_ByteByte_ReturnValue, uint8 Temp_byte_Variable_1, UFSDGameMode* CallFunc_GetFSDGameMode_ReturnValue, TSubclassOf<UMolly> CallFunc_GetMuleClass_ReturnValue, uint8 K2Node_Select_Default, AActor* CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue, UMolly* CallFunc_FinishSpawningActor_ReturnValue, bool CallFunc_IsValidClass_ReturnValue, TArray<AActor*>& CallFunc_GetOverlappingActors_OverlappingActors, bool Temp_bool_IsClosed_Variable_1, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_EqualEqual_IntInt_ReturnValue, float CallFunc_OperateMuleBay_ReturnValue, UAnimMontage* CallFunc_OperateMuleBay_Montage, FVector CallFunc_GetSocketLocation_ReturnValue_1, float CallFunc_OperateMuleBay_ReturnValue_1, UAnimMontage* CallFunc_OperateMuleBay_Montage_1, bool CallFunc_IsValid_ReturnValue_4, FVector CallFunc_BreakTransform_Location, FRotator CallFunc_BreakTransform_Rotation, FVector CallFunc_BreakTransform_Scale, USceneComponent* CallFunc_K2_GetRootComponent_ReturnValue_2, FTransform CallFunc_GetMuleUnloadTarget_RelativeTransform, bool Temp_bool_Whether_the_gate_is_currently_open_or_close_Variable, bool Temp_bool_Has_Been_Initd_Variable_1, FVector CallFunc_BreakTransform_Location_1, FRotator CallFunc_BreakTransform_Rotation_1, FVector CallFunc_BreakTransform_Scale_1, USceneComponent* CallFunc_K2_GetRootComponent_ReturnValue_3, FVector CallFunc_Vector_One_ReturnValue, float CallFunc_OperateMuleBay_ReturnValue_2, UAnimMontage* CallFunc_OperateMuleBay_Montage_2, bool Temp_bool_IsClosed_Variable_2, bool Temp_bool_Has_Been_Initd_Variable_2, GeneratedMissionSignature__DelegateSignature K2Node_CreateDelegate_OutputDelegate_1, UParticleSystemComponent* CallFunc_SpawnEmitterAttached_ReturnValue, UParticleSystemComponent* CallFunc_SpawnEmitterAttached_ReturnValue_1, UMULE* CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue_1, bool CallFunc_Greater_IntInt_ReturnValue, bool CallFunc_IsValid_ReturnValue_5, bool CallFunc_Not_PreBool_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, OnMuleBayOpenedDispatch__DelegateSignature K2Node_CreateDelegate_OutputDelegate_2, FVector CallFunc_BreakTransform_Location_2, FRotator CallFunc_BreakTransform_Rotation_2, FVector CallFunc_BreakTransform_Scale_2, float CallFunc_BreakVector_X, float CallFunc_BreakVector_Y, float CallFunc_BreakVector_Z, float CallFunc_Ease_ReturnValue, FVector CallFunc_VEase_ReturnValue, FRotator CallFunc_REase_ReturnValue, float CallFunc_BreakVector_X_1, float CallFunc_BreakVector_Y_1, float CallFunc_BreakVector_Z_1, FVector CallFunc_MakeVector_ReturnValue_2, FTransform CallFunc_MakeTransform_ReturnValue_1, FVector CallFunc_MakeVector_ReturnValue_3, FHitResult CallFunc_K2_SetRelativeTransform_SweepHitResult, bool Temp_bool_Has_Been_Initd_Variable_3, UFSDGameUserSettings* CallFunc_GetFSDGameUserSettings_ReturnValue, bool CallFunc_GetPhotosensitiveMode_ReturnValue, bool CallFunc_IsValid_ReturnValue_6, UMaterialInstanceDynamic* CallFunc_CreateDynamicMaterialInstance_ReturnValue, float CallFunc_Multiply_FloatFloat_ReturnValue, ABP_Widget_DropPod_AltitudeMeter_C* CallFunc_GetCountDown_AsBP_Count_Down_Actor, ABP_Widget_DropPod_AltitudeMeter_C* CallFunc_GetCountDown_AsBP_Count_Down_Actor_1, FLinearColor K2Node_MakeStruct_LinearColor, FLinearColor K2Node_MakeStruct_LinearColor_1, bool Temp_bool_IsClosed_Variable_3, FVector CallFunc_VEase_ReturnValue_1, FRotator CallFunc_REase_ReturnValue_1, UGeneratedMission* K2Node_CustomEvent_OutGeneratedMission, FTransform CallFunc_MakeTransform_ReturnValue_2, bool CallFunc_IsValid_ReturnValue_7, FHitResult CallFunc_K2_SetRelativeTransform_SweepHitResult_1, bool CallFunc_IsDeepDive_ReturnValue, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_1);
    void OnMuleBayOpenedDispatch__DelegateSignature();
    void DoorStateChanged__DelegateSignature(uint8 DoorState);
}

#endif
