#ifndef UE4SS_SDK_BP_EscortDestination_HPP
#define UE4SS_SDK_BP_EscortDestination_HPP

class ABP_EscortDestination_C : AEscortDestination
{
    FPointerToUberGraphFrame UberGraphFrame;
    UBP_Extractor_Shell_C* Layer3Break3_Shell3;
    UBP_Extractor_Shell_C* Layer3Break3_Shell2;
    UBP_Extractor_Shell_C* Layer3Break3_Shell1;
    UBP_Extractor_Shell_C* Layer3Break2_Shell2;
    UBP_Extractor_Shell_C* Layer3Break2_Shell1;
    UStaticMeshComponent* Layer3Break2;
    UStaticMeshComponent* Layer3Break1;
    UBP_Extractor_Shell_C* OuterBreak4_Shell4;
    UBP_Extractor_Shell_C* OuterBreak4_Shell3;
    UBP_Extractor_Shell_C* OuterBreak4_Shell2;
    UBP_Extractor_Shell_C* OuterBreak4_Shell1;
    UBP_Extractor_Shell_C* OuterBreak3_Shell3;
    UBP_Extractor_Shell_C* OuterBreak3_Shell2;
    UBP_Extractor_Shell_C* OuterBreak3_Shell1;
    UBP_Extractor_Shell_C* OuterBreak2_Shell3;
    UBP_Extractor_Shell_C* OuterBreak2_Shell2;
    UBP_Extractor_Shell_C* OuterBreak2_Shell1;
    UStaticMeshComponent* OuterBreak3;
    UStaticMeshComponent* OuterBreak2;
    UStaticMeshComponent* OuterBreak1;
    UAudioComponent* FlyingRocksEnergyLinkLoop;
    UBillboardComponent* BeamerSpawnLocation_9;
    UBillboardComponent* BeamerSpawnLocation_5;
    UBillboardComponent* BeamerSpawnLocation_10;
    UChildActorComponent* BP_Heartstone_Claw_04;
    USceneComponent* BeamersR;
    UBillboardComponent* BeamerSpawnLocation_7;
    UBillboardComponent* BeamerSpawnLocation_8;
    UBillboardComponent* BeamerSpawnLocation_2;
    UBillboardComponent* BeamerSpawnLocation_4;
    UBillboardComponent* BeamerSpawnLocation_12;
    UBillboardComponent* BeamerSpawnLocation_3;
    USphereComponent* Sphere12;
    USphereComponent* Sphere10;
    USphereComponent* Sphere9;
    USphereComponent* Sphere8;
    USphereComponent* Sphere7;
    USphereComponent* Sphere5;
    USphereComponent* Sphere4;
    USphereComponent* Sphere3;
    USphereComponent* Sphere2;
    USceneComponent* BeamersL;
    UParticleSystemComponent* P_Heartstone_AmbientDust;
    UParticleSystemComponent* P_CaveFX_heartstoneHangingDust;
    UStaticMeshComponent* Cone3;
    USpotLightComponent* SpotLight3;
    UPointLightComponent* PointLight3;
    USceneComponent* SpotlightCenter;
    UBillboardComponent* Check_24;
    UBillboardComponent* Check_23;
    UBillboardComponent* Check_22;
    UBillboardComponent* Check_21;
    UBillboardComponent* Check_20;
    UBillboardComponent* Check_19;
    UBillboardComponent* Check_18;
    UBillboardComponent* Check_17;
    UBillboardComponent* Check_16;
    UBillboardComponent* Check_15;
    UBillboardComponent* Check_14;
    UBillboardComponent* Check_13;
    UBillboardComponent* Check_12;
    UBillboardComponent* Check_11;
    UBillboardComponent* Check_10;
    UBillboardComponent* Check_9;
    UBillboardComponent* Check_8;
    UBillboardComponent* Check_7;
    UBillboardComponent* Check_6;
    UBillboardComponent* Check_5;
    UBillboardComponent* Check_4;
    UBillboardComponent* Check_3;
    UBillboardComponent* Check_2;
    UBillboardComponent* Check_1;
    USceneComponent* PlatformChecks;
    UBillboardComponent* AoE_Origin;
    UDamageComponent* GroundSlamDamage;
    UTerrainScannerStaticMesh* TerrainScannerStaticMesh;
    ULevelGenerationDebris* LevelGenerationDebris_Ring_02;
    ULevelGenerationCarverComponent* 1_LevelGenerationCarver_Floor;
    ULevelGenerationCarverComponent* 2_LevelGeneration_CleanCarver;
    UStaticMeshComponent* GunTower_Carver01;
    USceneComponent* ArenaCarvers;
    UStaticMeshComponent* CleanCraterCarver;
    USimpleObjectInfoComponent* SimpleObjectInfo;
    UChildActorComponent* BP_Heartstone_Claw_07;
    UChildActorComponent* BP_Heartstone_Claw_08;
    UChildActorComponent* BP_Heartstone_Claw_06;
    UChildActorComponent* BP_Heartstone_Claw_02;
    USceneComponent* Spikes;
    USpawnActorWithDebrisPosComponent* LaserClawDebrisPos;
    ULevelGenerationDebris* LevelGenerationDebris_Ring_01;
    ULevelGenerationDebris* LevelGenerationDebris_CORE;
    UStaticMeshComponent* Layer1Broken;
    UStaticMeshComponent* Layer1;
    UStaticMeshComponent* Layer2Broken;
    UStaticMeshComponent* Layer2;
    UStaticMeshComponent* Layer3Broken;
    UStaticMeshComponent* Layer3;
    UStaticMeshComponent* Layer4Broken;
    UStaticMeshComponent* Layer4;
    USceneComponent* HeartstoneMeshes;
    UPathfinderCollisionComponent* PathfinderCollision;
    UPointLightComponent* PointLight;
    USceneComponent* Rings;
    ULevelGenerationDebris* LevelGenerationDebris_MultipleRings;
    USceneComponent* GemSpawnPos;
    UTerrainPlacementComponent* terrainPlacement;
    USceneComponent* DefaultSceneRoot;
    int32 Stage;
    UEscortObjective* EscortObj;
    int32 SmarkRockSpawnGroups;
    UEWC_Escort_EndDefense_C* WaveController_FinalFight;
    int32 SmartRockSpawnIndex;
    float SmartRockGropuDelay;
    TArray<ABP_Heartstone_DefensiveCrystal_C*> DefensiveCrystals;
    bool IsMainCrystalWave;
    float LaserClawSpawnRadius;
    TArray<FVector> ForbiddenBeamerLocations;
    TArray<USceneComponent*> BeamerLocationsL;
    TArray<USceneComponent*> BeamerLocationsR;
    int32 BeamerIndexL;
    int32 BeamerIndexR;
    bool LRBeamerToggle;
    int32 NumActiveFlyingRocks;
    int32 OuterShellMiniBreakStage;
    float prevBreakPoint;
    TArray<FVector> SpawnPoints;

    void Update Shell Break Sub Stage(bool K2Node_SwitchInteger_CmpSuccess);
    void OnRep_OuterShellMiniBreakStage(TimerDynamicDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate, FTimerHandle CallFunc_K2_SetTimerDelegate_ReturnValue);
    void OnRep_Stage();
    void ReleaseShellCustom(UBP_Extractor_Shell_C* Shell);
    void OnRep_NumActiveFlyingRocks(UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue, bool CallFunc_IsPlaying_ReturnValue, bool CallFunc_IsPlaying_ReturnValue_1, FString CallFunc_Conv_IntToString_ReturnValue, bool CallFunc_GreaterEqual_IntInt_ReturnValue, FString CallFunc_Concat_StrStr_ReturnValue);
    void UserConstructionScript();
    void ReceiveBeginPlay();
    void DrillingComplete();
    void CountdownTimeChanged(float Progress);
    void NewStage();
    void SpawnRocks(int32 SpawnCountPerGroup, int32 NumGroups);
    void GrowLaserClaws();
    void DoBrokenShellEffects();
    void OnObjectiveUpdated(UObjective* Objective);
    void RegisterCrystal(ABP_Heartstone_DefensiveCrystal_C* Crystal);
    void DoAoEPush();
    void CheckForEngPlatofrms();
    void MoreLaserClaws();
    void TurnOffBrokenSHellEmissive();
    void OnPickedUp_Event_0();
    void TurnSpotOff();
    void SpawnBeamer();
    void DisableAllBeamers();
    void RegisterFlyingRock();
    void DeRegisterFlyingRock();
    void Spawn Group();
    void ExecuteUbergraph_BP_EscortDestination(int32 EntryPoint, FVector CallFunc_K2_GetActorLocation_ReturnValue, bool Temp_bool_Has_Been_Initd_Variable, int32 Temp_int_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Variable_1, CarriableEvent__DelegateSignature K2Node_CreateDelegate_OutputDelegate, int32 CallFunc_Add_IntInt_ReturnValue_1, bool CallFunc_HasAuthority_ReturnValue, int32 Temp_int_Variable_2, bool CallFunc_HasAuthority_ReturnValue_1, int32 Temp_int_Variable_3, int32 CallFunc_Add_IntInt_ReturnValue_2, bool Temp_bool_Variable, bool CallFunc_HasAuthority_ReturnValue_2, bool CallFunc_HasAuthority_ReturnValue_3, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue_3, int32 Temp_int_Array_Index_Variable, bool CallFunc_HasAuthority_ReturnValue_4, bool Temp_bool_Has_Been_Initd_Variable_1, bool Temp_bool_IsClosed_Variable, bool Temp_bool_Variable_1, bool CallFunc_HasAuthority_ReturnValue_5, ObjectiveUpdatedSignature__DelegateSignature K2Node_CreateDelegate_OutputDelegate_1, bool CallFunc_HasAuthority_ReturnValue_6, bool Temp_bool_Variable_2, UFSDGameState* CallFunc_GetFSDGameState_ReturnValue, bool CallFunc_HasAuthority_ReturnValue_7, bool CallFunc_IsValid_ReturnValue, UObjective* CallFunc_GetPrimaryObjective_ReturnValue, UFSDGameState* CallFunc_GetFSDGameState_ReturnValue_1, UEscortObjective* K2Node_DynamicCast_AsEscort_Objective, bool K2Node_DynamicCast_bSuccess, FVector CallFunc_K2_GetActorLocation_ReturnValue_1, float K2Node_CustomEvent_progress, ShellBreakTimerSignature__DelegateSignature K2Node_CreateDelegate_OutputDelegate_2, FTransform CallFunc_K2_GetComponentToWorld_ReturnValue, AActor* CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue, UBP_EscortGem_Heartstone_C* CallFunc_FinishSpawningActor_ReturnValue, bool K2Node_SwitchInteger_CmpSuccess, bool Temp_bool_IsClosed_Variable_1, FVector CallFunc_K2_GetActorLocation_ReturnValue_2, int32 K2Node_CustomEvent_SpawnCountPerGroup, int32 K2Node_CustomEvent_NumGroups, float CallFunc_Multiply_IntFloat_ReturnValue, TArray<FVector>& CallFunc_GetSpawnPointsInCircle_ReturnValue, int32 CallFunc_FTrunc_ReturnValue, int32 Temp_int_Array_Index_Variable_1, bool CallFunc_Greater_IntInt_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue, UFSDGameState* CallFunc_GetFSDGameState_ReturnValue_2, bool CallFunc_HasAuthority_ReturnValue_8, int32 CallFunc_Array_Length_ReturnValue, UFSDGameState* CallFunc_GetFSDGameState_ReturnValue_3, bool CallFunc_LessEqual_IntInt_ReturnValue, UObjective* CallFunc_GetPrimaryObjective_ReturnValue_1, UEscortObjective* K2Node_DynamicCast_AsEscort_Objective_1, bool K2Node_DynamicCast_bSuccess_1, int32 K2Node_Select_Default, UObjective* K2Node_CustomEvent_Objective, bool K2Node_SwitchEnum_CmpSuccess, float CallFunc_RandomFloatInRange_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, float CallFunc_Multiply_FloatFloat_ReturnValue, UFSDGameState* CallFunc_GetFSDGameState_ReturnValue_4, bool CallFunc_IsValid_ReturnValue_2, int32 CallFunc_Array_Length_ReturnValue_1, bool CallFunc_LessEqual_IntInt_ReturnValue_1, float K2Node_Select_Default_1, bool CallFunc_IsValid_ReturnValue_3, float CallFunc_Array_Get_Item, bool CallFunc_GreaterEqual_FloatFloat_ReturnValue, int32 CallFunc_Array_Find_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_4, float CallFunc_Array_Get_Item_1, FVector CallFunc_K2_GetActorLocation_ReturnValue_3, bool CallFunc_Array_IsValidIndex_ReturnValue, bool Temp_bool_Variable_3, FVector CallFunc_K2_GetActorLocation_ReturnValue_4, int32 Temp_int_Array_Index_Variable_2, int32 CallFunc_Add_IntInt_ReturnValue_5, FVector CallFunc_K2_GetActorLocation_ReturnValue_5, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue_1, ABP_Heartstone_DefensiveCrystal_C* K2Node_CustomEvent_Crystal, FVector CallFunc_K2_GetActorLocation_ReturnValue_6, int32 CallFunc_Array_AddUnique_ReturnValue, DelegateEvent__DelegateSignature K2Node_CreateDelegate_OutputDelegate_3, ABP_Heartstone_DefensiveCrystal_C* CallFunc_Array_Get_Item_2, bool CallFunc_IsValid_ReturnValue_4, int32 CallFunc_Array_Length_ReturnValue_2, UFSDGameState* CallFunc_GetFSDGameState_ReturnValue_5, int32 Temp_int_Loop_Counter_Variable_1, int32 CallFunc_Array_Length_ReturnValue_3, int32 CallFunc_Add_IntInt_ReturnValue_6, int32 Temp_int_Loop_Counter_Variable_2, ADeepCSGWorld* CallFunc_GetCSGWorld_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_7, FVector CallFunc_K2_GetActorLocation_ReturnValue_7, FVector CallFunc_K2_GetComponentLocation_ReturnValue, FVector CallFunc_K2_GetComponentLocation_ReturnValue_1, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue_2, float CallFunc_MakeLiteralFloat_ReturnValue, TArray<UPlayerCharacter*>& CallFunc_GetPlayersInRange_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue_8, int32 CallFunc_Array_Length_ReturnValue_4, bool CallFunc_Less_IntInt_ReturnValue, ADeepCSGWorld* CallFunc_GetCSGWorld_ReturnValue_1, TArray<USceneComponent*>& CallFunc_GetChildrenComponents_Children, ADeepCSGWorld* CallFunc_GetCSGWorld_ReturnValue_2, USceneComponent* CallFunc_Array_Get_Item_3, int32 CallFunc_Array_Length_ReturnValue_5, FVector CallFunc_K2_GetComponentLocation_ReturnValue_2, bool CallFunc_Less_IntInt_ReturnValue_1, FCSGRaycastHitInfo CallFunc_Raycast_hitInfo, bool CallFunc_Raycast_ReturnValue, UTerrainMaterial* CallFunc_GetTerrainMaterialByHandle_ReturnValue, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue_3, bool CallFunc_EqualEqual_ObjectObject_ReturnValue, bool CallFunc_EqualEqual_ObjectObject_ReturnValue_1, bool CallFunc_EqualEqual_ObjectObject_ReturnValue_2, bool CallFunc_EqualEqual_ObjectObject_ReturnValue_3, bool CallFunc_BooleanOR_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue_9, bool CallFunc_BooleanOR_ReturnValue_1, TArray<FVector>& K2Node_MakeArray_Array, bool CallFunc_BooleanOR_ReturnValue_2, UFSDGameState* CallFunc_GetFSDGameState_ReturnValue_6, int32 K2Node_Select_Default_2, bool CallFunc_Greater_IntInt_ReturnValue_1, int32 CallFunc_Array_Length_ReturnValue_6, float CallFunc_Conv_IntToFloat_ReturnValue, float CallFunc_Divide_FloatFloat_ReturnValue, float CallFunc_Add_FloatFloat_ReturnValue, int32 Temp_int_Variable_4, int32 Temp_int_Array_Index_Variable_3, UPlayerCharacter* CallFunc_Array_Get_Item_4, bool CallFunc_IsValid_ReturnValue_5, FVector CallFunc_K2_GetActorLocation_ReturnValue_10, FVector CallFunc_Subtract_VectorVector_ReturnValue, int32 Temp_int_Variable_5, int32 CallFunc_GetNumMaterials_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue_1, bool CallFunc_LessEqual_IntInt_ReturnValue_2, int32 CallFunc_GetNumMaterials_ReturnValue_1, int32 CallFunc_Subtract_IntInt_ReturnValue_2, bool CallFunc_LessEqual_IntInt_ReturnValue_3, TArray<USceneComponent*>& CallFunc_GetChildrenComponents_Children_1, int32 CallFunc_Array_Length_ReturnValue_7, int32 CallFunc_Subtract_IntInt_ReturnValue_3, AProceduralSetup* CallFunc_GetProceduralSetup_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_8, USceneComponent* CallFunc_Array_Get_Item_5, bool CallFunc_GreaterEqual_IntInt_ReturnValue, FVector CallFunc_K2_GetComponentLocation_ReturnValue_3, TArray<AActor*>& CallFunc_PlaceActors_OutSpawnedActors, bool CallFunc_PlaceActors_ReturnValue, int32 K2Node_Select_Default_3, TArray<USceneComponent*>& CallFunc_GetChildrenComponents_Children_2, int32 CallFunc_Array_Length_ReturnValue_8, int32 CallFunc_Subtract_IntInt_ReturnValue_4, AProceduralSetup* CallFunc_GetProceduralSetup_ReturnValue_1, bool CallFunc_GreaterEqual_IntInt_ReturnValue_1, int32 CallFunc_Add_IntInt_ReturnValue_9, FVector CallFunc_K2_GetActorLocation_ReturnValue_11, bool CallFunc_Not_PreBool_ReturnValue, TArray<FVector>& CallFunc_GetSpawnPointsFromLocation_ReturnValue, UFSDGameState* CallFunc_GetFSDGameState_ReturnValue_7, USceneComponent* CallFunc_Array_Get_Item_6, int32 CallFunc_Array_Length_ReturnValue_9, FVector CallFunc_K2_GetComponentLocation_ReturnValue_4, int32 CallFunc_Add_IntInt_ReturnValue_10, TArray<AActor*>& CallFunc_PlaceActors_OutSpawnedActors_1, bool CallFunc_PlaceActors_ReturnValue_1, bool CallFunc_LessEqual_IntInt_ReturnValue_4, int32 Temp_int_Loop_Counter_Variable_3, bool CallFunc_Less_IntInt_ReturnValue_2, int32 CallFunc_Add_IntInt_ReturnValue_11, TArray<ABP_Heartstone_DefensiveCrystal_C*>& CallFunc_GetAllActorsOfClass_OutActors, ABP_Heartstone_DefensiveCrystal_C* CallFunc_Array_Get_Item_7, int32 CallFunc_Array_Length_ReturnValue_10, bool CallFunc_Less_IntInt_ReturnValue_3, int32 CallFunc_Add_IntInt_ReturnValue_12, int32 CallFunc_Subtract_IntInt_ReturnValue_5, float CallFunc_Divide_FloatFloat_ReturnValue_1, bool K2Node_SwitchInteger_CmpSuccess_1, int32 CallFunc_Add_IntInt_ReturnValue_13, float CallFunc_Conv_IntToFloat_ReturnValue_1, float CallFunc_Multiply_FloatFloat_ReturnValue_1, bool CallFunc_GreaterEqual_FloatFloat_ReturnValue_1, int32 CallFunc_Add_IntInt_ReturnValue_14, FVector CallFunc_K2_GetActorLocation_ReturnValue_12, float CallFunc_Subtract_FloatFloat_ReturnValue, UNiagaraComponent* CallFunc_SpawnSystemAtLocation_ReturnValue, float CallFunc_Divide_FloatFloat_ReturnValue_2, FVector CallFunc_K2_GetActorLocation_ReturnValue_13, FVector CallFunc_K2_GetActorLocation_ReturnValue_14, FVector CallFunc_K2_GetActorLocation_ReturnValue_15, FVector CallFunc_K2_GetActorLocation_ReturnValue_16, UAudioComponent* CallFunc_SpawnSoundAtLocation_ReturnValue, UAudioComponent* CallFunc_SpawnSoundAtLocation_ReturnValue_1, int32 CallFunc_Array_Length_ReturnValue_11, FVector CallFunc_Array_Get_Item_8, float CallFunc_Conv_IntToFloat_ReturnValue_2, float CallFunc_Add_FloatFloat_ReturnValue_1, bool CallFunc_Less_IntInt_ReturnValue_4, float CallFunc_Divide_FloatFloat_ReturnValue_3, float CallFunc_Subtract_FloatFloat_ReturnValue_1, float CallFunc_RandomFloatInRange_ReturnValue_1, int32 Temp_int_Variable_6, int32 CallFunc_Add_IntInt_ReturnValue_15, int32 CallFunc_Add_IntInt_ReturnValue_16, float CallFunc_Conv_IntToFloat_ReturnValue_3, float CallFunc_Multiply_FloatFloat_ReturnValue_2, float CallFunc_Add_FloatFloat_ReturnValue_2, bool CallFunc_IsValid_ReturnValue_6, bool CallFunc_GreaterEqual_FloatFloat_ReturnValue_2, float CallFunc_RandomFloatInRange_ReturnValue_2, UFSDGameMode* CallFunc_GetFSDGameMode_ReturnValue, bool Temp_bool_Variable_4, UEnemyWaveManager* CallFunc_GetWaveManager_ReturnValue, bool CallFunc_IsValid_ReturnValue_7, int32 K2Node_Select_Default_4, UEWC_Escort_EndDefense_C* CallFunc_TriggerWave_ReturnValue, int32 Temp_int_Variable_7, bool CallFunc_Less_IntInt_ReturnValue_5, FVector CallFunc_K2_GetComponentLocation_ReturnValue_5, FVector CallFunc_Subtract_VectorVector_ReturnValue_1, float CallFunc_VSize_ReturnValue, float CallFunc_Divide_FloatFloat_ReturnValue_4, float CallFunc_FMin_ReturnValue, float CallFunc_Subtract_FloatFloat_ReturnValue_2, FVector CallFunc_VLerp_ReturnValue, FVector CallFunc_Normal_ReturnValue, FVector CallFunc_Multiply_VectorFloat_ReturnValue, float CallFunc_BreakVector_X, float CallFunc_BreakVector_Y, float CallFunc_BreakVector_Z, FVector CallFunc_MakeVector_ReturnValue);
}

#endif
