#ifndef UE4SS_SDK_BP_GameInstance_HPP
#define UE4SS_SDK_BP_GameInstance_HPP

class UBP_GameInstance_C : UFSDGameInstance
{
    FPointerToUberGraphFrame UberGraphFrame;
    FBP_GameInstance_COnAvailableCraftingItems OnAvailableCraftingItems;
    void OnAvailableCraftingItems(TArray<InterfaceProperty>& NewItems);
    bool EligibleForRetirementAssignment;
    FBP_GameInstance_COnEligibleForRetirementAssignment OnEligibleForRetirementAssignment;
    void OnEligibleForRetirementAssignment(UBP_GameInstance_C* GameInstance);
    UWND_JoiningPassword_C* JoinFriendInvitePasswordWidget;
    UWND_JoiningModded_C* JoinFriendInviteModdedWidget;
    FBlueprintSessionResult CurrentModdedSession;
    FString CurrentModdedPassword;
    UWND_Joining_C* JoiningFriendInviteWidget;
    UObject* JoinFriendInviteProgressionDisabling;
    FBlueprintSessionResult tmpSetupModdedSession;

    void ResetTempSessions();
    void CreateAndOpenModdedWidget(UWindowManager* CallFunc_GetWindowManager_ReturnValue, bool CallFunc_IsValid_ReturnValue, UPlayerController* CallFunc_GetPlayerController_ReturnValue, UWND_JoiningModded_C* CallFunc_Create_ReturnValue);
    void SetModdedSession(JoinModdedServer__DelegateSignature K2Node_CreateDelegate_OutputDelegate, OnCancel__DelegateSignature K2Node_CreateDelegate_OutputDelegate_1);
    void SetupJoinVanillaDisableProgressionMods(FBlueprintSessionResult Session, FText CallFunc_MakeLiteralText_ReturnValue, FText CallFunc_MakeLiteralText_ReturnValue_1, FText CallFunc_MakeLiteralText_ReturnValue_2, OnCancel__DelegateSignature K2Node_CreateDelegate_OutputDelegate, JoinModdedServer__DelegateSignature K2Node_CreateDelegate_OutputDelegate_1);
    void PromptSandboxUser(FBlueprintSessionResult Session, UWindowManager* CallFunc_GetWindowManager_ReturnValue, UBasic_Popup_YesNoPrompt_C* CallFunc_OpenWindowFromClass_ReturnValue, OnYesNoClickedDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate);
    void ShouldPromptSandboxUser(FBlueprintSessionResult Session, bool& Yes, bool CallFunc_FSDIsModdedSandboxServer_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, UFSDSaveGame* CallFunc_GetFSDSaveGame_ReturnValue, bool CallFunc_GetIsModded_ReturnValue, UUGCRegistry* CallFunc_GetUGCRegistry_ReturnValue, bool CallFunc_AreModsInstalled_ReturnValue, bool CallFunc_IsValid_ReturnValue, bool CallFunc_BooleanOR_ReturnValue);
    void SetupJoinModded(FBlueprintSessionResult Session, UGCLocalUserModsInstalled__DelegateSignature K2Node_CreateDelegate_OutputDelegate, bool CallFunc_ShouldPromptSandboxUser_Yes, UUGCSubsystem* CallFunc_GetEngineSubsystem_ReturnValue, UUGCSubsystem* CallFunc_GetEngineSubsystem_ReturnValue_1, bool CallFunc_IsValid_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, bool CallFunc_BooleanAND_ReturnValue);
    void Setup Join with Password(FBlueprintSessionResult Session, JoinWithPassword__DelegateSignature K2Node_CreateDelegate_OutputDelegate, OnCancel__DelegateSignature K2Node_CreateDelegate_OutputDelegate_1, bool CallFunc_IsValid_ReturnValue);
    void IsEligibleForRetirementAassignment(bool& EligibleForRetirementAssignment);
    void OnFailure_7B3ECFCE46627790F0C9B89A6B449207();
    void OnSuccess_7B3ECFCE46627790F0C9B89A6B449207();
    void OnFailure_7B3ECFCE46627790F0C9B89A0D72085C();
    void OnSuccess_7B3ECFCE46627790F0C9B89A0D72085C();
    void OnFailure_7B3ECFCE46627790F0C9B89A89B12120();
    void OnSuccess_7B3ECFCE46627790F0C9B89A89B12120();
    void OnFailure_D72617F2470A6492F0633884F8A94A97();
    void OnSuccess_D72617F2470A6492F0633884F8A94A97();
    void OnFailure_E6A52403462766A65D96D581DEE58F2A();
    void OnSuccess_E6A52403462766A65D96D581DEE58F2A();
    void OnFailure_3F92037B4548E12D6DF3A4A0C91F55FB();
    void OnSuccess_3F92037B4548E12D6DF3A4A0C91F55FB();
    void ReceiveInit();
    void JoinFriendInvite(FBlueprintSessionResult Session);
    void OnLoadComplete(FString MapName);
    void SetEligableForRetirementAssignment(bool eligable);
    void JoinFriendInviteWithPassword(FBlueprintSessionResult Session, FString Password);
    void OnCancelJoin();
    void OnJoiningModded(FBlueprintSessionResult Session, FString Password);
    void ModdedSaveLoaded();
    void OnSandboxAnswer(bool Yes);
    void OnSaveLoaded();
    void ExecuteUbergraph_BP_GameInstance(int32 EntryPoint, OnModdedSaveCancelled__DelegateSignature K2Node_CreateDelegate_OutputDelegate, EmptyOnlineDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_1, UPopup_ModdedSave_C* CallFunc_Create_ReturnValue, OnModdedSaveLoaded__DelegateSignature K2Node_CreateDelegate_OutputDelegate_2, EmptyOnlineDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_3, UWindowManager* CallFunc_GetWindowManager_ReturnValue, UPlayerController* CallFunc_GetPlayerController_ReturnValue, UMessagingSubSystem* CallFunc_GetGameInstanceSubsystem_ReturnValue, UWND_Joining_C* CallFunc_Create_ReturnValue_1, OnModdedSaveLoaded__DelegateSignature K2Node_CreateDelegate_OutputDelegate_4, UMessagingSubSystem* CallFunc_GetGameInstanceSubsystem_ReturnValue_1, UPlayerController* CallFunc_GetPlayerController_ReturnValue_1, UPlayerController* CallFunc_GetPlayerController_ReturnValue_2, EmptyOnlineDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_5, UWindowManager* CallFunc_GetWindowManager_ReturnValue_1, UPlayerController* CallFunc_GetPlayerController_ReturnValue_3, UWND_Joining_C* CallFunc_Create_ReturnValue_2, EmptyOnlineDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_6, UPlayerController* CallFunc_GetPlayerController_ReturnValue_4, EmptyOnlineDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_7, UWindowManager* CallFunc_GetWindowManager_ReturnValue_2, UPlayerController* CallFunc_GetPlayerController_ReturnValue_5, UWND_Joining_C* CallFunc_Create_ReturnValue_3, EmptyOnlineDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_8, bool Temp_bool_Variable, JoinSignature__DelegateSignature K2Node_CreateDelegate_OutputDelegate_9, UUGCRegistry* CallFunc_GetUGCRegistry_ReturnValue, EmptyOnlineDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_10, bool CallFunc_IsValid_ReturnValue, UFSDSaveGame* CallFunc_GetFSDSaveGame_ReturnValue, bool CallFunc_GetIsModded_ReturnValue, UUGCRegistry* CallFunc_GetUGCRegistry_ReturnValue_1, UUGCRegistry* CallFunc_GetUGCRegistry_ReturnValue_2, bool CallFunc_AreModsInstalled_ReturnValue, bool CallFunc_AreModsInstalled_ReturnValue_1, bool CallFunc_BooleanOR_ReturnValue, bool Temp_bool_Variable_1, bool Temp_bool_Variable_2, bool Temp_bool_Variable_3, EFSDTargetPlatform CallFunc_FSDTargetPlatform_ReturnValue, UFSDGameUserSettings* CallFunc_FSDGameUserSettings_ReturnValue, FBlueprintSessionResult K2Node_CustomEvent_Session_2, bool CallFunc_FSDIsPasswordRequired_ReturnValue, bool CallFunc_FSDIsModdedServer_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, UPlayerController* CallFunc_GetPlayerController_ReturnValue_6, bool CallFunc_IsInActiveSession_ReturnValue, UDestroySessionCallbackProxy* CallFunc_DestroySession_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, FString K2Node_Event_MapName, bool CallFunc_EndsWith_ReturnValue, EmptyOnlineDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_11, bool K2Node_Event_eligable, bool Temp_bool_Variable_4, bool CallFunc_NotEqual_BoolBool_ReturnValue, UPlayerController* CallFunc_GetPlayerController_ReturnValue_7, EFSDTargetPlatform Temp_byte_Variable, UFSDJoinSessionCallbackProxy* CallFunc_FSDJoinSession_ReturnValue, bool K2Node_Select_Default, bool CallFunc_IsValid_ReturnValue_2, FBlueprintSessionResult K2Node_CustomEvent_Session_1, FString K2Node_CustomEvent_Password_1, UFSDJoinSessionCallbackProxy* CallFunc_FSDJoinSession_ReturnValue_1, bool CallFunc_FSDIsSessionValid_ReturnValue, bool CallFunc_IsValid_ReturnValue_3, UUGCSubsystem* CallFunc_GetEngineSubsystem_ReturnValue, bool CallFunc_IsValid_ReturnValue_4, bool CallFunc_Not_PreBool_ReturnValue_1, UMessagingSubSystem* CallFunc_GetGameInstanceSubsystem_ReturnValue_2, FBlueprintSessionResult K2Node_CustomEvent_Session, FString K2Node_CustomEvent_Password, EmptyOnlineDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_12, UWindowManager* CallFunc_GetWindowManager_ReturnValue_3, UPopup_ModdedSave_C* CallFunc_OpenSingleUseWindow_ReturnValue, bool CallFunc_FSDIsSessionValid_ReturnValue_1, UFSDJoinSessionCallbackProxy* CallFunc_FSDJoinSession_ReturnValue_2, bool CallFunc_FSDIsSessionValid_ReturnValue_2, bool CallFunc_IsValid_ReturnValue_5, UFSDJoinSessionCallbackProxy* CallFunc_FSDJoinSession_ReturnValue_3, bool CallFunc_IsValid_ReturnValue_6, EmptyOnlineDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_13, UWindowManager* CallFunc_GetWindowManager_ReturnValue_4, UWindowWidget* CallFunc_GetCurrentWindow_ReturnValue, UWND_Joining_C* K2Node_DynamicCast_AsWND_Joining, bool K2Node_DynamicCast_bSuccess, UWindowManager* CallFunc_GetWindowManager_ReturnValue_5, UFSDSaveGame* CallFunc_GetFSDSaveGame_ReturnValue_1, bool CallFunc_GetIsModded_ReturnValue_1, bool CallFunc_FSDIsModdedSandboxServer_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue_2, UPlayerController* CallFunc_GetPlayerController_ReturnValue_8, bool CallFunc_BooleanAND_ReturnValue, UDestroySessionCallbackProxy* CallFunc_DestroySession_ReturnValue_1, bool CallFunc_IsValid_ReturnValue_7, bool K2Node_CustomEvent_Yes, bool CallFunc_Not_PreBool_ReturnValue_3, UWindowManager* CallFunc_GetWindowManager_ReturnValue_6, UMessagingSubSystem* CallFunc_GetGameInstanceSubsystem_ReturnValue_3, EmptyOnlineDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_14, EmptyOnlineDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_15);
    void OnEligibleForRetirementAssignment__DelegateSignature(UBP_GameInstance_C* GameInstance);
    void OnAvailableCraftingItems__DelegateSignature(TArray<InterfaceProperty>& NewItems);
}

#endif
