#ifndef UE4SS_SDK_BP_HackingPod_HPP
#define UE4SS_SDK_BP_HackingPod_HPP

class ABP_HackingPod_C : UFacilityHackingPod
{
    FPointerToUberGraphFrame UberGraphFrame;
    UInstantUsable* PettingUse;
    UStaticMeshComponent* RangeSphere;
    UChildActorComponent* BP_OxygenTankSound;
    UChildActorComponent* BP_OxygenTank1;
    UOxygenSourceComponent* OxygenSource;
    UChildActorComponent* BP_OxygenTank;
    USphereComponent* TriggerOnOffOutline;
    UTerrainScannerStaticMesh* TerrainScannerStaticMesh;
    UBillboardComponent* JunkSpawnPoint;
    UPointLightComponent* PointLight1;
    UPointLightComponent* PointLight3;
    UPointLightComponent* PointLight2;
    UPointLightComponent* PointLight;
    USphereComponent* SaluteTrigger;
    USphereComponent* PettingUseSphere;
    USkeletalMeshComponent* Drill;
    UAudioComponent* HackingPodHackingIdle;
    USimpleObjectInfoComponent* SimpleObjectInfo;
    UPointLightComponent* Light_FanRGB03;
    UPointLightComponent* Light_FanRGB02;
    UPointLightComponent* Light_FanRGB01;
    UCapsuleComponent* BodyCollision;
    UPointLightComponent* Light_Monitor;
    UWidgetComponent* Widget_MonitorTop;
    UWidgetComponent* Widget_MonitorRight;
    UWidgetComponent* Widget_MonitorMiddle;
    UWidgetComponent* Widget_MonitorLeft;
    UWidgetComponent* UseButtonWidget;
    UAutoCarverComponent* AutoCarver;
    UDropToTerrainComponent* DropToTerrain;
    UTerrainDetectComponent* TerrainDetect;
    UTerrainPlacementComponent* terrainPlacement;
    UOutlineComponent* outline;
    UChildActorComponent* DispenserActor;
    USkeletalMeshComponent* Base;
    USingleUsableComponent* ActivateUsable;
    USingleUsableComponent* ReviveUsable;
    UCapsuleComponent* UseCapsule;
    UObjectAttackerPositioning* ObjectAttackerPositioning;
    UFriendlyHealthComponent* FriendlyHealth;
    UTetherComponent* Tether;
    TArray<AActor*> ChildTethers;
    TArray<FLinearColor> Fans_StartColor;
    TArray<FLinearColor> Fans_EndColor;
    TArray<FLinearColor> Fans_ColorArray;
    TArray<FLinearColor> LightColors;
    FTimerHandle ResizeCarverTimer;
    bool IsFacilityMission;
    float OutlineTime;
    float LightMonitorIntensity;
    FBP_HackingPod_COpenChanged OpenChanged;
    void OpenChanged(bool Open);
    bool Open;
    bool HackingStarted;
    bool HackingOver;
    TEnumAsByte<ETetherDispenserState::Type> DispenserState;
    FBP_HackingPod_CStateChanged StateChanged;
    void StateChanged(uint8 State);
    USingleUsableComponent* NewVar_0;
    UParticleSystemComponent* ThrusterParticles;
    UAudioComponent* ThrusterSound;
    TArray<APlayerCharacter*> PlayersInside;
    bool HasActivated;
    UMaterialInstanceDynamic* CornerColors;
    TArray<TSubclassOf<AActor>> JunkActors;
    int32 MaxJunkSpawns;
    bool ShowRange;
    bool ConnectedToGoal;

    bool GetIsTargetable();
    FVector GetTargetCenterMass(FVector CallFunc_K2_GetComponentLocation_ReturnValue);
    UHealthComponentBase* GetTargetHealthComponent();
    void SetShowRange(bool ShowRange, UFSDGameState* CallFunc_GetFSDGameState_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Greater_IntInt_ReturnValue, float CallFunc_SelectFloat_ReturnValue, FVector CallFunc_MakeVector_ReturnValue);
    void UpdatePlayerCount();
    void EnableScreens(bool ScreensActive, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, TArray<UWidgetComponent*>& K2Node_MakeArray_Array, int32 CallFunc_Array_Length_ReturnValue, UWidgetComponent* CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, UUserWidget* CallFunc_GetUserWidgetObject_ReturnValue, UUI_HackingPod_Screen_Base_C* K2Node_DynamicCast_AsUI_Hacking_Pod_Screen_Base, bool K2Node_DynamicCast_bSuccess);
    void FanColorsIntact(bool& FansIntact, bool CallFunc_IsValid_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, bool CallFunc_BooleanAND_ReturnValue, bool CallFunc_IsValid_ReturnValue_2, bool CallFunc_BooleanAND_ReturnValue_1);
    void HackingInProgress(bool& NewParam, EHackingPodState CallFunc_GetState_ReturnValue, bool CallFunc_NotEqual_ByteByte_ReturnValue, bool CallFunc_BooleanAND_ReturnValue);
    void ReconnectTethers(int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, bool Temp_bool_True_if_break_was_hit_Variable, int32 Temp_int_Array_Index_Variable, bool CallFunc_Not_PreBool_ReturnValue, bool Temp_bool_True_if_break_was_hit_Variable_1, bool CallFunc_IsConnected_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue_1, int32 Temp_int_Loop_Counter_Variable_1, int32 Temp_int_Array_Index_Variable_1, int32 CallFunc_Add_IntInt_ReturnValue_1, TArray<UTetherComponent*>& CallFunc_GetConnectionHistory_ReturnValue, UTetherComponent* CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_ConnectToTetherLine_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, TArray<AActor*>& CallFunc_GetIgnoreTethers_ChildTethers, const TArray<uint8>& K2Node_MakeArray_Array, FVector CallFunc_GetConnectionPoint_ReturnValue, TArray<AActor*>& CallFunc_SphereOverlapActors_OutActors, bool CallFunc_SphereOverlapActors_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_1, AActor* CallFunc_Array_Get_Item_1, bool CallFunc_Less_IntInt_ReturnValue_1, UTetherComponent* CallFunc_GetComponentByClass_ReturnValue, bool CallFunc_BooleanAND_ReturnValue_1, bool CallFunc_IsActive_ReturnValue, bool CallFunc_ConnectToTetherLine_ReturnValue_1);
    void GetDispenser(UBP_TetherDispenser_C*& AsBP Tether Dispenser, UBP_TetherDispenser_C* K2Node_DynamicCast_AsBP_Tether_Dispenser, bool K2Node_DynamicCast_bSuccess);
    void GetIgnoreTethers(TArray<AActor*>& ChildTethers, UBP_TetherDispenser_C* K2Node_DynamicCast_AsBP_Tether_Dispenser, bool K2Node_DynamicCast_bSuccess, AActor* CallFunc_GetItem_ReturnValue, int32 CallFunc_Array_Add_ReturnValue);
    void UserConstructionScript(UMaterialInstanceDynamic* CallFunc_CreateDynamicMaterialInstance_ReturnValue);
    void OnTick_4437D92344C73CCB9F96AB832CABCA51(float DeltaTime, float NormalizedTime);
    void Completed_4437D92344C73CCB9F96AB832CABCA51(float DeltaTime, float NormalizedTime);
    void ShowDamageEffects(UParticleSystem* Particles, FVector Location, FRotator Orientation);
    void ReceiveBeginPlay();
    void OnDroppodImpact();
    void BndEvt__Tether_K2Node_ComponentBoundEvent_0_TeherMessage_Delegate__DelegateSignature(const FName& Message);
    void BndEvt__FriendlyHealth_K2Node_ComponentBoundEvent_1_DeathSig__DelegateSignature(UHealthComponentBase* HealthComponent);
    void BndEvt__SingleUsable_K2Node_ComponentBoundEvent_2_UsedBySignature__DelegateSignature(UPlayerCharacter* User, EInputKeys Key);
    void BndEvt__FriendlyHealth_K2Node_ComponentBoundEvent_3_DamageSig__DelegateSignature(float Amount);
    void BndEvt__ActivateUsable_K2Node_ComponentBoundEvent_6_UsedBySignature__DelegateSignature(UPlayerCharacter* User, EInputKeys Key);
    void SetLightColor(int32 Index);
    void BndEvt__DropToTerrain_K2Node_ComponentBoundEvent_7_OnIsFallingToTerrainChanged__DelegateSignature(bool IsFalling);
    void ManageOutlines();
    void OnDropStarted();
    void DeployAnimations();
    void OnDroppodCloseToImpact();
    void ResizeCarver();
    void UpdateUseIcon();
    void BndEvt__ReviveUsable_K2Node_ComponentBoundEvent_0_UsableChangedSignature__DelegateSignature(bool CanUse);
    void StartFanColoring();
    void BndEvt__ActivateUsable_K2Node_ComponentBoundEvent_9_UsableChangedSignature__DelegateSignature(bool CanUse);
    void TakeOff();
    void BndEvt__PettingUsable_K2Node_ComponentBoundEvent_4_UsedBySignature__DelegateSignature(UPlayerCharacter* User, EInputKeys Key);
    void BndEvt__Sphere_K2Node_ComponentBoundEvent_5_ComponentBeginOverlapSignature__DelegateSignature(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult);
    void OnBoscoSalute_Event_0(UPlayerCharacter* ShoutingPlayer);
    void All_Pet();
    void OnEnterState(EHackingPodState NextState);
    void OnExitState(EHackingPodState oldState);
    void BndEvt__TriggerOutline_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult);
    void BndEvt__TriggerOutline_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, int32 OtherBodyIndex);
    void All_PlaySalute(AActor* Saluter);
    void BndEvt__Tether_K2Node_ComponentBoundEvent_12_TetherConnectionChanged_Deletage__DelegateSignature(UTetherComponent* frontConnection, UTetherComponent* backConnection);
    void ItemTaken(AActor* spawnedItem);
    void OnPlayerJoined_Event_0(UFSDPlayerState* PlayerState);
    void OnPlayerLeave_Event_0(UFSDPlayerState* PlayerState);
    void BndEvt__PettingUse_K2Node_ComponentBoundEvent_13_UsedBySignature__DelegateSignature(UPlayerCharacter* User, EInputKeys Key);
    void ExecuteUbergraph_BP_HackingPod(int32 EntryPoint, UPlayerCharacter* K2Node_ComponentBoundEvent_user, EInputKeys K2Node_ComponentBoundEvent_key, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, bool Temp_bool_True_if_break_was_hit_Variable, int32 Temp_int_Array_Index_Variable, bool CallFunc_Not_PreBool_ReturnValue, bool Temp_bool_Has_Been_Initd_Variable, bool Temp_bool_IsClosed_Variable, bool Temp_bool_Has_Been_Initd_Variable_1, bool Temp_bool_Has_Been_Initd_Variable_2, bool Temp_bool_IsClosed_Variable_1, bool Temp_bool_Has_Been_Initd_Variable_3, bool Temp_bool_IsClosed_Variable_2, TimerDynamicDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate, FTimerHandle CallFunc_K2_SetTimerDelegate_ReturnValue, bool Temp_bool_Has_Been_Initd_Variable_4, bool Temp_bool_IsClosed_Variable_3, int32 Temp_int_Variable, int32 CallFunc_Add_IntInt_ReturnValue_1, bool CallFunc_HasAuthority_ReturnValue, UParticleSystem* K2Node_Event_particles, FVector K2Node_Event_location, FRotator K2Node_Event_orientation, UFSDGameMode* CallFunc_GetFSDGameMode_ReturnValue, const FName K2Node_ComponentBoundEvent_message, bool K2Node_SwitchName_CmpSuccess, UObjective* CallFunc_GetPrimaryObjective_ReturnValue, UHealthComponentBase* K2Node_ComponentBoundEvent_HealthComponent, UFacilityObjective* K2Node_DynamicCast_AsFacility_Objective, bool K2Node_DynamicCast_bSuccess, UPlayerCharacter* K2Node_ComponentBoundEvent_user_3, EInputKeys K2Node_ComponentBoundEvent_key_3, FVector CallFunc_K2_GetComponentLocation_ReturnValue, UAudioComponent* CallFunc_SpawnSoundAtLocation_ReturnValue, float Temp_float_Variable, bool CallFunc_HasAuthority_ReturnValue_1, float K2Node_ComponentBoundEvent_Amount, FName CallFunc_MakeLiteralName_ReturnValue, UPlayerCharacter* K2Node_ComponentBoundEvent_user_2, EInputKeys K2Node_ComponentBoundEvent_key_2, FName CallFunc_MakeLiteralName_ReturnValue_1, int32 K2Node_CustomEvent_Index, FLinearColor CallFunc_Array_Get_Item, FTransform CallFunc_MakeTransform_ReturnValue, AActor* CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue, UBP_TetherDispenserBeacon_C* CallFunc_FinishSpawningActor_ReturnValue, bool K2Node_ComponentBoundEvent_IsFalling, bool CallFunc_ConnectToTetherLine_ReturnValue, float Temp_float_Variable_1, UBP_BarrelDispenser_C* K2Node_DynamicCast_AsBP_Barrel_Dispenser, bool K2Node_DynamicCast_bSuccess_1, FVector CallFunc_K2_GetActorLocation_ReturnValue, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue, UAudioComponent* CallFunc_SpawnSoundAtLocation_ReturnValue_1, UAudioComponent* CallFunc_SpawnSoundAttached_ReturnValue, UParticleSystemComponent* CallFunc_SpawnEmitterAttached_ReturnValue, UParticleSystemComponent* CallFunc_SpawnEmitterAttached_ReturnValue_1, bool CallFunc_HasAuthority_ReturnValue_2, TickDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_1, PlayerDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_2, PlayerDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_3, bool CallFunc_K2_IsTimerActiveHandle_ReturnValue, float CallFunc_RandomFloatInRange_ReturnValue, bool CallFunc_HasAuthority_ReturnValue_3, float CallFunc_BreakVector_X, float CallFunc_BreakVector_Y, float CallFunc_BreakVector_Z, FVector CallFunc_MakeVector_ReturnValue, float CallFunc_RandomFloatInRange_ReturnValue_1, FRotator CallFunc_MakeRotator_ReturnValue, FHitResult CallFunc_K2_SetRelativeRotation_SweepHitResult, ItemDispenserDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_4, bool K2Node_ComponentBoundEvent_canUse_1, FLinearColor CallFunc_Array_Get_Item_1, FLinearColor CallFunc_Array_Get_Item_2, TArray<UPointLightComponent*>& K2Node_MakeArray_Array, UPointLightComponent* CallFunc_Array_Get_Item_3, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_IsValid_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, FLinearColor CallFunc_Array_GetRandom_Item, FLinearColor CallFunc_Array_GetRandom_Item_1, FLinearColor CallFunc_Array_GetRandom_Item_2, FLinearColor CallFunc_Array_GetRandom_Item_3, TArray<FLinearColor>& K2Node_MakeArray_Array_1, FLinearColor CallFunc_Array_GetRandom_Item_4, FLinearColor CallFunc_Array_GetRandom_Item_5, TArray<FLinearColor>& K2Node_MakeArray_Array_2, bool CallFunc_BooleanOR_ReturnValue, bool K2Node_ComponentBoundEvent_canUse, EHackingPodState Temp_byte_Variable, UFSDGameMode* CallFunc_GetFSDGameMode_ReturnValue_1, UDifficultyManager* CallFunc_GetDifficultyManager_ReturnValue, float CallFunc_GetPointExtractionScaler_ReturnValue, float CallFunc_Divide_FloatFloat_ReturnValue, bool Temp_bool_IsClosed_Variable_4, bool Temp_bool_Variable, bool CallFunc_IsAlive_ReturnValue, float K2Node_Select_Default, bool CallFunc_HasAuthority_ReturnValue_4, bool CallFunc_HackingInProgress_NewParam, bool CallFunc_HackingInProgress_NewParam_1, float CallFunc_MakeLiteralFloat_ReturnValue, FVector CallFunc_MakeVector_ReturnValue_1, UParticleSystemComponent* CallFunc_SpawnEmitterAttached_ReturnValue_2, UAudioComponent* CallFunc_SpawnSoundAttached_ReturnValue_1, bool CallFunc_FanColorsIntact_FansIntact, bool CallFunc_HasAuthority_ReturnValue_5, EHackingPodState Temp_byte_Variable_1, UPlayerCharacter* K2Node_ComponentBoundEvent_user_1, EInputKeys K2Node_ComponentBoundEvent_key_1, UPrimitiveComponent* K2Node_ComponentBoundEvent_OverlappedComponent_2, AActor* K2Node_ComponentBoundEvent_OtherActor_2, UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp_2, int32 K2Node_ComponentBoundEvent_OtherBodyIndex_2, bool K2Node_ComponentBoundEvent_bFromSweep_1, const FHitResult K2Node_ComponentBoundEvent_SweepResult_1, UAnimInstance* CallFunc_GetAnimInstance_ReturnValue, UPlayerCharacter* K2Node_DynamicCast_AsPlayer_Character, bool K2Node_DynamicCast_bSuccess_2, float CallFunc_PlaySlotAnimation_ReturnValue, UPlayerCharacter* K2Node_CustomEvent_ShoutingPlayer, FVector CallFunc_GetActorGroundLocation_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue_1, float CallFunc_Square_ReturnValue, float CallFunc_Vector_DistanceSquared_ReturnValue, bool CallFunc_Less_FloatFloat_ReturnValue, bool CallFunc_Array_Contains_ReturnValue, int32 CallFunc_Array_Add_ReturnValue, bool Temp_bool_Variable_1, EHackingPodState K2Node_Select_Default_1, EHackingPodState K2Node_Event_nextState, EHackingPodState K2Node_Event_oldState, bool K2Node_SwitchEnum_CmpSuccess, bool K2Node_SwitchEnum_CmpSuccess_1, UBP_TetherDispenser_C* CallFunc_GetDispenser_AsBP_Tether_Dispenser, UBP_TetherDispenser_C* CallFunc_GetDispenser_AsBP_Tether_Dispenser_1, EHackingPodState CallFunc_GetState_ReturnValue, bool CallFunc_EqualEqual_ByteByte_ReturnValue, OnPlayerShoutEvent__DelegateSignature K2Node_CreateDelegate_OutputDelegate_5, bool CallFunc_IsConnected_ReturnValue, EHackingPodState CallFunc_GetState_ReturnValue_1, bool CallFunc_EqualEqual_ByteByte_ReturnValue_1, uint8 Temp_byte_Variable_2, float K2Node_CustomEvent_DeltaTime_1, float K2Node_CustomEvent_NormalizedTime_1, bool CallFunc_HasAuthority_ReturnValue_6, TSubclassOf<AActor> CallFunc_Array_GetRandom_Item_6, int32 CallFunc_Subtract_IntInt_ReturnValue, FTransform CallFunc_K2_GetComponentToWorld_ReturnValue, int32 CallFunc_RandomIntegerInRange_ReturnValue, AActor* CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_1, bool CallFunc_LessEqual_IntInt_ReturnValue, AActor* CallFunc_FinishSpawningActor_ReturnValue_1, bool CallFunc_RandomBoolWithWeight_ReturnValue, EHackingPodState CallFunc_GetState_ReturnValue_2, bool CallFunc_EqualEqual_ByteByte_ReturnValue_2, UPrimitiveComponent* K2Node_ComponentBoundEvent_OverlappedComponent_1, AActor* K2Node_ComponentBoundEvent_OtherActor_1, UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp_1, int32 K2Node_ComponentBoundEvent_OtherBodyIndex_1, bool K2Node_ComponentBoundEvent_bFromSweep, const FHitResult K2Node_ComponentBoundEvent_SweepResult, UPrimitiveComponent* K2Node_ComponentBoundEvent_OverlappedComponent, AActor* K2Node_ComponentBoundEvent_OtherActor, UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp, int32 K2Node_ComponentBoundEvent_OtherBodyIndex, UPlayerCharacter* K2Node_DynamicCast_AsPlayer_Character_1, bool K2Node_DynamicCast_bSuccess_3, UPlayerCharacter* K2Node_DynamicCast_AsPlayer_Character_2, bool K2Node_DynamicCast_bSuccess_4, bool CallFunc_IsLocallyControlled_ReturnValue, bool CallFunc_IsLocallyControlled_ReturnValue_1, bool CallFunc_HasAuthority_ReturnValue_7, bool CallFunc_Not_PreBool_ReturnValue_1, bool CallFunc_BooleanAND_ReturnValue_1, FVector CallFunc_K2_GetComponentLocation_ReturnValue_1, EHackingPodState CallFunc_GetState_ReturnValue_3, bool CallFunc_EqualEqual_ByteByte_ReturnValue_3, UMiniTimerAction* CallFunc_MiniTimer_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, bool CallFunc_IsAlive_ReturnValue_1, float Temp_float_Variable_2, AActor* K2Node_CustomEvent_Saluter, UAnimInstance* CallFunc_GetAnimInstance_ReturnValue_1, EHackingPodState CallFunc_GetState_ReturnValue_4, UFacilityHackingPodAnimInstance* K2Node_DynamicCast_AsFacility_Hacking_Pod_Anim_Instance, bool K2Node_DynamicCast_bSuccess_5, bool CallFunc_EqualEqual_ByteByte_ReturnValue_4, float CallFunc_PlaySlotAnimation_ReturnValue_1, float Temp_float_Variable_3, FLinearColor CallFunc_LinearColorLerp_ReturnValue, float K2Node_CustomEvent_DeltaTime, float K2Node_CustomEvent_NormalizedTime, FVector CallFunc_MakeVector_ReturnValue_2, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue_1, FTransform CallFunc_K2_GetComponentToWorld_ReturnValue_1, UTetherComponent* CallFunc_GetForwardConnection_ReturnValue, AActor* CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_2, bool CallFunc_IsValid_ReturnValue_2, UBP_HackingPodDrillDebris_C* CallFunc_FinishSpawningActor_ReturnValue_2, bool CallFunc_Not_PreBool_ReturnValue_2, UTetherComponent* K2Node_ComponentBoundEvent_frontConnection, UTetherComponent* K2Node_ComponentBoundEvent_backConnection, bool CallFunc_BooleanAND_ReturnValue_2, bool CallFunc_IsValid_ReturnValue_3, bool CallFunc_Not_PreBool_ReturnValue_3, EHackingPodState CallFunc_GetState_ReturnValue_5, bool CallFunc_EqualEqual_ByteByte_ReturnValue_5, TickDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_6, bool CallFunc_BooleanAND_ReturnValue_3, UBP_TetherDispenser_C* CallFunc_GetDispenser_AsBP_Tether_Dispenser_2, AActor* K2Node_CustomEvent_spawnedItem, EHackingPodState CallFunc_GetState_ReturnValue_6, bool CallFunc_EqualEqual_ByteByte_ReturnValue_6, bool CallFunc_Not_PreBool_ReturnValue_4, bool CallFunc_BooleanAND_ReturnValue_4, EHackingPodState CallFunc_GetState_ReturnValue_7, UFSDGameState* CallFunc_GetFSDGameState_ReturnValue, bool CallFunc_NotEqual_ByteByte_ReturnValue, bool CallFunc_IsValid_ReturnValue_4, UFSDPlayerState* K2Node_CustomEvent_PlayerState_1, UFSDPlayerState* K2Node_CustomEvent_PlayerState);
    void StateChanged__DelegateSignature(uint8 State);
    void OpenChanged__DelegateSignature(bool Open);
}

#endif
