#ifndef UE4SS_SDK_BP_MineHead_HPP
#define UE4SS_SDK_BP_MineHead_HPP

class ABP_MineHead_C : UFSDMiningHead
{
    FPointerToUberGraphFrame UberGraphFrame;
    UTerrainScannerStaticMesh* MineHead_ TerrainScanner;
    UPathfinderCollisionComponent* PB_SmallPlatform05;
    UPathfinderCollisionComponent* PB_SmallPlatform04;
    UPathfinderCollisionComponent* PB_SmallPlatform03;
    UPathfinderCollisionComponent* PB_SmallPlatform02;
    UPathfinderCollisionComponent* PB_SmallPlatform01;
    UChildActorComponent* OxygenAudio;
    UChildActorComponent* OxygenTank05;
    UChildActorComponent* OxygenTank04;
    UChildActorComponent* OxygenTank03;
    UChildActorComponent* OxygenTank02;
    UChildActorComponent* OxygenTank01;
    UCapsuleComponent* Capsule;
    UTerrainPlacementComponent* terrainPlacement;
    UPathfinderCollisionComponent* PathfinderCollision_Ramp2_Blocker;
    UPathfinderCollisionComponent* PathfinderCollision_Ramp3_Blocker;
    UPathfinderCollisionComponent* PathfinderCollision_Ramp4_Blocker;
    UPathfinderCollisionComponent* PathfinderCollision_Ramp5_Blocker;
    UPathfinderCollisionComponent* ButtonPlatform_Blocker;
    UPathfinderCollisionComponent* MainPlatform_Blocker;
    UPathfinderCollisionComponent* AIBlockBelow3;
    UPathfinderCollisionComponent* AIBlockBelow2;
    UPathfinderCollisionComponent* AIBlockBelow1;
    UOxygenSourceComponent* OxygenSource;
    USphereComponent* HeatSource;
    UAudioComponent* AudioDepositing;
    UWidgetComponent* ButtonActive_Widget;
    UParticleSystemComponent* P_Minehead_LaunchDust;
    UChildActorComponent* Sentry3;
    UChildActorComponent* Sentry2;
    UChildActorComponent* Sentry1;
    UAudioComponent* GrinderAudio;
    UPathfinderCollisionComponent* AIBlockBelow;
    USpotLightComponent* SpotLight_Rocket;
    USphereComponent* KillSphere;
    UBoxComponent* OpenDepositerBox;
    UCapsuleComponent* ResourceBankUsableCapsule_01;
    USingleUsableComponent* Usable_LaunchRocket;
    USphereComponent* LaunchRocketSphere;
    UPathfinderCollisionComponent* PathfinderCollision_Rocket;
    UPathfinderCollisionComponent* PathfinderCollision_Drill;
    UPathfinderCollisionComponent* PFSmallPlatform05;
    UPathfinderCollisionComponent* PFSmallPlatform04;
    UPathfinderCollisionComponent* PFSmallPlatform03;
    UPathfinderCollisionComponent* PFSmallPlatform02;
    UPathfinderCollisionComponent* PFSmallPlatform01;
    UPathfinderCollisionComponent* MainPlatform;
    UPathfinderCollisionComponent* ButtonPlatform_01;
    UPathfinderCollisionComponent* PathfinderCollision_Ramp2;
    UPathfinderCollisionComponent* PathfinderCollision_Ramp3;
    UPathfinderCollisionComponent* PathfinderCollision_Ramp4;
    UOutlineComponent* outline;
    USimpleObjectInfoComponent* SimpleObjectInfo;
    UActorTrackingComponent* ActorTracking;
    UStaticMeshComponent* StaticMesh2;
    USpotLightComponent* SpotLight1;
    UStaticMeshComponent* StaticMesh3;
    UChildActorComponent* Lights_02;
    UPathfinderCollisionComponent* PathfinderCollision_Ramp5;
    UStaticMeshComponent* StaticMesh1;
    USpotLightComponent* SpotLight;
    UStaticMeshComponent* Light;
    UChildActorComponent* Lights_01;
    UPointLightComponent* PointLight;
    USkeletalMeshComponent* Drill;
    USkeletalMeshComponent* MineHead;
    UAudioComponent* DrillingSoundInstance;
    bool IsLiftingOff;
    bool CanLaunch;
    int32 PlayersInDepositRange;
    UMaterialInstanceDynamic* BlinkingLightsMaterial_Button;
    UMaterialInstanceDynamic* BlinkingLightsMaterial_Pole;
    float BlinkingLightsEmmissive_Button;
    float BlinkingLightsEmmissive_Pole;
    TArray<APlayerCharacter*> DeadPlayers;
    FBP_MineHead_CMinheadStateChanged MinheadStateChanged;
    void MinheadStateChanged(uint8 State);
    TEnumAsByte<Minehead_State::Type> MineheadState;
    UParticleSystemComponent* DrillParticles01;
    UParticleSystemComponent* DrillParticles02;
    ABP_Minehead_LandingZone_C* LandingZoneMarker;
    UAudioComponent* ButtonLaunchSoundInstance;

    void ConditionallyEnableShadows(ADeepCSGWorld* CallFunc_GetCSGWorld_ReturnValue, int32 CallFunc_GetShadowQuality_ReturnValue, bool CallFunc_IsValid_ReturnValue, bool CallFunc_GreaterEqual_IntInt_ReturnValue);
    void OnRep_MineheadState(bool K2Node_SwitchEnum_CmpSuccess);
    void SetState(uint8 MineheadState, bool CallFunc_HasAuthority_ReturnValue);
    void HandleDeadPlayers(int32 Temp_int_Array_Index_Variable, bool CallFunc_HasAuthority_ReturnValue, int32 Temp_int_Loop_Counter_Variable, AActor* CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, FVector CallFunc_GetSocketLocation_ReturnValue, FHitResult CallFunc_K2_SetActorLocation_SweepHitResult, bool CallFunc_K2_SetActorLocation_ReturnValue);
    void OnRep_CanLaunch(UFSDGameUserSettings* CallFunc_GetFSDGameUserSettings_ReturnValue, bool CallFunc_GetPhotosensitiveMode_ReturnValue, FVector CallFunc_K2_GetComponentLocation_ReturnValue, UAudioComponent* CallFunc_SpawnSoundAtLocation_ReturnValue);
    void OnRep_IsLiftingOff();
    void UserConstructionScript(float CallFunc_K2_GetScalarParameterValue_ReturnValue, float CallFunc_K2_GetScalarParameterValue_ReturnValue_1, UMaterialInstanceDynamic* CallFunc_CreateDynamicMaterialInstance_ReturnValue, UMaterialInstanceDynamic* CallFunc_CreateDynamicMaterialInstance_ReturnValue_1);
    void OnDrillingStarted();
    void OnDroppodImpact();
    void ReceiveBeginPlay();
    void OnLiftoff();
    void objectivesCompleted();
    void BndEvt__Usable_LaunchRocket_K2Node_ComponentBoundEvent_0_UsedBySignature__DelegateSignature(UPlayerCharacter* User, EInputKeys Key);
    void BndEvt__OpenDepositerBox_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult);
    void BndEvt__OpenDepositerBox_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, int32 OtherBodyIndex);
    void BndEvt__KillSphere_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult);
    void BndEvt__ResourceBank_K2Node_ComponentBoundEvent_0_ResourceBankEvent__DelegateSignature(UPlayerCharacter* User);
    void BndEvt__ResourceBank_K2Node_ComponentBoundEvent_1_ResourceBankEvent__DelegateSignature(UPlayerCharacter* User);
    void BndEvt__HeatSource_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult);
    void BndEvt__HeatSource_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, int32 OtherBodyIndex);
    void UpdateShadows();
    void BndEvt__Usable_LaunchRocket_K2Node_ComponentBoundEvent_3_UsableChangedSignature__DelegateSignature(bool CanUse);
    void ExecuteUbergraph_BP_MineHead(int32 EntryPoint, bool CallFunc_HasAuthority_ReturnValue, bool CallFunc_IsValid_ReturnValue, int32 Temp_int_Variable, bool CallFunc_EqualEqual_IntInt_ReturnValue, UAudioComponent* CallFunc_SpawnSoundAttached_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, UAudioComponent* CallFunc_SpawnSoundAtLocation_ReturnValue, bool CallFunc_HasAuthority_ReturnValue_1, FVector CallFunc_K2_GetActorLocation_ReturnValue_1, UPlayerCharacter* K2Node_ComponentBoundEvent_user_2, EInputKeys K2Node_ComponentBoundEvent_key, UGameModeBase* CallFunc_GetGameMode_ReturnValue, UGM_Motherlode_C* K2Node_DynamicCast_AsGM_Motherlode, bool K2Node_DynamicCast_bSuccess, UPrimitiveComponent* K2Node_ComponentBoundEvent_OverlappedComponent_4, AActor* K2Node_ComponentBoundEvent_OtherActor_4, UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp_4, int32 K2Node_ComponentBoundEvent_OtherBodyIndex_4, bool K2Node_ComponentBoundEvent_bFromSweep_2, const FHitResult K2Node_ComponentBoundEvent_SweepResult_2, UPrimitiveComponent* K2Node_ComponentBoundEvent_OverlappedComponent_3, AActor* K2Node_ComponentBoundEvent_OtherActor_3, UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp_3, int32 K2Node_ComponentBoundEvent_OtherBodyIndex_3, bool CallFunc_IsValid_ReturnValue_2, bool CallFunc_IsValid_ReturnValue_3, UPlayerCharacter* K2Node_DynamicCast_AsPlayer_Character, bool K2Node_DynamicCast_bSuccess_1, UPlayerCharacter* K2Node_DynamicCast_AsPlayer_Character_1, bool K2Node_DynamicCast_bSuccess_2, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue, int32 Temp_int_Variable_1, bool CallFunc_EqualEqual_IntInt_ReturnValue_1, UPrimitiveComponent* K2Node_ComponentBoundEvent_OverlappedComponent_2, AActor* K2Node_ComponentBoundEvent_OtherActor_2, UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp_2, int32 K2Node_ComponentBoundEvent_OtherBodyIndex_2, bool K2Node_ComponentBoundEvent_bFromSweep_1, const FHitResult K2Node_ComponentBoundEvent_SweepResult_1, bool CallFunc_IsValid_ReturnValue_4, UPlayerCharacter* K2Node_DynamicCast_AsPlayer_Character_2, bool K2Node_DynamicCast_bSuccess_3, UHealthComponentBase* CallFunc_GetComponentByClass_ReturnValue, bool CallFunc_IsValid_ReturnValue_5, UFSDGameState* CallFunc_GetFSDGameState_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue_2, FVector CallFunc_Add_VectorVector_ReturnValue, bool CallFunc_IsValid_ReturnValue_6, FTransform CallFunc_MakeTransform_ReturnValue, int32 CallFunc_Array_AddUnique_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue_3, FVector CallFunc_K2_GetActorLocation_ReturnValue_4, FVector CallFunc_Add_VectorVector_ReturnValue_1, UAudioComponent* CallFunc_SpawnSoundAtLocation_ReturnValue_1, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue_1, bool CallFunc_EqualEqual_ByteByte_ReturnValue, FVector CallFunc_K2_GetComponentLocation_ReturnValue, FVector CallFunc_Add_VectorVector_ReturnValue_2, UAudioComponent* CallFunc_SpawnSoundAtLocation_ReturnValue_2, UBP_Minehead_Sentry_C* K2Node_DynamicCast_AsBP_Minehead_Sentry, bool K2Node_DynamicCast_bSuccess_4, UBP_Minehead_Sentry_C* K2Node_DynamicCast_AsBP_Minehead_Sentry_1, bool K2Node_DynamicCast_bSuccess_5, UBP_Minehead_Sentry_C* K2Node_DynamicCast_AsBP_Minehead_Sentry_2, bool K2Node_DynamicCast_bSuccess_6, ABP_SpotLightInteractive_C* K2Node_DynamicCast_AsBP_Spot_Light_Interactive, bool K2Node_DynamicCast_bSuccess_7, ABP_SpotLightInteractive_C* K2Node_DynamicCast_AsBP_Spot_Light_Interactive_1, bool K2Node_DynamicCast_bSuccess_8, UPlayerCharacter* K2Node_ComponentBoundEvent_user_1, UPlayerCharacter* K2Node_ComponentBoundEvent_user, bool CallFunc_IsValid_ReturnValue_7, UPrimitiveComponent* K2Node_ComponentBoundEvent_OverlappedComponent_1, AActor* K2Node_ComponentBoundEvent_OtherActor_1, UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp_1, int32 K2Node_ComponentBoundEvent_OtherBodyIndex_1, bool K2Node_ComponentBoundEvent_bFromSweep, const FHitResult K2Node_ComponentBoundEvent_SweepResult, UPrimitiveComponent* K2Node_ComponentBoundEvent_OverlappedComponent, AActor* K2Node_ComponentBoundEvent_OtherActor, UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp, int32 K2Node_ComponentBoundEvent_OtherBodyIndex, bool CallFunc_TryPopActiveStatusEffect_ReturnValue, bool CallFunc_TryPushActiveStatusEffect_ReturnValue, FRotator CallFunc_K2_GetActorRotation_ReturnValue, FTransform CallFunc_MakeTransform_ReturnValue_1, AActor* CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue, UFSDGameState* CallFunc_GetFSDGameState_ReturnValue_1, ABP_Minehead_LandingZone_C* CallFunc_FinishSpawningActor_ReturnValue, bool K2Node_ComponentBoundEvent_canUse, ShadowQualityChanged__DelegateSignature K2Node_CreateDelegate_OutputDelegate, FVector CallFunc_K2_GetComponentLocation_ReturnValue_1, UAudioComponent* CallFunc_SpawnSoundAtLocation_ReturnValue_3, FRotator CallFunc_K2_GetActorRotation_ReturnValue_1);
    void MinheadStateChanged__DelegateSignature(uint8 State);
}

#endif
