#ifndef UE4SS_SDK_BP_NetworkPlayGameMode_HPP
#define UE4SS_SDK_BP_NetworkPlayGameMode_HPP

class ABP_NetworkPlayGameMode_C : UBP_GameMode_C
{
    FPointerToUberGraphFrame UberGraphFrame;

    UClass* GetDefaultPawnClassForController(AController* InControllerbool Temp_bool_Variable, bool CallFunc_IsLocalPlayerController_ReturnValue, TSubclassOf<UObject> CallFunc_LoadClass_ReturnValue, UFSDPlayerState* K2Node_DynamicCast_AsFSDPlayer_State, bool K2Node_DynamicCast_bSuccess, TSubclassOf<UPlayerCharacter> CallFunc_GetSelectedCharacter_ReturnValue, bool CallFunc_IsOnSpaceRig_OnSpaceRig, bool CallFunc_Not_PreBool_ReturnValue, bool CallFunc_IsValidClass_ReturnValue, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue, bool CallFunc_IsPlayInEditor_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, bool CallFunc_BooleanAND_ReturnValue_1, UGameData* CallFunc_GetFSDGameData_ReturnValue, TSubclassOf<UPlayerCharacter> CallFunc_GetDefaultEditorCharacter_ReturnValue, TSubclassOf<UPlayerCharacter> CallFunc_GetDefaultCharacter_ReturnValue, TSubclassOf<UObject> K2Node_Select_Default);
    void RecieveAllDwarvesDown();
    void ExecuteUbergraph_BP_NetworkPlayGameMode(int32 EntryPoint);
}

#endif
