#ifndef UE4SS_SDK_BP_PlayerCharacter_HPP
#define UE4SS_SDK_BP_PlayerCharacter_HPP

class ABP_PlayerCharacter_C : UPlayerCharacter
{
    FPointerToUberGraphFrame UberGraphFrame;
    UBP_EnemyControlState_C* BP_EnemyControlState;
    UPointLightComponent* FilmFaceLight;
    UBP_PushingState_C* BP_PushingState;
    UBP_TrackMovementState_C* BP_TrackMovementState;
    UBP_SelfiePoint_C* SelfieSpringArmPoint;
    USpringArmComponent* SelfieSpringArm;
    USceneComponent* Fixed_Selfie_Points;
    USceneComponent* SelfieCameraSetup;
    UShieldBoostUsable* ShieldBoostUsable;
    UBP_AudioControl_LowHealth_C* BP_AudioControl;
    UBP_AttachedState_C* BP_AttachedState;
    UBP_PilotingState_C* BP_PilotingState;
    UBP_DeadState_C* BP_DeadState;
    UBP_PhotographyState_C* BP_PhotographyState;
    UBP_PassedOut_C* BP_PassedOut;
    UBP_IntoxicationComponent_C* BP_IntoxicationComponent;
    UBP_FrozenState_C* BP_FrozenState;
    UStaticMeshComponent* ScannerArrow;
    UBP_GrabbedState_C* BP_GrabbedState;
    UPointLightComponent* PointLight;
    USpotLightComponent* SpotLight;
    UPointLightComponent* FP_PointLight_CloseShine_Ground;
    USceneComponent* ShoulderCamLocation;
    USpringArmComponent* ShoulderCamArm;
    UPointLightComponent* DebugPointLight;
    UBP_SelfiePoint_C* BP_SelfiePoint6;
    UBP_SelfiePoint_C* BP_SelfiePoint5;
    UBP_SelfiePoint_C* BP_SelfiePoint4;
    UBP_SelfiePoint_C* BP_SelfiePoint3;
    UBP_SelfiePoint_C* BP_SelfiePoint2;
    UBP_SelfiePoint_C* BP_SelfiePoint1;
    UBP_SelfiePoint_C* BP_SelfiePoint;
    UBP_SelfiePoint_C* BP_SelfiePoint8;
    UStaticMeshComponent* DropShadow;
    UFragileDebrisCleaner* FragileDebrisCleanerCore;
    UFragileDebrisCleaner* FragileDebrisCleanerFeet;
    UParticleSystemComponent* P_Ambient_Dust;
    UBP_FlyingState_C* BP_FlyingState;
    USpotLightComponent* TP_SpotLight_shadow;
    USceneComponent* TP_SpotLight;
    USpotLightComponent* FP_SpotLight_Light;
    USceneComponent* FP_SpotLight;
    UPointLightComponent* EmergencyLight;
    UPointLightComponent* FP_PointLight_CloseShine;
    UBP_NoMovementState_C* BP_NoMovementState;
    UBP_ZipLineState_C* BP_ZipLineState;
    UBP_UsingState_C* BP_UsingState;
    UAudioComponent* ShieldRegenAudio;
    URadarPointComponent* radarPoint;
    UBP_ParalyzedState_C* BP_ParalyzedState;
    UPointLightComponent* PointLight_SpotCloseShine;
    UBP_DownedState_C* BP_DownedState;
    UBP_FallingState_C* BP_FallingState;
    UBP_WalkingState_C* BP_WalkingState;
    UStaticMeshComponent* SM_LightCone;
    UStaticMeshComponent* Mesh_Lamp_rim;
    UStaticMeshComponent* Mesh_Lamp;
    USphereComponent* UsableCollision;
    float Emergency_Timeline_Light_Intensity_49385F0B40EDFCE34D2340AC7114B889;
    TEnumAsByte<ETimelineDirection::Type> Emergency_Timeline__Direction_49385F0B40EDFCE34D2340AC7114B889;
    UTimelineComponent* Emergency Timeline;
    float ShieldRegenTimeline_Volume_007E924B43B618D88D08859A06A1CF61;
    float ShieldRegenTimeline_Pitch_007E924B43B618D88D08859A06A1CF61;
    TEnumAsByte<ETimelineDirection::Type> ShieldRegenTimeline__Direction_007E924B43B618D88D08859A06A1CF61;
    UTimelineComponent* ShieldRegenTimeline;
    float ShieldRegenTime;
    float LastDamageTime;
    TArray<UBP_SelfiePoint_C*> FixedSelfiePointList;
    UBP_SelfiePoint_C* ActiveSelfiePoint;
    bool WasHUDVisible;
    UReverbEffect* PreDownReverb;
    FScaledEffect MixerConfetti;
    UParticleSystem* InstantReviveParticles;
    USoundBase* InstantReviveCue;
    bool LeftShiftPressed;
    bool LeftCtrPressed;
    FTimerHandle SelfieZoomTimer;
    FTimerHandle SelfieMoveRightTimer;
    FTimerHandle SelfieMoveUpTimer;

    void GotoNextSelfiePoint(bool ForceExitSelfieMode, int32 NextIndex, int32 CallFunc_Array_Length_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, FString CallFunc_Conv_IntToString_ReturnValue, FString CallFunc_Conv_IntToString_ReturnValue_1, FString CallFunc_Concat_StrStr_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, FString CallFunc_Concat_StrStr_ReturnValue_1, FString CallFunc_Concat_StrStr_ReturnValue_2, int32 CallFunc_Array_Find_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_1, int32 CallFunc_Add_IntInt_ReturnValue_1, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, UBP_SelfiePoint_C* CallFunc_Array_Get_Item);
    void SetActiveSelfiePoint(UBP_SelfiePoint_C* InSelfiePoint, bool CallFunc_IsValid_ReturnValue, UFSDPlayerController* CallFunc_GetPlayerController_ReturnValue, AHUD* CallFunc_GetHUD_ReturnValue, UBP_HUD_C* K2Node_DynamicCast_AsBP_HUD, bool K2Node_DynamicCast_bSuccess, bool CallFunc_IsValid_ReturnValue_1, UFSDPlayerController* CallFunc_GetPlayerController_ReturnValue_1, bool CallFunc_IsValid_ReturnValue_2, AHUD* CallFunc_GetHUD_ReturnValue_1, UFSDHUD* K2Node_DynamicCast_AsFSDHUD, bool K2Node_DynamicCast_bSuccess_1, bool CallFunc_GetHUDVisible_ReturnValue, bool CallFunc_NotEqual_ObjectObject_ReturnValue);
    bool DamageCausesReaction(UDamageClass* DamageClassbool CallFunc_NotEqual_ObjectObject_ReturnValue);
    USceneComponent* GetDownCameraAttachPoint();
    USceneComponent* GetDownCameraRotationPoint();
    void ChromaEffect(uint8 effect);
    void CharacterAudioThrottled(UDialogDataAsset* Shout, float CallFunc_GetGameTimeInSeconds_ReturnValue, float CallFunc_TimeSince_ReturnValue, bool CallFunc_Greater_FloatFloat_ReturnValue);
    void UpdateHeadLight(bool Temp_bool_Variable, USoundBase* Temp_object_Variable, USoundBase* Temp_object_Variable_1, USoundBase* K2Node_Select_Default, bool CallFunc_IsFirstPerson_ReturnValue, FVector CallFunc_K2_GetComponentLocation_ReturnValue);
    void ShieldRegenTimeline__FinishedFunc();
    void ShieldRegenTimeline__UpdateFunc();
    void Emergency Timeline__FinishedFunc();
    void Emergency Timeline__UpdateFunc();
    void InpActEvt_P_K2Node_InputKeyEvent_16(FKey Key);
    void InpActEvt_LeftShift_K2Node_InputKeyEvent_15(FKey Key);
    void InpActEvt_LeftShift_K2Node_InputKeyEvent_14(FKey Key);
    void InpActEvt_LeftControl_K2Node_InputKeyEvent_13(FKey Key);
    void InpActEvt_LeftControl_K2Node_InputKeyEvent_12(FKey Key);
    void InpActEvt_PageDown_K2Node_InputKeyEvent_11(FKey Key);
    void InpActEvt_PageDown_K2Node_InputKeyEvent_10(FKey Key);
    void InpActEvt_PageUp_K2Node_InputKeyEvent_9(FKey Key);
    void InpActEvt_PageUp_K2Node_InputKeyEvent_8(FKey Key);
    void InpActEvt_Home_K2Node_InputKeyEvent_7(FKey Key);
    void InpActEvt_Home_K2Node_InputKeyEvent_6(FKey Key);
    void InpActEvt_End_K2Node_InputKeyEvent_5(FKey Key);
    void InpActEvt_End_K2Node_InputKeyEvent_4(FKey Key);
    void InpActEvt_Insert_K2Node_InputKeyEvent_3(FKey Key);
    void InpActEvt_Insert_K2Node_InputKeyEvent_2(FKey Key);
    void InpActEvt_Delete_K2Node_InputKeyEvent_1(FKey Key);
    void InpActEvt_Delete_K2Node_InputKeyEvent_0(FKey Key);
    void BP_OnControllerReady();
    void ReceiveBeginPlay();
    void BndEvt__HealthComponent_K2Node_ComponentBoundEvent_0_ArmorHealedSig__DelegateSignature(float Amount);
    void StopRegenAudio();
    void BP_OnUpdateMeshes();
    void CharacterState Changed(ECharacterState NewState);
    void BndEvt__HealthComponent_K2Node_ComponentBoundEvent_0_DamageSig__DelegateSignature(float Amount);
    void BndEvt__HealthComponent_K2Node_ComponentBoundEvent_2_DamageSig__DelegateSignature(float Amount);
    void Init Selfie Cam();
    void SetDustVisible(bool Visible);
    void ReceiveOnHeadlightOn();
    void ResetSaveGameIDInEditor();
    void On Temporary Buff Changed(UTemporaryBuff* buff, UPlayerCharacter* AffectedPlayer);
    void MixerClientSpawnConfettii(FVector Location, FRotator Rotation);
    void MixerServerSpawnConfettii(FVector Location, FRotator Rotation);
    void MixerSpawnConfetti(FVector Location, FRotator Rotation);
    void PrepareForEndScreen();
    void BndEvt__HealthComponent_K2Node_ComponentBoundEvent_0_HitSig__DelegateSignature(float Damage, UDamageClass* DamageClass, AActor* DamageCauser, bool anyHealthLost);
    void BndEvt__HealthComponent_K2Node_ComponentBoundEvent_1_HitSig__DelegateSignature(float Damage, UDamageClass* DamageClass, AActor* DamageCauser, bool anyHealthLost);
    void Activate Temporary buff on server(UTemporaryBuff* buff, UPlayerCharacter* Player);
    void Receive_ShowFieldMedicInstantReviveEffects();
    void InpAxisKeyEvt_MouseX_K2Node_InputAxisKeyEvent_0(float AxisValue);
    void InpAxisKeyEvt_MouseY_K2Node_InputAxisKeyEvent_1(float AxisValue);
    void SelfieZoom(float InDelta);
    void TickSelfieZoom();
    void SelfieMoveUp(float InDirection);
    void TickSelfieMoveUp();
    void SelfieMoveRight(float InDirection);
    void TickSelfieMoveRight();
    void ExecuteUbergraph_BP_PlayerCharacter(int32 EntryPoint, FKey K2Node_InputKeyEvent_Key_8, FKey Temp_struct_Variable, TimerDynamicDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate, FKey K2Node_InputKeyEvent_Key_7, FTimerHandle CallFunc_K2_SetTimerDelegate_ReturnValue, FKey K2Node_InputKeyEvent_Key_6, FKey Temp_struct_Variable_1, FKey K2Node_InputKeyEvent_Key_5, FKey K2Node_InputKeyEvent_Key_4, FKey Temp_struct_Variable_2, TimerDynamicDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_1, FTimerHandle CallFunc_K2_SetTimerDelegate_ReturnValue_1, TimerDynamicDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_2, FKey K2Node_InputKeyEvent_Key_3, FTimerHandle CallFunc_K2_SetTimerDelegate_ReturnValue_2, FKey K2Node_InputKeyEvent_Key_2, FKey Temp_struct_Variable_3, FKey K2Node_InputKeyEvent_Key_1, FKey K2Node_InputKeyEvent_Key, FKey Temp_struct_Variable_4, FKey Temp_struct_Variable_5, FKey K2Node_InputKeyEvent_Key_14, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_HasAuthority_ReturnValue, FKey K2Node_InputKeyEvent_Key_15, UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue, UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue_1, bool CallFunc_IsValid_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue_2, FKey K2Node_InputKeyEvent_Key_16, bool CallFunc_IsValid_ReturnValue_2, UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue_3, bool CallFunc_IsValid_ReturnValue_3, TemporaryBuffChanged__DelegateSignature K2Node_CreateDelegate_OutputDelegate_3, UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue_4, UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue_5, bool CallFunc_IsValid_ReturnValue_4, bool CallFunc_IsValid_ReturnValue_5, UFSDPlayerController* CallFunc_GetPlayerController_ReturnValue, FKey K2Node_InputKeyEvent_Key_9, float CallFunc_Multiply_FloatFloat_ReturnValue, bool CallFunc_HasAuthority_ReturnValue_1, float K2Node_ComponentBoundEvent_Amount_2, float CallFunc_GetMaxArmor_ReturnValue, float CallFunc_GetArmorPct_ReturnValue, float CallFunc_Divide_FloatFloat_ReturnValue, bool CallFunc_GreaterEqual_FloatFloat_ReturnValue, bool CallFunc_IsPlaying_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, float CallFunc_Add_FloatFloat_ReturnValue, FKey Temp_struct_Variable_6, bool CallFunc_IsLocallyControlled_ReturnValue, bool CallFunc_IsFirstPerson_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue_1, ECharacterState K2Node_CustomEvent_newState, FKey K2Node_InputKeyEvent_Key_10, bool CallFunc_EqualEqual_ByteByte_ReturnValue, FKey K2Node_InputKeyEvent_Key_11, bool CallFunc_BooleanAND_ReturnValue, float K2Node_ComponentBoundEvent_Amount_1, bool CallFunc_BooleanAND_ReturnValue_1, float K2Node_ComponentBoundEvent_Amount, FVector CallFunc_K2_GetActorLocation_ReturnValue, UAudioComponent* CallFunc_SpawnSoundAtLocation_ReturnValue, AProceduralSetup* CallFunc_GetProceduralSetup_ReturnValue, bool CallFunc_IsValid_ReturnValue_6, OnCharacterStateChangedSignature__DelegateSignature K2Node_CreateDelegate_OutputDelegate_4, UParticleSystem* CallFunc_GetAtmosphericParticles_ReturnValue, bool K2Node_CustomEvent_Visible, bool CallFunc_IsValid_ReturnValue_7, bool CallFunc_IsLocallyControlled_ReturnValue_1, UReverbEffect* CallFunc_GetCurrentReverbEffect_ReturnValue, UBP_SelfiePoint_C* Temp_object_Variable, TArray<USceneComponent*>& CallFunc_GetChildrenComponents_Children, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_IsLocallyControlled_ReturnValue_2, bool CallFunc_IsLocallyControlled_ReturnValue_3, bool CallFunc_IsDown_ReturnValue, ADeepCSGWorld* CallFunc_GetCSGWorld_ReturnValue, bool CallFunc_IsValid_ReturnValue_8, UMaterialInterface* CallFunc_GetMaterial_ReturnValue, UMaterialInstanceDynamic* CallFunc_CreateDynamicMaterialInstance_ReturnValue, const FLinearColor CallFunc_GetHeroColor_ReturnValue, bool Temp_bool_Variable, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue, UTemporaryBuff* K2Node_CustomEvent_buff_1, UPlayerCharacter* K2Node_CustomEvent_AffectedPlayer, bool CallFunc_IsValid_ReturnValue_9, AController* CallFunc_GetController_ReturnValue, UFSDPlayerController* CallFunc_GetPlayerController_ReturnValue_1, UFSDPlayerController* K2Node_DynamicCast_AsFSDPlayer_Controller, bool K2Node_DynamicCast_bSuccess, FVector K2Node_CustomEvent_Location_2, FRotator K2Node_CustomEvent_Rotation_2, UAudioComponent* CallFunc_SpawnSoundAtLocation_ReturnValue_1, UFXSystemComponent* CallFunc_SpawnScaledEmitterAtLocation_ReturnValue, USceneComponent* CallFunc_K2_GetRootComponent_ReturnValue, FVector K2Node_CustomEvent_Location_1, FRotator K2Node_CustomEvent_Rotation_1, FVector K2Node_CustomEvent_Location, FRotator K2Node_CustomEvent_Rotation, FKey Temp_struct_Variable_7, float K2Node_ComponentBoundEvent_Damage_1, UDamageClass* K2Node_ComponentBoundEvent_damageClass_1, AActor* K2Node_ComponentBoundEvent_DamageCauser_1, bool K2Node_ComponentBoundEvent_anyHealthLost_1, FKey K2Node_InputKeyEvent_Key_12, InterfaceProperty K2Node_DynamicCast_AsIOn_Damaged_Player, bool K2Node_DynamicCast_bSuccess_1, float K2Node_ComponentBoundEvent_Damage, UDamageClass* K2Node_ComponentBoundEvent_damageClass, AActor* K2Node_ComponentBoundEvent_DamageCauser, bool K2Node_ComponentBoundEvent_anyHealthLost, bool CallFunc_NotEqual_ObjectObject_ReturnValue, bool CallFunc_Greater_FloatFloat_ReturnValue, UTemporaryBuff* K2Node_CustomEvent_buff, UPlayerCharacter* K2Node_CustomEvent_player, bool CallFunc_IsLocallyControlled_ReturnValue_4, bool CallFunc_IsLocallyControlled_ReturnValue_5, bool CallFunc_BooleanAND_ReturnValue_2, UFSDPlayerController* CallFunc_GetPlayerController_ReturnValue_2, UFSDPlayerController* CallFunc_GetPlayerController_ReturnValue_3, int32 Temp_int_Array_Index_Variable, FVector CallFunc_K2_GetActorLocation_ReturnValue_1, USceneComponent* CallFunc_Array_Get_Item, UBP_SelfiePoint_C* K2Node_DynamicCast_AsBP_Selfie_Point, bool K2Node_DynamicCast_bSuccess_2, int32 CallFunc_Array_Add_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue_2, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue, UAudioComponent* CallFunc_SpawnSoundAtLocation_ReturnValue_2, float K2Node_InputAxisKeyEvent_AxisValue_1, float K2Node_InputAxisKeyEvent_AxisValue, float CallFunc_Multiply_FloatFloat_ReturnValue_1, float CallFunc_Multiply_FloatFloat_ReturnValue_2, bool CallFunc_K2_AttachToComponent_ReturnValue, UBP_SelfiePoint_C* K2Node_Select_Default, float CallFunc_GetWorldDeltaSeconds_ReturnValue, float CallFunc_Multiply_FloatFloat_ReturnValue_3, FRotator CallFunc_MakeRotator_ReturnValue, float CallFunc_GetWorldDeltaSeconds_ReturnValue_1, FHitResult CallFunc_K2_AddRelativeRotation_SweepHitResult, float CallFunc_Multiply_FloatFloat_ReturnValue_4, FKey K2Node_InputKeyEvent_Key_13, FRotator CallFunc_MakeRotator_ReturnValue_1, FHitResult CallFunc_K2_AddRelativeRotation_SweepHitResult_1, FVector CallFunc_K2_GetActorLocation_ReturnValue_3, UAudioComponent* CallFunc_SpawnSoundAtLocation_ReturnValue_3, float K2Node_CustomEvent_InDelta, float CallFunc_Abs_ReturnValue, float CallFunc_Multiply_FloatFloat_ReturnValue_5, bool CallFunc_Greater_FloatFloat_ReturnValue_1, float CallFunc_Add_FloatFloat_ReturnValue_1, float K2Node_CustomEvent_InDirection_1, float CallFunc_SignOfFloat_ReturnValue, float CallFunc_Abs_ReturnValue_1, float CallFunc_Multiply_FloatFloat_ReturnValue_6, bool CallFunc_Greater_FloatFloat_ReturnValue_2, float CallFunc_Multiply_FloatFloat_ReturnValue_7, FVector CallFunc_MakeVector_ReturnValue, float K2Node_CustomEvent_InDirection, FHitResult CallFunc_K2_AddRelativeLocation_SweepHitResult, float CallFunc_SignOfFloat_ReturnValue_1, float CallFunc_Abs_ReturnValue_2, float CallFunc_Multiply_FloatFloat_ReturnValue_8, bool CallFunc_Greater_FloatFloat_ReturnValue_3, float CallFunc_Multiply_FloatFloat_ReturnValue_9, FVector CallFunc_MakeVector_ReturnValue_1, FHitResult CallFunc_K2_AddRelativeLocation_SweepHitResult_1, UCharacterVanityComponent* CallFunc_GetCharacterVanity_ReturnValue, UAudioComponent* CallFunc_SpawnSound2D_ReturnValue, UAudioComponent* CallFunc_SpawnSound2D_ReturnValue_1, UAudioComponent* CallFunc_SpawnSound2D_ReturnValue_2);
}

#endif
