#ifndef UE4SS_SDK_BP_PlayerController_SpaceRig_HPP
#define UE4SS_SDK_BP_PlayerController_SpaceRig_HPP

class ABP_PlayerController_SpaceRig_C : UBP_SR_PlayerControllerBase_C
{
    FPointerToUberGraphFrame UberGraphFrame;
    UWindowWidget* ServerBrowser;
    UMENU_Loadout_C* Loadout;
    UWindowWidget* options;
    UWindowWidget* MissionSelect;
    int32 OldCounter;
    TArray<UUserWidget*> Widgets;
    UPopup_GearUpgrade_Buy_C* PopUp_BuyUpgrade;
    FVector StartLocation;
    bool CharacterPossed;
    FBP_PlayerController_SpaceRig_COnToggleHUD OnToggleHUD;
    void OnToggleHUD();
    UWindowWidget* CharCustomization;
    UWindowWidget* Crafting;
    UWindowWidget* Popup_Crafting;
    bool ShowingReconnectcontroller;
    bool IsHUDVisible;
    USCREEN_CharacterSelection_Clean_C* CharacterSelection;
    bool HasShownCharacterSelector;
    UWindowWidget* ReconnectController;
    UWindowWidget* NetworkError;
    UWindowWidget* Trading;
    UWindowWidget* Cheat;
    UWindowWidget* Jobs;
    UWND_AssignmentMissionComplete_C* C;
    UWindowWidget* RetirementPopup_0;
    UMENU_UpgradeScreen_C* ItemUpgrade;
    bool EscapeMenuEnabled;
    UWindowWidget* Bosco;
    int32 Medbay speech counter;
    float Time between shouts;
    int32 MixerConfettiTime;
    FScaledEffect MixerConfetti;
    UFSDAchievement* SelfControlAchievement;
    bool HasKickedABarrel;
    UFSDAchievement* MugInHoopAchievement;
    UFSDAchievement* DiscJockeyAchievement;
    bool CanUseInstantUsableDiscord;
    UWindowWidget* DeepDives;
    TArray<FSoftObjectPath> UIToAsyncLoad;
    FBP_PlayerController_SpaceRig_COnOpenedEscapeMenu OnOpenedEscapeMenu;
    void OnOpenedEscapeMenu();
    int32 CheatCounter;
    FBP_PlayerController_SpaceRig_COnCheatRequested OnCheatRequested;
    void OnCheatRequested();

    void ModdedSavegameCheck(UUGCRegistry* CallFunc_GetUGCRegistry_ReturnValue, OnModdedSaveLoaded__DelegateSignature K2Node_CreateDelegate_OutputDelegate, bool CallFunc_IsValid_ReturnValue, bool CallFunc_AreModsInstalled_ReturnValue, UWindowManager* CallFunc_GetWindowManager_ReturnValue, UFSDSaveGame* CallFunc_GetFSDSaveGame_ReturnValue, UPopup_ModdedSave_C* CallFunc_OpenSingleUseWindow_ReturnValue, bool CallFunc_GetIsModded_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, bool CallFunc_BooleanAND_ReturnValue);
    void Change Savegame(UFSDSaveGame* CallFunc_GetFSDSaveGame_ReturnValue, OnModdedSaveLoaded__DelegateSignature K2Node_CreateDelegate_OutputDelegate, bool CallFunc_GetIsModded_ReturnValue, UWindowManager* CallFunc_GetWindowManager_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, UPopup_ModdedSave_C* CallFunc_OpenSingleUseWindow_ReturnValue);
    void GetMissionSelect(UWindowWidget*& Widget);
    void GetPopupCrafting(UWindowWidget*& Widget);
    void GetCrafting(UWindowWidget*& Widget);
    void PreloadAssets(int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, const AsyncLoadCompleteDelegate__DelegateSignature Temp_delegate_Variable, UAsyncManager* CallFunc_GetGameInstanceSubsystem_ReturnValue, UAsyncManager* CallFunc_GetGameInstanceSubsystem_ReturnValue_1, UGameData* CallFunc_GetFSDGameData_ReturnValue, UGameData* CallFunc_GetFSDGameData_ReturnValue_1, int32 CallFunc_Array_Length_ReturnValue, FMissionBiomeItem CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, TArray<FSoftObjectPath>& CallFunc_GetBiomeMapAssetList_ReturnValue);
    bool hudVisible(bool CallFunc_IsHUDVisibleFlagSet_ReturnValue, bool CallFunc_IsHUDVisibleFlagSet_ReturnValue_1, bool CallFunc_IsHUDVisibleFlagSet_ReturnValue_2, bool CallFunc_IsHUDVisibleFlagSet_ReturnValue_3, bool CallFunc_BooleanOR_ReturnValue, bool CallFunc_BooleanOR_ReturnValue_1, bool CallFunc_BooleanOR_ReturnValue_2);
    void ChangeHUDVisible(bool IsHUDVisible, EHUDVisibilityReason reason, AHUD* CallFunc_GetHUD_ReturnValue, UFSDHUD* K2Node_DynamicCast_AsFSDHUD, bool K2Node_DynamicCast_bSuccess);
    void SelectLastPlayedCharacter(bool Temp_bool_Variable, UGameData* CallFunc_GetFSDGameData_ReturnValue, UGameData* CallFunc_GetFSDGameData_ReturnValue_1, const TArray<UPlayerCharacterID*>& CallFunc_GetRankedHeroIDs_ReturnValue, UFSDPlayerState* CallFunc_GetFSDPlayerState_ReturnValue, UFSDSaveGame* CallFunc_GetFSDSaveGame_ReturnValue, bool CallFunc_IsValid_ReturnValue, bool CallFunc_Array_Contains_ReturnValue, FString CallFunc_GetDisplayName_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, FString CallFunc_Concat_StrStr_ReturnValue, UPlayerCharacterID* K2Node_Select_Default);
    void AddWidget(UUserWidget*& Widget, int32 ZOrder, ESlateVisibility InVisibility, int32 CallFunc_Array_AddUnique_ReturnValue);
    void ChangeCharacter(UPlayerCharacterID* NewCharacter, TArray<UDrinkEffectComponent*> Previous character drink effects, FTransform Transform, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, APawn* CallFunc_K2_GetPawn_ReturnValue, UDrinkEffectComponent* CallFunc_Array_Get_Item, UPlayerCharacter* K2Node_DynamicCast_AsPlayer_Character, bool K2Node_DynamicCast_bSuccess, TSubclassOf<UDrinkEffectComponent> CallFunc_GetObjectClass_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, APawn* CallFunc_K2_GetPawn_ReturnValue_1, TArray<UDrinkEffectComponent*>& CallFunc_K2_GetComponentsByClass_ReturnValue, UFSDPlayerState* CallFunc_GetFSDPlayerState_ReturnValue, APawn* CallFunc_K2_GetPawn_ReturnValue_2, const FTransform CallFunc_GetTransform_ReturnValue, UGameModeBase* CallFunc_GetGameMode_ReturnValue);
    void CreateUI(TSubclassOf<UWindowWidget> CallFunc_LoadWindowWidgetClass_ReturnValue, TSubclassOf<UWindowWidget> CallFunc_LoadWindowWidgetClass_ReturnValue_1, UWindowWidget* CallFunc_Create_ReturnValue, TSubclassOf<UWindowWidget> CallFunc_LoadWindowWidgetClass_ReturnValue_2, UWindowWidget* CallFunc_Create_ReturnValue_1, UMENU_UpgradeScreen_C* CallFunc_Create_ReturnValue_2, TSubclassOf<UObject> CallFunc_LoadClass_ReturnValue, TSubclassOf<UWindowWidget> CallFunc_LoadWindowWidgetClass_ReturnValue_3, TSubclassOf<UWindowWidget> CallFunc_LoadWindowWidgetClass_ReturnValue_4, UWindowWidget* CallFunc_Create_ReturnValue_3, TSubclassOf<UWindowWidget> CallFunc_LoadWindowWidgetClass_ReturnValue_5, UWindowWidget* CallFunc_Create_ReturnValue_4, TSubclassOf<UWindowWidget> CallFunc_LoadWindowWidgetClass_ReturnValue_6, TSubclassOf<UWindowWidget> CallFunc_LoadWindowWidgetClass_ReturnValue_7, TSubclassOf<UWindowWidget> CallFunc_LoadWindowWidgetClass_ReturnValue_8, TSubclassOf<UWindowWidget> CallFunc_LoadWindowWidgetClass_ReturnValue_9, TSubclassOf<UWindowWidget> CallFunc_LoadWindowWidgetClass_ReturnValue_10, TSubclassOf<UWindowWidget> CallFunc_LoadWindowWidgetClass_ReturnValue_11, TSubclassOf<UWindowWidget> CallFunc_LoadWindowWidgetClass_ReturnValue_12, TSubclassOf<UWindowWidget> CallFunc_LoadWindowWidgetClass_ReturnValue_13, UWindowWidget* CallFunc_Create_ReturnValue_5, UWindowWidget* CallFunc_Create_ReturnValue_6, UWindowWidget* CallFunc_Create_ReturnValue_7, UWindowWidget* CallFunc_Create_ReturnValue_8, USCREEN_CharacterSelection_Clean_C* CallFunc_Create_ReturnValue_9, UWindowWidget* CallFunc_Create_ReturnValue_10, UWindowWidget* CallFunc_Create_ReturnValue_11, UWindowWidget* CallFunc_Create_ReturnValue_12, UPopup_GearUpgrade_Buy_C* CallFunc_Create_ReturnValue_13, UWindowWidget* CallFunc_Create_ReturnValue_14, UMENU_Loadout_C* CallFunc_Create_ReturnValue_15, UWindowWidget* CallFunc_Create_ReturnValue_16, UWindowWidget* CallFunc_Create_ReturnValue_17);
    void InpActEvt_PushToTalk_K2Node_InputActionEvent_5(FKey Key);
    void InpActEvt_PushToTalk_K2Node_InputActionEvent_4(FKey Key);
    void InpActEvt_MenuButton_K2Node_InputActionEvent_3(FKey Key);
    void InpActEvt_Chat_K2Node_InputActionEvent_2(FKey Key);
    void InpActEvt_CallDonkey_K2Node_InputActionEvent_1(FKey Key);
    void InpActEvt_MapTool_K2Node_InputActionEvent_0(FKey Key);
    void InpActEvt_Subtract_K2Node_InputKeyEvent_6(FKey Key);
    void InpActEvt_Eight_K2Node_InputKeyEvent_5(FKey Key);
    void InpActEvt_Eight_K2Node_InputKeyEvent_4(FKey Key);
    void InpActEvt_Nine_K2Node_InputKeyEvent_3(FKey Key);
    void InpActEvt_Nine_K2Node_InputKeyEvent_2(FKey Key);
    void InpActEvt_Ctrl+Alt_H_K2Node_InputKeyEvent_1(FKey Key);
    void OnLoaded_0C1A95084D16C934A469CF8C3B445101(TSubclassOf<UObject> Loaded);
    void OnFailure_84F86EB44BDC03B3D4D52D92FC0B069A();
    void OnSuccess_84F86EB44BDC03B3D4D52D92FC0B069A();
    void InpActEvt_Home_K2Node_InputKeyEvent_0(FKey Key);
    void OnFailure_FD5D0BC24D561288D20ABE9353DBA180();
    void OnSuccess_FD5D0BC24D561288D20ABE9353DBA180();
    void ShowServerBrowser();
    void ShowMissionSelect();
    void Client_OpenMap();
    void PlayerChangeCharacter(UPlayerCharacterID* NewCharacter);
    void RecievePreClientTravel();
    void ShowCharacterSelect();
    void ControllerReady();
    void RecieveOnControllerReady();
    void ShowBuyItemPopup(TSubclassOf<AActor> Item, UItemUpgrade* Upgrade);
    void ReceiveDestroyed();
    void OnCharacterPossesd();
    void ReceiveBeginPlay();
    void ShowCharCustomization();
    void ShowCrafting();
    void ShowCharacterScreenAndWorld();
    void ShowCraftingAndWorld();
    void ShowCustomizationAndWorld();
    void SpawnPlayer();
    void ShowFirstCharacterSelect();
    void OpenCharacterSelector(bool OpenVideo, bool AllowBack);
    void ShowReconnectController();
    void OnFirstWindowOpened();
    void OnLastWindowClosed();
    void ShowNetworkError();
    void ShowTrading();
    void ShowWindowByClass(TSubclassOf<UWindowWidget> windowClass, int32 ZOrder);
    void ShowCheatMenu();
    void ShowBarMenu(ASpaceRigBar* Bar);
    void OnRoundSelected_Event(ASpaceRigBar* Bar, UDrinkableDataAsset* RequestedDrink);
    void OrderBarRound(ASpaceRigBar* Bar, UDrinkableDataAsset* Drink);
    void Deduct Credits On Client(int32 Amount);
    void ShowJobs();
    void ShowItemUpgradeScreen(TSubclassOf<UPlayerCharacter> CharacterClass, TSubclassOf<AActor> itemClass, EItemCategory ItemCategory);
    void ShowBoscoUpgrades();
    void OnPlayerSpawnBegin(int32 PlayerId);
    void OnDroppodLeave();
    void PlayerThrewMugInHoop();
    void PlayerPlayedEntireSong();
    void HandleDiscordConsole(ABP_DiscordConsole_C* DiscordConsole);
    void SetUsableDiscord(bool Usable);
    void ShowDeepDives();
    void OpenSpacerigConsole(ABP_BaseSpaceRigConsole_C* Console);
    void SetHasShownCharacterSelector(bool HasShown);
    void SetIsEscapeMenuEnabled(bool IsEscapeMenuEnabled);
    void Reset Player Location();
    void Reset Player Scale On Clients();
    void Server_PopLooatAtAffliction();
    void ShowLookAtConsole();
    void LaunchTutorial();
    void PromptLaunchTutorial();
    void On Prompt(bool Yes);
    void ShowCharacterSelectionBackground(bool resetToDefaultWeapon, ECharselectionCameraLocation cameraLocation);
    void ShowForgeWorkshop();
    void ReloadSpacerig();
    void OnRestartGame(bool Yes, bool CreateModdedSave);
    void OnRestartSpacerig(bool Yes, bool CreateModdedSave);
    void OnPackageMounted(bool Sandbox);
    void OnPlayer(UFSDPlayerState* PlayerState);
    void Back_Event_0();
    void OnCharacterSelected();
    void OnHostTimerChanged(float newTime);
    void OnMissionTimerChanged(float newTime);
    void DoCountDown(float newTime);
    void ShowReconnect(bool Show);
    void OnGravityChanged(float CurrentGravity, float Change);
    void CustomEvent_0();
    void ExecuteUbergraph_BP_PlayerController_SpaceRig(int32 EntryPoint, OnAssetClassLoaded__DelegateSignature K2Node_CreateDelegate_OutputDelegate, bool CallFunc_HasAuthority_ReturnValue, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue, WindowManagerDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_1, UPlayerController* CallFunc_GetPlayerController_ReturnValue, bool CallFunc_HasAuthority_ReturnValue_1, UWidget* CallFunc_GetFocusedWidget_ReturnValue, bool CallFunc_IsValid_ReturnValue, float Temp_float_Variable, bool CallFunc_IsLocalController_ReturnValue, UPlayerController* CallFunc_GetPlayerController_ReturnValue_1, UWidget* CallFunc_GetFocusedWidget_ReturnValue_1, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_1, bool CallFunc_IsValid_ReturnValue_1, UPlayerController* CallFunc_GetPlayerController_ReturnValue_2, UWidget* CallFunc_GetFocusedWidget_ReturnValue_2, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_2, bool CallFunc_IsValid_ReturnValue_2, float Temp_float_Variable_1, EmptyOnlineDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_2, bool Temp_bool_Variable, int32 Temp_int_Loop_Counter_Variable, EmptyOnlineDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_3, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_3, uint8 CallFunc_MakeLiteralByte_ReturnValue, UPlayerController* CallFunc_GetPlayerController_ReturnValue_3, FString CallFunc_GetEnumeratorUserFriendlyName_ReturnValue, UWidget* CallFunc_GetFocusedWidget_ReturnValue_3, FString CallFunc_Concat_StrStr_ReturnValue, bool CallFunc_IsValid_ReturnValue_3, FString CallFunc_Concat_StrStr_ReturnValue_1, CravityChangedSignature__DelegateSignature K2Node_CreateDelegate_OutputDelegate_4, ShowReconnectController__DelegateSignature K2Node_CreateDelegate_OutputDelegate_5, UPlayerController* CallFunc_GetPlayerController_ReturnValue_4, UWidget* CallFunc_GetFocusedWidget_ReturnValue_4, FKey K2Node_InputActionEvent_Key_2, bool CallFunc_IsValid_ReturnValue_4, bool CallFunc_Greater_IntInt_ReturnValue, OnPlayerCharacterPossesed__DelegateSignature K2Node_CreateDelegate_OutputDelegate_6, FKey K2Node_InputActionEvent_Key_3, OnMissionTimerChanged__DelegateSignature K2Node_CreateDelegate_OutputDelegate_7, OnHostTimerChanged__DelegateSignature K2Node_CreateDelegate_OutputDelegate_8, int32 Temp_int_Loop_Counter_Variable_1, int32 CallFunc_Add_IntInt_ReturnValue_1, int32 Temp_int_Array_Index_Variable_1, uint8 CallFunc_MakeLiteralByte_ReturnValue_1, UPlayerCharacterID* K2Node_CustomEvent_NewCharacter, FKey Temp_struct_Variable, TArray<UUserWidget*>& CallFunc_GetAllWidgetsOfClass_FoundWidgets, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_4, int32 CallFunc_Array_Length_ReturnValue, AHUD* CallFunc_GetHUD_ReturnValue, FKey K2Node_InputActionEvent_Key_4, bool CallFunc_IsValid_ReturnValue_5, bool CallFunc_IsLocalController_ReturnValue_1, UGameModeBase* CallFunc_GetGameMode_ReturnValue, UBP_SpaceRig_Gamemode_C* K2Node_DynamicCast_AsBP_Space_Rig_Gamemode, bool K2Node_DynamicCast_bSuccess, bool CallFunc_IsLocalController_ReturnValue_2, TSubclassOf<AActor> K2Node_CustomEvent_Item, UItemUpgrade* K2Node_CustomEvent_Upgrade, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_5, APawn* CallFunc_K2_GetPawn_ReturnValue, FKey K2Node_InputActionEvent_Key_5, FVector CallFunc_K2_GetActorLocation_ReturnValue, UPlayerCharacter* K2Node_DynamicCast_AsPlayer_Character, bool K2Node_DynamicCast_bSuccess_1, UAudioComponent* CallFunc_PlayPitched_ReturnValue, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_6, UGameModeBase* CallFunc_GetGameMode_ReturnValue_1, UBP_SpaceRig_Gamemode_C* K2Node_DynamicCast_AsBP_Space_Rig_Gamemode_1, bool K2Node_DynamicCast_bSuccess_2, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_7, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_8, CharacterSelected__DelegateSignature K2Node_CreateDelegate_OutputDelegate_9, UPlayerController* CallFunc_GetPlayerController_ReturnValue_5, UWindowManager* CallFunc_GetWindowManager_ReturnValue, UWidget* CallFunc_GetFocusedWidget_ReturnValue_5, bool CallFunc_IsValid_ReturnValue_6, float K2Node_Select_Default, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_9, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_10, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_11, bool K2Node_CustomEvent_OpenVideo, bool K2Node_CustomEvent_AllowBack, UWindowManager* CallFunc_GetWindowManager_ReturnValue_1, UWindowManager* CallFunc_GetWindowManager_ReturnValue_2, UWindowManager* CallFunc_GetWindowManager_ReturnValue_3, UWindowManager* CallFunc_GetWindowManager_ReturnValue_4, UWindowManager* CallFunc_GetWindowManager_ReturnValue_5, bool CallFunc_IsWindowOpen_ReturnValue, UWindowManager* CallFunc_GetWindowManager_ReturnValue_6, UWindowManager* CallFunc_GetWindowManager_ReturnValue_7, bool CallFunc_IsWindowOpen_ReturnValue_1, bool CallFunc_IsWindowOpen_ReturnValue_2, UWindowManager* CallFunc_GetWindowManager_ReturnValue_8, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_12, UWindowManager* CallFunc_GetWindowManager_ReturnValue_9, bool CallFunc_IsLocalPlayerController_ReturnValue, Back__DelegateSignature K2Node_CreateDelegate_OutputDelegate_10, UUGCSubsystem* CallFunc_GetEngineSubsystem_ReturnValue, FKey K2Node_InputKeyEvent_Key, bool CallFunc_IsValid_ReturnValue_7, UWindowManager* CallFunc_GetWindowManager_ReturnValue_10, TSubclassOf<UWindowWidget> K2Node_CustomEvent_windowClass, int32 K2Node_CustomEvent_zOrder, UWindowManager* CallFunc_GetWindowManager_ReturnValue_11, UWindowWidget* CallFunc_OpenWindowFromClass_ReturnValue, int32 Temp_int_Array_Index_Variable_2, UUserWidget* CallFunc_Array_Get_Item, UWindowManager* CallFunc_GetWindowManager_ReturnValue_12, bool CallFunc_AnyWindowsOpen_ReturnValue, ASpaceRigBar* K2Node_CustomEvent_Bar_2, bool CallFunc_Not_PreBool_ReturnValue, UWindowManager* CallFunc_GetWindowManager_ReturnValue_13, UUGCSubsystem* CallFunc_GetEngineSubsystem_ReturnValue_1, UUI_Bar_OrderMenu_C* CallFunc_OpenWindowFromClass_ReturnValue_1, bool CallFunc_IsValid_ReturnValue_8, ASpaceRigBar* K2Node_CustomEvent_Bar_1, UDrinkableDataAsset* K2Node_CustomEvent_RequestedDrink, ASpaceRigBar* K2Node_CustomEvent_Bar, UDrinkableDataAsset* K2Node_CustomEvent_Drink, UBP_SpaceRig_Bartender_C* K2Node_DynamicCast_AsBP_Space_Rig_Bartender, bool K2Node_DynamicCast_bSuccess_3, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_13, UWindowManager* CallFunc_GetWindowManager_ReturnValue_14, int32 K2Node_CustomEvent_Amount, bool CallFunc_AnyWindowsOpen_ReturnValue_1, UFSDSaveGame* CallFunc_GetFSDSaveGame_ReturnValue, bool CallFunc_TryDeductCredits_ReturnValue, UUGCSubsystem* CallFunc_GetEngineSubsystem_ReturnValue_2, UUGCSubsystem* CallFunc_GetEngineSubsystem_ReturnValue_3, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_14, bool CallFunc_IsLocalPlayerController_ReturnValue_1, bool CallFunc_IsLocalPlayerController_ReturnValue_2, PlayerDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_11, UPresenceSubSystem* CallFunc_GetGameInstanceSubsystem_ReturnValue, int32 Temp_int_Loop_Counter_Variable_2, bool CallFunc_IsValid_ReturnValue_9, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_2, UUGCSubsystem* CallFunc_GetEngineSubsystem_ReturnValue_4, UGCPackageMounted__DelegateSignature K2Node_CreateDelegate_OutputDelegate_12, UPlayerController* CallFunc_GetPlayerController_ReturnValue_6, UWidget* CallFunc_GetFocusedWidget_ReturnValue_6, TSubclassOf<UPlayerCharacter> K2Node_CustomEvent_CharacterClass, TSubclassOf<AActor> K2Node_CustomEvent_itemClass, EItemCategory K2Node_CustomEvent_ItemCategory, bool CallFunc_IsValid_ReturnValue_10, EmptyOnlineDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_13, UWindowManager* CallFunc_GetWindowManager_ReturnValue_15, UGoogleAnalyticsWrapper* CallFunc_GetGoogleAnalyticsWrapper_ReturnValue, bool CallFunc_IsWindowOpen_ReturnValue_3, UGoogleAnalyticsWrapper* CallFunc_GetGoogleAnalyticsWrapper_ReturnValue_1, int32 K2Node_Event_PlayerID, bool CallFunc_EqualEqual_ByteByte_ReturnValue, UAudioComponent* CallFunc_SpawnSoundAtLocation_ReturnValue, APawn* CallFunc_K2_GetPawn_ReturnValue_1, bool CallFunc_IsLocallyControlled_ReturnValue, uint8 CallFunc_MakeLiteralByte_ReturnValue_2, bool CallFunc_IsPlayInEditor_ReturnValue, FString CallFunc_GetEnumeratorUserFriendlyName_ReturnValue_1, FString CallFunc_Concat_StrStr_ReturnValue_2, FString CallFunc_Concat_StrStr_ReturnValue_3, ABP_DiscordConsole_C* K2Node_CustomEvent_DiscordConsole, bool K2Node_CustomEvent_Usable, UFSDSaveGame* CallFunc_GetFSDSaveGame_ReturnValue_1, UWindowManager* CallFunc_GetWindowManager_ReturnValue_16, ABP_BaseSpaceRigConsole_C* K2Node_CustomEvent_Console, bool K2Node_Event_HasShown, bool K2Node_Event_IsEscapeMenuEnabled, bool CallFunc_IsLocalPlayerController_ReturnValue_3, EmptyOnlineDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_14, UDeepDiveManager* CallFunc_GetDeepDiveManager_ReturnValue, bool CallFunc_IsValid_ReturnValue_11, UFSDPlayerState* CallFunc_GetFSDPlayerState_ReturnValue, UFSDGameModeSpaceRig* CallFunc_GetFSDSRGameMode_ReturnValue, TArray<UDrinkEffectComponent*>& CallFunc_K2_GetComponentsByClass_ReturnValue, AActor* CallFunc_GetPlayerStart_ReturnValue, UDrinkEffectComponent* CallFunc_Array_Get_Item_1, const FTransform CallFunc_GetTransform_ReturnValue, FVector CallFunc_BreakTransform_Location, FRotator CallFunc_BreakTransform_Rotation, FVector CallFunc_BreakTransform_Scale, int32 CallFunc_Array_Length_ReturnValue_1, FTransform CallFunc_MakeTransform_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue_1, FHitResult CallFunc_K2_SetActorTransform_SweepHitResult, bool CallFunc_K2_SetActorTransform_ReturnValue, UFSDPlayerState* CallFunc_GetFSDPlayerState_ReturnValue_1, APawn* CallFunc_K2_GetPawn_ReturnValue_2, UPlayerCharacter* K2Node_DynamicCast_AsPlayer_Character_1, bool K2Node_DynamicCast_bSuccess_4, UPlayerCharacter* K2Node_DynamicCast_AsPlayer_Character_2, bool K2Node_DynamicCast_bSuccess_5, ECharacterSelectorItemStatus Temp_byte_Variable, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_15, UPlayerController* CallFunc_GetPlayerController_ReturnValue_7, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_16, UWindowManager* CallFunc_GetWindowManager_ReturnValue_17, UBasic_Popup_YesNoPrompt_C* CallFunc_OpenWindowFromClass_ReturnValue_2, bool K2Node_CustomEvent_Yes_2, UFSDGameState* CallFunc_GetFSDGameState_ReturnValue, uint8 CallFunc_MakeLiteralByte_ReturnValue_3, int32 CallFunc_Array_Length_ReturnValue_2, bool CallFunc_Less_IntInt_ReturnValue_2, int32 Temp_int_Variable, int32 CallFunc_Add_IntInt_ReturnValue_3, int32 CallFunc_Subtract_IntInt_ReturnValue, bool K2Node_Event_resetToDefaultWeapon, ECharselectionCameraLocation K2Node_Event_cameraLocation, FString CallFunc_GetEnumeratorUserFriendlyName_ReturnValue_2, FString CallFunc_Concat_StrStr_ReturnValue_4, FString CallFunc_Concat_StrStr_ReturnValue_5, uint8 CallFunc_MakeLiteralByte_ReturnValue_4, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_17, ECharacterSelectorItemStatus Temp_byte_Variable_1, ESteamBranch CallFunc_GetSteamBranch_ReturnValue, bool CallFunc_EqualEqual_ByteByte_ReturnValue_1, bool CallFunc_IsPlayInEditor_ReturnValue_1, UWindowManager* CallFunc_GetWindowManager_ReturnValue_18, bool CallFunc_Not_PreBool_ReturnValue_1, bool CallFunc_AnyWindowsOpen_ReturnValue_2, bool CallFunc_BooleanAND_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue_2, bool Temp_bool_Variable_1, TSubclassOf<UObject> Temp_class_Variable, ECharacterSelectorItemStatus K2Node_Select_Default_1, TSubclassOf<UWindowWidget> K2Node_ClassDynamicCast_AsWindow_Widget, bool K2Node_ClassDynamicCast_bSuccess, UWindowWidget* CallFunc_OpenWindowFromClass_ReturnValue_3, uint8 CallFunc_MakeLiteralByte_ReturnValue_5, UPlayerController* CallFunc_GetPlayerController_ReturnValue_8, UDestroySessionCallbackProxy* CallFunc_DestroySession_ReturnValue, FString CallFunc_GetEnumeratorUserFriendlyName_ReturnValue_3, FString CallFunc_Concat_StrStr_ReturnValue_6, FString CallFunc_Concat_StrStr_ReturnValue_7, bool CallFunc_IsValid_ReturnValue_12, UWindowManager* CallFunc_GetWindowManager_ReturnValue_19, UWindowManager* CallFunc_GetWindowManager_ReturnValue_20, UPlayerController* CallFunc_GetPlayerController_ReturnValue_9, bool K2Node_CustomEvent_Yes_1, bool K2Node_CustomEvent_CreateModdedSave_1, bool K2Node_CustomEvent_Yes, bool K2Node_CustomEvent_CreateModdedSave, UUGCRegistry* CallFunc_GetUGCRegistry_ReturnValue, bool K2Node_CustomEvent_Sandbox, UWindowManager* CallFunc_GetWindowManager_ReturnValue_21, OnModdedSaveLoaded__DelegateSignature K2Node_CreateDelegate_OutputDelegate_15, UPopup_ModdedSave_C* CallFunc_OpenSingleUseWindow_ReturnValue, UFSDSaveGame* CallFunc_GetFSDSaveGame_ReturnValue_2, bool CallFunc_GetIsModded_ReturnValue, TSubclassOf<UObject> K2Node_CustomEvent_Loaded, bool CallFunc_Not_PreBool_ReturnValue_3, bool CallFunc_BooleanAND_ReturnValue_1, FKey K2Node_InputKeyEvent_Key_1, UFSDGameState* CallFunc_GetFSDGameState_ReturnValue_1, UFSDPlayerState* K2Node_CustomEvent_PlayerState, FKey Temp_struct_Variable_1, bool CallFunc_EqualEqual_IntInt_ReturnValue, UFSDGameState* CallFunc_GetFSDGameState_ReturnValue_2, FKey K2Node_InputKeyEvent_Key_2, int32 CallFunc_Array_Length_ReturnValue_3, bool CallFunc_Greater_IntInt_ReturnValue_1, UFSDGameState* CallFunc_GetFSDGameState_ReturnValue_3, bool CallFunc_IsPlayInEditor_ReturnValue_2, int32 CallFunc_Array_Length_ReturnValue_4, TArray<UBP_SeasonsConsole_C*>& CallFunc_GetAllActorsOfClass_OutActors, bool CallFunc_EqualEqual_IntInt_ReturnValue_1, UBP_SeasonsConsole_C* CallFunc_Array_Get_Item_2, int32 CallFunc_Array_Length_ReturnValue_5, FKey K2Node_InputKeyEvent_Key_3, bool CallFunc_Greater_IntInt_ReturnValue_2, EInviteBlockReason CallFunc_CanPlayerInvite_ReturnValue, FKey Temp_struct_Variable_2, bool CallFunc_EqualEqual_ByteByte_ReturnValue_2, FKey K2Node_InputKeyEvent_Key_4, bool CallFunc_BooleanAND_ReturnValue_2, UUGCRegistry* CallFunc_GetUGCRegistry_ReturnValue_1, bool CallFunc_IsValid_ReturnValue_13, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_18, bool CallFunc_BooleanAND_ReturnValue_3, UWindowManager* CallFunc_GetWindowManager_ReturnValue_22, UFSDPlayerState* CallFunc_GetFSDPlayerState_ReturnValue_2, UPlayerCharacterID* CallFunc_GetSelectedCharacterID_ReturnValue, uint8 CallFunc_MakeLiteralByte_ReturnValue_6, APawn* CallFunc_K2_GetPawn_ReturnValue_3, bool CallFunc_IsValid_ReturnValue_14, UFSDPlayerState* CallFunc_GetFSDPlayerState_ReturnValue_3, UPlayerCharacterID* CallFunc_GetSelectedCharacterID_ReturnValue_1, FKey K2Node_InputKeyEvent_Key_5, UUserWidget* CallFunc_Array_Get_Item_3, int32 CallFunc_Array_Length_ReturnValue_6, bool CallFunc_Less_IntInt_ReturnValue_3, UFSDGameState* CallFunc_GetFSDGameState_ReturnValue_4, OnYesNoClickedDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_16, UBP_GameState_SpaceRig_C* K2Node_DynamicCast_AsBP_Game_State_Space_Rig, bool K2Node_DynamicCast_bSuccess_6, float K2Node_CustomEvent_NewTime_2, float K2Node_CustomEvent_NewTime_1, FKey K2Node_InputKeyEvent_Key_6, float K2Node_CustomEvent_NewTime, FKey K2Node_InputActionEvent_Key, int32 CallFunc_FCeil_ReturnValue, UFSDGameState* CallFunc_GetFSDGameState_ReturnValue_5, UBP_GameState_SpaceRig_C* K2Node_DynamicCast_AsBP_Game_State_Space_Rig_1, bool K2Node_DynamicCast_bSuccess_7, bool CallFunc_NotEqual_IntInt_ReturnValue, uint8 CallFunc_MakeLiteralByte_ReturnValue_7, FString CallFunc_GetEnumeratorUserFriendlyName_ReturnValue_4, FString CallFunc_Concat_StrStr_ReturnValue_8, FString CallFunc_Concat_StrStr_ReturnValue_9, uint8 CallFunc_MakeLiteralByte_ReturnValue_8, FString CallFunc_GetEnumeratorUserFriendlyName_ReturnValue_5, UWindowManager* CallFunc_GetWindowManager_ReturnValue_23, FString CallFunc_Concat_StrStr_ReturnValue_10, FString CallFunc_Concat_StrStr_ReturnValue_11, UWindowManager* CallFunc_GetWindowManager_ReturnValue_24, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_19, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_20, bool K2Node_CustomEvent_Show, bool CallFunc_NotEqual_BoolBool_ReturnValue, uint8 CallFunc_MakeLiteralByte_ReturnValue_9, float CallFunc_GetWorldDeltaSeconds_ReturnValue, APawn* CallFunc_K2_GetPawn_ReturnValue_4, UPlayerCharacter* K2Node_DynamicCast_AsPlayer_Character_3, bool K2Node_DynamicCast_bSuccess_8, float K2Node_CustomEvent_CurrentGravity, float K2Node_CustomEvent_Change, bool CallFunc_Greater_FloatFloat_ReturnValue, float CallFunc_Multiply_FloatFloat_ReturnValue, FVector CallFunc_MakeVector_ReturnValue, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_21, int32 Temp_int_Variable_1, OnRoundSelected__DelegateSignature K2Node_CreateDelegate_OutputDelegate_17, FKey K2Node_InputActionEvent_Key_1, uint8 CallFunc_MakeLiteralByte_ReturnValue_10, UWND_SpaceRig_Chat_C* CallFunc_Create_ReturnValue, uint8 CallFunc_MakeLiteralByte_ReturnValue_11, FString CallFunc_GetEnumeratorUserFriendlyName_ReturnValue_6, WindowManagerDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_18, FString CallFunc_Concat_StrStr_ReturnValue_12, FString CallFunc_Concat_StrStr_ReturnValue_13, bool CallFunc_IsInActiveSession_ReturnValue, UDestroySessionCallbackProxy* CallFunc_DestroySession_ReturnValue_1, bool CallFunc_IsValid_ReturnValue_15);
    void OnCheatRequested__DelegateSignature();
    void OnOpenedEscapeMenu__DelegateSignature();
    void OnToggleHUD__DelegateSignature();
}

#endif
