#ifndef UE4SS_SDK_BP_ThornVinesChokingWoodRoots_2_HPP
#define UE4SS_SDK_BP_ThornVinesChokingWoodRoots_2_HPP

class ABP_ThornVinesChokingWoodRoots_2_C : ABP_ThornVinesChokingWoodRoots_Base_C
{
}

#endif
