#ifndef UE4SS_SDK_BPL_ProceduralLevelSetup_HPP
#define UE4SS_SDK_BPL_ProceduralLevelSetup_HPP

class UBPL_ProceduralLevelSetup_C : UBlueprintFunctionLibrary
{

    void CreateLinearPathFromDNA(UPLS_Base_C* ProceduralSetup, FVector Origin, FVector PathDirection, float horizontalDeviation, float verticalDeviation, FRandRange PathRoomDistance, bool PlaceFirstRoomAtOrigin, bool AddRoomRadiusToRoomDistance, UMissionDNA*& DNA, FRoomGeneratorGroupInstance& groupInstance, UObject* __WorldContext, FVector& LastOrigin, int32& LastRoomID, URoomGenerator*& LastRoomGenerator, URoomGenerator* RoomGen, float PrevRoomBounds, UPLS_Base_C* Procedural_Setup, FVector CurrentOrigin, int32 CallFunc_Array_LastIndex_ReturnValue, float CallFunc_Add_FloatFloat_ReturnValue, float CallFunc_SelectFloat_ReturnValue, int32 CallFunc_Array_LastIndex_ReturnValue_1, FVector CallFunc_AddRoom_outCenter, FRoomNode CallFunc_AddRoom_outRoom, int32 CallFunc_AddRoom_ReturnValue, FVector CallFunc_FindLocationInDirection_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue, int32 CallFunc_ConnectRoomIds_ReturnValue, int32 Temp_int_Variable, int32 CallFunc_Add_IntInt_ReturnValue, URoomGenerator* CallFunc_GetRandomRoomWithTags_ReturnValue, bool CallFunc_EqualEqual_IntInt_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, FString CallFunc_GetDisplayName_ReturnValue, FString CallFunc_Concat_StrStr_ReturnValue, bool CallFunc_LessEqual_IntInt_ReturnValue);
    void CreateLinearPath(UPLS_Base_C* ProceduralSetup, FVector Origin, FVector& PathDirection, FVector2D& GraphDeviation, int32 RoomCount, TArray<URoomGenerator*>& PathRooms, FRandRange& PathRoomDistance, bool PlaceFirstRoomAtOrigin, UObject* __WorldContext, FVector& LastOrigin, int32& LastRoomID, UPLS_Base_C* Procedural_Setup, FVector CurrentOrigin, FWeightedRoomSelector WeightedRooms, int32 CallFunc_Subtract_IntInt_ReturnValue, float CallFunc_BreakVector2D_X, float CallFunc_BreakVector2D_Y, int32 Temp_int_Variable, bool CallFunc_EqualEqual_IntInt_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, int32 CallFunc_Array_LastIndex_ReturnValue, FRoomNode CallFunc_Array_Get_Item, bool CallFunc_LessEqual_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, URoomGenerator* CallFunc_SelectRandomRoom_ReturnValue, FVector CallFunc_FindLocationInDirection_ReturnValue, FVector CallFunc_AddRoom_outCenter, FRoomNode CallFunc_AddRoom_outRoom, int32 CallFunc_AddRoom_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue_1, int32 CallFunc_ConnectRoomIds_ReturnValue);
    void CreateLinearPathGrouped(UPLS_Base_C* ProceduralSetup, FVector Origin, FVector PathDirection, int32 RoomCount, float horizontalDeviation, float verticalDeviation, FRandRange PathRoomDistance, TArray<URoomGeneratorGroup*>& RoomGroups, bool PlaceFirstRoomAtOrigin, bool AddRoomRadiusToRoomDistance, UObject* __WorldContext, FVector& LastOrigin, int32& LastRoomID, URoomGenerator*& LastRoomGenerator, float PrevRoomBounds, int32 roomIndex, TArray<URoomGeneratorGroup*> Room_Groups, UPLS_Base_C* Procedural_Setup, FVector CurrentOrigin, int32 CallFunc_Subtract_IntInt_ReturnValue, int32 Temp_int_Variable, bool CallFunc_EqualEqual_IntInt_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, bool CallFunc_LessEqual_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Array_LastIndex_ReturnValue, int32 CallFunc_RandomIntegerInRangeFromStream_ReturnValue, int32 CallFunc_Array_LastIndex_ReturnValue_1, URoomGeneratorGroup* CallFunc_Array_Get_Item, URoomGenerator* CallFunc_GetRandomRoom_ReturnValue, FVector CallFunc_AddRoom_outCenter, FRoomNode CallFunc_AddRoom_outRoom, int32 CallFunc_AddRoom_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue_1, int32 CallFunc_ConnectRoomIds_ReturnValue, float CallFunc_Add_FloatFloat_ReturnValue, float CallFunc_SelectFloat_ReturnValue, FVector CallFunc_FindLocationInDirection_ReturnValue);
}

#endif
