#ifndef UE4SS_SDK_Cheat_List_VictoryMoves_HPP
#define UE4SS_SDK_Cheat_List_VictoryMoves_HPP

class UCheat_List_VictoryMoves_C : UCheat_EquipList_C
{

    void Refresh(UVictoryPose* Equipped, UPlayerCharacterID* characterID, UVictoryPose* VictoryPose, UCheat_EquipList_Entry_C* Entry, bool CallFunc_IsValid_ReturnValue, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_IsUnlockedNotFromStart_ReturnValue, bool CallFunc_EqualEqual_ObjectObject_ReturnValue, UVictoryPose* CallFunc_GetEquippedVictoryPose_ReturnValue, UPlayerCharacterID* CallFunc_GetCharacterID_CharacterID, OnOwnedClicked__DelegateSignature K2Node_CreateDelegate_OutputDelegate, UCheat_EquipList_Entry_C* CallFunc_AddEntry_OutEntryWidget, OnEquipClicked__DelegateSignature K2Node_CreateDelegate_OutputDelegate_1, UGameData* CallFunc_GetFSDGameData_ReturnValue, const TArray<UVictoryPose*>& CallFunc_GetVictoryPoses_ReturnValue, UVictoryPose* CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue);
    void GetCharacter(UPlayerCharacter*& OutCharacter, APawn* CallFunc_GetOwningPlayerPawn_ReturnValue, UPlayerCharacter* K2Node_DynamicCast_AsPlayer_Character, bool K2Node_DynamicCast_bSuccess);
    void ReceiveEntryOwnedClick(UCheat_EquipList_Entry_C* InEntryWidget, UObject* InData, bool InOwned, UPlayerCharacterID* CallFunc_GetCharacterID_CharacterID, UVictoryPose* K2Node_DynamicCast_AsVictory_Pose, bool K2Node_DynamicCast_bSuccess);
    void ReceiveEntryEquipClick(UCheat_EquipList_Entry_C* InEntryWidget, UObject* InData, bool InEquipped, UCheat_EquipList_Entry_C* OtherEntry, bool CallFunc_Not_PreBool_ReturnValue, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, TArray<UCheat_EquipList_Entry_C*>& CallFunc_GetEntries_OutEntries, UCheat_EquipList_Entry_C* CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_EqualEqual_ObjectObject_ReturnValue, UPlayerCharacterID* CallFunc_GetCharacterID_CharacterID, bool CallFunc_EqualEqual_IntInt_ReturnValue, UVictoryPose* K2Node_DynamicCast_AsVictory_Pose, bool K2Node_DynamicCast_bSuccess);
    void GetCharacterID(UPlayerCharacterID*& characterID, APawn* CallFunc_GetOwningPlayerPawn_ReturnValue, UPlayerCharacter* K2Node_DynamicCast_AsPlayer_Character, bool K2Node_DynamicCast_bSuccess);
}

#endif
