#ifndef UE4SS_SDK_Cheat_OverclockSelection_HPP
#define UE4SS_SDK_Cheat_OverclockSelection_HPP

class UCheat_OverclockSelection_C : UUserWidget
{
    FPointerToUberGraphFrame UberGraphFrame;
    UBorder* Border_0;
    UScrollBox* SB_OverclockList;
    TArray<UCheat_PerkListItem_C*> perklistItems;

    void Initiate widget(EItemCategory ItemCategory);
    void On state change(bool is Checked, UItemUpgrade* Item, EItemCategory Item Category);
    void ExecuteUbergraph_Cheat_OverclockSelection(int32 EntryPoint, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue, OnCheckStateChanged__DelegateSignature K2Node_CreateDelegate_OutputDelegate, UFSDPlayerState* CallFunc_GetPlayerState_ReturnValue, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable_1, int32 Temp_int_Loop_Counter_Variable_1, int32 CallFunc_Add_IntInt_ReturnValue_1, EItemCategory K2Node_CustomEvent_ItemCategory, UPlayerController* CallFunc_GetOwningPlayer_ReturnValue, UFSDSaveGame* CallFunc_GetFSDSaveGame_ReturnValue, UCheat_PerkListItem_C* CallFunc_Create_ReturnValue, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_1, TSubclassOf<UPlayerCharacter> CallFunc_GetObjectClass_ReturnValue, UPlayerCharacterID* CallFunc_GetCharacterID_ReturnValue, UPanelSlot* CallFunc_AddChild_ReturnValue, TSubclassOf<AActor> CallFunc_GetEquippedItem_ReturnValue, UItemUpgrade* CallFunc_GetEquippedOverclock_ReturnValue, UUpgradableGearComponent* CallFunc_GetComponentFromClass_ReturnValue, bool K2Node_CustomEvent_Is_Checked, UItemUpgrade* K2Node_CustomEvent_Item, EItemCategory K2Node_CustomEvent_item_category, bool CallFunc_IsValid_ReturnValue, const TArray<UItemUpgrade*>& CallFunc_GetOverClocks_ReturnValue, UFSDSaveGame* CallFunc_GetFSDSaveGame_ReturnValue_1, UItemUpgrade* CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_EqualEqual_ObjectObject_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_1, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_2, bool CallFunc_LessEqual_IntInt_ReturnValue, TSubclassOf<AActor> CallFunc_GetEquippedItem_ReturnValue_1, int32 CallFunc_Array_AddUnique_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_2, UCheat_PerkListItem_C* CallFunc_Array_Get_Item_1, bool CallFunc_Less_IntInt_ReturnValue_1, bool CallFunc_NotEqual_ObjectObject_ReturnValue);
}

#endif
