#ifndef UE4SS_SDK_HUD_SpaceRig_NotificationsManager_HPP
#define UE4SS_SDK_HUD_SpaceRig_NotificationsManager_HPP

class UHUD_SpaceRig_NotificationsManager_C : UUserWidget
{
    FPointerToUberGraphFrame UberGraphFrame;
    UVerticalBox* EntryBox;
    UHUD_Milestone_Manager_C* HUD_Milestone_Manager;
    UBP_GameInstance_C* BP_GameInstance;

    void Construct();
    void CheckForNewNotifications(UFSDGameInstance* GameInstance);
    void CreateNotificationWidget(FSpaceRigNotification Notification);
    void CheckCraftingNotification();
    void ExecuteUbergraph_HUD_SpaceRig_NotificationsManager(int32 EntryPoint, NewSpaceRigNotification__DelegateSignature K2Node_CreateDelegate_OutputDelegate, ItemUINotificationDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_1, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_1, UBP_GameInstance_C* K2Node_DynamicCast_AsBP_Game_Instance, bool K2Node_DynamicCast_bSuccess, UFSDGameInstance* K2Node_CustomEvent_GameInstance, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_2, FSpaceRigNotification K2Node_CustomEvent_Notification, FSpaceRigNotification CallFunc_GetNextSpaceRigNotification_NextNotification, bool CallFunc_GetNextSpaceRigNotification_ReturnValue, UPlayerController* CallFunc_GetOwningPlayer_ReturnValue, UHUD_SpaceRig_Notification_C* CallFunc_Create_ReturnValue, UVerticalBoxSlot* CallFunc_AddChildToVerticalBox_ReturnValue, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_3, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_4, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_5, FLinearColor CallFunc_MenuColors_OutputColor, UFSDSaveGame* CallFunc_GetFSDSaveGame_ReturnValue, FSpaceRigNotification K2Node_MakeStruct_SpaceRigNotification, UGameData* CallFunc_GetFSDGameData_ReturnValue, TArray<UObject*>& K2Node_MakeArray_Array, bool CallFunc_CheckItemUINotification_HasNotification);
}

#endif
