#ifndef UE4SS_SDK_ITM_BarGlass_Item_FlintlockesDelight_HPP
#define UE4SS_SDK_ITM_BarGlass_Item_FlintlockesDelight_HPP

class AITM_BarGlass_Item_FlintlockesDelight_C : UITM_BarGlass_Item_C
{
}

#endif
