#ifndef UE4SS_SDK_ITM_CommunityGoal_TotalProgress_HPP
#define UE4SS_SDK_ITM_CommunityGoal_TotalProgress_HPP

class UITM_CommunityGoal_TotalProgress_C : UFSDUserWidget
{
    FPointerToUberGraphFrame UberGraphFrame;
    UButton* BackgroundButton;
    UButton* Button_Goal_0;
    UButton* Button_Goal_1;
    UButton* Button_Goal_2;
    UButton* Button_Goal_3;
    UButton* Button_Goal_4;
    UButton* Button_Goal_5;
    UButton* Button_Goal_6;
    UButton* Button_Goal_7;
    UButton* Button_Goal_8;
    UCheckBox* CheckBox_Goal_0;
    UCheckBox* CheckBox_Goal_1;
    UCheckBox* CheckBox_Goal_2;
    UCheckBox* CheckBox_Goal_3;
    UCheckBox* CheckBox_Goal_4;
    UCheckBox* CheckBox_Goal_5;
    UCheckBox* CheckBox_Goal_6;
    UCheckBox* CheckBox_Goal_7;
    UCheckBox* CheckBox_Goal_8;
    UButton* FactionIconToolTip;
    UImage* Image_132;
    UImage* Image_524;
    UImage* Image_Goal_0;
    UImage* Image_Goal_1;
    UImage* Image_Goal_2;
    UImage* Image_Goal_3;
    UImage* Image_Goal_4;
    UImage* Image_Goal_5;
    UImage* Image_Goal_6;
    UImage* Image_Goal_7;
    UImage* Image_Goal_8;
    UProgressBar* ProgressBar_0;
    UProgressBar* ProgressBar_1;
    UProgressBar* ProgressBar_2;
    UProgressBar* ProgressBar_3;
    UProgressBar* ProgressBar_4;
    UProgressBar* ProgressBar_5;
    UProgressBar* ProgressBar_6;
    UProgressBar* ProgressBar_7;
    UProgressBar* ProgressBar_8;
    UTextBlock* Title_Text;
    UUI_ImageTinted_C* UI_ImageTinted;
    float AnimTime;
    float TotalAnimTime;
    float CurrentProgress;
    float CurrentlyTopGoalProgress;
    float ProgressBarAnimSpeed;
    bool Show_Title;
    FLinearColor CheckColorTier1;
    FLinearColor UnCheckColorTier1;
    FLinearColor CheckColorTier2;
    FLinearColor UnCheckColorTier2;
    FLinearColor CheckColorTier3;
    FLinearColor UnCheckColorTier3;
    FLinearColor BarColor;
    FITM_CommunityGoal_TotalProgress_CHoverStarted HoverStarted;
    void HoverStarted(UCommunityGoalFaction* Faction, UCommunityGoal* Goal);
    FITM_CommunityGoal_TotalProgress_CHoverEnded HoverEnded;
    void HoverEnded();
    UITM_CommunityGoalRewardToolTip_C* ToolTip;
    UITM_FactionToolTip_C* FactionToolTip;

    void DoFactionToolTip(bool CallFunc_IsValid_ReturnValue, UUserWidget* CallFunc_CreateToolTip_OutToolTip, UITM_FactionToolTip_C* K2Node_DynamicCast_AsITM_Faction_Tool_Tip, bool K2Node_DynamicCast_bSuccess);
    void SendButtonToolTipOpen(UWidget* Button, int32 Tier, UUserWidget* CallFunc_CreateToolTip_OutToolTip, bool CallFunc_IsValid_ReturnValue, UITM_CommunityGoalRewardToolTip_C* K2Node_DynamicCast_AsITM_Community_Goal_Reward_Tool_Tip, bool K2Node_DynamicCast_bSuccess);
    FLinearColor Get_Image_Goal_8_ColorAndOpacity_0(bool CallFunc_IsChecked_ReturnValue);
    FLinearColor Get_Image_Goal_7_ColorAndOpacity_0(bool CallFunc_IsChecked_ReturnValue);
    FLinearColor Get_Image_Goal_6_ColorAndOpacity_0(bool CallFunc_IsChecked_ReturnValue);
    FLinearColor Get_Image_Goal_5_ColorAndOpacity_0(bool CallFunc_IsChecked_ReturnValue);
    FLinearColor Get_Image_Goal_4_ColorAndOpacity_0(bool CallFunc_IsChecked_ReturnValue);
    FLinearColor Get_Image_Goal_3_ColorAndOpacity_0(bool CallFunc_IsChecked_ReturnValue);
    FLinearColor Get_Image_Goal_2_ColorAndOpacity_0(bool CallFunc_IsChecked_ReturnValue);
    FLinearColor Get_Image_Goal_1_ColorAndOpacity_0(bool CallFunc_IsChecked_ReturnValue);
    FLinearColor Get_Image_Goal_0_ColorAndOpacity_0(bool CallFunc_IsChecked_ReturnValue);
    void IncreaseTotalGoalsProgressByGoal(UCommunityGoal* Goal, float Value, int32 memberCount, float ThisGoalProgress, int32 CallFunc_FFloor_ReturnValue, float CallFunc_Conv_IntToFloat_ReturnValue, float CallFunc_Subtract_FloatFloat_ReturnValue, bool CallFunc_Greater_FloatFloat_ReturnValue, float CallFunc_TierProgress_ReturnValue, float CallFunc_TierProgress_ReturnValue_1, float CallFunc_FClamp_ReturnValue, float CallFunc_FClamp_ReturnValue_1, bool CallFunc_GreaterEqual_FloatFloat_ReturnValue, bool CallFunc_GreaterEqual_FloatFloat_ReturnValue_1, float CallFunc_Conv_BoolToFloat_ReturnValue, float CallFunc_Conv_BoolToFloat_ReturnValue_1, float CallFunc_TierProgress_ReturnValue_2, bool CallFunc_GreaterEqual_FloatFloat_ReturnValue_2, float CallFunc_FClamp_ReturnValue_2, float CallFunc_Conv_BoolToFloat_ReturnValue_2, float CallFunc_Add_FloatFloat_ReturnValue, float CallFunc_Add_FloatFloat_ReturnValue_1, float CallFunc_Add_FloatFloat_ReturnValue_2, float CallFunc_Add_FloatFloat_ReturnValue_3, float CallFunc_Add_FloatFloat_ReturnValue_4);
    float ProgressBar_8_Percent_0(bool Temp_bool_Variable, uint8 Temp_byte_Variable, uint8 Temp_byte_Variable_1, float CallFunc_Subtract_FloatFloat_ReturnValue, float CallFunc_Subtract_FloatFloat_ReturnValue_1, bool CallFunc_Less_FloatFloat_ReturnValue, float CallFunc_FMax_ReturnValue, float CallFunc_FMin_ReturnValue, uint8 K2Node_Select_Default, float CallFunc_Subtract_FloatFloat_ReturnValue_2, float CallFunc_FMin_ReturnValue_1, float CallFunc_Ease_ReturnValue, float CallFunc_FMin_ReturnValue_2, bool CallFunc_GreaterEqual_FloatFloat_ReturnValue);
    float ProgressBar_7_Percent_0(bool Temp_bool_Variable, uint8 Temp_byte_Variable, uint8 Temp_byte_Variable_1, float CallFunc_Subtract_FloatFloat_ReturnValue, float CallFunc_Subtract_FloatFloat_ReturnValue_1, bool CallFunc_Less_FloatFloat_ReturnValue, float CallFunc_FMax_ReturnValue, float CallFunc_FMin_ReturnValue, uint8 K2Node_Select_Default, float CallFunc_Subtract_FloatFloat_ReturnValue_2, float CallFunc_FMin_ReturnValue_1, float CallFunc_Ease_ReturnValue, float CallFunc_FMin_ReturnValue_2, bool CallFunc_GreaterEqual_FloatFloat_ReturnValue);
    float ProgressBar_6_Percent_0(bool Temp_bool_Variable, uint8 Temp_byte_Variable, uint8 Temp_byte_Variable_1, float CallFunc_Subtract_FloatFloat_ReturnValue, float CallFunc_Subtract_FloatFloat_ReturnValue_1, bool CallFunc_Less_FloatFloat_ReturnValue, float CallFunc_FMax_ReturnValue, float CallFunc_FMin_ReturnValue, uint8 K2Node_Select_Default, float CallFunc_Subtract_FloatFloat_ReturnValue_2, float CallFunc_FMin_ReturnValue_1, float CallFunc_Ease_ReturnValue, float CallFunc_FMin_ReturnValue_2, bool CallFunc_GreaterEqual_FloatFloat_ReturnValue);
    float ProgressBar_5_Percent_0(bool Temp_bool_Variable, uint8 Temp_byte_Variable, uint8 Temp_byte_Variable_1, float CallFunc_Subtract_FloatFloat_ReturnValue, float CallFunc_Subtract_FloatFloat_ReturnValue_1, bool CallFunc_Less_FloatFloat_ReturnValue, float CallFunc_FMax_ReturnValue, float CallFunc_FMin_ReturnValue, uint8 K2Node_Select_Default, float CallFunc_Subtract_FloatFloat_ReturnValue_2, float CallFunc_FMin_ReturnValue_1, float CallFunc_Ease_ReturnValue, float CallFunc_FMin_ReturnValue_2, bool CallFunc_GreaterEqual_FloatFloat_ReturnValue);
    float ProgressBar_4_Percent_0(bool Temp_bool_Variable, uint8 Temp_byte_Variable, uint8 Temp_byte_Variable_1, float CallFunc_Subtract_FloatFloat_ReturnValue, float CallFunc_Subtract_FloatFloat_ReturnValue_1, bool CallFunc_Less_FloatFloat_ReturnValue, float CallFunc_FMax_ReturnValue, float CallFunc_FMin_ReturnValue, uint8 K2Node_Select_Default, float CallFunc_Subtract_FloatFloat_ReturnValue_2, float CallFunc_FMin_ReturnValue_1, float CallFunc_Ease_ReturnValue, float CallFunc_FMin_ReturnValue_2, bool CallFunc_GreaterEqual_FloatFloat_ReturnValue);
    float ProgressBar_3_Percent_0(bool Temp_bool_Variable, uint8 Temp_byte_Variable, uint8 Temp_byte_Variable_1, float CallFunc_Subtract_FloatFloat_ReturnValue, float CallFunc_Subtract_FloatFloat_ReturnValue_1, bool CallFunc_Less_FloatFloat_ReturnValue, float CallFunc_FMax_ReturnValue, float CallFunc_FMin_ReturnValue, uint8 K2Node_Select_Default, float CallFunc_Subtract_FloatFloat_ReturnValue_2, float CallFunc_FMin_ReturnValue_1, float CallFunc_Ease_ReturnValue, float CallFunc_FMin_ReturnValue_2, bool CallFunc_GreaterEqual_FloatFloat_ReturnValue);
    float ProgressBar_2_Percent_0(bool Temp_bool_Variable, uint8 Temp_byte_Variable, uint8 Temp_byte_Variable_1, float CallFunc_Subtract_FloatFloat_ReturnValue, float CallFunc_Subtract_FloatFloat_ReturnValue_1, bool CallFunc_Less_FloatFloat_ReturnValue, float CallFunc_FMax_ReturnValue, float CallFunc_FMin_ReturnValue, uint8 K2Node_Select_Default, float CallFunc_Subtract_FloatFloat_ReturnValue_2, float CallFunc_FMin_ReturnValue_1, float CallFunc_Ease_ReturnValue, float CallFunc_FMin_ReturnValue_2, bool CallFunc_GreaterEqual_FloatFloat_ReturnValue);
    float ProgressBar_1_Percent_0(bool Temp_bool_Variable, uint8 Temp_byte_Variable, uint8 Temp_byte_Variable_1, float CallFunc_Subtract_FloatFloat_ReturnValue, float CallFunc_Subtract_FloatFloat_ReturnValue_1, bool CallFunc_Less_FloatFloat_ReturnValue, float CallFunc_FMax_ReturnValue, float CallFunc_FMin_ReturnValue, uint8 K2Node_Select_Default, float CallFunc_Subtract_FloatFloat_ReturnValue_2, float CallFunc_FMin_ReturnValue_1, float CallFunc_Ease_ReturnValue, float CallFunc_FMin_ReturnValue_2, bool CallFunc_GreaterEqual_FloatFloat_ReturnValue);
    float ProgressBar_0_Percent_0(bool Temp_bool_Variable, uint8 Temp_byte_Variable, uint8 Temp_byte_Variable_1, bool CallFunc_Less_FloatFloat_ReturnValue, float CallFunc_FMin_ReturnValue, uint8 K2Node_Select_Default, float CallFunc_FMin_ReturnValue_1, float CallFunc_Ease_ReturnValue, float CallFunc_FMin_ReturnValue_2, bool CallFunc_GreaterEqual_FloatFloat_ReturnValue);
    void ResetAnim();
    void PreConstruct(bool IsDesignTime);
    void Tick(FGeometry MyGeometry, float InDeltaTime);
    void SetGoals(const TArray<FString>& GoalID, const TArray<float>& GoalValue, const TArray<int32>& Members);
    void SetGoalsTier(float TierProgress);
    void BndEvt__BackgroundButton_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__BackgroundButton_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__Button_Goal_1_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__Button_Goal_0_K2Node_ComponentBoundEvent_3_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__Button_Goal_2_K2Node_ComponentBoundEvent_4_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__Button_Goal_3_K2Node_ComponentBoundEvent_6_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__Button_Goal_4_K2Node_ComponentBoundEvent_7_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__Button_Goal_5_K2Node_ComponentBoundEvent_8_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__Button_Goal_6_K2Node_ComponentBoundEvent_9_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__Button_Goal_7_K2Node_ComponentBoundEvent_10_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__Button_Goal_8_K2Node_ComponentBoundEvent_11_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__Button_Goal_0_K2Node_ComponentBoundEvent_12_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__Button_Goal_1_K2Node_ComponentBoundEvent_13_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__Button_Goal_2_K2Node_ComponentBoundEvent_14_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__Button_Goal_4_K2Node_ComponentBoundEvent_15_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__Button_Goal_3_K2Node_ComponentBoundEvent_16_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__Button_Goal_5_K2Node_ComponentBoundEvent_17_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__Button_Goal_6_K2Node_ComponentBoundEvent_18_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__Button_Goal_7_K2Node_ComponentBoundEvent_19_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__Button_Goal_8_K2Node_ComponentBoundEvent_20_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__FactionIconToolTip_K2Node_ComponentBoundEvent_5_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__FactionIconToolTip_K2Node_ComponentBoundEvent_21_OnButtonHoverEvent__DelegateSignature();
    void Construct();
    void ExecuteUbergraph_ITM_CommunityGoal_TotalProgress(int32 EntryPoint, ESlateVisibility Temp_byte_Variable, UUserWidget* CallFunc_CreateToolTip_OutToolTip, UITM_FactionToolTip_C* K2Node_DynamicCast_AsITM_Faction_Tool_Tip, bool K2Node_DynamicCast_bSuccess, ESlateVisibility Temp_byte_Variable_1, bool CallFunc_IsValid_ReturnValue, bool K2Node_Event_IsDesignTime, FGeometry K2Node_Event_MyGeometry, float K2Node_Event_InDeltaTime, float CallFunc_Add_FloatFloat_ReturnValue, bool CallFunc_GreaterEqual_FloatFloat_ReturnValue, const TArray<FString>& K2Node_CustomEvent_GoalID, const TArray<float>& K2Node_CustomEvent_GoalValue, const TArray<int32>& K2Node_CustomEvent_Members, bool Temp_bool_Variable, int32 CallFunc_Array_Length_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_1, int32 CallFunc_Array_Length_ReturnValue_2, int32 Temp_int_Variable, int32 CallFunc_Min_ReturnValue, int32 CallFunc_Min_ReturnValue_1, int32 CallFunc_Subtract_IntInt_ReturnValue, bool CallFunc_LessEqual_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, UGameData* CallFunc_GetFSDGameData_ReturnValue, UCommunityGoal* CallFunc_FindGoal_ReturnValue, float CallFunc_Add_FloatFloat_ReturnValue_1, float CallFunc_Multiply_FloatFloat_ReturnValue, float CallFunc_Add_FloatFloat_ReturnValue_2, float CallFunc_FMin_ReturnValue, ESlateVisibility K2Node_Select_Default, float K2Node_CustomEvent_TierProgress);
    void HoverEnded__DelegateSignature();
    void HoverStarted__DelegateSignature(UCommunityGoalFaction* Faction, UCommunityGoal* Goal);
}

#endif
