#ifndef UE4SS_SDK_ITM_Grenade_HE_Base_HPP
#define UE4SS_SDK_ITM_Grenade_HE_Base_HPP

class AITM_Grenade_HE_Base_C : UITM_Grenade_Base_C
{
    FPointerToUberGraphFrame UberGraphFrame;
    UDamageComponent* Damage;
    UExplosionComponent* Explosion;
    UParticleSystem* ExplosionParticles;
    USoundBase* ExplosionSound;

    void AddGearStateEntries(UFSDPlayerState* PlayerState, TArray<FGearStatEntry>& Stats, TSubclassOf<UITM_Grenade_HE_Base_C> CallFunc_GetObjectClass_ReturnValue, FGearStatEntry CallFunc_UPGDESC_Damage_GearStatEntry, bool CallFunc_UPGDESC_Damage_HasUpgradedValue, int32 CallFunc_Array_Add_ReturnValue, TSubclassOf<UITM_Grenade_HE_Base_C> CallFunc_GetObjectClass_ReturnValue_1, FGearStatEntry CallFunc_UPGDESC_Damage_GearStatEntry_1, bool CallFunc_UPGDESC_Damage_HasUpgradedValue_1, int32 CallFunc_Array_Add_ReturnValue_1, TSubclassOf<UITM_Grenade_HE_Base_C> CallFunc_GetObjectClass_ReturnValue_2, FGearStatEntry CallFunc_UPGDESC_Damage_GearStatEntry_2, bool CallFunc_UPGDESC_Damage_HasUpgradedValue_2, int32 CallFunc_Array_Add_ReturnValue_2, TSubclassOf<UITM_Grenade_HE_Base_C> CallFunc_GetObjectClass_ReturnValue_3, FGearStatEntry CallFunc_UPGDESC_Damage_GearStatEntry_3, bool CallFunc_UPGDESC_Damage_HasUpgradedValue_3, int32 CallFunc_Array_Add_ReturnValue_3);
    void OnExploded();
    void ExecuteUbergraph_ITM_Grenade_HE_Base(int32 EntryPoint, FVector CallFunc_K2_GetActorLocation_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue_1, bool CallFunc_IsCloseToLocalPlayer_ReturnValue, bool CallFunc_IsCloseToLocalPlayer_ReturnValue_1, bool CallFunc_HasAuthority_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue_2, UCharacter* CallFunc_GetPlayerCharacter_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue_3, bool CallFunc_IsInRangeOfLocalPlayer_ReturnValue, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue_4);
}

#endif
