#ifndef UE4SS_SDK_ITM_Prerequisites_HPP
#define UE4SS_SDK_ITM_Prerequisites_HPP

class UITM_Prerequisites_C : UUserWidget
{
    UHorizontalBox* PrereqHolder;
    UTextBlock* TXT_Prereqs;
    UCampaign* Campaign;
    bool ShowText;

    void SetData(UCampaign* Campaign, bool& RequirementsMet, ESlateVisibility Temp_byte_Variable, ESlateVisibility Temp_byte_Variable_1, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, bool Temp_bool_Variable, bool CallFunc_Not_PreBool_ReturnValue, UPlayerController* CallFunc_GetOwningPlayer_ReturnValue, UFSDPlayerController* K2Node_DynamicCast_AsFSDPlayer_Controller, bool K2Node_DynamicCast_bSuccess, UCampaignRequirement* CallFunc_Array_Get_Item, ESlateVisibility K2Node_Select_Default, UPlayerRankCampaignRequirement* K2Node_DynamicCast_AsPlayer_Rank_Campaign_Requirement, bool K2Node_DynamicCast_bSuccess_1, UCaracterLevelCampaignRequirement* K2Node_DynamicCast_AsCaracter_Level_Campaign_Requirement, bool K2Node_DynamicCast_bSuccess_2, URetirementCampaignRequirement* K2Node_DynamicCast_AsRetirement_Campaign_Requirement, bool K2Node_DynamicCast_bSuccess_3, UValidWeeklySeedCampaignRequirement* K2Node_DynamicCast_AsValid_Weekly_Seed_Campaign_Requirement, bool K2Node_DynamicCast_bSuccess_4, UCamapaignCompletedRequirement* K2Node_DynamicCast_AsCamapaign_Completed_Requirement, bool K2Node_DynamicCast_bSuccess_5, UAnyRetiredCampaignRequirement* K2Node_DynamicCast_AsAny_Retired_Campaign_Requirement, bool K2Node_DynamicCast_bSuccess_6, bool CallFunc_IsRequirementMet_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue_1, bool CallFunc_Less_IntInt_ReturnValue);
    void CreateValidSeedRequirement(UCampaignRequirement* Requirement, UCampaign* Campaign, UPlayerController* CallFunc_GetOwningPlayer_ReturnValue, UPlayerController* CallFunc_GetOwningPlayer_ReturnValue_1, UITM_ValidSeedRequirement_C* CallFunc_Create_ReturnValue, UFSDPlayerController* K2Node_DynamicCast_AsFSDPlayer_Controller, bool K2Node_DynamicCast_bSuccess, UPanelSlot* CallFunc_AddChild_ReturnValue, bool CallFunc_IsRequirementMet_ReturnValue);
    void CreateCampaignCompletedRequirement(UCampaignRequirement* Requirement, UCampaign* Campaign, UPlayerController* CallFunc_GetOwningPlayer_ReturnValue, UPlayerController* CallFunc_GetOwningPlayer_ReturnValue_1, UITM_CampaignCompletedRequirement_C* CallFunc_Create_ReturnValue, UFSDPlayerController* K2Node_DynamicCast_AsFSDPlayer_Controller, bool K2Node_DynamicCast_bSuccess, UPanelSlot* CallFunc_AddChild_ReturnValue, bool CallFunc_IsRequirementMet_ReturnValue);
    void CreateAnyRequirement(UCampaignRequirement* Requirenent, UCampaign* Campaign, UPlayerController* CallFunc_GetOwningPlayer_ReturnValue, UPlayerController* CallFunc_GetOwningPlayer_ReturnValue_1, UITM_AnyRetiredRequirement_C* CallFunc_Create_ReturnValue, UFSDPlayerController* K2Node_DynamicCast_AsFSDPlayer_Controller, bool K2Node_DynamicCast_bSuccess, UPanelSlot* CallFunc_AddChild_ReturnValue, bool CallFunc_IsRequirementMet_ReturnValue);
    void CreatePlayerRankBox(int32 Required Rank, FLinearColor CallFunc_MenuColors_OutputColor, FText CallFunc_Conv_IntToText_ReturnValue, UPlayerController* CallFunc_GetOwningPlayer_ReturnValue, UITM_JobsEntry_Resource_C* CallFunc_Create_ReturnValue, UPanelSlot* CallFunc_AddChild_ReturnValue);
    void CreateLevelRequirementBox(int32 RequiredLevel, UPlayerCharacterID* ID, UPlayerController* CallFunc_GetOwningPlayer_ReturnValue, UITM_ClassLevelRequirement_C* CallFunc_Create_ReturnValue, UPanelSlot* CallFunc_AddChild_ReturnValue);
}

#endif
