#ifndef UE4SS_SDK_Menu_Cheats_HPP
#define UE4SS_SDK_Menu_Cheats_HPP

class UMenu_Cheats_C : UWindowWidget
{
    FPointerToUberGraphFrame UberGraphFrame;
    UButton* ActivateCommonCheatsButton;
    UMenuAnchor* AdvEnemySpawn;
    USpinBox* AnselDistanceSpinBox;
    USpinBox* AnselSpeedSpinBox;
    UScrollBox* BoscoUpgradePanel;
    UButton* Button_AdvancedEnemyspawn;
    UButton* Button_Bosco;
    UButton* Button_Character;
    UButton* Button_Close;
    UButton* Button_Driller;
    UButton* Button_Engineer;
    UButton* Button_General;
    UButton* Button_Gunner;
    UButton* Button_Info;
    UButton* Button_Mission;
    UButton* Button_ReloadChar;
    UButton* Button_Scout;
    UButton* Button_SpawnMinimule;
    UButton* Button_Vanity;
    UCheat_AddGold_C* Cheat_AddGold;
    UCheat_AddMorkite_C* Cheat_AddMorkite;
    UCheat_AddNitra_C* Cheat_AddNitra;
    UCheat_CharacterPointLight_C* Cheat_CharacterPointLight;
    UCheat_CompleteMission_C* Cheat_CompleteMission;
    UCheat_ConsoleCmd_C* Cheat_ConsoleCmd;
    UCheat_ConsoleCmd_C* Cheat_ConsoleCmd_C_0;
    UCheat_FlyMode_C* Cheat_DebugCam;
    UCheat_DestroyAllFlares_C* Cheat_DestroyAllFlares;
    UCheat_DestroyMolly_C* Cheat_DestroyMolly;
    UCheat_FastMovement_C* Cheat_FastMovement;
    UCheat_MiscUpgradesItem_C* Cheat_FifthItem;
    UCheat_MiscUpgradesItem_C* Cheat_FirstItem;
    UCheat_MiscUpgradesItem_C* Cheat_FourthItem;
    UCheat_GiveBeerBuff_C* Cheat_GiveBeerBuff;
    UCheat_God_C* Cheat_God;
    UCheat_JumpToNextRoom_C* Cheat_JumpToNextRoom;
    UCheat_KillAll_C* Cheat_KillAll_20;
    UCheat_LevelScale_C* Cheat_LevelScale;
    UCheat_MaterialInfo_C* Cheat_MaterialInfo_C_2;
    UCheat_MaterialInfo_C* Cheat_MaterialInfo_C_3;
    UCheat_MaterialInfo_C* Cheat_MaterialInfo_C_4;
    UCheat_QuadPickAxe_C* Cheat_QuadPickAxe;
    UCheat_QuickLight_C* Cheat_QuickLight;
    UButton* Cheat_ResetAchievement;
    UCheat_Resupply_C* Cheat_Resupply;
    UCheat_RoomList_C* Cheat_RoomList;
    UCheat_MiscUpgradesItem_C* Cheat_SecondItem;
    UCheat_SetDifficulty_C* Cheat_SetDifficulty;
    UCheat_SetFastFlares_C* Cheat_SetFastFlares;
    UCheat_SetPerk_C* Cheat_SetPerk;
    UCheat_ShowHUD_C* Cheat_ShowHUD;
    UCheat_ShowPathfinder_C* Cheat_ShowPathfinder;
    UCheat_SimulateLateJoin_C* Cheat_SimulateLateJoin;
    UCheat_SimulatePlayerCount_C* Cheat_SimulatePlayerCount;
    UCheat_MiscUpgradesItem_C* Cheat_SixthItem;
    UCheat_SpawnBosco_C* Cheat_SpawnBosco;
    UCheat_SpawnCritter_C* Cheat_SpawnCritter;
    UCheat_SpawnEarthQuake_C* Cheat_SpawnEarthQuake;
    UCheat_SpawnEnemy_C* Cheat_SpawnEnemy_C_0;
    UCheat_SpawnEnemies_C* Cheat_SpawnOnOff;
    UCheat_SpawnSandStorm_C* Cheat_SpawnSnowStorm;
    UCheat_SpawnSnowStorm_C* Cheat_SpawnSnowStorm_456;
    UCheat_ScriptedWave_C* Cheat_SpawnWave;
    UCheat_StandingDown_C* Cheat_StandingDown;
    UCheat_StopAIMovement_C* Cheat_StopAIMovement;
    UCheat_MiscUpgradesItem_C* Cheat_ThirdItem;
    UCheat_VanityTab_C* Cheat_VanityTab;
    UButton* CleanSpawnPos;
    UHorizontalBox* Content_Mission;
    UWidgetSwitcher* ContentSwitcher;
    UTextBlock* CritterPoolList;
    UTextBlock* EnemyPool;
    UCheckBox* FastPowerAttack;
    USlider* HealthSlider;
    UComboBoxString* mainWeaponselector;
    USpinBox* MinimuleAmountselect;
    UButton* PlaceSpawnpos;
    UButton* RespawnboscoBTN;
    UTextBlock* SavedCheatsActiveText;
    UScrollBox* SB_ColorSkinMain;
    UScrollBox* SB_ColorSkinSecondary;
    UScrollBox* SB_MeshSkinMain;
    UScrollBox* SB_MeshSkinSecondary;
    UScrollBox* SB_SecWepPerks;
    UScrollBox* SB_WeaponPerkList;
    UComboBoxString* SecondaryWeaponSelector;
    UTextBlock* StationaryPool;
    UCanvasPanel* TopCanvasPanel;
    UButton* UseSavedCheatsButton;
    UVerticalBox* VerticalBox_Materials;
    UButton* ActiveTab;
    UButton* ActiveCharacterTab;
    int32 Current Tab Index;
    int32 Amount of main tabs;
    bool Fast Select Enabled;
    bool Power User Mode Active;
    UCheat_SpawnEnemyAdvanced_C* advancedSpawnMenu;
    UPlayerCharacterID* ActiveCharacter;

    void CountResources(int32 Temp_int_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue_1, int32 Temp_int_Array_Index_Variable, AProceduralSetup* CallFunc_GetProceduralSetup_ReturnValue, bool CallFunc_IsValid_ReturnValue, int32 CallFunc_GetChildrenCount_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue, UWidget* CallFunc_GetChildAt_ReturnValue, bool CallFunc_LessEqual_IntInt_ReturnValue, UCheat_MaterialInfo_C* K2Node_DynamicCast_AsCheat_Material_Info, bool K2Node_DynamicCast_bSuccess, UPlayerController* CallFunc_GetOwningPlayer_ReturnValue, UResourceData* CallFunc_Array_Get_Item, UCheat_Collectible_C* CallFunc_Create_ReturnValue, UCollectableResourceData* K2Node_DynamicCast_AsCollectable_Resource_Data, bool K2Node_DynamicCast_bSuccess_1, UGemResourceData* K2Node_DynamicCast_AsGem_Resource_Data, bool K2Node_DynamicCast_bSuccess_2, UCarvedResourceData* K2Node_DynamicCast_AsCarved_Resource_Data, bool K2Node_DynamicCast_bSuccess_3, UVeinResourceData* K2Node_DynamicCast_AsVein_Resource_Data, bool K2Node_DynamicCast_bSuccess_4, UCarvedResourceCreator* CallFunc_LoadResourceCreator_ReturnValue, UTerrainMaterial* CallFunc_GetTerrainMaterial_ReturnValue, UCheat_GemInfo_C* CallFunc_Create_ReturnValue_1, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, UVerticalBoxSlot* CallFunc_AddChildToVerticalBox_ReturnValue, UVerticalBoxSlot* CallFunc_AddChildToVerticalBox_ReturnValue_1, UPlayerController* CallFunc_GetOwningPlayer_ReturnValue_1, UCheat_MaterialInfo_C* CallFunc_Create_ReturnValue_2, UCheat_MaterialInfo_C* CallFunc_Create_ReturnValue_3, UVerticalBoxSlot* CallFunc_AddChildToVerticalBox_ReturnValue_2, UVerticalBoxSlot* CallFunc_AddChildToVerticalBox_ReturnValue_3);
    UWidget* On_AdvEnemySpawn_GetMenuContent(bool CallFunc_IsValid_ReturnValue, UPlayerController* CallFunc_GetOwningPlayer_ReturnValue, UCheat_SpawnEnemyAdvanced_C* CallFunc_Create_ReturnValue);
    UUpgradableBoscoComponent* GetBoscoUpgradeComponent(UBosco*& DroneUFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue, UUpgradableBoscoComponent* CallFunc_GetUpgradeComponent_ReturnValue, bool CallFunc_IsValid_ReturnValue);
    void InitiateAnselSpinBox(APlayerCameraManager* CallFunc_GetPlayerCameraManager_ReturnValue, UBP_FSDCameraManager_C* K2Node_DynamicCast_AsBP_FSDCamera_Manager, bool K2Node_DynamicCast_bSuccess);
    UWidget* OnGetMenuContent_0(UPlayerController* CallFunc_GetOwningPlayer_ReturnValue, UCheat_OverclockSelection_C* CallFunc_Create_ReturnValue);
    ESlateVisibility Get_ActivateCommonCheatsButton_Visibility_0(bool Temp_bool_Variable, ESlateVisibility Temp_byte_Variable, ESlateVisibility Temp_byte_Variable_1, UPlayerController* CallFunc_GetOwningPlayer_ReturnValue, bool CallFunc_HasAuthority_ReturnValue, ESlateVisibility K2Node_Select_Default);
    float Get_HealthSlider_Value_0(UCharacter* CallFunc_GetPlayerCharacter_ReturnValue, UPlayerCharacter* K2Node_DynamicCast_AsPlayer_Character, bool K2Node_DynamicCast_bSuccess, float CallFunc_GetHealth_ReturnValue, float CallFunc_Divide_FloatFloat_ReturnValue);
    FEventReply OnKeyDown(FGeometry MyGeometry, FKeyEvent InKeyEventFKey CallFunc_GetKey_ReturnValue, FText CallFunc_Key_GetDisplayName_ReturnValue, FString CallFunc_Conv_TextToString_ReturnValue, bool K2Node_SwitchString_CmpSuccess, UWindowManager* CallFunc_GetWindowManager_ReturnValue, FEventReply CallFunc_Handled_ReturnValue);
    void Get Character to change(FText Character, UPlayerCharacterID*& character out, FString CallFunc_Conv_TextToString_ReturnValue, int32 Temp_int_Array_Index_Variable, FString CallFunc_RightChop_ReturnValue, FText CallFunc_Conv_StringToText_ReturnValue, UFSDGameState* CallFunc_GetFSDGameState_ReturnValue, FText CallFunc_TextToUpper_ReturnValue, TArray<UPlayerCharacterID*>& CallFunc_GetPlayableCharacterIDs_ReturnValue, int32 Temp_int_Loop_Counter_Variable, UPlayerCharacterID* CallFunc_Array_Get_Item, int32 CallFunc_Add_IntInt_ReturnValue, UFSDGameState* CallFunc_GetFSDGameState_ReturnValue_1, TArray<UPlayerCharacterID*>& CallFunc_GetPlayableCharacterIDs_ReturnValue_1, int32 CallFunc_Array_Length_ReturnValue, UPlayerCharacterID* CallFunc_Array_Get_Item_1, bool CallFunc_Less_IntInt_ReturnValue, const FText CallFunc_GetName_ReturnValue, bool CallFunc_EqualEqual_TextText_ReturnValue);
    void DeselectTab(UButton* Tab, bool CallFunc_EqualEqual_ObjectObject_ReturnValue, bool CallFunc_IsValid_ReturnValue);
    void SelectTab(int32 Index, UButton* TabButton, bool CallFunc_EqualEqual_ObjectObject_ReturnValue);
    void OnLoaded_A7093BF7410CE2BD47E9B6A07D503818(TSubclassOf<UObject> Loaded);
    void BndEvt__Button_Close_K2Node_ComponentBoundEvent_62_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_General_K2Node_ComponentBoundEvent_323_OnButtonClickedEvent__DelegateSignature();
    void SelectFirstTab();
    void Init Tabs();
    void BndEvt__Button_Controls_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_UI_K2Node_ComponentBoundEvent_107_OnButtonClickedEvent__DelegateSignature();
    void OnShown();
    void OnClosed();
    void BndEvt__Button_539_K2Node_ComponentBoundEvent_140_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_Gunner_K2Node_ComponentBoundEvent_683_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_Engineer_K2Node_ComponentBoundEvent_735_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_Driller_K2Node_ComponentBoundEvent_758_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_Scout_K2Node_ComponentBoundEvent_782_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_0_K2Node_ComponentBoundEvent_20_OnButtonClickedEvent__DelegateSignature();
    void Update weapon info(EItemCategory categoryType, UComboBoxString* ComboBoxToFill);
    void Set new weapon(FString Weapon name, EItemCategory Category);
    void Construct();
    void update selected upgrade();
    void Reload lists();
    void Fill Perk list(EItemCategory ItemSlotType, UScrollBox* scrollbox to change);
    void BndEvt__mainWeaponselector_K2Node_ComponentBoundEvent_1369_OnSelectionChangedEvent__DelegateSignature(FString SelectedItem, uint8 SelectionType);
    void BndEvt__SecondaryWeaponSelector_K2Node_ComponentBoundEvent_1395_OnSelectionChangedEvent__DelegateSignature(FString SelectedItem, uint8 SelectionType);
    void Swap Weapon to next(EItemCategory Item Category);
    void HotKey Interaction change character();
    void Select Next Tab();
    void Select previous tab();
    void Select current tab();
    void BndEvt__CheckBox_QuickSelect_K2Node_ComponentBoundEvent_777_OnCheckBoxComponentStateChanged__DelegateSignature(bool bIsChecked);
    void Fill Misc Upgrades(EItemCategory Item Slot type, UCheat_MiscUpgradesItem_C* CheatBoxToFill);
    void Set player misc upgrades();
    void Reload Character();
    void Build Bosco abilities();
    void BndEvt__RespawnboscoBTN_K2Node_ComponentBoundEvent_172_OnButtonClickedEvent__DelegateSignature();
    void Initiate Pool lists();
    void BndEvt__Button_Vanity_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Cheat_ResetAchievement_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__HealthSlider_K2Node_ComponentBoundEvent_2_OnFloatValueChangedEvent__DelegateSignature(float Value);
    void BndEvt__FastPowerAttack_K2Node_ComponentBoundEvent_5_OnCheckBoxComponentStateChanged__DelegateSignature(bool bIsChecked);
    void BndEvt__ActivateCommonCheatsButton_K2Node_ComponentBoundEvent_6_OnButtonClickedEvent__DelegateSignature();
    void Power user key pressed();
    void BndEvt__AnselSpeedSpinBox_K2Node_ComponentBoundEvent_3_OnSpinBoxValueChangedEvent__DelegateSignature(float InValue);
    void BndEvt__AnselDistanceSpinBox_K2Node_ComponentBoundEvent_4_OnSpinBoxValueChangedEvent__DelegateSignature(float InValue);
    void BndEvt__Button_SpawnMinimule_K2Node_ComponentBoundEvent_7_OnButtonClickedEvent__DelegateSignature();
    void Fill Weapon skin SB(UScrollBox* SkinScrollBox, EItemCategory Item Slot, EItemSkinType SkinType);
    void Reload skin list(EItemCategory Category);
    void BndEvt__Button_AdvancedEnemyspawn_K2Node_ComponentBoundEvent_8_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__AdvEnemySpawn_K2Node_ComponentBoundEvent_9_OnMenuOpenChangedEvent__DelegateSignature(bool bIsOpen);
    void Close Advanced spawning();
    void BndEvt__PlaceSpawnpos_K2Node_ComponentBoundEvent_10_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__CleanSpawnPos_K2Node_ComponentBoundEvent_11_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__UseSavedCheatsButton_K2Node_ComponentBoundEvent_12_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_Mission_K2Node_ComponentBoundEvent_13_OnButtonClickedEvent__DelegateSignature();
    void ExecuteUbergraph_Menu_Cheats(int32 EntryPoint, TSubclassOf<UObject> Temp_class_Variable, TSubclassOf<UUserWidget> K2Node_ClassDynamicCast_AsUser_Widget, bool K2Node_ClassDynamicCast_bSuccess, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable_1, TSubclassOf<UObject> K2Node_CustomEvent_Loaded, int32 Temp_int_Loop_Counter_Variable_1, int32 CallFunc_Add_IntInt_ReturnValue_1, int32 Temp_int_Loop_Counter_Variable_2, int32 CallFunc_Add_IntInt_ReturnValue_2, int32 Temp_int_Array_Index_Variable_2, FText Temp_text_Variable, int32 Temp_int_Array_Index_Variable_3, int32 Temp_int_Variable, int32 CallFunc_Add_IntInt_ReturnValue_3, int32 Temp_int_Array_Index_Variable_4, int32 Temp_int_Loop_Counter_Variable_3, int32 CallFunc_Add_IntInt_ReturnValue_4, int32 CallFunc_Add_IntInt_ReturnValue_5, FString CallFunc_Conv_IntToString_ReturnValue, FString CallFunc_Concat_StrStr_ReturnValue, FText CallFunc_Conv_StringToText_ReturnValue, int32 Temp_int_Array_Index_Variable_5, FText Temp_text_Variable_1, Bosco spawn requested__DelegateSignature K2Node_CreateDelegate_OutputDelegate, int32 Temp_int_Loop_Counter_Variable_4, int32 CallFunc_Add_IntInt_ReturnValue_6, int32 Temp_int_Array_Index_Variable_6, int32 Temp_int_Loop_Counter_Variable_5, int32 CallFunc_Add_IntInt_ReturnValue_7, int32 Temp_int_Variable_1, int32 Temp_int_Loop_Counter_Variable_6, int32 CallFunc_Add_IntInt_ReturnValue_8, int32 Temp_int_Array_Index_Variable_7, bool Temp_bool_Variable, int32 Temp_int_Loop_Counter_Variable_7, int32 CallFunc_Add_IntInt_ReturnValue_9, int32 Temp_int_Array_Index_Variable_8, FText Temp_text_Variable_2, int32 Temp_int_Loop_Counter_Variable_8, TimerDynamicDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_1, FTimerHandle CallFunc_K2_SetTimerDelegate_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_10, bool Temp_bool_IsClosed_Variable, int32 Temp_int_Array_Index_Variable_9, int32 CallFunc_Add_IntInt_ReturnValue_11, FString CallFunc_Conv_IntToString_ReturnValue_1, FString CallFunc_Concat_StrStr_ReturnValue_1, FText CallFunc_Conv_StringToText_ReturnValue_1, bool Temp_bool_Has_Been_Initd_Variable, TArray<UButton*>& K2Node_MakeArray_Array, UButton* CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, UPlayerController* CallFunc_GetPlayerController_ReturnValue, UPlayerController* CallFunc_GetPlayerController_ReturnValue_1, UWindowManager* CallFunc_GetWindowManager_ReturnValue, UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue, bool CallFunc_IsValid_ReturnValue, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue, UFSDSaveGame* CallFunc_GetFSDSaveGame_ReturnValue, UInventoryList* CallFunc_GetInventoryList_ReturnValue, UFSDSaveGame* CallFunc_GetFSDSaveGame_ReturnValue_1, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_1, UWindowManager* CallFunc_GetWindowManager_ReturnValue_1, UPlayerCharacterID* CallFunc_GetCharacterIDFromCharacter_ReturnValue, EItemCategory K2Node_CustomEvent_categoryType, UComboBoxString* K2Node_CustomEvent_ComboBoxToFill, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_2, UFSDSaveGame* CallFunc_GetFSDSaveGame_ReturnValue_2, UInventoryList* CallFunc_GetHeroInventoryList_ReturnValue, UItemID* CallFunc_GetEquippedItemID_ReturnValue, UInventoryList* CallFunc_GetHeroInventoryList_ReturnValue_1, FString CallFunc_GetDisplayName_ReturnValue, const TArray<UItemID*>& CallFunc_GetItemList_ReturnValue, UItemID* CallFunc_Array_Get_Item_1, int32 CallFunc_Array_Length_ReturnValue_1, FString CallFunc_GetDisplayName_ReturnValue_1, bool CallFunc_Less_IntInt_ReturnValue_1, int32 CallFunc_FindOptionIndex_ReturnValue, FString K2Node_CustomEvent_Weapon_name, EItemCategory K2Node_CustomEvent_category_1, bool CallFunc_NotEqual_IntInt_ReturnValue, bool K2Node_SwitchEnum_CmpSuccess, const TArray<UItemID*>& CallFunc_GetItemList_ReturnValue_1, UFSDSaveGame* CallFunc_GetFSDSaveGame_ReturnValue_3, UItemID* CallFunc_Array_Get_Item_2, int32 CallFunc_Array_Length_ReturnValue_2, TSubclassOf<AItem> CallFunc_GetItemClass_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue_2, FString CallFunc_GetDisplayName_ReturnValue_2, bool CallFunc_EqualEqual_StrStr_ReturnValue, FString CallFunc_GetSelectedOption_ReturnValue, FString CallFunc_GetSelectedOption_ReturnValue_1, EItemCategory K2Node_CustomEvent_ItemSlotType, UScrollBox* K2Node_CustomEvent_scrollbox_to_change, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_3, UFSDSaveGame* CallFunc_GetFSDSaveGame_ReturnValue_4, FString K2Node_ComponentBoundEvent_SelectedItem_1, uint8 K2Node_ComponentBoundEvent_SelectionType_1, TSubclassOf<AActor> CallFunc_GetEquippedItem_ReturnValue, FString K2Node_ComponentBoundEvent_SelectedItem, uint8 K2Node_ComponentBoundEvent_SelectionType, const TArray<FUpgradeTier>& CallFunc_GetItemUpgradeTiers_ReturnValue, FUpgradeTier CallFunc_Array_Get_Item_3, int32 CallFunc_Array_Length_ReturnValue_3, FText Temp_text_Variable_3, int32 Temp_int_Loop_Counter_Variable_9, bool CallFunc_Less_IntInt_ReturnValue_3, int32 CallFunc_Add_IntInt_ReturnValue_12, UPlayerController* CallFunc_GetPlayerController_ReturnValue_2, EItemCategory K2Node_CustomEvent_item_category, UCheat_PerkListTier_C* CallFunc_Create_ReturnValue, TSubclassOf<AActor> CallFunc_GetEquippedItem_ReturnValue_1, UItemID* CallFunc_GetItemID_ReturnValue, UItemID* CallFunc_GetNextItem_ReturnValue, TSubclassOf<AActor> CallFunc_GetActorClass_ReturnValue, UPanelSlot* CallFunc_AddChild_ReturnValue, bool Temp_bool_Variable_1, int32 CallFunc_Subtract_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_13, int32 CallFunc_Subtract_IntInt_ReturnValue_1, bool K2Node_ComponentBoundEvent_bIsChecked_1, UPlayerController* CallFunc_GetPlayerController_ReturnValue_3, UFSDPlayerControllerBase* K2Node_DynamicCast_AsFSDPlayer_Controller_Base, bool K2Node_DynamicCast_bSuccess, UPlayerController* CallFunc_GetPlayerController_ReturnValue_4, UFSDPlayerControllerBase* K2Node_DynamicCast_AsFSDPlayer_Controller_Base_1, bool K2Node_DynamicCast_bSuccess_1, EItemCategory K2Node_CustomEvent_Item_Slot_type, UCheat_MiscUpgradesItem_C* K2Node_CustomEvent_CheatBoxToFill, UPlayerController* CallFunc_GetPlayerController_ReturnValue_5, UCheat_PerkListTier_C* CallFunc_Create_ReturnValue_1, UCheat_SpawnBosco_C* CallFunc_Create_ReturnValue_2, UPanelSlot* CallFunc_AddChild_ReturnValue_1, UPanelSlot* CallFunc_AddChild_ReturnValue_2, UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue_1, UFSDGameMode* CallFunc_GetFSDGameMode_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, UEncounterManager* CallFunc_GetEncounterManager_ReturnValue, const TArray<UCritterDescriptor*>& CallFunc_GetCritterPool_ReturnValue, const TArray<UEnemyDescriptor*>& CallFunc_GetEnemyPool_ReturnValue, UCritterDescriptor* CallFunc_Array_Get_Item_4, UEnemyDescriptor* CallFunc_Array_Get_Item_5, FString CallFunc_GetObjectName_ReturnValue, FString CallFunc_GetObjectName_ReturnValue_1, int32 CallFunc_Array_Length_ReturnValue_4, int32 CallFunc_Array_Length_ReturnValue_5, bool CallFunc_Less_IntInt_ReturnValue_4, bool CallFunc_Less_IntInt_ReturnValue_5, const TArray<UEnemyDescriptor*>& CallFunc_GetEncounterPool_ReturnValue, UEnemyDescriptor* CallFunc_Array_Get_Item_6, On close requested__DelegateSignature K2Node_CreateDelegate_OutputDelegate_2, FString CallFunc_GetObjectName_ReturnValue_2, int32 CallFunc_Array_Length_ReturnValue_6, bool CallFunc_Less_IntInt_ReturnValue_6, FText CallFunc_GetText_ReturnValue, FString CallFunc_Conv_TextToString_ReturnValue, FString CallFunc_Concat_StrStr_ReturnValue_2, FText CallFunc_GetText_ReturnValue_1, FString CallFunc_Concat_StrStr_ReturnValue_3, FString CallFunc_Conv_TextToString_ReturnValue_1, FText CallFunc_Conv_StringToText_ReturnValue_2, FString CallFunc_Concat_StrStr_ReturnValue_4, FString CallFunc_Concat_StrStr_ReturnValue_5, FText CallFunc_Conv_StringToText_ReturnValue_3, OnSkinEquipped__DelegateSignature K2Node_CreateDelegate_OutputDelegate_3, int32 Temp_int_Variable_2, bool CallFunc_Greater_IntInt_ReturnValue, FText CallFunc_GetText_ReturnValue_2, FString CallFunc_Conv_TextToString_ReturnValue_2, FString CallFunc_Concat_StrStr_ReturnValue_6, FString CallFunc_Concat_StrStr_ReturnValue_7, FText CallFunc_Conv_StringToText_ReturnValue_4, UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue_2, float K2Node_ComponentBoundEvent_Value, UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue_3, UCharacter* CallFunc_GetPlayerCharacter_ReturnValue, bool K2Node_ComponentBoundEvent_bIsChecked, UPlayerCharacter* K2Node_DynamicCast_AsPlayer_Character, bool K2Node_DynamicCast_bSuccess_2, float CallFunc_SelectFloat_ReturnValue, UCharacter* CallFunc_GetPlayerCharacter_ReturnValue_1, UPlayerCharacter* K2Node_DynamicCast_AsPlayer_Character_1, bool K2Node_DynamicCast_bSuccess_3, float CallFunc_Multiply_FloatFloat_ReturnValue, UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue_4, UPlayerController* CallFunc_GetOwningPlayer_ReturnValue, UPlayerController* CallFunc_GetOwningPlayer_ReturnValue_1, bool CallFunc_HasAuthority_ReturnValue, UCheat_OverclockSelection_C* CallFunc_Create_ReturnValue_3, UPanelSlot* CallFunc_AddChild_ReturnValue_3, UPanelSlot* CallFunc_AddChild_ReturnValue_4, float K2Node_ComponentBoundEvent_InValue_1, APlayerCameraManager* CallFunc_GetPlayerCameraManager_ReturnValue, float K2Node_ComponentBoundEvent_InValue, UBP_FSDCameraManager_C* K2Node_DynamicCast_AsBP_FSDCamera_Manager, bool K2Node_DynamicCast_bSuccess_4, APlayerCameraManager* CallFunc_GetPlayerCameraManager_ReturnValue_1, UBP_FSDCameraManager_C* K2Node_DynamicCast_AsBP_FSDCamera_Manager_1, bool K2Node_DynamicCast_bSuccess_5, UPlayerCharacter* CallFunc_GetLocalPlayerCharacter_ReturnValue, float CallFunc_GetValue_ReturnValue, const FTransform CallFunc_GetTransform_ReturnValue, int32 CallFunc_FTrunc_ReturnValue, FVector CallFunc_BreakTransform_Location, FRotator CallFunc_BreakTransform_Rotation, FVector CallFunc_BreakTransform_Scale, bool CallFunc_LessEqual_IntInt_ReturnValue, float CallFunc_BreakVector_X, float CallFunc_BreakVector_Y, float CallFunc_BreakVector_Z, float CallFunc_Multiply_IntFloat_ReturnValue, FVector CallFunc_MakeVector_ReturnValue, FTransform CallFunc_MakeTransform_ReturnValue, UScrollBox* K2Node_CustomEvent_SkinScrollBox, EItemCategory K2Node_CustomEvent_Item_Slot, EItemSkinType K2Node_CustomEvent_skinType, UFSDSaveGame* CallFunc_GetFSDSaveGame_ReturnValue_5, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_4, UPlayerController* CallFunc_GetOwningPlayer_ReturnValue_2, UCheat_SkinListItem_C* CallFunc_Create_ReturnValue_4, TSubclassOf<AActor> CallFunc_GetEquippedItem_ReturnValue_2, UItemID* CallFunc_GetItemID_ReturnValue_1, TArray<UItemSkin*>& CallFunc_GetSkinsForItem_ReturnValue, UPanelSlot* CallFunc_AddChild_ReturnValue_5, UItemSkin* CallFunc_Array_Get_Item_7, int32 CallFunc_Array_Length_ReturnValue_7, bool CallFunc_Less_IntInt_ReturnValue_7, EItemCategory K2Node_CustomEvent_category, bool K2Node_SwitchEnum_CmpSuccess_1, UBosco* CallFunc_GetBoscoUpgradeComponent_Drone, UUpgradableBoscoComponent* CallFunc_GetBoscoUpgradeComponent_ReturnValue, bool CallFunc_IsValid_ReturnValue_2, FUpgradeTier CallFunc_Array_Get_Item_8, int32 CallFunc_Array_Length_ReturnValue_8, TSubclassOf<UBosco> CallFunc_GetObjectClass_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue_8, bool K2Node_ComponentBoundEvent_bIsOpen, UWidget* CallFunc_On_AdvEnemySpawn_GetMenuContent_ReturnValue, bool CallFunc_IsValid_ReturnValue_3, APawn* CallFunc_GetPlayerPawn_ReturnValue, bool CallFunc_IsServer_ReturnValue, bool CallFunc_IsValid_ReturnValue_4, const FTransform CallFunc_GetTransform_ReturnValue_1, UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue_5, AActor* CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue, ASpawnPosMarker_C* CallFunc_FinishSpawningActor_ReturnValue, TArray<ASpawnPosMarker_C*>& CallFunc_GetAllActorsOfClass_OutActors, ASpawnPosMarker_C* CallFunc_Array_Get_Item_9, int32 CallFunc_Array_Length_ReturnValue_9, bool CallFunc_Less_IntInt_ReturnValue_9, UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue_6, UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue_7, bool CallFunc_Not_PreBool_ReturnValue, FText K2Node_Select_Default, UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue_8, FText K2Node_Select_Default_1, TSubclassOf<UObject> CallFunc_LoadClass_ReturnValue, TSubclassOf<UMiniMule> K2Node_ClassDynamicCast_AsMini_Mule, bool K2Node_ClassDynamicCast_bSuccess_1, AActor* CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_1, UMiniMule* CallFunc_FinishSpawningActor_ReturnValue_1, URepairableComponent* CallFunc_GetComponentByClass_ReturnValue, UButton* K2Node_Select_Default_2, UFSDGameMode* CallFunc_GetFSDGameMode_ReturnValue_1, int32 Temp_int_Variable_3, bool CallFunc_IsValid_ReturnValue_5, bool CallFunc_Less_IntInt_ReturnValue_10, UFSDGameMode* CallFunc_GetFSDGameMode_ReturnValue_2, OnAssetClassLoaded__DelegateSignature K2Node_CreateDelegate_OutputDelegate_4, bool CallFunc_IsValidSoftClassReference_ReturnValue, UPlayerController* CallFunc_GetOwningPlayer_ReturnValue_3, UUserWidget* CallFunc_Create_ReturnValue_5, UHorizontalBoxSlot* CallFunc_AddChildToHorizontalBoxEx_OutSlot, UHorizontalBox* CallFunc_AddChildToHorizontalBoxEx_OutHorizontalBox, UUserWidget* CallFunc_AddChildToHorizontalBoxEx_ReturnValue);
}

#endif
