#ifndef UE4SS_SDK_Menu_Cheats_SpaceRig_HPP
#define UE4SS_SDK_Menu_Cheats_SpaceRig_HPP

class UMenu_Cheats_SpaceRig_C : UWindowWidget
{
    FPointerToUberGraphFrame UberGraphFrame;
    UScrollBox* BoscoUpgradePanel;
    UButton* Button_Close;
    UButton* Button_Driller;
    UButton* Button_Engineer;
    UButton* Button_General;
    UButton* Button_GenericHero;
    UButton* Button_Gunner;
    UButton* Button_Info;
    UButton* Button_ReloadChar;
    UButton* Button_Scout;
    UButton* Button_Vanity;
    UCheat_ConsoleCmd_C* Cheat_ConsoleCmd;
    UCheat_ConsoleCmd_C* Cheat_ConsoleCmd_C_0;
    UCheat_ConvertSave_C* Cheat_ConvertSave;
    UCheat_MiscUpgradesItem_C* Cheat_FifthItem;
    UCheat_MiscUpgradesItem_C* Cheat_FirstItem;
    UCheat_MiscUpgradesItem_C* Cheat_FourthItem;
    UCheat_LevelScale_C* Cheat_LevelScale;
    UCheat_MakeMainSave_C* Cheat_MakeMainSave;
    UCheat_MaterialInfo_C* Cheat_MaterialInfo_C_2;
    UCheat_MaterialInfo_C* Cheat_MaterialInfo_C_3;
    UCheat_MaterialInfo_C* Cheat_MaterialInfo_C_4;
    UButton* Cheat_ResetAchievement;
    UCheat_RoomList_C* Cheat_RoomList;
    UCheat_MiscUpgradesItem_C* Cheat_SecondItem;
    UCheat_SetPromotionRank_C* Cheat_SetPromotionRank;
    UCheat_MiscUpgradesItem_C* Cheat_SixthItem;
    UCheat_MiscUpgradesItem_C* Cheat_ThirdItem;
    UCheat_VanityTab_C* Cheat_VanityTab;
    UWidgetSwitcher* ContentSwitcher;
    UTextBlock* CritterPoolList;
    UTextBlock* EnemyPool;
    UComboBoxString* mainWeaponselector;
    UButton* RespawnboscoBTN;
    UScrollBox* SB_ColorSkinMain;
    UScrollBox* SB_ColorSkinSecondary;
    UScrollBox* SB_MeshSkinMain;
    UScrollBox* SB_MeshSkinSecondary;
    UScrollBox* SB_SecWepPerks;
    UScrollBox* SB_WeaponPerkList;
    UComboBoxString* SecondaryWeaponSelector;
    UTextBlock* StationaryPool;
    UCanvasPanel* TopCanvasPanel;
    UVerticalBox* VerticalBox_Materials;
    UButton* ActiveTab;
    UButton* ActiveCharacterTab;
    int32 Current Tab Index;
    int32 Amount of main tabs;
    bool Fast Select Enabled;
    bool Power User Mode Active;
    UCheat_SpawnEnemyAdvanced_C* advancedSpawnMenu;

    UWidget* On_AdvEnemySpawn_GetMenuContent(bool CallFunc_IsValid_ReturnValue, UPlayerController* CallFunc_GetOwningPlayer_ReturnValue, UCheat_SpawnEnemyAdvanced_C* CallFunc_Create_ReturnValue);
    UUpgradableBoscoComponent* GetBoscoUpgradeComponent(UBosco*& DroneUFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue, UUpgradableBoscoComponent* CallFunc_GetUpgradeComponent_ReturnValue, bool CallFunc_IsValid_ReturnValue);
    void InitiateAnselSpinBox();
    UWidget* OnGetMenuContent_0(UPlayerController* CallFunc_GetOwningPlayer_ReturnValue, UCheat_OverclockSelection_C* CallFunc_Create_ReturnValue);
    ESlateVisibility Get_ActivateCommonCheatsButton_Visibility_0(bool Temp_bool_Variable, ESlateVisibility Temp_byte_Variable, ESlateVisibility Temp_byte_Variable_1, UPlayerController* CallFunc_GetOwningPlayer_ReturnValue, bool CallFunc_HasAuthority_ReturnValue, ESlateVisibility K2Node_Select_Default);
    float Get_HealthSlider_Value_0(UCharacter* CallFunc_GetPlayerCharacter_ReturnValue, UPlayerCharacter* K2Node_DynamicCast_AsPlayer_Character, bool K2Node_DynamicCast_bSuccess, float CallFunc_GetHealth_ReturnValue, float CallFunc_Divide_FloatFloat_ReturnValue);
    FEventReply OnKeyDown(FGeometry MyGeometry, FKeyEvent InKeyEventFKey CallFunc_GetKey_ReturnValue, FText CallFunc_Key_GetDisplayName_ReturnValue, FString CallFunc_Conv_TextToString_ReturnValue, bool K2Node_SwitchString_CmpSuccess, UWindowManager* CallFunc_GetWindowManager_ReturnValue, FEventReply CallFunc_Handled_ReturnValue);
    void Get Character to change(FText Character, UPlayerCharacterID*& character out, FString CallFunc_Conv_TextToString_ReturnValue, int32 Temp_int_Array_Index_Variable, FString CallFunc_RightChop_ReturnValue, FText CallFunc_Conv_StringToText_ReturnValue, UFSDGameState* CallFunc_GetFSDGameState_ReturnValue, FText CallFunc_TextToUpper_ReturnValue, TArray<UPlayerCharacterID*>& CallFunc_GetPlayableCharacterIDs_ReturnValue, UFSDGameState* CallFunc_GetFSDGameState_ReturnValue_1, UPlayerCharacterID* CallFunc_Array_Get_Item, TArray<UPlayerCharacterID*>& CallFunc_GetPlayableCharacterIDs_ReturnValue_1, UPlayerCharacterID* CallFunc_Array_Get_Item_1, int32 CallFunc_Array_Length_ReturnValue, int32 Temp_int_Loop_Counter_Variable, const FText CallFunc_GetName_ReturnValue, bool CallFunc_EqualEqual_TextText_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue);
    void DeselectTab(UButton* Tab, bool CallFunc_EqualEqual_ObjectObject_ReturnValue, bool CallFunc_IsValid_ReturnValue);
    void SelectTab(int32 Index, UButton* TabButton);
    void BndEvt__Button_Close_K2Node_ComponentBoundEvent_62_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_General_K2Node_ComponentBoundEvent_323_OnButtonClickedEvent__DelegateSignature();
    void SelectFirstTab();
    void Init Tabs();
    void BndEvt__Button_Controls_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
    void OnShown();
    void OnClosed();
    void BndEvt__Button_Gunner_K2Node_ComponentBoundEvent_683_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_Engineer_K2Node_ComponentBoundEvent_735_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_Driller_K2Node_ComponentBoundEvent_758_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_Scout_K2Node_ComponentBoundEvent_782_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_0_K2Node_ComponentBoundEvent_20_OnButtonClickedEvent__DelegateSignature();
    void Update weapon info(EItemCategory categoryType, UComboBoxString* ComboBoxToFill);
    void Set new weapon(FString Weapon name, EItemCategory Category);
    void Construct();
    void update selected upgrade();
    void Reload lists();
    void Fill Perk list(EItemCategory ItemSlotType, UScrollBox* scrollbox to change);
    void BndEvt__mainWeaponselector_K2Node_ComponentBoundEvent_1369_OnSelectionChangedEvent__DelegateSignature(FString SelectedItem, uint8 SelectionType);
    void BndEvt__SecondaryWeaponSelector_K2Node_ComponentBoundEvent_1395_OnSelectionChangedEvent__DelegateSignature(FString SelectedItem, uint8 SelectionType);
    void Swap Weapon to next(EItemCategory Item Category);
    void HotKey Interaction change character();
    void Select Next Tab();
    void Select previous tab();
    void Select current tab();
    void BndEvt__CheckBox_QuickSelect_K2Node_ComponentBoundEvent_777_OnCheckBoxComponentStateChanged__DelegateSignature(bool bIsChecked);
    void BndEvt__Button_GenericHero_K2Node_ComponentBoundEvent_164_OnButtonClickedEvent__DelegateSignature();
    void Fill Misc Upgrades(EItemCategory Item Slot type, UCheat_MiscUpgradesItem_C* CheatBoxToFill);
    void Set player misc upgrades();
    void Reload Character();
    void Build Bosco abilities();
    void BndEvt__RespawnboscoBTN_K2Node_ComponentBoundEvent_172_OnButtonClickedEvent__DelegateSignature();
    void Initiate Pool lists();
    void BndEvt__Button_Vanity_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Cheat_ResetAchievement_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__HealthSlider_K2Node_ComponentBoundEvent_2_OnFloatValueChangedEvent__DelegateSignature(float Value);
    void BndEvt__FastPowerAttack_K2Node_ComponentBoundEvent_5_OnCheckBoxComponentStateChanged__DelegateSignature(bool bIsChecked);
    void BndEvt__AnselSpeedSpinBox_K2Node_ComponentBoundEvent_3_OnSpinBoxValueChangedEvent__DelegateSignature(float InValue);
    void BndEvt__AnselDistanceSpinBox_K2Node_ComponentBoundEvent_4_OnSpinBoxValueChangedEvent__DelegateSignature(float InValue);
    void Fill Weapon skin SB(UScrollBox* SkinScrollBox, EItemCategory Item Slot, EItemSkinType SkinType);
    void Reload skin list(EItemCategory Category);
    void BndEvt__AdvEnemySpawn_K2Node_ComponentBoundEvent_9_OnMenuOpenChangedEvent__DelegateSignature(bool bIsOpen);
    void BndEvt__PlaceSpawnpos_K2Node_ComponentBoundEvent_10_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__CleanSpawnPos_K2Node_ComponentBoundEvent_11_OnButtonClickedEvent__DelegateSignature();
    void ExecuteUbergraph_Menu_Cheats_SpaceRig(int32 EntryPoint, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_1, FString CallFunc_Conv_IntToString_ReturnValue, FString CallFunc_Concat_StrStr_ReturnValue, FText CallFunc_Conv_StringToText_ReturnValue, int32 Temp_int_Array_Index_Variable_1, int32 Temp_int_Loop_Counter_Variable_1, int32 Temp_int_Loop_Counter_Variable_2, int32 CallFunc_Add_IntInt_ReturnValue_2, int32 CallFunc_Add_IntInt_ReturnValue_3, int32 Temp_int_Array_Index_Variable_2, Bosco spawn requested__DelegateSignature K2Node_CreateDelegate_OutputDelegate, int32 Temp_int_Loop_Counter_Variable_3, int32 CallFunc_Add_IntInt_ReturnValue_4, int32 Temp_int_Array_Index_Variable_3, int32 Temp_int_Array_Index_Variable_4, int32 Temp_int_Array_Index_Variable_5, int32 Temp_int_Loop_Counter_Variable_4, int32 CallFunc_Add_IntInt_ReturnValue_5, int32 CallFunc_Add_IntInt_ReturnValue_6, FString CallFunc_Conv_IntToString_ReturnValue_1, FString CallFunc_Concat_StrStr_ReturnValue_1, FText CallFunc_Conv_StringToText_ReturnValue_1, int32 Temp_int_Array_Index_Variable_6, int32 Temp_int_Loop_Counter_Variable_5, int32 CallFunc_Add_IntInt_ReturnValue_7, int32 Temp_int_Array_Index_Variable_7, int32 Temp_int_Loop_Counter_Variable_6, int32 CallFunc_Add_IntInt_ReturnValue_8, int32 Temp_int_Array_Index_Variable_8, TimerDynamicDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_1, FTimerHandle CallFunc_K2_SetTimerDelegate_ReturnValue, int32 Temp_int_Loop_Counter_Variable_7, int32 CallFunc_Add_IntInt_ReturnValue_9, int32 Temp_int_Array_Index_Variable_9, int32 Temp_int_Loop_Counter_Variable_8, TArray<UButton*>& K2Node_MakeArray_Array, UButton* CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_10, UPlayerController* CallFunc_GetPlayerController_ReturnValue, UPlayerController* CallFunc_GetPlayerController_ReturnValue_1, UWindowManager* CallFunc_GetWindowManager_ReturnValue, UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue, bool CallFunc_IsValid_ReturnValue, UWidget* CallFunc_GetChildAt_ReturnValue, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue, UTextBlock* K2Node_DynamicCast_AsText, bool K2Node_DynamicCast_bSuccess, FText CallFunc_GetText_ReturnValue, UPlayerCharacterID* CallFunc_Get_Character_to_change_character_out, UInventoryList* CallFunc_GetInventoryList_ReturnValue, UFSDSaveGame* CallFunc_GetFSDSaveGame_ReturnValue, UFSDSaveGame* CallFunc_GetFSDSaveGame_ReturnValue_1, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_1, UWindowManager* CallFunc_GetWindowManager_ReturnValue_1, EItemCategory K2Node_CustomEvent_categoryType, UComboBoxString* K2Node_CustomEvent_ComboBoxToFill, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_2, TSubclassOf<UPlayerCharacter> CallFunc_GetObjectClass_ReturnValue, UInventoryList* CallFunc_GetHeroInventoryList_ReturnValue, UPlayerCharacterID* CallFunc_GetCharacterID_ReturnValue, UPlayerCharacterID* CallFunc_GetCharacterID_ReturnValue_1, UInventoryList* CallFunc_GetHeroInventoryList_ReturnValue_1, UFSDSaveGame* CallFunc_GetFSDSaveGame_ReturnValue_2, TArray<TSubclassOf<AActor>>& CallFunc_GetLoadedItemList_ReturnValue, TSubclassOf<AActor> CallFunc_GetEquippedItem_ReturnValue, TSubclassOf<AActor> CallFunc_Array_Get_Item_1, FString CallFunc_GetClassDisplayName_ReturnValue, FString CallFunc_GetClassDisplayName_ReturnValue_1, int32 CallFunc_FindOptionIndex_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_1, bool CallFunc_NotEqual_IntInt_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, FString K2Node_CustomEvent_Weapon_name, EItemCategory K2Node_CustomEvent_category_1, UFSDSaveGame* CallFunc_GetFSDSaveGame_ReturnValue_3, bool K2Node_SwitchEnum_CmpSuccess, TArray<TSubclassOf<AActor>>& CallFunc_GetLoadedItemList_ReturnValue_1, TSubclassOf<AActor> CallFunc_Array_Get_Item_2, int32 CallFunc_Array_Length_ReturnValue_2, bool CallFunc_Less_IntInt_ReturnValue_1, FString CallFunc_GetClassDisplayName_ReturnValue_2, bool CallFunc_EqualEqual_StrStr_ReturnValue, FString CallFunc_GetSelectedOption_ReturnValue, FString CallFunc_GetSelectedOption_ReturnValue_1, EItemCategory K2Node_CustomEvent_ItemSlotType, UScrollBox* K2Node_CustomEvent_scrollbox_to_change, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_3, UFSDSaveGame* CallFunc_GetFSDSaveGame_ReturnValue_4, FString K2Node_ComponentBoundEvent_SelectedItem_1, uint8 K2Node_ComponentBoundEvent_SelectionType_1, TSubclassOf<AActor> CallFunc_GetEquippedItem_ReturnValue_1, FString K2Node_ComponentBoundEvent_SelectedItem, uint8 K2Node_ComponentBoundEvent_SelectionType, const TArray<FUpgradeTier>& CallFunc_GetItemUpgradeTiers_ReturnValue, FUpgradeTier CallFunc_Array_Get_Item_3, int32 CallFunc_Array_Length_ReturnValue_3, bool CallFunc_Less_IntInt_ReturnValue_2, int32 Temp_int_Loop_Counter_Variable_9, bool CallFunc_Less_IntInt_ReturnValue_3, int32 CallFunc_Add_IntInt_ReturnValue_11, int32 Temp_int_Variable, UPlayerController* CallFunc_GetPlayerController_ReturnValue_2, EItemCategory K2Node_CustomEvent_item_category, UCheat_PerkListTier_C* CallFunc_Create_ReturnValue, TSubclassOf<AActor> CallFunc_GetEquippedItem_ReturnValue_2, UItemID* CallFunc_GetItemID_ReturnValue, UItemID* CallFunc_GetNextItem_ReturnValue, TSubclassOf<AActor> CallFunc_GetActorClass_ReturnValue, UPanelSlot* CallFunc_AddChild_ReturnValue, int32 Temp_int_Variable_1, bool CallFunc_Greater_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_12, int32 CallFunc_Subtract_IntInt_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue_1, bool K2Node_ComponentBoundEvent_bIsChecked_1, UPlayerController* CallFunc_GetPlayerController_ReturnValue_3, UFSDPlayerControllerBase* K2Node_DynamicCast_AsFSDPlayer_Controller_Base, bool K2Node_DynamicCast_bSuccess_1, UPlayerController* CallFunc_GetPlayerController_ReturnValue_4, UFSDPlayerControllerBase* K2Node_DynamicCast_AsFSDPlayer_Controller_Base_1, bool K2Node_DynamicCast_bSuccess_2, EItemCategory K2Node_CustomEvent_Item_Slot_type, UCheat_MiscUpgradesItem_C* K2Node_CustomEvent_CheatBoxToFill, UPlayerController* CallFunc_GetPlayerController_ReturnValue_5, UCheat_PerkListTier_C* CallFunc_Create_ReturnValue_1, UCheat_SpawnBosco_C* CallFunc_Create_ReturnValue_2, UPanelSlot* CallFunc_AddChild_ReturnValue_1, UPanelSlot* CallFunc_AddChild_ReturnValue_2, UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue_1, UFSDGameMode* CallFunc_GetFSDGameMode_ReturnValue, UEncounterManager* CallFunc_GetEncounterManager_ReturnValue, const TArray<UCritterDescriptor*>& CallFunc_GetCritterPool_ReturnValue, FText CallFunc_GetText_ReturnValue_1, UCritterDescriptor* CallFunc_Array_Get_Item_4, FString CallFunc_Conv_TextToString_ReturnValue, FString CallFunc_GetObjectName_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_4, FString CallFunc_Concat_StrStr_ReturnValue_2, bool CallFunc_Less_IntInt_ReturnValue_4, FString CallFunc_Concat_StrStr_ReturnValue_3, FText CallFunc_Conv_StringToText_ReturnValue_2, const TArray<UEnemyDescriptor*>& CallFunc_GetEnemyPool_ReturnValue, UEnemyDescriptor* CallFunc_Array_Get_Item_5, int32 CallFunc_Array_Length_ReturnValue_5, FString CallFunc_GetObjectName_ReturnValue_1, bool CallFunc_Less_IntInt_ReturnValue_5, const TArray<UEnemyDescriptor*>& CallFunc_GetEncounterPool_ReturnValue, UEnemyDescriptor* CallFunc_Array_Get_Item_6, int32 CallFunc_Array_Length_ReturnValue_6, FString CallFunc_GetObjectName_ReturnValue_2, bool CallFunc_Less_IntInt_ReturnValue_6, FText CallFunc_GetText_ReturnValue_2, FString CallFunc_Conv_TextToString_ReturnValue_1, OnSkinEquipped__DelegateSignature K2Node_CreateDelegate_OutputDelegate_2, FString CallFunc_Concat_StrStr_ReturnValue_4, FString CallFunc_Concat_StrStr_ReturnValue_5, FText CallFunc_Conv_StringToText_ReturnValue_3, FText CallFunc_GetText_ReturnValue_3, FString CallFunc_Conv_TextToString_ReturnValue_2, UButton* K2Node_Select_Default, FString CallFunc_Concat_StrStr_ReturnValue_6, FString CallFunc_Concat_StrStr_ReturnValue_7, FText CallFunc_Conv_StringToText_ReturnValue_4, UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue_2, float K2Node_ComponentBoundEvent_Value, UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue_3, UCharacter* CallFunc_GetPlayerCharacter_ReturnValue, bool K2Node_ComponentBoundEvent_bIsChecked, UPlayerCharacter* K2Node_DynamicCast_AsPlayer_Character, bool K2Node_DynamicCast_bSuccess_3, float CallFunc_SelectFloat_ReturnValue, UCharacter* CallFunc_GetPlayerCharacter_ReturnValue_1, UBP_PlayerCharacter_C* K2Node_DynamicCast_AsBP_Player_Character, bool K2Node_DynamicCast_bSuccess_4, float CallFunc_Multiply_FloatFloat_ReturnValue, UPlayerController* CallFunc_GetOwningPlayer_ReturnValue, UCheat_OverclockSelection_C* CallFunc_Create_ReturnValue_3, float K2Node_ComponentBoundEvent_InValue_1, UPanelSlot* CallFunc_AddChild_ReturnValue_3, UPanelSlot* CallFunc_AddChild_ReturnValue_4, APlayerCameraManager* CallFunc_GetPlayerCameraManager_ReturnValue, float K2Node_ComponentBoundEvent_InValue, UBP_FSDCameraManager_C* K2Node_DynamicCast_AsBP_FSDCamera_Manager, bool K2Node_DynamicCast_bSuccess_5, APlayerCameraManager* CallFunc_GetPlayerCameraManager_ReturnValue_1, UBP_FSDCameraManager_C* K2Node_DynamicCast_AsBP_FSDCamera_Manager_1, bool K2Node_DynamicCast_bSuccess_6, UScrollBox* K2Node_CustomEvent_SkinScrollBox, EItemCategory K2Node_CustomEvent_Item_Slot, EItemSkinType K2Node_CustomEvent_skinType, UFSDSaveGame* CallFunc_GetFSDSaveGame_ReturnValue_5, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_4, int32 Temp_int_Variable_2, bool CallFunc_Less_IntInt_ReturnValue_7, TSubclassOf<UPlayerCharacter> CallFunc_GetObjectClass_ReturnValue_1, UPlayerCharacterID* CallFunc_GetCharacterID_ReturnValue_2, TSubclassOf<AActor> CallFunc_GetEquippedItem_ReturnValue_3, UItemID* CallFunc_GetItemID_ReturnValue_1, UPlayerController* CallFunc_GetOwningPlayer_ReturnValue_1, TArray<UItemSkin*>& CallFunc_GetSkinsForItem_ReturnValue, UCheat_SkinListItem_C* CallFunc_Create_ReturnValue_4, UItemSkin* CallFunc_Array_Get_Item_7, UPanelSlot* CallFunc_AddChild_ReturnValue_5, int32 CallFunc_Array_Length_ReturnValue_7, EItemCategory K2Node_CustomEvent_category, bool CallFunc_Less_IntInt_ReturnValue_8, bool K2Node_SwitchEnum_CmpSuccess_1, UBosco* CallFunc_GetBoscoUpgradeComponent_Drone, UUpgradableBoscoComponent* CallFunc_GetBoscoUpgradeComponent_ReturnValue, bool K2Node_ComponentBoundEvent_bIsOpen, bool CallFunc_IsValid_ReturnValue_1, TSubclassOf<UBosco> CallFunc_GetObjectClass_ReturnValue_2, FUpgradeTier CallFunc_Array_Get_Item_8, int32 CallFunc_Array_Length_ReturnValue_8, bool CallFunc_Less_IntInt_ReturnValue_9, UWidget* CallFunc_On_AdvEnemySpawn_GetMenuContent_ReturnValue, bool CallFunc_IsValid_ReturnValue_2, APawn* CallFunc_GetPlayerPawn_ReturnValue, bool CallFunc_IsServer_ReturnValue, bool CallFunc_IsValid_ReturnValue_3, const FTransform CallFunc_GetTransform_ReturnValue, UFSDCheatManager* CallFunc_GetCheatManager_ReturnValue_4, AActor* CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue, ASpawnPosMarker_C* CallFunc_FinishSpawningActor_ReturnValue, TArray<ASpawnPosMarker_C*>& CallFunc_GetAllActorsOfClass_OutActors, ASpawnPosMarker_C* CallFunc_Array_Get_Item_9, int32 CallFunc_Array_Length_ReturnValue_9, bool CallFunc_Less_IntInt_ReturnValue_10);
}

#endif
