#ifndef UE4SS_SDK_Options_ResetProgress_HPP
#define UE4SS_SDK_Options_ResetProgress_HPP

class UOptions_ResetProgress_C : UUserWidget
{
    FPointerToUberGraphFrame UberGraphFrame;
    UBasic_ButtonWithControls_C* Basic_ButtonWithControls;

    void OnFailure_E60EC8DB4E80DB2E20AA1A9F09A53224();
    void OnSuccess_E60EC8DB4E80DB2E20AA1A9F09A53224();
    void BndEvt__Basic_ButtonWithControls_K2Node_ComponentBoundEvent_21_OnClicked__DelegateSignature();
    void Answer(bool Yes);
    void TutorialAnswer(bool Yes);
    void ExecuteUbergraph_Options_ResetProgress(int32 EntryPoint, UWindowManager* CallFunc_GetWindowManager_ReturnValue, EmptyOnlineDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate, OnYesNoClickedDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_1, bool K2Node_CustomEvent_Yes_1, UWindowManager* CallFunc_GetWindowManager_ReturnValue_1, UBasic_Popup_YesNoPrompt_C* CallFunc_OpenSingleUseWindow_ReturnValue, UPlayerController* CallFunc_GetOwningPlayer_ReturnValue, UFSDGameUserSettings* CallFunc_GetFSDGameUserSettings_ReturnValue, UDestroySessionCallbackProxy* CallFunc_DestroySession_ReturnValue, FString CallFunc_GetCurrentUserSaveSlotName_ReturnValue, bool CallFunc_IsEmpty_ReturnValue, bool CallFunc_IsValid_ReturnValue, UFSDSaveGame* CallFunc_GetFSDSaveGame_ReturnValue, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue, int32 CallFunc_GetAvailableUserSlotIndex_ReturnValue, EmptyOnlineDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_2, UFSDGameInstance* CallFunc_GetFSDGameInstance_ReturnValue_1, UWindowManager* CallFunc_GetWindowManager_ReturnValue_2, UBasic_Popup_YesNoPrompt_C* CallFunc_OpenSingleUseWindow_ReturnValue_1, bool K2Node_CustomEvent_Yes, bool CallFunc_Not_PreBool_ReturnValue, UFSDSaveGame* CallFunc_GetFSDSaveGame_ReturnValue_1, OnYesNoClickedDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_3);
}

#endif
