#ifndef UE4SS_SDK_PRJ_PlatformMaker_HPP
#define UE4SS_SDK_PRJ_PlatformMaker_HPP

class APRJ_PlatformMaker_C : UProjectile
{
    FPointerToUberGraphFrame UberGraphFrame;
    UStaticMeshComponent* Projectile;
    float Timeline_0_NewTrack_1_6344ADF74893FE5BE85A6CA2C1A57EE3;
    TEnumAsByte<ETimelineDirection::Type> Timeline_0__Direction_6344ADF74893FE5BE85A6CA2C1A57EE3;
    UTimelineComponent* Timeline_0;
    float Diameter;
    float PlatformCreationDelay (seconds);
    UStaticMesh* PlatformCarverMesh;
    FVector PlatformScale;
    UTerrainMaterial* FoamMaterial;

    void Timeline_0__FinishedFunc();
    void Timeline_0__UpdateFunc();
    void OnImpacted(bool PredictedImpact, const FHitResult& HitResult);
    void ReceiveBeginPlay();
    void Set Carver mesh(UStaticMesh* Mesh to use);
    void SetCarverMeshScale(FVector Scale);
    void UseLessFallDamageMaterial();
    void UseBugRepellantMaterial();
    void UseFallDmgAndBugRepellant();
    void ExecuteUbergraph_PRJ_PlatformMaker(int32 EntryPoint, APawn* CallFunc_GetInstigator_ReturnValue, FVector CallFunc_MakeVector_ReturnValue, bool CallFunc_IsValid_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue_1, bool Temp_bool_Variable, float CallFunc_BreakVector_X, float CallFunc_BreakVector_Y, float CallFunc_BreakVector_Z, bool CallFunc_Not_PreBool_ReturnValue, float CallFunc_BreakVector_X_1, float CallFunc_BreakVector_Y_1, float CallFunc_BreakVector_Z_1, float CallFunc_Multiply_FloatFloat_ReturnValue, float CallFunc_FMax_ReturnValue, bool K2Node_Event_PredictedImpact, const FHitResult K2Node_Event_HitResult, float CallFunc_Multiply_FloatFloat_ReturnValue_1, bool CallFunc_BreakHitResult_bBlockingHit, bool CallFunc_BreakHitResult_bInitialOverlap, float CallFunc_BreakHitResult_Time, float CallFunc_BreakHitResult_Distance, FVector CallFunc_BreakHitResult_Location, FVector CallFunc_BreakHitResult_ImpactPoint, FVector CallFunc_BreakHitResult_Normal, FVector CallFunc_BreakHitResult_ImpactNormal, UPhysicalMaterial* CallFunc_BreakHitResult_PhysMat, AActor* CallFunc_BreakHitResult_HitActor, UPrimitiveComponent* CallFunc_BreakHitResult_HitComponent, FName CallFunc_BreakHitResult_HitBoneName, int32 CallFunc_BreakHitResult_HitItem, int32 CallFunc_BreakHitResult_FaceIndex, FVector CallFunc_BreakHitResult_TraceStart, FVector CallFunc_BreakHitResult_TraceEnd, float CallFunc_Multiply_FloatFloat_ReturnValue_2, InterfaceProperty K2Node_DynamicCast_AsGameplay_Tag_Asset_Interface, bool K2Node_DynamicCast_bSuccess, bool CallFunc_DoesImplementInterface_ReturnValue, FRotator CallFunc_Conv_VectorToRotator_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue_1, float CallFunc_BreakRotator_Roll, float CallFunc_BreakRotator_Pitch, float CallFunc_BreakRotator_Yaw, bool CallFunc_BooleanOR_ReturnValue, FRotator CallFunc_MakeRotator_ReturnValue, FVector CallFunc_Multiply_VectorFloat_ReturnValue, bool CallFunc_BreakHitResult_bBlockingHit_1, bool CallFunc_BreakHitResult_bInitialOverlap_1, float CallFunc_BreakHitResult_Time_1, float CallFunc_BreakHitResult_Distance_1, FVector CallFunc_BreakHitResult_Location_1, FVector CallFunc_BreakHitResult_ImpactPoint_1, FVector CallFunc_BreakHitResult_Normal_1, FVector CallFunc_BreakHitResult_ImpactNormal_1, UPhysicalMaterial* CallFunc_BreakHitResult_PhysMat_1, AActor* CallFunc_BreakHitResult_HitActor_1, UPrimitiveComponent* CallFunc_BreakHitResult_HitComponent_1, FName CallFunc_BreakHitResult_HitBoneName_1, int32 CallFunc_BreakHitResult_HitItem_1, int32 CallFunc_BreakHitResult_FaceIndex_1, FVector CallFunc_BreakHitResult_TraceStart_1, FVector CallFunc_BreakHitResult_TraceEnd_1, FVector CallFunc_Add_VectorVector_ReturnValue, FRotator CallFunc_Conv_VectorToRotator_ReturnValue_1, UAudioComponent* CallFunc_SpawnSoundAtLocation_ReturnValue, float CallFunc_BreakRotator_Roll_1, float CallFunc_BreakRotator_Pitch_1, float CallFunc_BreakRotator_Yaw_1, FRotator CallFunc_MakeRotator_ReturnValue_1, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue, bool CallFunc_HasAuthority_ReturnValue, UFSDGameState* CallFunc_GetFSDGameState_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, FGameplayTagContainer CallFunc_MakeGameplayTagContainerFromTag_ReturnValue, bool CallFunc_HasAnyMatchingGameplayTags_ReturnValue, UStaticMesh* K2Node_CustomEvent_Mesh_to_use, FVector K2Node_CustomEvent_Scale, FVector CallFunc_Multiply_VectorFloat_ReturnValue_1, FTransform CallFunc_MakeTransform_ReturnValue, FVector CallFunc_BreakTransform_Location, FRotator CallFunc_BreakTransform_Rotation, FVector CallFunc_BreakTransform_Scale, FVector CallFunc_Subtract_VectorVector_ReturnValue, float CallFunc_BreakVector_X_2, float CallFunc_BreakVector_Y_2, float CallFunc_BreakVector_Z_2, float CallFunc_BreakVector_X_3, float CallFunc_BreakVector_Y_3, float CallFunc_BreakVector_Z_3, float CallFunc_Add_FloatFloat_ReturnValue, float CallFunc_Abs_ReturnValue, float CallFunc_Abs_ReturnValue_1, bool CallFunc_LessEqual_FloatFloat_ReturnValue, float CallFunc_Abs_ReturnValue_2, bool CallFunc_Greater_FloatFloat_ReturnValue, float CallFunc_FMax_ReturnValue_1, float CallFunc_SelectFloat_ReturnValue, bool CallFunc_LessEqual_FloatFloat_ReturnValue_1, FVector CallFunc_MakeVector_ReturnValue_1, bool CallFunc_BooleanAND_ReturnValue);
}

#endif
