#ifndef UE4SS_SDK_PRJ_GooProjectile_Fragment_GooBomoberSpecial_HPP
#define UE4SS_SDK_PRJ_GooProjectile_Fragment_GooBomoberSpecial_HPP

class APRJ_GooProjectile_Fragment_GooBomoberSpecial_C : UPRJ_GooProjectile_Fragment_Base_C
{
    FPointerToUberGraphFrame UberGraphFrame;
    USphereComponent* ApplyGooTrigger;

    void OnInitialized();
    void BndEvt__ApplyGooTrigger_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult);
    void ExecuteUbergraph_PRJ_GooProjectile_Fragment_GooBomoberSpecial(int32 EntryPoint, UPrimitiveComponent* K2Node_ComponentBoundEvent_OverlappedComponent, AActor* K2Node_ComponentBoundEvent_OtherActor, UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp, int32 K2Node_ComponentBoundEvent_OtherBodyIndex, bool K2Node_ComponentBoundEvent_bFromSweep, const FHitResult K2Node_ComponentBoundEvent_SweepResult, float CallFunc_Subtract_FloatFloat_ReturnValue, float CallFunc_Subtract_FloatFloat_ReturnValue_1);
}

#endif
