#ifndef UE4SS_SDK_TSK_DrillToTarget_HPP
#define UE4SS_SDK_TSK_DrillToTarget_HPP

class UTSK_DrillToTarget_C : UBTTask_BlueprintBase
{
    FPointerToUberGraphFrame UberGraphFrame;
    FBlackboardKeySelector StartPosKey;
    FBlackboardKeySelector EndPosKey;
    FBlackboardKeySelector StartTangentKey;
    FBlackboardKeySelector EndTangentKey;
    float Progress;
    float MoveSpeed;
    FVector NewLocation;
    AEscortMule* MULE;
    float RotateSpeedMod;
    FRotator NewRotation;

    void FindNextLoc(float DeltaSeconds, float& additionalProgress, FVector& NewLoc, FRotator& NewRotation, FVector CallFunc_GetBlackboardValueAsVector_ReturnValue, FVector CallFunc_GetBlackboardValueAsVector_ReturnValue_1, FVector CallFunc_GetBlackboardValueAsVector_ReturnValue_2, FVector CallFunc_K2_GetActorLocation_ReturnValue, FVector CallFunc_GetBlackboardValueAsVector_ReturnValue_3, float CallFunc_Multiply_FloatFloat_ReturnValue, float CallFunc_Multiply_FloatFloat_ReturnValue_1, float CallFunc_Add_FloatFloat_ReturnValue, FVector CallFunc_CubicInterpBlueprint_ReturnValue, FVector CallFunc_Subtract_VectorVector_ReturnValue, FRotator CallFunc_MakeRotFromX_ReturnValue);
    void ReceiveExecuteAI(UAIController* OwnerController, APawn* ControlledPawn);
    void ReceiveTickAI(UAIController* OwnerController, APawn* ControlledPawn, float DeltaSeconds);
    void ExecuteUbergraph_TSK_DrillToTarget(int32 EntryPoint, FVector CallFunc_GetBlackboardValueAsVector_ReturnValue, UAIController* K2Node_Event_OwnerController_1, APawn* K2Node_Event_ControlledPawn_1, UAIController* K2Node_Event_OwnerController, APawn* K2Node_Event_ControlledPawn, float K2Node_Event_DeltaSeconds, float CallFunc_FindNextLoc_additionalProgress, FVector CallFunc_FindNextLoc_newLoc, FRotator CallFunc_FindNextLoc_newRotation, bool CallFunc_GreaterEqual_FloatFloat_ReturnValue, UEscortMule* K2Node_DynamicCast_AsEscort_Mule, bool K2Node_DynamicCast_bSuccess, FVector CallFunc_GetBlackboardValueAsVector_ReturnValue_1, FVector CallFunc_GetBlackboardValueAsVector_ReturnValue_2, FVector CallFunc_GetBlackboardValueAsVector_ReturnValue_3, FVector CallFunc_GetBlackboardValueAsVector_ReturnValue_4, FVector CallFunc_GetBlackboardValueAsVector_ReturnValue_5, float CallFunc_Multiply_FloatFloat_ReturnValue, FVector CallFunc_GetBlackboardValueAsVector_ReturnValue_6, FRotator CallFunc_K2_GetActorRotation_ReturnValue, FVector CallFunc_GetBlackboardValueAsVector_ReturnValue_7, FRotator CallFunc_NormalizedDeltaRotator_ReturnValue, float CallFunc_CubicSegmentLength_ReturnValue, float CallFunc_BreakRotator_Roll, float CallFunc_BreakRotator_Pitch, float CallFunc_BreakRotator_Yaw, float CallFunc_FMax_ReturnValue, float K2Node_MathExpression_ReturnValue, float CallFunc_Divide_FloatFloat_ReturnValue, float K2Node_MathExpression_ReturnValue_1, float CallFunc_Add_FloatFloat_ReturnValue_1, FRotator CallFunc_K2_GetActorRotation_ReturnValue_1, FRotator CallFunc_RInterpTo_Constant_ReturnValue, FVector CallFunc_CubicInterpBlueprint_ReturnValue, FTransform CallFunc_MakeTransform_ReturnValue, FHitResult CallFunc_K2_SetActorTransform_SweepHitResult, bool CallFunc_K2_SetActorTransform_ReturnValue, bool CallFunc_NotEqual_FloatFloat_ReturnValue);
}

#endif
