#ifndef UE4SS_SDK_Tutorial_Hint_Sabotage_FollowTheCables_HPP
#define UE4SS_SDK_Tutorial_Hint_Sabotage_FollowTheCables_HPP

class UTutorial_Hint_Sabotage_FollowTheCables_C : UTutorialHintComponent
{
    FPointerToUberGraphFrame UberGraphFrame;
    TSubclassOf<UObjective> Target Objective;
    float DelayAfterFacilityWasSeenBeforeShowingHint;
    bool FoundPowerstation;

    void ReceiveOnInitialized();
    void FacilityWasFound();
    void ExecuteUbergraph_Tutorial_Hint_Sabotage_FollowTheCables(int32 EntryPoint, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, FacilityFound__DelegateSignature K2Node_CreateDelegate_OutputDelegate, int32 Temp_int_Array_Index_Variable, UFSDGameState* CallFunc_GetFSDGameState_ReturnValue, UObjective* CallFunc_GetPrimaryObjective_ReturnValue, UFSDGameState* CallFunc_GetFSDGameState_ReturnValue_1, TSubclassOf<UObjective> CallFunc_GetObjectClass_ReturnValue, UObjective* CallFunc_GetPrimaryObjective_ReturnValue_1, bool CallFunc_EqualEqual_ClassClass_ReturnValue, UFacilityObjective* K2Node_DynamicCast_AsFacility_Objective, bool K2Node_DynamicCast_bSuccess, TArray<AActor*>& CallFunc_GetShieldGenerators_ReturnValue, AActor* CallFunc_Array_Get_Item, UBP_MainFacility_DataVault_C* K2Node_DynamicCast_AsBP_Main_Facility_Data_Vault, bool K2Node_DynamicCast_bSuccess_1, UBP_Facility_PowerStation_ShieldGenerator_C* K2Node_DynamicCast_AsBP_Facility_Power_Station_Shield_Generator, bool K2Node_DynamicCast_bSuccess_2, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue);
}

#endif
