#ifndef UE4SS_SDK_WND_SeasonEventBonus_HPP
#define UE4SS_SDK_WND_SeasonEventBonus_HPP

class UWND_SeasonEventBonus_C : UUserWidget
{
    FPointerToUberGraphFrame UberGraphFrame;
    UBasic_Menu_ColorBar_C* Basic_Menu_ColorBar;
    UHorizontalBox* HorizontalBox_Outer;

    void PreConstruct(bool IsDesignTime);
    void Construct();
    void OnScripChallengeUpdated_Event();
    void ExecuteUbergraph_WND_SeasonEventBonus(int32 EntryPoint, ESeasonVisibilityState Temp_byte_Variable, bool Temp_bool_Variable, ESeasonVisibilityState Temp_byte_Variable_1, bool Temp_bool_Variable_1, ESeasonVisibilityState Temp_byte_Variable_2, ESeasonVisibilityState Temp_byte_Variable_3, bool Temp_bool_Variable_2, ESeasonVisibilityState Temp_byte_Variable_4, USeasonsSubsystem* CallFunc_GetGameInstanceSubsystem_ReturnValue, OnScripChallengeUpdated__DelegateSignature K2Node_CreateDelegate_OutputDelegate, int32 Temp_int_Variable, int32 CallFunc_Add_IntInt_ReturnValue, bool K2Node_Event_IsDesignTime, int32 Temp_int_Variable_1, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue_1, ESeasonVisibilityState K2Node_Select_Default, bool CallFunc_LessEqual_IntInt_ReturnValue, ESeasonVisibilityState K2Node_Select_Default_1, int32 CallFunc_Add_IntInt_ReturnValue_1, USeasonsSubsystem* CallFunc_GetGameInstanceSubsystem_ReturnValue_1, int32 CallFunc_GetScriptChallengeInfo_completed, int32 CallFunc_GetScriptChallengeInfo_claimed, int32 CallFunc_GetScriptChallengeInfo_total, int32 CallFunc_Subtract_IntInt_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue_2, bool CallFunc_LessEqual_IntInt_ReturnValue_1, bool CallFunc_LessEqual_IntInt_ReturnValue_2, bool CallFunc_Less_IntInt_ReturnValue_3, bool CallFunc_Not_PreBool_ReturnValue, ESeasonVisibilityState Temp_byte_Variable_5, UITM_SeasonEventBonus_C* CallFunc_Create_ReturnValue, UHorizontalBoxSlot* CallFunc_AddChildToHorizontalBox_ReturnValue, bool Temp_bool_Variable_3, UITM_SeasonEventBonus_C* CallFunc_Create_ReturnValue_1, ESeasonVisibilityState K2Node_Select_Default_2, UHorizontalBoxSlot* CallFunc_AddChildToHorizontalBox_ReturnValue_1, ESeasonVisibilityState K2Node_Select_Default_3);
}

#endif
