#ifndef UE4SS_SDK_WND_SeasonChallenges_HPP
#define UE4SS_SDK_WND_SeasonChallenges_HPP

class UWND_SeasonChallenges_C : UUserWidget
{
    FPointerToUberGraphFrame UberGraphFrame;
    UBasic_Menu_ColorBar_C* Basic_Menu_ColorBar;
    UGridPanel* Grid_Challenges;
    UITM_Season_ChallengeTimer_C* ChallengeTimer;

    void OnNewChallenge(int32 SwapIndex, int32 CallFunc_Add_IntInt_ReturnValue, USeasonsSubsystem* CallFunc_GetGameInstanceSubsystem_ReturnValue, UGridSlot* CallFunc_AddChildToGrid_ReturnValue, TArray<FChallengeInfo>& CallFunc_GetActiveChallenges_ReturnValue, UGameData* CallFunc_GetFSDGameData_ReturnValue, UGridSlot* CallFunc_SlotAsGridSlot_ReturnValue, FChallengeInfo CallFunc_Array_Get_Item, USeasonsSubsystem* CallFunc_GetGameInstanceSubsystem_ReturnValue_1, bool CallFunc_CanRerollChallenge_ReturnValue, UITM_Season_Challenge_C* CallFunc_AddChallengeToGrid_W_Challenge, USeasonsSubsystem* CallFunc_GetGameInstanceSubsystem_ReturnValue_2, TArray<FChallengeInfo>& CallFunc_GetActiveChallenges_ReturnValue_1, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue);
    void AddChallengeToGrid(FChallengeInfo ChallengeInfo, bool CanReroll, int32 Column, UITM_Season_Challenge_C*& W_Challenge, FMargin K2Node_MakeStruct_Margin, UITM_Season_Challenge_C* CallFunc_Create_ReturnValue, UGridSlot* CallFunc_AddChildToGrid_ReturnValue);
    void OnReroll(UITM_Season_Challenge_C* W_Challenge, bool CanReroll, int32 Index, UGridSlot* CallFunc_SlotAsGridSlot_ReturnValue, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, USeasonsSubsystem* CallFunc_GetGameInstanceSubsystem_ReturnValue, bool CallFunc_CanRerollChallenge_ReturnValue, TArray<UWidget*>& CallFunc_GetAllChildren_ReturnValue, USeasonsSubsystem* CallFunc_GetGameInstanceSubsystem_ReturnValue_1, UWidget* CallFunc_Array_Get_Item, TArray<FChallengeInfo>& CallFunc_GetActiveChallenges_ReturnValue, UITM_Season_Challenge_C* K2Node_DynamicCast_AsITM_Season_Challenge, bool K2Node_DynamicCast_bSuccess, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue);
    void PreConstruct(bool IsDesignTime);
    void Refresh();
    void ExecuteUbergraph_WND_SeasonChallenges(int32 EntryPoint, ShouldGetNewChallenge__DelegateSignature K2Node_CreateDelegate_OutputDelegate, UITM_Season_ChallengeTimer_C* CallFunc_Create_ReturnValue, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable, bool K2Node_Event_IsDesignTime, int32 Temp_int_Variable, UITM_Season_Challenge_C* CallFunc_AddChallengeToGrid_W_Challenge, bool CallFunc_LessEqual_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_1, USeasonsSubsystem* CallFunc_GetGameInstanceSubsystem_ReturnValue, UGameData* CallFunc_GetFSDGameData_ReturnValue, bool CallFunc_CanRerollChallenge_ReturnValue, TArray<FChallengeInfo>& CallFunc_GetActiveChallenges_ReturnValue, FChallengeInfo CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, UITM_Season_Challenge_C* CallFunc_AddChallengeToGrid_W_Challenge_1, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_1, bool CallFunc_Less_IntInt_ReturnValue_1, FMargin K2Node_MakeStruct_Margin, RerollClicked__DelegateSignature K2Node_CreateDelegate_OutputDelegate_1, int32 CallFunc_GetChildrenCount_ReturnValue, UGridSlot* CallFunc_AddChildToGrid_ReturnValue);
}

#endif
