#ifndef UE4SS_SDK_WPN_Autocannon_HPP
#define UE4SS_SDK_WPN_Autocannon_HPP

class AWPN_Autocannon_C : UAutoCannon
{
    FPointerToUberGraphFrame UberGraphFrame;
    UNiagaraComponent* ParticleSystem;
    UWeaponImpactComponent* WeaponImpact;
    UDamageComponent* Damage;
    UFirstPersonParticleSystemComponent* FirstPersonParticleSystem;
    UFirstPersonPointLightComponent* Light_MuzzleFlash;
    UFirstPersonWidgetComponent* Widget_Overheat;
    UFirstPersonWidgetComponent* Widget_Ammo;
    UCrosshairAggregator* CrosshairAggregator;
    UHitscanComponent* HitScan;
    float SplashDamage;
    float SplashRadius;
    float StartTime;

    FText RoundStatValue(const FText& InText, FString Suffix, bool KeepSignFString CallFunc_Conv_TextToString_ReturnValue, float CallFunc_Conv_StringToFloat_ReturnValue, float CallFunc_Multiply_FloatFloat_ReturnValue, int32 CallFunc_Round_ReturnValue, int32 CallFunc_Multiply_IntInt_ReturnValue, FText CallFunc_Conv_IntToText_ReturnValue, FString CallFunc_Conv_TextToString_ReturnValue_1, FString CallFunc_Concat_StrStr_ReturnValue, FText CallFunc_Conv_StringToText_ReturnValue);
    void GetGearStatEntry(UFSDPlayerState* PlayerState, TArray<FGearStatEntry>& Stats, TSubclassOf<UWPN_Autocannon_C> CallFunc_GetObjectClass_ReturnValue, FGearStatEntry CallFunc_UPGDESC_AutoCannon_GearStatEntry, bool CallFunc_UPGDESC_AutoCannon_HasUpgradedValue, int32 CallFunc_Array_Add_ReturnValue, FText CallFunc_GetUpgradeName_ReturnValue, TSubclassOf<UWPN_Autocannon_C> CallFunc_GetObjectClass_ReturnValue_1, FGearStatEntry CallFunc_UPGDESC_Generic_GearStatEntry, bool CallFunc_UPGDESC_Generic_HasUpgradedValue, TSubclassOf<UWPN_Autocannon_C> CallFunc_GetObjectClass_ReturnValue_2, int32 CallFunc_Array_Add_ReturnValue_1, FGearStatEntry CallFunc_UPGDESC_Item_GearStatEntry, bool CallFunc_UPGDESC_Item_HasUpgradedValue, TSubclassOf<UWPN_Autocannon_C> CallFunc_GetObjectClass_ReturnValue_3, int32 CallFunc_Array_Add_ReturnValue_2, FGearStatEntry CallFunc_UPGDESC_HitScan_GearStatEntry, bool CallFunc_UPGDESC_HitScan_HasAnyUpgrades, FText CallFunc_RoundStatValue_ReturnValue, FText CallFunc_RoundStatValue_ReturnValue_1, FGearStatEntry K2Node_MakeStruct_GearStatEntry, int32 CallFunc_Array_Add_ReturnValue_3, TSubclassOf<UWPN_Autocannon_C> CallFunc_GetObjectClass_ReturnValue_4, FGearStatEntry CallFunc_UPGDESC_Damage_GearStatEntry, bool CallFunc_UPGDESC_Damage_HasUpgradedValue, FGearStatEntry CallFunc_UPGDESC_Damage_GearStatEntry_1, bool CallFunc_UPGDESC_Damage_HasUpgradedValue_1, int32 CallFunc_Array_Add_ReturnValue_4, int32 CallFunc_Array_Add_ReturnValue_5, FGearStatEntry CallFunc_UPGDESC_AutoCannon_GearStatEntry_1, bool CallFunc_UPGDESC_AutoCannon_HasUpgradedValue_1, FGearStatEntry CallFunc_UPGDESC_AutoCannon_GearStatEntry_2, bool CallFunc_UPGDESC_AutoCannon_HasUpgradedValue_2, int32 CallFunc_Array_Add_ReturnValue_6, int32 CallFunc_Array_Add_ReturnValue_7, FGearStatEntry CallFunc_UPGDESC_AutoCannon_GearStatEntry_3, bool CallFunc_UPGDESC_AutoCannon_HasUpgradedValue_3, FGearStatEntry CallFunc_UPGDESC_Damage_GearStatEntry_2, bool CallFunc_UPGDESC_Damage_HasUpgradedValue_2, int32 CallFunc_Array_Add_ReturnValue_8, int32 CallFunc_Array_Add_ReturnValue_9, FGearStatEntry CallFunc_UPGDESC_Damage_GearStatEntry_3, bool CallFunc_UPGDESC_Damage_HasUpgradedValue_3, FGearStatEntry CallFunc_UPGDESC_AmmoDriven_GearStatEntry, bool CallFunc_UPGDESC_AmmoDriven_HasAnyUpgrades, int32 CallFunc_Array_Add_ReturnValue_10, FGearStatEntry CallFunc_UPGDESC_AmmoDriven_GearStatEntry_1, bool CallFunc_UPGDESC_AmmoDriven_HasAnyUpgrades_1, FGearStatEntry CallFunc_UPGDESC_AmmoDriven_GearStatEntry_2, bool CallFunc_UPGDESC_AmmoDriven_HasAnyUpgrades_2, FGearStatEntry CallFunc_UPGDESC_AmmoDriven_GearStatEntry_3, bool CallFunc_UPGDESC_AmmoDriven_HasAnyUpgrades_3, FGearStatEntry CallFunc_UPGDESC_Damage_GearStatEntry_4, bool CallFunc_UPGDESC_Damage_HasUpgradedValue_4, FGearStatEntry CallFunc_UPGDESC_Damage_GearStatEntry_5, bool CallFunc_UPGDESC_Damage_HasUpgradedValue_5, int32 CallFunc_Array_Add_ReturnValue_11, int32 CallFunc_Array_Add_ReturnValue_12, FGearStatEntry CallFunc_UPGDESC_Damage_GearStatEntry_6, bool CallFunc_UPGDESC_Damage_HasUpgradedValue_6, int32 CallFunc_Array_Add_ReturnValue_13, int32 CallFunc_Array_Add_ReturnValue_14, int32 CallFunc_Array_Add_ReturnValue_15, int32 CallFunc_Array_Add_ReturnValue_16, int32 CallFunc_Array_Add_ReturnValue_17);
    void UserConstructionScript();
    void ShowCurentFireTime();
    void ReceiveBeginPlay();
    void RecieveUnequipped();
    void RecieveEquipped();
    void Receive_IsFiringChanged(bool NewValue);
    void BndEvt__WeaponImpact_K2Node_ComponentBoundEvent_1_HightAccelerationSignature__DelegateSignature();
    void RecieveFiredWeapon();
    void ExecuteUbergraph_WPN_Autocannon(int32 EntryPoint, bool K2Node_Event_newValue, UUserWidget* CallFunc_GetUserWidgetObject_ReturnValue, UWeaponDisplay_Base_AmmoCount_C* K2Node_DynamicCast_AsWeapon_Display_Base_Ammo_Count, bool K2Node_DynamicCast_bSuccess, USkeletalMeshComponent* CallFunc_GetItemMesh_ReturnValue, UAudioComponent* CallFunc_SpawnSoundAttached_ReturnValue, USkeletalMeshComponent* CallFunc_GetItemMesh_ReturnValue_1);
}

#endif
