#ifndef UE4SS_SDK_WPN_ChargeBlaster_HPP
#define UE4SS_SDK_WPN_ChargeBlaster_HPP

class AWPN_ChargeBlaster_C : UChargedWeapon
{
    FPointerToUberGraphFrame UberGraphFrame;
    UAudioComponent* AC_ChargeLevel;
    UFirstPersonWidgetComponent* Widget_ChargeNew;
    UFirstPersonStaticMeshComponent* FirstPersonStaticMesh2;
    UFirstPersonWidgetComponent* Widget_Ammo;
    UFirstPersonWidgetComponent* Widget_HeatNew;
    UFirstPersonStaticMeshComponent* FirstPersonStaticMesh1;
    UFirstPersonStaticMeshComponent* FirstPersonStaticMesh;
    UFirstPersonParticleSystemComponent* FirstPersonParticleSystem_Arc;
    UFirstPersonParticleSystemComponent* FirstPersonParticleSystem_Right;
    UFirstPersonParticleSystemComponent* FirstPersonParticleSystem_Left;
    UChargedProjectileLauncherComponent* ChargedProjectileLauncher;
    UPointLightComponent* MuzzlePointLight;
    UCrosshairAggregator* CrosshairAggregator;
    UWeaponDisplay_ChargeBlaster_Charge_C* ChargeUI;
    UWeaponDisplay_ChargeBlaster_Heat_C* OverheatUI;
    UWeaponDisplay_ChargeBlaster_AmmoCounter_C* AmmoUI;
    int32 ChargeLevel;
    UAudioComponent* AC_Heat;
    USoundBase* TemperatureAudio;
    USoundBase* OverheatedAudio;
    UAudioComponent* AC_ChargeLevel_0;
    UAudioComponent* AC_ChargeSpinUp;
    UParticleSystemComponent* OverheatEmitterInstance;
    UMaterialInstanceDynamic* SlideParameter;

    void FadeOutIfValid(UAudioComponent*& AC, bool CallFunc_IsValid_ReturnValue);
    void HandleHeatAudio(bool CallFunc_IsValid_ReturnValue, bool Temp_bool_Variable, USoundBase* K2Node_Select_Default, bool CallFunc_Greater_FloatFloat_ReturnValue);
    void HandleChargeAudio(float charge, int32 CurrentLevel, int32 MaxLevel, int32 Temp_int_Variable, float Temp_float_Variable, float Temp_float_Variable_1, float Temp_float_Variable_2, float Temp_float_Variable_3, float K2Node_Select_Default, bool CallFunc_EqualEqual_IntInt_ReturnValue, float CallFunc_Conv_IntToFloat_ReturnValue, float CallFunc_Multiply_FloatFloat_ReturnValue, int32 CallFunc_FTrunc_ReturnValue, bool CallFunc_Greater_IntInt_ReturnValue);
    void GetGearStatEntry(UFSDPlayerState* PlayerState, TArray<FGearStatEntry>& Stats, FText CallFunc_GetUpgradeName_ReturnValue, TSubclassOf<UWPN_ChargeBlaster_C> CallFunc_GetObjectClass_ReturnValue, FGearStatEntry CallFunc_UPGDESC_Generic_GearStatEntry, bool CallFunc_UPGDESC_Generic_HasUpgradedValue, FText CallFunc_GetUpgradeName_ReturnValue_1, int32 CallFunc_Array_Add_ReturnValue, TSubclassOf<UWPN_ChargeBlaster_C> CallFunc_GetObjectClass_ReturnValue_1, FGearStatEntry CallFunc_UPGDESC_Generic_GearStatEntry_1, bool CallFunc_UPGDESC_Generic_HasUpgradedValue_1, int32 CallFunc_Array_Add_ReturnValue_1, FText CallFunc_MakeLiteralText_ReturnValue, TSubclassOf<UWPN_ChargeBlaster_C> CallFunc_GetObjectClass_ReturnValue_2, FGearStatEntry CallFunc_UPGDESC_Damage_GearStatEntry, bool CallFunc_UPGDESC_Damage_HasUpgradedValue, FGearStatEntry CallFunc_UPGDESC_Generic_GearStatEntry_2, bool CallFunc_UPGDESC_Generic_HasUpgradedValue_2, int32 CallFunc_Array_Add_ReturnValue_2, FGearStatEntry CallFunc_UPGDESC_Projectile_GearStatEntry, bool CallFunc_UPGDESC_Projectile_HasUpgradedValue, FGearStatEntry CallFunc_UPGDESC_ChargedWeapon_GearStatEntry, bool CallFunc_UPGDESC_ChargedWeapon_HasUpgradedValue, int32 CallFunc_Array_Add_ReturnValue_3, int32 CallFunc_Array_Add_ReturnValue_4, FGearStatEntry CallFunc_UPGDESC_Projectile_GearStatEntry_1, bool CallFunc_UPGDESC_Projectile_HasUpgradedValue_1, FGearStatEntry CallFunc_UPGDESC_ChargedProjectile_GearStatEntry, bool CallFunc_UPGDESC_ChargedProjectile_HasUpgradedValue, int32 CallFunc_Array_Add_ReturnValue_5, int32 CallFunc_Array_Add_ReturnValue_6, FGearStatEntry CallFunc_UPGDESC_ChargedProjectile_GearStatEntry_1, bool CallFunc_UPGDESC_ChargedProjectile_HasUpgradedValue_1, FGearStatEntry CallFunc_UPGDESC_ChargedWeapon_GearStatEntry_1, bool CallFunc_UPGDESC_ChargedWeapon_HasUpgradedValue_1, int32 CallFunc_Array_Add_ReturnValue_7, int32 CallFunc_Array_Add_ReturnValue_8, FGearStatEntry CallFunc_UPGDESC_ChargedWeapon_GearStatEntry_2, bool CallFunc_UPGDESC_ChargedWeapon_HasUpgradedValue_2, FGearStatEntry CallFunc_UPGDESC_ChargedWeapon_GearStatEntry_3, bool CallFunc_UPGDESC_ChargedWeapon_HasUpgradedValue_3, int32 CallFunc_Array_Add_ReturnValue_9, int32 CallFunc_Array_Add_ReturnValue_10, FGearStatEntry CallFunc_UPGDESC_ChargedWeapon_GearStatEntry_4, bool CallFunc_UPGDESC_ChargedWeapon_HasUpgradedValue_4, FGearStatEntry CallFunc_UPGDESC_ChargedWeapon_GearStatEntry_5, bool CallFunc_UPGDESC_ChargedWeapon_HasUpgradedValue_5, int32 CallFunc_Array_Add_ReturnValue_11, int32 CallFunc_Array_Add_ReturnValue_12, FGearStatEntry CallFunc_UPGDESC_Damage_GearStatEntry_1, bool CallFunc_UPGDESC_Damage_HasUpgradedValue_1, FGearStatEntry CallFunc_UPGDESC_Damage_GearStatEntry_2, bool CallFunc_UPGDESC_Damage_HasUpgradedValue_2, int32 CallFunc_Array_Add_ReturnValue_13, int32 CallFunc_Array_Add_ReturnValue_14, FGearStatEntry CallFunc_UPGDESC_Damage_GearStatEntry_3, bool CallFunc_UPGDESC_Damage_HasUpgradedValue_3, FGearStatEntry CallFunc_UPGDESC_AmmoDriven_GearStatEntry, bool CallFunc_UPGDESC_AmmoDriven_HasAnyUpgrades, int32 CallFunc_Array_Add_ReturnValue_15, int32 CallFunc_Array_Add_ReturnValue_16);
    void UserConstructionScript(UMaterialInstanceDynamic* CallFunc_CreateDynamicMaterialInstance_ReturnValue);
    void OnHeatChanged_Event_0(float charge);
    void ChargeChanged(float charge);
    void RecieveUnequipped();
    void ReceiveOverheatedChanged(bool isOverheated);
    void OnSkinChanged(USkinEffect* Skin);
    void AddedToInventory(UPlayerCharacter* ItemOwner);
    void ExecuteUbergraph_WPN_ChargeBlaster(int32 EntryPoint, UUserWidget* CallFunc_GetUserWidgetObject_ReturnValue, bool CallFunc_IsValid_ReturnValue, ChargeChangedSignature__DelegateSignature K2Node_CreateDelegate_OutputDelegate, float K2Node_CustomEvent_charge_1, float K2Node_CustomEvent_charge, UUserWidget* CallFunc_GetUserWidgetObject_ReturnValue_1, UWeaponDisplay_ChargeBlaster_Heat_C* K2Node_DynamicCast_AsWeapon_Display_Charge_Blaster_Heat, bool K2Node_DynamicCast_bSuccess, UUserWidget* CallFunc_GetUserWidgetObject_ReturnValue_2, UWeaponDisplay_ChargeBlaster_Charge_C* K2Node_DynamicCast_AsWeapon_Display_Charge_Blaster_Charge, bool K2Node_DynamicCast_bSuccess_1, UUserWidget* CallFunc_GetUserWidgetObject_ReturnValue_3, UWeaponDisplay_ChargeBlaster_AmmoCounter_C* K2Node_DynamicCast_AsWeapon_Display_Charge_Blaster_Ammo_Counter, bool K2Node_DynamicCast_bSuccess_2, bool K2Node_Event_IsOverheated, UParticleSystemComponent* CallFunc_SpawnFirstPersonEmitterAttached_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, bool CallFunc_IsLocallyControlled_ReturnValue, USkinEffect* K2Node_Event_skin, UMaterialInstanceDynamic* CallFunc_CreateDynamicMaterialInstance_ReturnValue, bool CallFunc_IsValid_ReturnValue_2, ChargeChangedSignature__DelegateSignature K2Node_CreateDelegate_OutputDelegate_1, UPlayerCharacter* K2Node_Event_ItemOwner, bool CallFunc_IsLocallyControlled_ReturnValue_1);
}

#endif
