#ifndef UE4SS_SDK_WPN_BurstPistol_HPP
#define UE4SS_SDK_WPN_BurstPistol_HPP

class AWPN_BurstPistol_C : UBurstWeapon
{
    FPointerToUberGraphFrame UberGraphFrame;
    UFirstPersonStaticMeshComponent* FirstPersonStaticMesh;
    UStaticMeshComponent* TP_Mag;
    UFirstPersonStaticMeshComponent* FP_Mag;
    UHitscanComponent* HitScan;
    UFirstPersonWidgetComponent* FirstPersonWidget;
    UPointLightComponent* MuzzlePointLight;
    UCrosshairAggregator* CrosshairAggregator;

    void GetGearStatEntry(UFSDPlayerState* PlayerState, TArray<FGearStatEntry>& Stats, TSubclassOf<UWPN_BurstPistol_C> CallFunc_GetObjectClass_ReturnValue, FGearStatEntry CallFunc_UPGDESC_DamageBonus_Random_GearStatEntry, bool CallFunc_UPGDESC_DamageBonus_Random_HasUpgradedValue, TSubclassOf<UWPN_BurstPistol_C> CallFunc_GetObjectClass_ReturnValue_1, int32 CallFunc_Array_Add_ReturnValue, FText CallFunc_GetUpgradeName_ReturnValue, FText CallFunc_GetUpgradeName_ReturnValue_1, FGearStatEntry CallFunc_UPGDESC_Generic_GearStatEntry, bool CallFunc_UPGDESC_Generic_HasUpgradedValue, FText CallFunc_GetUpgradeName_ReturnValue_2, int32 CallFunc_Array_Add_ReturnValue_1, TSubclassOf<UWPN_BurstPistol_C> CallFunc_GetObjectClass_ReturnValue_2, FGearStatEntry CallFunc_UPGDESC_Generic_GearStatEntry_1, bool CallFunc_UPGDESC_Generic_HasUpgradedValue_1, TSubclassOf<UWPN_BurstPistol_C> CallFunc_GetObjectClass_ReturnValue_3, int32 CallFunc_Array_Add_ReturnValue_2, FGearStatEntry CallFunc_UPGDESC_Generic_GearStatEntry_2, bool CallFunc_UPGDESC_Generic_HasUpgradedValue_2, TSubclassOf<UWPN_BurstPistol_C> CallFunc_GetObjectClass_ReturnValue_4, int32 CallFunc_Array_Add_ReturnValue_3, FGearStatEntry CallFunc_UPGDESC_HitScan_GearStatEntry, bool CallFunc_UPGDESC_HitScan_HasAnyUpgrades, TSubclassOf<UWPN_BurstPistol_C> CallFunc_GetObjectClass_ReturnValue_5, int32 CallFunc_Array_Add_ReturnValue_4, FGearStatEntry CallFunc_UPGDESC_HitScan_GearStatEntry_1, bool CallFunc_UPGDESC_HitScan_HasAnyUpgrades_1, TSubclassOf<UWPN_BurstPistol_C> CallFunc_GetObjectClass_ReturnValue_6, FGearStatEntry CallFunc_UPGDESC_AmmoDriven_GearStatEntry, bool CallFunc_UPGDESC_AmmoDriven_HasAnyUpgrades, int32 CallFunc_Array_Add_ReturnValue_5, int32 CallFunc_Array_Add_ReturnValue_6, FText CallFunc_GetUpgradeName_ReturnValue_3, TSubclassOf<UWPN_BurstPistol_C> CallFunc_GetObjectClass_ReturnValue_7, TSubclassOf<UWPN_BurstPistol_C> CallFunc_GetObjectClass_ReturnValue_8, FGearStatEntry CallFunc_UPGDESC_BurstWeapon_GearStatEntry, bool CallFunc_UPGDESC_BurstWeapon_HasUpgradedValue, FGearStatEntry CallFunc_UPGDESC_BurstWeapon_GearStatEntry_1, bool CallFunc_UPGDESC_BurstWeapon_HasUpgradedValue_1, int32 CallFunc_Array_Add_ReturnValue_7, int32 CallFunc_Array_Add_ReturnValue_8, TSubclassOf<UWPN_BurstPistol_C> CallFunc_GetObjectClass_ReturnValue_9, FGearStatEntry CallFunc_UPGDESC_HitScan_GearStatEntry_2, bool CallFunc_UPGDESC_HitScan_HasAnyUpgrades_2, FGearStatEntry CallFunc_UPGDESC_Damage_GearStatEntry, bool CallFunc_UPGDESC_Damage_HasUpgradedValue, int32 CallFunc_Array_Add_ReturnValue_9, int32 CallFunc_Array_Add_ReturnValue_10, FGearStatEntry CallFunc_UPGDESC_Damage_GearStatEntry_1, bool CallFunc_UPGDESC_Damage_HasUpgradedValue_1, FGearStatEntry CallFunc_UPGDESC_AmmoDriven_GearStatEntry_1, bool CallFunc_UPGDESC_AmmoDriven_HasAnyUpgrades_1, int32 CallFunc_Array_Add_ReturnValue_11, int32 CallFunc_Array_Add_ReturnValue_12, FGearStatEntry CallFunc_UPGDESC_AmmoDriven_GearStatEntry_2, bool CallFunc_UPGDESC_AmmoDriven_HasAnyUpgrades_2, FGearStatEntry CallFunc_UPGDESC_AmmoDriven_GearStatEntry_3, bool CallFunc_UPGDESC_AmmoDriven_HasAnyUpgrades_3, int32 CallFunc_Array_Add_ReturnValue_13, int32 CallFunc_Array_Add_ReturnValue_14, FGearStatEntry CallFunc_UPGDESC_AmmoDriven_GearStatEntry_4, bool CallFunc_UPGDESC_AmmoDriven_HasAnyUpgrades_4, FGearStatEntry CallFunc_UPGDESC_AmmoDriven_GearStatEntry_5, bool CallFunc_UPGDESC_AmmoDriven_HasAnyUpgrades_5, int32 CallFunc_Array_Add_ReturnValue_15, int32 CallFunc_Array_Add_ReturnValue_16, FGearStatEntry CallFunc_UPGDESC_Damage_GearStatEntry_2, bool CallFunc_UPGDESC_Damage_HasUpgradedValue_2, int32 CallFunc_Array_Add_ReturnValue_17);
    void UserConstructionScript();
    void ReceiveBeginPlay();
    void Receive_ReloadBegin();
    void Receive_ReloadEnd();
    void ExecuteUbergraph_WPN_BurstPistol(int32 EntryPoint, UUserWidget* CallFunc_GetUserWidgetObject_ReturnValue, UWeaponDisplay_Base_AmmoCount_C* K2Node_DynamicCast_AsWeapon_Display_Base_Ammo_Count, bool K2Node_DynamicCast_bSuccess);
}

#endif
