#ifndef UE4SS_SDK_ABP_Bosco_HPP
#define UE4SS_SDK_ABP_Bosco_HPP

class UABP_Bosco_C : public UBoscoAnimInstance
{
    FPointerToUberGraphFrame UberGraphFrame;
    FAnimNode_Root AnimGraphNode_Root;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_27;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_26;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_25;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_24;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_23;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_22;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_21;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_20;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_19;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_18;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_17;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_16;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_15;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_14;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_13;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_12;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_11;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_10;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_9;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_8;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_7;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_6;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_5;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_4;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_3;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_2;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_1;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult;
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_17;
    FAnimNode_StateResult AnimGraphNode_StateResult_17;
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_16;
    FAnimNode_StateResult AnimGraphNode_StateResult_16;
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_15;
    FAnimNode_StateResult AnimGraphNode_StateResult_15;
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_14;
    FAnimNode_StateResult AnimGraphNode_StateResult_14;
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_13;
    FAnimNode_StateResult AnimGraphNode_StateResult_13;
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_12;
    FAnimNode_StateResult AnimGraphNode_StateResult_12;
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_11;
    FAnimNode_StateResult AnimGraphNode_StateResult_11;
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_10;
    FAnimNode_StateResult AnimGraphNode_StateResult_10;
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_9;
    FAnimNode_StateResult AnimGraphNode_StateResult_9;
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_8;
    FAnimNode_StateResult AnimGraphNode_StateResult_8;
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_7;
    FAnimNode_StateResult AnimGraphNode_StateResult_7;
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_6;
    FAnimNode_StateResult AnimGraphNode_StateResult_6;
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_5;
    FAnimNode_StateResult AnimGraphNode_StateResult_5;
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_4;
    FAnimNode_StateResult AnimGraphNode_StateResult_4;
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_3;
    FAnimNode_StateResult AnimGraphNode_StateResult_3;
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_2;
    FAnimNode_StateResult AnimGraphNode_StateResult_2;
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_1;
    FAnimNode_StateResult AnimGraphNode_StateResult_1;
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer;
    FAnimNode_StateResult AnimGraphNode_StateResult;
    FAnimNode_StateMachine AnimGraphNode_StateMachine;
    FAnimNode_Slot AnimGraphNode_Slot_2;
    FAnimNode_Slot AnimGraphNode_Slot_1;
    FAnimNode_Slot AnimGraphNode_Slot;
    FAnimNode_RigidBody AnimGraphNode_RigidBody;
    FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace;
    FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace;

    void AnimGraph(FPoseLink& AnimGraph);
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Bosco_AnimGraphNode_TransitionResult_2C87CB004D2625203839959DD2898B0F();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Bosco_AnimGraphNode_TransitionResult_E97316F74C131834F52E939615D6EB9F();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Bosco_AnimGraphNode_TransitionResult_17AED0154078A27DA892FB904C2082E8();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Bosco_AnimGraphNode_TransitionResult_DEE9FCD1470CCB102ED91EA81D4E7E1E();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Bosco_AnimGraphNode_TransitionResult_4210E8D0438F626F0E4D59B0905F0238();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Bosco_AnimGraphNode_TransitionResult_0D42714B4E07EE59C224B6AA5BA921EE();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Bosco_AnimGraphNode_TransitionResult_41E16860408AC6C966BA7293316AABA7();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Bosco_AnimGraphNode_TransitionResult_B234EC8445E906CA1BB3FEA4CF754B26();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Bosco_AnimGraphNode_TransitionResult_E393F0194FCE38452A8905B4D30BB79F();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Bosco_AnimGraphNode_TransitionResult_AC6E7F4141767F676AB4B7ABB9BCF08B();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Bosco_AnimGraphNode_TransitionResult_AE7C675B491AD99BA560EF80DF56A191();
    void BlueprintUpdateAnimation(float DeltaTimeX);
    void BlueprintInitializeAnimation();
    void ExecuteUbergraph_ABP_Bosco(int32 EntryPoint);
};

#endif
