#ifndef UE4SS_SDK_BP_CrystalFormation_SpikyBunch_01_HPP
#define UE4SS_SDK_BP_CrystalFormation_SpikyBunch_01_HPP

class ABP_CrystalFormation_SpikyBunch_01_C : public ABP_CrystalFormationsSpikyBunch_Base_C
{
};

#endif
