#ifndef UE4SS_SDK_BP_CrystalFormations_SlantedPillars_02Small_HPP
#define UE4SS_SDK_BP_CrystalFormations_SlantedPillars_02Small_HPP

class ABP_CrystalFormations_SlantedPillars_02Small_C : public ABP_CrystalFormations_SlantedPillars_Base_C
{
};

#endif
