#ifndef UE4SS_SDK_BP_CrystalFormations_SlantedPillars_06_HPP
#define UE4SS_SDK_BP_CrystalFormations_SlantedPillars_06_HPP

class ABP_CrystalFormations_SlantedPillars_06_C : public ABP_CrystalFormations_SlantedPillars_Base_C
{
};

#endif
