#ifndef UE4SS_SDK_CameraShake_Earthquake_DropPod_Digging_HPP
#define UE4SS_SDK_CameraShake_Earthquake_DropPod_Digging_HPP

class UCameraShake_Earthquake_DropPod_Digging_C : public UMatineeCameraShake
{
};

#endif
