#ifndef UE4SS_SDK_PRJ_GooProjectile_Fragment_Normal_HPP
#define UE4SS_SDK_PRJ_GooProjectile_Fragment_Normal_HPP

class APRJ_GooProjectile_Fragment_Normal_C : public APRJ_GooProjectile_Fragment_Base_C
{
};

#endif
