#ifndef UE4SS_SDK_PRJ_Crossbow_ChemicalExplosionProjecitle_HPP
#define UE4SS_SDK_PRJ_Crossbow_ChemicalExplosionProjecitle_HPP

class APRJ_Crossbow_ChemicalExplosionProjecitle_C : public APRJ_Crossbow_Projectile_C
{
};

#endif
