#ifndef UE4SS_SDK_BP_CrystalFormations_SlantedPillar_Solo_Skinny_HPP
#define UE4SS_SDK_BP_CrystalFormations_SlantedPillar_Solo_Skinny_HPP

class ABP_CrystalFormations_SlantedPillar_Solo_Skinny_C : public ABP_CrystalFormations_SlantedPillars_Base_C
{
};

#endif
