#ifndef UE4SS_SDK_BP_CrystalFormations_SlantedPillar_Solo_2_HPP
#define UE4SS_SDK_BP_CrystalFormations_SlantedPillar_Solo_2_HPP

class ABP_CrystalFormations_SlantedPillar_Solo_2_C : public ABP_CrystalFormations_SlantedPillars_Base_C
{
};

#endif
